// 自动生成的JS模块 - grade5_1.json
// 生成时间: 2025-12-20T08:18:44.724Z

module.exports = {
  "grade": 5,
  "semester": 1,
  "gradeName": "小学五年级上册",
  "total": 297,
  "lastUpdated": "2025-12-20T02:06:14.946Z",
  "words": [
    {
      "word": "lake",
      "meaning": "湖；湖泊",
      "grade": "5.1",
      "phonetic": "/leik/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "1"
    },
    {
      "word": "day",
      "meaning": "一天；白天",
      "grade": "5.1",
      "phonetic": "/dei/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "2"
    },
    {
      "word": "play",
      "meaning": "踢；玩；参加(体育运动)",
      "grade": "5.1",
      "phonetic": "/plei/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "3"
    },
    {
      "word": "Sunday",
      "meaning": "星期日",
      "grade": "5.1",
      "phonetic": "/'sʌndei/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "4"
    },
    {
      "word": "Wednesday",
      "meaning": "星期三",
      "grade": "5.1",
      "phonetic": "/'wenzdei/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "5"
    },
    {
      "word": "tree",
      "meaning": "树木",
      "grade": "5.1",
      "phonetic": "/tri:/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "6"
    },
    {
      "word": "week",
      "meaning": "周",
      "grade": "5.1",
      "phonetic": "/wi:k/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "7"
    },
    {
      "word": "sweet",
      "meaning": "含糖的；甜的",
      "grade": "5.1",
      "phonetic": "/swi:t/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "形容",
      "serialNumber": "8"
    },
    {
      "word": "between",
      "meaning": "在……（两者）之间",
      "grade": "5.1",
      "phonetic": "/bi'twi:n/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "介",
      "serialNumber": "9"
    },
    {
      "word": "ice",
      "meaning": "冰",
      "grade": "5.1",
      "phonetic": "/ais/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "10"
    },
    {
      "word": "bike",
      "meaning": "自行车；脚踏车",
      "grade": "5.1",
      "phonetic": "/baik/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "11"
    },
    {
      "word": "time",
      "meaning": "时间（不可数）",
      "grade": "5.1",
      "phonetic": "/taim/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "12"
    },
    {
      "word": "times",
      "meaning": "次数；时段（复数）",
      "grade": "5.1",
      "phonetic": "/taimz/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "13"
    },
    {
      "word": "beside",
      "meaning": "在旁边(附近)",
      "grade": "5.1",
      "phonetic": "/bi'said/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "介",
      "serialNumber": "14"
    },
    {
      "word": "polite",
      "meaning": "有礼貌的；客气的",
      "grade": "5.1",
      "phonetic": "/pə'lait/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "15"
    },
    {
      "word": "shy",
      "meaning": "羞怯的；腼腆的；怕生的",
      "grade": "5.1",
      "phonetic": "/ʃai/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y词尾重读/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "16"
    },
    {
      "word": "photo",
      "meaning": "照片；相片",
      "grade": "5.1",
      "phonetic": "/'fəutəu/",
      "highlightLetters": "o，o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "17"
    },
    {
      "word": "robot",
      "meaning": "机器人",
      "grade": "5.1",
      "phonetic": "/'rəubɒt/",
      "highlightLetters": "第1个o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "18"
    },
    {
      "word": "Tuesday",
      "meaning": "星期二",
      "grade": "5.1",
      "phonetic": "/'tju:zdei/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "19"
    },
    {
      "word": "schedule",
      "meaning": "工作计划；日程安排",
      "grade": "5.1",
      "phonetic": "/'ʃedju:l/",
      "highlightLetters": "u,e",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "20"
    },
    {
      "word": "at",
      "meaning": "在(后面接邮件地址)",
      "grade": "5.1",
      "phonetic": "/æt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "介",
      "serialNumber": "21"
    },
    {
      "word": "rabbit",
      "meaning": "兔；野兔",
      "grade": "5.1",
      "phonetic": "/'ræbit/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "22"
    },
    {
      "word": "salad",
      "meaning": "沙拉",
      "grade": "5.1",
      "phonetic": "/'sæləd/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "23"
    },
    {
      "word": "grandparent",
      "meaning": "(外)祖父(母)",
      "grade": "5.1",
      "phonetic": "/'grænpeərənt/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "24"
    },
    {
      "word": "hamburger",
      "meaning": "汉堡包",
      "grade": "5.1",
      "phonetic": "/'hæmbɜ:g/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "25"
    },
    {
      "word": "Saturday",
      "meaning": "星期六",
      "grade": "5.1",
      "phonetic": "/'sætədei/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "26"
    },
    {
      "word": "end",
      "meaning": "末尾",
      "grade": "5.1",
      "phonetic": "/end/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "27"
    },
    {
      "word": "send",
      "meaning": "邮寄；发送",
      "grade": "5.1",
      "phonetic": "/send/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "28"
    },
    {
      "word": "next",
      "meaning": "下一个的；接下来的",
      "grade": "5.1",
      "phonetic": "/nekst/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "29"
    },
    {
      "word": "fresh",
      "meaning": "新鲜的；刚摘的",
      "grade": "5.1",
      "phonetic": "/freʃ/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "30"
    },
    {
      "word": "clever",
      "meaning": "聪明的；聪颖的",
      "grade": "5.1",
      "phonetic": "/'klevə(r)/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "31"
    },
    {
      "word": "every",
      "meaning": "每个",
      "grade": "5.1",
      "phonetic": "/'evri/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "32"
    },
    {
      "word": "help",
      "meaning": "帮助",
      "grade": "5.1",
      "phonetic": "/'help/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "33"
    },
    {
      "word": "helpful",
      "meaning": "有用的；助人的",
      "grade": "5.1",
      "phonetic": "/'helpfl/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "34"
    },
    {
      "word": "Wednesday",
      "meaning": "星期三",
      "grade": "5.1",
      "phonetic": "/'wenzdei/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "35"
    },
    {
      "word": "health",
      "meaning": "健康",
      "grade": "5.1",
      "phonetic": "/'helθ/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "不可数名",
      "serialNumber": "36"
    },
    {
      "word": "healthy",
      "meaning": "健康的",
      "grade": "5.1",
      "phonetic": "/'helθi/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "37"
    },
    {
      "word": "any",
      "meaning": "任何的；任一的",
      "grade": "5.1",
      "phonetic": "/'eni/",
      "highlightLetters": "a",
      "highlightPhonetic": "/e/",
      "note": "a读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "38"
    },
    {
      "word": "many",
      "meaning": "许多的（+名词复数）",
      "grade": "5.1",
      "phonetic": "/'meni/",
      "highlightLetters": "a",
      "highlightPhonetic": "/e/",
      "note": "a读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "39"
    },
    {
      "word": "him",
      "meaning": "他(用于动词或介词之后)",
      "grade": "5.1",
      "phonetic": "/him/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "代",
      "serialNumber": "40"
    },
    {
      "word": "hill",
      "meaning": "山丘；小山",
      "grade": "5.1",
      "phonetic": "/hil/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "41"
    },
    {
      "word": "will",
      "meaning": "将要",
      "grade": "5.1",
      "phonetic": "/wil/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "42"
    },
    {
      "word": "live",
      "meaning": "住；居住",
      "grade": "5.1",
      "phonetic": "/liv/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "43"
    },
    {
      "word": "sing",
      "meaning": "唱；唱歌",
      "grade": "5.1",
      "phonetic": "/siŋ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "44"
    },
    {
      "word": "strict",
      "meaning": "严格的；严厉的",
      "grade": "5.1",
      "phonetic": "/strikt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形容",
      "serialNumber": "45"
    },
    {
      "word": "swim",
      "meaning": "游泳",
      "grade": "5.1",
      "phonetic": "/swim/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "46"
    },
    {
      "word": "bridge",
      "meaning": "桥",
      "grade": "5.1",
      "phonetic": "/bridʒ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "47"
    },
    {
      "word": "build",
      "meaning": "建造；建设",
      "grade": "5.1",
      "phonetic": "/bild/",
      "highlightLetters": "ui",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "48"
    },
    {
      "word": "building",
      "meaning": "建筑物；楼房",
      "grade": "5.1",
      "phonetic": "/'bildiŋ/",
      "highlightLetters": "ui",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "49"
    },
    {
      "word": "village",
      "meaning": "村庄",
      "grade": "5.1",
      "phonetic": "/'vilidʒ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "50"
    },
    {
      "word": "delicious",
      "meaning": "美味的；可口的",
      "grade": "5.1",
      "phonetic": "/di'liʃs/",
      "highlightLetters": "第1个i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形容",
      "serialNumber": "51"
    },
    {
      "word": "finish",
      "meaning": "完成",
      "grade": "5.1",
      "phonetic": "/'finiʃ/",
      "highlightLetters": "第1个i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "52"
    },
    {
      "word": "hot",
      "meaning": "辣的；热的",
      "grade": "5.1",
      "phonetic": "/hɒt/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形容",
      "serialNumber": "53"
    },
    {
      "word": "lot",
      "meaning": "大量；许多",
      "grade": "5.1",
      "phonetic": "/lɒt/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "54"
    },
    {
      "word": "song",
      "meaning": "歌曲",
      "grade": "5.1",
      "phonetic": "/sɒŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "55"
    },
    {
      "word": "bottle",
      "meaning": "瓶子",
      "grade": "5.1",
      "phonetic": "/'bɒtl/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "56"
    },
    {
      "word": "clock",
      "meaning": "时钟；钟",
      "grade": "5.1",
      "phonetic": "/klɒk/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "57"
    },
    {
      "word": "forest",
      "meaning": "森林；林区",
      "grade": "5.1",
      "phonetic": "/'fɒrist/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "58"
    },
    {
      "word": "problem",
      "meaning": "问题",
      "grade": "5.1",
      "phonetic": "/'prɒbləm/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "59"
    },
    {
      "word": "want",
      "meaning": "要；想要",
      "grade": "5.1",
      "phonetic": "/wɒnt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɒ/",
      "note": "a读短音/ɒ /",
      "partOfSpeech": "动",
      "serialNumber": "60"
    },
    {
      "word": "wash",
      "meaning": "洗",
      "grade": "5.1",
      "phonetic": "/wɒʃ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɒ/",
      "note": "a读短音/ɒ /",
      "partOfSpeech": "动",
      "serialNumber": "61"
    },
    {
      "word": "watch",
      "meaning": "观看；观察",
      "grade": "5.1",
      "phonetic": "/wɒtʃ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɒ/",
      "note": "a读短音/ɒ /",
      "partOfSpeech": "动",
      "serialNumber": "62"
    },
    {
      "word": "fun",
      "meaning": "乐趣；开心（不可数）",
      "grade": "5.1",
      "phonetic": "/fʌn/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "不可数名",
      "serialNumber": "63"
    },
    {
      "word": "funny",
      "meaning": "滑稽的；可笑的",
      "grade": "5.1",
      "phonetic": "/'fʌni/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "形容",
      "serialNumber": "64"
    },
    {
      "word": "sun",
      "meaning": "太阳；阳光（不可数）",
      "grade": "5.1",
      "phonetic": "/sʌn/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "65"
    },
    {
      "word": "kung fu",
      "meaning": "功夫；武术",
      "grade": "5.1",
      "phonetic": "/,kʌŋ'fu:/",
      "highlightLetters": "第1个u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "不可数名",
      "serialNumber": "66"
    },
    {
      "word": "Sunday",
      "meaning": "星期日",
      "grade": "5.1",
      "phonetic": "/'sʌndei/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "67"
    },
    {
      "word": "above",
      "meaning": "在……上方",
      "grade": "5.1",
      "phonetic": "/ə'bʌv/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "介",
      "serialNumber": "68"
    },
    {
      "word": "front",
      "meaning": "正面；前面",
      "grade": "5.1",
      "phonetic": "/frʌnt/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "69"
    },
    {
      "word": "Monday",
      "meaning": "星期一",
      "grade": "5.1",
      "phonetic": "/'mʌndei/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "70"
    },
    {
      "word": "onion",
      "meaning": "洋葱",
      "grade": "5.1",
      "phonetic": "/'ʌnjən/",
      "highlightLetters": "第1个o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "71"
    },
    {
      "word": "sometimes",
      "meaning": "有时；间或",
      "grade": "5.1",
      "phonetic": "/'sʌmtaimz/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "副",
      "serialNumber": "72"
    },
    {
      "word": "wonderful",
      "meaning": "极好的；了不起的",
      "grade": "5.1",
      "phonetic": "/'wʌndəfl/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "形容",
      "serialNumber": "73"
    },
    {
      "word": "young",
      "meaning": "年轻的",
      "grade": "5.1",
      "phonetic": "/jʌŋ/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʌ/",
      "note": "ou读短音/ʌ /",
      "partOfSpeech": "形容",
      "serialNumber": "74"
    },
    {
      "word": "cook",
      "meaning": "烹调；做饭",
      "grade": "5.1",
      "phonetic": "/kuk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʌ/",
      "note": "oo读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "75"
    },
    {
      "word": "cooking",
      "meaning": "烹饪；做饭",
      "grade": "5.1",
      "phonetic": "/'kukiŋ/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʌ/",
      "note": "oo读短音/ʌ /",
      "partOfSpeech": "不可数名",
      "serialNumber": "76"
    },
    {
      "word": "should",
      "meaning": "(纠正别人)应该，应当",
      "grade": "5.1",
      "phonetic": "/ʃud/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʊ/",
      "note": "ou读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "77"
    },
    {
      "word": "dance",
      "meaning": "跳舞",
      "grade": "5.1",
      "phonetic": "/dɑ:ns/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "动",
      "serialNumber": "78"
    },
    {
      "word": "plant",
      "meaning": "植物",
      "grade": "5.1",
      "phonetic": "/plɑ:nt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "79"
    },
    {
      "word": "hard",
      "meaning": "努力地；困难的",
      "grade": "5.1",
      "phonetic": "/hɑ:d/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "副;形容",
      "serialNumber": "80"
    },
    {
      "word": "park",
      "meaning": "公园",
      "grade": "5.1",
      "phonetic": "/pɑ:k/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "81"
    },
    {
      "word": "party",
      "meaning": "聚会；派对",
      "grade": "5.1",
      "phonetic": "/'pɑ:ti/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "82"
    },
    {
      "word": "cartoon",
      "meaning": "漫画;卡通",
      "grade": "5.1",
      "phonetic": "/kɑ:'tu:n/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "83"
    },
    {
      "word": "sport",
      "meaning": "体育运动",
      "grade": "5.1",
      "phonetic": "/spɔ:t/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "84"
    },
    {
      "word": "draw",
      "meaning": "画",
      "grade": "5.1",
      "phonetic": "/drɔ:/",
      "highlightLetters": "aw",
      "highlightPhonetic": "/ɔː/",
      "note": "aw读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "85"
    },
    {
      "word": "dirty",
      "meaning": "肮脏的",
      "grade": "5.1",
      "phonetic": "/'dɜ:ti/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir重读长音/ɜː/",
      "partOfSpeech": "形容",
      "serialNumber": "86"
    },
    {
      "word": "thirsty",
      "meaning": "口渴的",
      "grade": "5.1",
      "phonetic": "/'θɜ:sti/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir重读长音/ɜː/",
      "partOfSpeech": "形容",
      "serialNumber": "87"
    },
    {
      "word": "learn",
      "meaning": "学习；学会",
      "grade": "5.1",
      "phonetic": "/lɜ:n/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɜː/",
      "note": "ear重读长音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "88"
    },
    {
      "word": "hamburger",
      "meaning": "汉堡包",
      "grade": "5.1",
      "phonetic": "/'hæmbɜ:g/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "89"
    },
    {
      "word": "Thursday",
      "meaning": "星期四",
      "grade": "5.1",
      "phonetic": "/'θɜ:zdei/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "90"
    },
    {
      "word": "hard-working",
      "meaning": "工作努力的；辛勤的",
      "grade": "5.1",
      "phonetic": "/,hɑ:d'wɜ:kiŋ/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɜː/",
      "note": "or重读长音/ɜː/",
      "partOfSpeech": "形容",
      "serialNumber": "91"
    },
    {
      "word": "email",
      "meaning": "电子邮件",
      "grade": "5.1",
      "phonetic": "/ 'i:meil/",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "92"
    },
    {
      "word": "read",
      "meaning": "读书；看书",
      "grade": "5.1",
      "phonetic": "/ri:d/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "93"
    },
    {
      "word": "tea",
      "meaning": "茶；茶水",
      "grade": "5.1",
      "phonetic": "/ti:/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "94"
    },
    {
      "word": "speak",
      "meaning": "讲，说(+某国语言)",
      "grade": "5.1",
      "phonetic": "/spi:k/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "95"
    },
    {
      "word": "cream",
      "meaning": "奶油；淡黄色",
      "grade": "5.1",
      "phonetic": "/kri:m/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "96"
    },
    {
      "word": "move",
      "meaning": "搬家",
      "grade": "5.1",
      "phonetic": "/mu:v/",
      "highlightLetters": "o",
      "highlightPhonetic": "/uː/",
      "note": "o读长元音/uː/",
      "partOfSpeech": "动",
      "serialNumber": "97"
    },
    {
      "word": "food",
      "meaning": "食物（不可数）",
      "grade": "5.1",
      "phonetic": "/fu:d/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "98"
    },
    {
      "word": "cartoons",
      "meaning": "漫画;卡通（复数）",
      "grade": "5.1",
      "phonetic": "/kɑ:'tu:nz/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名,复数",
      "serialNumber": "99"
    },
    {
      "word": "kung fu",
      "meaning": "功夫；武术",
      "grade": "5.1",
      "phonetic": "/,kʌŋ'fu:/",
      "highlightLetters": "第2个u",
      "highlightPhonetic": "/uː/",
      "note": "u读长元音/uː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "100"
    },
    {
      "word": "email",
      "meaning": "电子邮件",
      "grade": "5.1",
      "phonetic": "/ 'i:meil/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/eɪ/",
      "note": "ai读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "101"
    },
    {
      "word": "favourite",
      "meaning": "特别喜爱的",
      "grade": "5.1",
      "phonetic": "/'feivərit/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "102"
    },
    {
      "word": "nature",
      "meaning": "自然界；大自然",
      "grade": "5.1",
      "phonetic": "/'neitʃə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "103"
    },
    {
      "word": "high",
      "meaning": "高的",
      "grade": "5.1",
      "phonetic": "/hai/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "104"
    },
    {
      "word": "Friday",
      "meaning": "星期五",
      "grade": "5.1",
      "phonetic": "/'fraidei/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "105"
    },
    {
      "word": "kind",
      "meaning": "体贴的；慈祥的；宽容的",
      "grade": "5.1",
      "phonetic": "/kaind/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "106"
    },
    {
      "word": "behind",
      "meaning": "在……后面",
      "grade": "5.1",
      "phonetic": "/bi'haind/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "介",
      "serialNumber": "107"
    },
    {
      "word": "tired",
      "meaning": "疲倦的；累的",
      "grade": "5.1",
      "phonetic": "/'taiəd/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "108"
    },
    {
      "word": "boy",
      "meaning": "男生",
      "grade": "5.1",
      "phonetic": "/bɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "109"
    },
    {
      "word": "toy",
      "meaning": "玩具",
      "grade": "5.1",
      "phonetic": "/tɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "110"
    },
    {
      "word": "our",
      "meaning": "我们的",
      "grade": "5.1",
      "phonetic": "/'auə/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "代",
      "serialNumber": "111"
    },
    {
      "word": "house",
      "meaning": "房子；住宅",
      "grade": "5.1",
      "phonetic": "/haus/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "名",
      "serialNumber": "112"
    },
    {
      "word": "mouse",
      "meaning": "老鼠",
      "grade": "5.1",
      "phonetic": "/maus/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "名",
      "serialNumber": "113"
    },
    {
      "word": "mountain",
      "meaning": "高山；山岳",
      "grade": "5.1",
      "phonetic": "/'mauntən/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "名",
      "serialNumber": "114"
    },
    {
      "word": "flower",
      "meaning": "花朵",
      "grade": "5.1",
      "phonetic": "/'flauə/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/aʊ/",
      "note": "ow读双元音/aʊ/",
      "partOfSpeech": "名",
      "serialNumber": "115"
    },
    {
      "word": "old",
      "meaning": "老的；年纪大的",
      "grade": "5.1",
      "phonetic": "/əuld/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "形容",
      "serialNumber": "116"
    },
    {
      "word": "know",
      "meaning": "知道；了解",
      "grade": "5.1",
      "phonetic": "/nəu/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "117"
    },
    {
      "word": "boating",
      "meaning": "划船",
      "grade": "5.1",
      "phonetic": "/'bəutiŋ/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读双元音/əʊ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "118"
    },
    {
      "word": "Dear",
      "meaning": "(写信或头衔前)亲爱的",
      "grade": "5.1",
      "phonetic": "/diə/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɪə/",
      "note": "ear读双元音/ɪə/",
      "partOfSpeech": "形容",
      "serialNumber": "119"
    },
    {
      "word": "parent",
      "meaning": "父(母)",
      "grade": "5.1",
      "phonetic": "/'peərənt/",
      "highlightLetters": "are",
      "highlightPhonetic": "/eə/",
      "note": "are读双元音/eə/",
      "partOfSpeech": "名",
      "serialNumber": "120"
    },
    {
      "word": "their",
      "meaning": "他/她/它们的",
      "grade": "5.1",
      "phonetic": "/ðeə/",
      "highlightLetters": "eir",
      "highlightPhonetic": "/eə/",
      "note": "eir读双元音/eə/",
      "partOfSpeech": "代",
      "serialNumber": "121"
    },
    {
      "word": "there",
      "meaning": "那儿(表示存在或发生)",
      "grade": "5.1",
      "phonetic": "/ðeə/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "122"
    },
    {
      "word": "where",
      "meaning": "在哪里",
      "grade": "5.1",
      "phonetic": "/weə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "123"
    },
    {
      "word": "sure",
      "meaning": "当然可以",
      "grade": "5.1",
      "phonetic": "/ʃuə(r)/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/uə/",
      "note": "ure读双元音/uə/",
      "partOfSpeech": "副",
      "serialNumber": "124"
    },
    {
      "word": "poor",
      "meaning": "穷的；可怜的",
      "grade": "5.1",
      "phonetic": "/puə(r)/",
      "highlightLetters": "oor",
      "highlightPhonetic": "/uə/",
      "note": "oor读双元音/uə/",
      "partOfSpeech": "形容",
      "serialNumber": "125"
    },
    {
      "word": "above",
      "meaning": "在……上方",
      "grade": "5.1",
      "phonetic": "/ə'bʌv/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "介",
      "serialNumber": "126"
    },
    {
      "word": "salad",
      "meaning": "沙拉",
      "grade": "5.1",
      "phonetic": "/'sæləd/",
      "highlightLetters": "第2个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "127"
    },
    {
      "word": "polite",
      "meaning": "有礼貌的；客气的",
      "grade": "5.1",
      "phonetic": "/pə'lait/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "形容",
      "serialNumber": "128"
    },
    {
      "word": "robot",
      "meaning": "机器人",
      "grade": "5.1",
      "phonetic": "/'rəubɒt/",
      "highlightLetters": "第2个o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "129"
    },
    {
      "word": "favourite",
      "meaning": "特别喜爱的",
      "grade": "5.1",
      "phonetic": "/'feivərit/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ə/",
      "note": "ou弱音读/ə/",
      "partOfSpeech": "形容",
      "serialNumber": "130"
    },
    {
      "word": "Saturday",
      "meaning": "星期六",
      "grade": "5.1",
      "phonetic": "/'sætədei/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ə/",
      "note": "ur弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "131"
    },
    {
      "word": "mountain",
      "meaning": "高山；山岳",
      "grade": "5.1",
      "phonetic": "/'mauntən/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/ə/",
      "note": "ai弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "132"
    },
    {
      "word": "problem",
      "meaning": "问题",
      "grade": "5.1",
      "phonetic": "/'prɒbləm/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ə/",
      "note": "e弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "133"
    },
    {
      "word": "behind",
      "meaning": "在……后面",
      "grade": "5.1",
      "phonetic": "/bi'haind/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "介",
      "serialNumber": "134"
    },
    {
      "word": "beside",
      "meaning": "在旁边(附近)",
      "grade": "5.1",
      "phonetic": "/bi'said/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "介",
      "serialNumber": "135"
    },
    {
      "word": "delicious",
      "meaning": "美味的；可口的",
      "grade": "5.1",
      "phonetic": "/di'liʃs/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "136"
    },
    {
      "word": "between",
      "meaning": "在……（两者）之间",
      "grade": "5.1",
      "phonetic": "/bi'twi:n/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "介",
      "serialNumber": "137"
    },
    {
      "word": "village",
      "meaning": "村庄",
      "grade": "5.1",
      "phonetic": "/'vilidʒ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/i/",
      "note": "a弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "138"
    },
    {
      "word": "dirty",
      "meaning": "肮脏的",
      "grade": "5.1",
      "phonetic": "/'dɜ:ti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "139"
    },
    {
      "word": "every",
      "meaning": "每个",
      "grade": "5.1",
      "phonetic": "/'evri/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "140"
    },
    {
      "word": "funny",
      "meaning": "滑稽的；可笑的",
      "grade": "5.1",
      "phonetic": "/'fʌni/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "141"
    },
    {
      "word": "healthy",
      "meaning": "健康的",
      "grade": "5.1",
      "phonetic": "/'helθi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "142"
    },
    {
      "word": "party",
      "meaning": "聚会；派对",
      "grade": "5.1",
      "phonetic": "/'pɑ:ti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "143"
    },
    {
      "word": "thirsty",
      "meaning": "口渴的",
      "grade": "5.1",
      "phonetic": "/'θɜ:sti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "144"
    },
    {
      "word": "often",
      "meaning": "时常；经常",
      "grade": "5.1",
      "phonetic": "/'ɒfn/",
      "highlightLetters": "ften",
      "highlightPhonetic": "/fn/",
      "note": "/fn/弱音省略",
      "partOfSpeech": "副",
      "serialNumber": "145"
    },
    {
      "word": "helpful",
      "meaning": "有用的；助人的",
      "grade": "5.1",
      "phonetic": "/'helpfl/",
      "highlightLetters": "ful",
      "highlightPhonetic": "/fl/",
      "note": "/fl/弱音省略",
      "partOfSpeech": "形容",
      "serialNumber": "146"
    },
    {
      "word": "wonderful",
      "meaning": "极好的；了不起的",
      "grade": "5.1",
      "phonetic": "/'wʌndəfl/",
      "highlightLetters": "ful",
      "highlightPhonetic": "/fl/",
      "note": "/fl/弱音省略",
      "partOfSpeech": "形容",
      "serialNumber": "147"
    },
    {
      "word": "bike",
      "meaning": "自行车；脚踏车",
      "grade": "5.1",
      "phonetic": "/baik/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "148"
    },
    {
      "word": "build",
      "meaning": "建造；建设",
      "grade": "5.1",
      "phonetic": "/bild/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "动",
      "serialNumber": "149"
    },
    {
      "word": "above",
      "meaning": "在……上方",
      "grade": "5.1",
      "phonetic": "/ə'bʌv/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "介",
      "serialNumber": "150"
    },
    {
      "word": "behind",
      "meaning": "在……后面",
      "grade": "5.1",
      "phonetic": "/bi'haind/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "介",
      "serialNumber": "151"
    },
    {
      "word": "beside",
      "meaning": "在旁边(附近)",
      "grade": "5.1",
      "phonetic": "/bi'said/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "介",
      "serialNumber": "152"
    },
    {
      "word": "boating",
      "meaning": "划船",
      "grade": "5.1",
      "phonetic": "/'bəutiŋ/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "不可数名",
      "serialNumber": "153"
    },
    {
      "word": "bottle",
      "meaning": "瓶子",
      "grade": "5.1",
      "phonetic": "/'bɒtl/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "154"
    },
    {
      "word": "building",
      "meaning": "建筑物；楼房",
      "grade": "5.1",
      "phonetic": "/'bildiŋ/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "不可数名",
      "serialNumber": "155"
    },
    {
      "word": "rabbit",
      "meaning": "兔；野兔",
      "grade": "5.1",
      "phonetic": "/'ræbit/",
      "highlightLetters": "bb",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "156"
    },
    {
      "word": "cartoons",
      "meaning": "漫画;卡通（复数）",
      "grade": "5.1",
      "phonetic": "/kɑ:'tu:nz/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名,复数",
      "serialNumber": "157"
    },
    {
      "word": "cook",
      "meaning": "烹调；做饭",
      "grade": "5.1",
      "phonetic": "/kuk/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "动",
      "serialNumber": "158"
    },
    {
      "word": "cooking",
      "meaning": "烹饪；做饭",
      "grade": "5.1",
      "phonetic": "/'kukiŋ/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在辅音前）",
      "partOfSpeech": "不可数名",
      "serialNumber": "159"
    },
    {
      "word": "strict",
      "meaning": "严格的；严厉的",
      "grade": "5.1",
      "phonetic": "/strikt/",
      "highlightLetters": "第1个c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在辅音前）",
      "partOfSpeech": "形容",
      "serialNumber": "160"
    },
    {
      "word": "clock",
      "meaning": "时钟；钟",
      "grade": "5.1",
      "phonetic": "/klɒk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "名",
      "serialNumber": "161"
    },
    {
      "word": "dance",
      "meaning": "跳舞",
      "grade": "5.1",
      "phonetic": "/dɑ:ns/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "162"
    },
    {
      "word": "delicious",
      "meaning": "美味的；可口的",
      "grade": "5.1",
      "phonetic": "/di'liʃs/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形容",
      "serialNumber": "163"
    },
    {
      "word": "sandwich",
      "meaning": "三明治",
      "grade": "5.1",
      "phonetic": "/'sænwitʃ/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "164"
    },
    {
      "word": "schedule",
      "meaning": "工作计划；日程安排",
      "grade": "5.1",
      "phonetic": "/'ʃedju:l/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "165"
    },
    {
      "word": "day",
      "meaning": "一天；白天",
      "grade": "5.1",
      "phonetic": "/dei/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "166"
    },
    {
      "word": "Dear",
      "meaning": "(写信或头衔前)亲爱的",
      "grade": "5.1",
      "phonetic": "/diə/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形容",
      "serialNumber": "167"
    },
    {
      "word": "do",
      "meaning": "做；干；用于代替动词来变形",
      "grade": "5.1",
      "phonetic": "/du:/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "168"
    },
    {
      "word": "dirty",
      "meaning": "肮脏的",
      "grade": "5.1",
      "phonetic": "/'dɜ:ti/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形容",
      "serialNumber": "169"
    },
    {
      "word": "delicious",
      "meaning": "美味的；可口的",
      "grade": "5.1",
      "phonetic": "/di'liʃs/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形容",
      "serialNumber": "170"
    },
    {
      "word": "end",
      "meaning": "末尾",
      "grade": "5.1",
      "phonetic": "/end/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "171"
    },
    {
      "word": "food",
      "meaning": "食物",
      "grade": "5.1",
      "phonetic": "/fu:d/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "不可数名",
      "serialNumber": "172"
    },
    {
      "word": "hard",
      "meaning": "努力地；困难的",
      "grade": "5.1",
      "phonetic": "/hɑ:d/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "副;形容",
      "serialNumber": "173"
    },
    {
      "word": "kind",
      "meaning": "体贴的；友善的",
      "grade": "5.1",
      "phonetic": "/kaind/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形容",
      "serialNumber": "174"
    },
    {
      "word": "send",
      "meaning": "邮寄；发送",
      "grade": "5.1",
      "phonetic": "/send/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "175"
    },
    {
      "word": "build",
      "meaning": "建造；建设",
      "grade": "5.1",
      "phonetic": "/bild/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "176"
    },
    {
      "word": "grandparent",
      "meaning": "(外)祖父(母)",
      "grade": "5.1",
      "phonetic": "/'grænpeərənt/",
      "highlightLetters": "d",
      "highlightPhonetic": "",
      "note": "不发音",
      "partOfSpeech": "名",
      "serialNumber": "177"
    },
    {
      "word": "sandwich",
      "meaning": "三明治",
      "grade": "5.1",
      "phonetic": "/'sænwitʃ/",
      "highlightLetters": "d",
      "highlightPhonetic": "",
      "note": "不发音",
      "partOfSpeech": "名",
      "serialNumber": "178"
    },
    {
      "word": "finish",
      "meaning": "完成",
      "grade": "5.1",
      "phonetic": "/'finiʃ/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "179"
    },
    {
      "word": "food",
      "meaning": "食物（不可数）",
      "grade": "5.1",
      "phonetic": "/fu:d/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "不可数名",
      "serialNumber": "180"
    },
    {
      "word": "forest",
      "meaning": "森林；林区",
      "grade": "5.1",
      "phonetic": "/'fɒrist/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "181"
    },
    {
      "word": "fun",
      "meaning": "乐趣；开心（不可数）",
      "grade": "5.1",
      "phonetic": "/'fʌn/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "不可数名",
      "serialNumber": "182"
    },
    {
      "word": "funny",
      "meaning": "滑稽的；可笑的",
      "grade": "5.1",
      "phonetic": "/'fʌni/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "形容",
      "serialNumber": "183"
    },
    {
      "word": "photo",
      "meaning": "照片；相片",
      "grade": "5.1",
      "phonetic": "/'fəutəu/",
      "highlightLetters": "ph",
      "highlightPhonetic": "/f/",
      "note": "ph读/f/",
      "partOfSpeech": "名",
      "serialNumber": "184"
    },
    {
      "word": "hamburger",
      "meaning": "汉堡包",
      "grade": "5.1",
      "phonetic": "/'hæmbɜ:gə/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "185"
    },
    {
      "word": "bridge",
      "meaning": "桥",
      "grade": "5.1",
      "phonetic": "/bridʒ/",
      "highlightLetters": "dge",
      "highlightPhonetic": "/dʒ/",
      "note": "g读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "186"
    },
    {
      "word": "village",
      "meaning": "村庄",
      "grade": "5.1",
      "phonetic": "/'vilidʒ/",
      "highlightLetters": "g",
      "highlightPhonetic": "/dʒ/",
      "note": "g读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "187"
    },
    {
      "word": "high",
      "meaning": "高的",
      "grade": "5.1",
      "phonetic": "/hai/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "形容",
      "serialNumber": "188"
    },
    {
      "word": "hill",
      "meaning": "山丘；小山",
      "grade": "5.1",
      "phonetic": "/hil/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "189"
    },
    {
      "word": "him",
      "meaning": "(用于动词或介词之后)他",
      "grade": "5.1",
      "phonetic": "/him/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代",
      "serialNumber": "190"
    },
    {
      "word": "hot",
      "meaning": "辣的；热的",
      "grade": "5.1",
      "phonetic": "/hɒt/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "形容",
      "serialNumber": "191"
    },
    {
      "word": "house",
      "meaning": "房子；住宅",
      "grade": "5.1",
      "phonetic": "/haus/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "192"
    },
    {
      "word": "kind",
      "meaning": "体贴的；友善的",
      "grade": "5.1",
      "phonetic": "/kaind/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "形容",
      "serialNumber": "193"
    },
    {
      "word": "know",
      "meaning": "知道；了解",
      "grade": "5.1",
      "phonetic": "/nəu/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "不发音",
      "partOfSpeech": "动",
      "serialNumber": "194"
    },
    {
      "word": "kung fu",
      "meaning": "功夫；武术",
      "grade": "5.1",
      "phonetic": "/,kʌŋ'fu:/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "不可数名",
      "serialNumber": "195"
    },
    {
      "word": "lake",
      "meaning": "湖；湖泊",
      "grade": "5.1",
      "phonetic": "/leik/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "196"
    },
    {
      "word": "cook",
      "meaning": "烹调；做饭",
      "grade": "5.1",
      "phonetic": "/kuk/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "动",
      "serialNumber": "197"
    },
    {
      "word": "park",
      "meaning": "公园",
      "grade": "5.1",
      "phonetic": "/pɑ:k/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "198"
    },
    {
      "word": "lake",
      "meaning": "湖；湖泊",
      "grade": "5.1",
      "phonetic": "/leik/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "199"
    },
    {
      "word": "learn",
      "meaning": "学；学习；学会",
      "grade": "5.1",
      "phonetic": "/lɜ:n/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "200"
    },
    {
      "word": "live",
      "meaning": "住；居住",
      "grade": "5.1",
      "phonetic": "/liv/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "201"
    },
    {
      "word": "lot",
      "meaning": "大量；许多",
      "grade": "5.1",
      "phonetic": "/lɒt/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "202"
    },
    {
      "word": "Monday",
      "meaning": "星期一",
      "grade": "5.1",
      "phonetic": "/'mʌndei/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "203"
    },
    {
      "word": "mountain",
      "meaning": "高山；山脉",
      "grade": "5.1",
      "phonetic": "/'mauntən/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "204"
    },
    {
      "word": "mouse",
      "meaning": "老鼠",
      "grade": "5.1",
      "phonetic": "/maus/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "205"
    },
    {
      "word": "move",
      "meaning": "搬家",
      "grade": "5.1",
      "phonetic": "/mu:v/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "动",
      "serialNumber": "206"
    },
    {
      "word": "sometimes",
      "meaning": "有时；间或",
      "grade": "5.1",
      "phonetic": "/'sʌmtaimz/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "副",
      "serialNumber": "207"
    },
    {
      "word": "time",
      "meaning": "时间（不可数）",
      "grade": "5.1",
      "phonetic": "/taim/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "不可数名",
      "serialNumber": "208"
    },
    {
      "word": "times",
      "meaning": "次数；时段（复数）",
      "grade": "5.1",
      "phonetic": "/taimz/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名,复数",
      "serialNumber": "209"
    },
    {
      "word": "problem",
      "meaning": "问题",
      "grade": "5.1",
      "phonetic": "/'prɒbləm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "210"
    },
    {
      "word": "next",
      "meaning": "下一个的；接下来的",
      "grade": "5.1",
      "phonetic": "/nekst/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "形容",
      "serialNumber": "211"
    },
    {
      "word": "know",
      "meaning": "知道；了解",
      "grade": "5.1",
      "phonetic": "/nəu/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "动",
      "serialNumber": "212"
    },
    {
      "word": "nature",
      "meaning": "自然界；大自然",
      "grade": "5.1",
      "phonetic": "/'neitʃə(r)/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "213"
    },
    {
      "word": "onion",
      "meaning": "洋葱",
      "grade": "5.1",
      "phonetic": "/'ʌnjən/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "214"
    },
    {
      "word": "finish",
      "meaning": "完成",
      "grade": "5.1",
      "phonetic": "/'finiʃ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "动",
      "serialNumber": "215"
    },
    {
      "word": "funny",
      "meaning": "滑稽的；可笑的",
      "grade": "5.1",
      "phonetic": "/'fʌni/",
      "highlightLetters": "nn",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "形容",
      "serialNumber": "216"
    },
    {
      "word": "end",
      "meaning": "末尾",
      "grade": "5.1",
      "phonetic": "/end/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "217"
    },
    {
      "word": "want",
      "meaning": "要；想要",
      "grade": "5.1",
      "phonetic": "/wɒnt/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "动",
      "serialNumber": "218"
    },
    {
      "word": "parent",
      "meaning": "父(母)",
      "grade": "5.1",
      "phonetic": "/'peərənt/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "219"
    },
    {
      "word": "park",
      "meaning": "公园",
      "grade": "5.1",
      "phonetic": "/pɑ:k/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "220"
    },
    {
      "word": "party",
      "meaning": "聚会；派对",
      "grade": "5.1",
      "phonetic": "/'pɑ:ti/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "221"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "5.1",
      "phonetic": "/ˈkwaiət/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "形容",
      "serialNumber": "222"
    },
    {
      "word": "quite",
      "meaning": "非常；十分",
      "grade": "5.1",
      "phonetic": "/ˈkwait/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "副",
      "serialNumber": "223"
    },
    {
      "word": "queen",
      "meaning": "女王",
      "grade": "5.1",
      "phonetic": "/kwiːn/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "名",
      "serialNumber": "224"
    },
    {
      "word": "read",
      "meaning": "看书；读书",
      "grade": "5.1",
      "phonetic": "/ri:d/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "动",
      "serialNumber": "225"
    },
    {
      "word": "river",
      "meaning": "河；江",
      "grade": "5.1",
      "phonetic": "/'rivə/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "226"
    },
    {
      "word": "rabbit",
      "meaning": "兔；野兔",
      "grade": "5.1",
      "phonetic": "/'ræbit/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "227"
    },
    {
      "word": "robot",
      "meaning": "机器人",
      "grade": "5.1",
      "phonetic": "/'rəubɒt/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "228"
    },
    {
      "word": "sing",
      "meaning": "唱；唱歌",
      "grade": "5.1",
      "phonetic": "/siŋ/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "动",
      "serialNumber": "229"
    },
    {
      "word": "song",
      "meaning": "歌曲",
      "grade": "5.1",
      "phonetic": "/sɒŋ/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "230"
    },
    {
      "word": "some",
      "meaning": "一些（不可数或可数复数）",
      "grade": "5.1",
      "phonetic": "/sʌm/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "形容",
      "serialNumber": "231"
    },
    {
      "word": "photos",
      "meaning": "照片(复数)",
      "grade": "5.1",
      "phonetic": "/'fəutəuz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "232"
    },
    {
      "word": "times",
      "meaning": "次数；时段（复数）",
      "grade": "5.1",
      "phonetic": "/taimz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "233"
    },
    {
      "word": "sometimes",
      "meaning": "有时；间或",
      "grade": "5.1",
      "phonetic": "/'sʌmtaimz/",
      "highlightLetters": "第2个s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "副",
      "serialNumber": "234"
    },
    {
      "word": "Tuesday",
      "meaning": "星期二",
      "grade": "5.1",
      "phonetic": "/'tju:zdei/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "235"
    },
    {
      "word": "Wednesday",
      "meaning": "星期三",
      "grade": "5.1",
      "phonetic": "/'wenzdei/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "236"
    },
    {
      "word": "Thursday",
      "meaning": "星期四",
      "grade": "5.1",
      "phonetic": "/'θɜ:zdei/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "237"
    },
    {
      "word": "tea",
      "meaning": "茶；茶水",
      "grade": "5.1",
      "phonetic": "/ti:/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "不可数名",
      "serialNumber": "238"
    },
    {
      "word": "cartoon",
      "meaning": "漫画;卡通",
      "grade": "5.1",
      "phonetic": "/kɑ:'tu:n/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "239"
    },
    {
      "word": "at",
      "meaning": "在(后面接邮件地址)",
      "grade": "5.1",
      "phonetic": "/æt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "介",
      "serialNumber": "240"
    },
    {
      "word": "hot",
      "meaning": "辣的；热的",
      "grade": "5.1",
      "phonetic": "/hɒt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形容",
      "serialNumber": "241"
    },
    {
      "word": "lot",
      "meaning": "大量；许多",
      "grade": "5.1",
      "phonetic": "/lɒt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "242"
    },
    {
      "word": "next",
      "meaning": "下一个的；紧接着的；接下来的",
      "grade": "5.1",
      "phonetic": "/nekst/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形容",
      "serialNumber": "243"
    },
    {
      "word": "plant",
      "meaning": "植物",
      "grade": "5.1",
      "phonetic": "/plɑ:nt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "244"
    },
    {
      "word": "want",
      "meaning": "要；想要",
      "grade": "5.1",
      "phonetic": "/wɒnt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "245"
    },
    {
      "word": "bottle",
      "meaning": "瓶子",
      "grade": "5.1",
      "phonetic": "/'bɒtl/",
      "highlightLetters": "tt",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "246"
    },
    {
      "word": "often",
      "meaning": "时常；经常",
      "grade": "5.1",
      "phonetic": "/'ɒfn/",
      "highlightLetters": "t",
      "highlightPhonetic": "",
      "note": "t不发音",
      "partOfSpeech": "副",
      "serialNumber": "247"
    },
    {
      "word": "village",
      "meaning": "村庄",
      "grade": "5.1",
      "phonetic": "/'vilidʒ/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "248"
    },
    {
      "word": "above",
      "meaning": "在……上方",
      "grade": "5.1",
      "phonetic": "/ə'bʌv/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "介",
      "serialNumber": "249"
    },
    {
      "word": "live",
      "meaning": "住；居住",
      "grade": "5.1",
      "phonetic": "/liv/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "动",
      "serialNumber": "250"
    },
    {
      "word": "move",
      "meaning": "搬家",
      "grade": "5.1",
      "phonetic": "/mu:v/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "动",
      "serialNumber": "251"
    },
    {
      "word": "clever",
      "meaning": "聪明的；聪颖的",
      "grade": "5.1",
      "phonetic": "/'klevə(r)/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "形容",
      "serialNumber": "252"
    },
    {
      "word": "river",
      "meaning": "河；江",
      "grade": "5.1",
      "phonetic": "/'rivə/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "253"
    },
    {
      "word": "every",
      "meaning": "每个",
      "grade": "5.1",
      "phonetic": "/'evri/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "形容",
      "serialNumber": "254"
    },
    {
      "word": "favourite",
      "meaning": "特别喜爱的",
      "grade": "5.1",
      "phonetic": "/'feivərit/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "形容",
      "serialNumber": "255"
    },
    {
      "word": "of",
      "meaning": "的",
      "grade": "5.1",
      "phonetic": "/əv/",
      "highlightLetters": "f",
      "highlightPhonetic": "/v/",
      "note": "f读/v/",
      "partOfSpeech": "介",
      "serialNumber": "256"
    },
    {
      "word": "want",
      "meaning": "要；想要",
      "grade": "5.1",
      "phonetic": "/wɒnt/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "257"
    },
    {
      "word": "wash",
      "meaning": "洗",
      "grade": "5.1",
      "phonetic": "/wɒʃ/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "258"
    },
    {
      "word": "watch",
      "meaning": "观看；观察",
      "grade": "5.1",
      "phonetic": "/wɒtʃ/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "259"
    },
    {
      "word": "week",
      "meaning": "周",
      "grade": "5.1",
      "phonetic": "/wi:k/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "260"
    },
    {
      "word": "weekend",
      "meaning": "周末",
      "grade": "5.1",
      "phonetic": "/,wi:k'end/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "261"
    },
    {
      "word": "will",
      "meaning": "将要",
      "grade": "5.1",
      "phonetic": "/wil/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "262"
    },
    {
      "word": "wonderful",
      "meaning": "极好的；了不起的",
      "grade": "5.1",
      "phonetic": "/'wʌndəfl/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "形容",
      "serialNumber": "263"
    },
    {
      "word": "young",
      "meaning": "年轻的",
      "grade": "5.1",
      "phonetic": "/jʌŋ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （辅音）",
      "partOfSpeech": "形容",
      "serialNumber": "264"
    },
    {
      "word": "sing",
      "meaning": "唱；唱歌",
      "grade": "5.1",
      "phonetic": "/siŋ/",
      "highlightLetters": "ng",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "动",
      "serialNumber": "265"
    },
    {
      "word": "song",
      "meaning": "歌曲",
      "grade": "5.1",
      "phonetic": "/sɒŋ/",
      "highlightLetters": "ng",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "名",
      "serialNumber": "266"
    },
    {
      "word": "boating",
      "meaning": "划船",
      "grade": "5.1",
      "phonetic": "/'bəutiŋ/",
      "highlightLetters": "ng",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "267"
    },
    {
      "word": "building",
      "meaning": "建筑物；楼房",
      "grade": "5.1",
      "phonetic": "/'bildiŋ/",
      "highlightLetters": "ng",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "268"
    },
    {
      "word": "cooking",
      "meaning": "烹饪；做饭",
      "grade": "5.1",
      "phonetic": "/'kukiŋ/",
      "highlightLetters": "ng",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "269"
    },
    {
      "word": "hard-working",
      "meaning": "工作努力的；辛勤的",
      "grade": "5.1",
      "phonetic": "/,hɑ:d'wɜ:kiŋ/",
      "highlightLetters": "ng",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "270"
    },
    {
      "word": "pingpong",
      "meaning": "乒乓球",
      "grade": "5.1",
      "phonetic": "/'piŋpɒŋ/",
      "highlightLetters": "ng,ng",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "名",
      "serialNumber": "271"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "5.1",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "数",
      "serialNumber": "272"
    },
    {
      "word": "between",
      "meaning": "在……（两者）之间",
      "grade": "5.1",
      "phonetic": "/bi'twi:n/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "介",
      "serialNumber": "273"
    },
    {
      "word": "health",
      "meaning": "健康",
      "grade": "5.1",
      "phonetic": "/'helθ/",
      "highlightLetters": "lth",
      "highlightPhonetic": "/lθ/",
      "note": "lth读/lθ/",
      "partOfSpeech": "名",
      "serialNumber": "274"
    },
    {
      "word": "help",
      "meaning": "帮助",
      "grade": "5.1",
      "phonetic": "/'help/",
      "highlightLetters": "lp",
      "highlightPhonetic": "/lp/",
      "note": "lp读/lp/",
      "partOfSpeech": "动",
      "serialNumber": "275"
    },
    {
      "word": "bridge",
      "meaning": "桥",
      "grade": "5.1",
      "phonetic": "/bridʒ/",
      "highlightLetters": "br",
      "highlightPhonetic": "/br/",
      "note": "br读/br/",
      "partOfSpeech": "名",
      "serialNumber": "276"
    },
    {
      "word": "cream",
      "meaning": "奶油；淡黄色",
      "grade": "5.1",
      "phonetic": "/kri:m/",
      "highlightLetters": "cr",
      "highlightPhonetic": "/kr/",
      "note": "kr读/kr/",
      "partOfSpeech": "不可数名",
      "serialNumber": "277"
    },
    {
      "word": "draw",
      "meaning": "画",
      "grade": "5.1",
      "phonetic": "/drɔ:/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "动",
      "serialNumber": "278"
    },
    {
      "word": "drink",
      "meaning": "喝；饮",
      "grade": "5.1",
      "phonetic": "/driŋk/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "动",
      "serialNumber": "279"
    },
    {
      "word": "fresh",
      "meaning": "新鲜的；刚摘的",
      "grade": "5.1",
      "phonetic": "/freʃ/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "形容",
      "serialNumber": "280"
    },
    {
      "word": "Friday",
      "meaning": "星期五",
      "grade": "5.1",
      "phonetic": "/'fraidei/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "名",
      "serialNumber": "281"
    },
    {
      "word": "front",
      "meaning": "正面；前面",
      "grade": "5.1",
      "phonetic": "/frʌnt/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "名",
      "serialNumber": "282"
    },
    {
      "word": "grandparent",
      "meaning": "(外)祖父(母)",
      "grade": "5.1",
      "phonetic": "/'grænpeərənt/",
      "highlightLetters": "gr",
      "highlightPhonetic": "/ɡr/",
      "note": "gr读/ɡr/",
      "partOfSpeech": "名",
      "serialNumber": "283"
    },
    {
      "word": "problem",
      "meaning": "问题",
      "grade": "5.1",
      "phonetic": "/'prɒbləm/",
      "highlightLetters": "pr",
      "highlightPhonetic": "/pr/",
      "note": "pr读/pr/",
      "partOfSpeech": "名",
      "serialNumber": "284"
    },
    {
      "word": "clever",
      "meaning": "聪明的；聪颖的",
      "grade": "5.1",
      "phonetic": "/'klevə(r)/",
      "highlightLetters": "kl",
      "highlightPhonetic": "/kl/",
      "note": "kl读/fl/",
      "partOfSpeech": "形容",
      "serialNumber": "285"
    },
    {
      "word": "clock",
      "meaning": "时钟；钟",
      "grade": "5.1",
      "phonetic": "/klɒk/",
      "highlightLetters": "kl",
      "highlightPhonetic": "/kl/",
      "note": "kl读/fl/",
      "partOfSpeech": "名",
      "serialNumber": "286"
    },
    {
      "word": "flower",
      "meaning": "花朵",
      "grade": "5.1",
      "phonetic": "/'flauə/",
      "highlightLetters": "fl",
      "highlightPhonetic": "/fl/",
      "note": "fl读/ɡl/",
      "partOfSpeech": "名",
      "serialNumber": "287"
    },
    {
      "word": "plant",
      "meaning": "植物",
      "grade": "5.1",
      "phonetic": "/plɑ:nt/",
      "highlightLetters": "pl",
      "highlightPhonetic": "/pl/",
      "note": "pl读/kl/",
      "partOfSpeech": "名",
      "serialNumber": "288"
    },
    {
      "word": "play",
      "meaning": "玩；打（球）；放（音乐）",
      "grade": "5.1",
      "phonetic": "/ˈpleɪ/",
      "highlightLetters": "pl",
      "highlightPhonetic": "/pl/",
      "note": "pl读/kl/",
      "partOfSpeech": "动",
      "serialNumber": "289"
    },
    {
      "word": "speak",
      "meaning": "讲，说(+某种语言)",
      "grade": "5.1",
      "phonetic": "/spi:k/",
      "highlightLetters": "sp",
      "highlightPhonetic": "/sp/",
      "note": "sp读/sp/",
      "partOfSpeech": "动",
      "serialNumber": "290"
    },
    {
      "word": "sport",
      "meaning": "体育运动",
      "grade": "5.1",
      "phonetic": "/spɔ:t/",
      "highlightLetters": "sp",
      "highlightPhonetic": "/sp/",
      "note": "sp读/sp/",
      "partOfSpeech": "名",
      "serialNumber": "291"
    },
    {
      "word": "strict",
      "meaning": "严格的；严厉的",
      "grade": "5.1",
      "phonetic": "/strikt/",
      "highlightLetters": "str",
      "highlightPhonetic": "/str/",
      "note": "str读/str/",
      "partOfSpeech": "形容",
      "serialNumber": "292"
    },
    {
      "word": "sweet",
      "meaning": "含糖的；甜的",
      "grade": "5.1",
      "phonetic": "/swi:t/",
      "highlightLetters": "sw",
      "highlightPhonetic": "/sw/",
      "note": "sw读/sw/",
      "partOfSpeech": "形容",
      "serialNumber": "293"
    },
    {
      "word": "swim",
      "meaning": "游泳",
      "grade": "5.1",
      "phonetic": "/swim/",
      "highlightLetters": "sw",
      "highlightPhonetic": "/sw/",
      "note": "sw读/sw/",
      "partOfSpeech": "动",
      "serialNumber": "294"
    },
    {
      "word": "shy",
      "meaning": "害羞的；腼腆的",
      "grade": "5.1",
      "phonetic": "/ʃai/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "形容",
      "serialNumber": "295"
    },
    {
      "word": "should",
      "meaning": "(纠正别人)应该，应当",
      "grade": "5.1",
      "phonetic": "/ʃud/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "动",
      "serialNumber": "296"
    },
    {
      "word": "schedule",
      "meaning": "工作计划；日程安排",
      "grade": "5.1",
      "phonetic": "/'ʃedju:l/",
      "highlightLetters": "sch",
      "highlightPhonetic": "/ʃ/",
      "note": "sch读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "297"
    }
  ]
};
