// 自动生成的JS模块 - grade4_1.json
// 生成时间: 2025-12-20T02:20:06.954Z

module.exports = {
  "grade": 4,
  "semester": 1,
  "gradeName": "小学四年级上册",
  "total": 304,
  "lastUpdated": "2025-12-20T02:06:14.892Z",
  "words": [
    {
      "word": "date",
      "meaning": "日期",
      "grade": "4.1",
      "phonetic": "/deɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "1"
    },
    {
      "word": "hate",
      "meaning": "憎恨；讨厌",
      "grade": "4.1",
      "phonetic": "/heɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "2"
    },
    {
      "word": "table",
      "meaning": "桌子",
      "grade": "4.1",
      "phonetic": "/ˈteɪbl/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "3"
    },
    {
      "word": "grape",
      "meaning": "葡萄",
      "grade": "4.1",
      "phonetic": "/ɡreɪp/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "4"
    },
    {
      "word": "plate",
      "meaning": "盘子",
      "grade": "4.1",
      "phonetic": "/pleɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "5"
    },
    {
      "word": "these",
      "meaning": "这些",
      "grade": "4.1",
      "phonetic": "/ðiːz/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "e读字母音/iː/",
      "partOfSpeech": "代;形",
      "serialNumber": "6"
    },
    {
      "word": "Chinese",
      "meaning": "汉语（的）；中国（的）",
      "grade": "4.1",
      "phonetic": "/ˌtʃaɪˈniːz /",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "e读字母音/iː/",
      "partOfSpeech": "名;形",
      "serialNumber": "7"
    },
    {
      "word": "see",
      "meaning": "看见",
      "grade": "4.1",
      "phonetic": "/siː/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "动",
      "serialNumber": "8"
    },
    {
      "word": "beef",
      "meaning": "牛肉",
      "grade": "4.1",
      "phonetic": "/biːf/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "9"
    },
    {
      "word": "keep",
      "meaning": "保有；留着",
      "grade": "4.1",
      "phonetic": "/kiːp/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "动",
      "serialNumber": "10"
    },
    {
      "word": "knife",
      "meaning": "刀",
      "grade": "4.1",
      "phonetic": "/naɪf/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "11"
    },
    {
      "word": "size",
      "meaning": "尺寸",
      "grade": "4.1",
      "phonetic": "/saɪz/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "12"
    },
    {
      "word": "smile",
      "meaning": "微笑",
      "grade": "4.1",
      "phonetic": "/smaɪl/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "13"
    },
    {
      "word": "white",
      "meaning": "白色(的)",
      "grade": "4.1",
      "phonetic": "/waɪt/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名;形",
      "serialNumber": "14"
    },
    {
      "word": "write",
      "meaning": "写",
      "grade": "4.1",
      "phonetic": "/raɪt/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "15"
    },
    {
      "word": "by",
      "meaning": "以……方式",
      "grade": "4.1",
      "phonetic": "/baɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "介",
      "serialNumber": "16"
    },
    {
      "word": "my",
      "meaning": "我的",
      "grade": "4.1",
      "phonetic": "/maɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "代",
      "serialNumber": "17"
    },
    {
      "word": "why",
      "meaning": "为什么",
      "grade": "4.1",
      "phonetic": "/waɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "副",
      "serialNumber": "18"
    },
    {
      "word": "bone",
      "meaning": "骨头",
      "grade": "4.1",
      "phonetic": "/bəʊn/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "19"
    },
    {
      "word": "cone",
      "meaning": "圆锥形物体",
      "grade": "4.1",
      "phonetic": "/kəʊn/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "代;形",
      "serialNumber": "20"
    },
    {
      "word": "phone",
      "meaning": "电话",
      "grade": "4.1",
      "phonetic": "/fəʊn/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "21"
    },
    {
      "word": "hope",
      "meaning": "希望",
      "grade": "4.1",
      "phonetic": "/həʊp/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "22"
    },
    {
      "word": "joke",
      "meaning": "玩笑",
      "grade": "4.1",
      "phonetic": "/dʒəʊk/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "23"
    },
    {
      "word": "note",
      "meaning": "笔记",
      "grade": "4.1",
      "phonetic": "/ˈnəʊt/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "24"
    },
    {
      "word": "use",
      "meaning": "使用",
      "grade": "4.1",
      "phonetic": "/juːz/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "动",
      "serialNumber": "25"
    },
    {
      "word": "excuse",
      "meaning": "原谅",
      "grade": "4.1",
      "phonetic": "/iks'kjuːz/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "动",
      "serialNumber": "26"
    },
    {
      "word": "cute",
      "meaning": "可爱的",
      "grade": "4.1",
      "phonetic": "/kjuːt/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "形",
      "serialNumber": "27"
    },
    {
      "word": "mute",
      "meaning": "哑的；无声的",
      "grade": "4.1",
      "phonetic": "/mjuːt/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "形",
      "serialNumber": "28"
    },
    {
      "word": "tube",
      "meaning": "管子",
      "grade": "4.1",
      "phonetic": "/tjuːb/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "29"
    },
    {
      "word": "student",
      "meaning": "学生",
      "grade": "4.1",
      "phonetic": "/ˈstjuːdnt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "30"
    },
    {
      "word": "computer",
      "meaning": "计算机；电脑",
      "grade": "4.1",
      "phonetic": "/kəmˈpjuːtə(r)/",
      "highlightLetters": "u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "31"
    },
    {
      "word": "fan",
      "meaning": "风扇",
      "grade": "4.1",
      "phonetic": "/fæn/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "32"
    },
    {
      "word": "hat",
      "meaning": "(带檐的) 帽子",
      "grade": "4.1",
      "phonetic": "/hæt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "33"
    },
    {
      "word": "black",
      "meaning": "黑色（的）",
      "grade": "4.1",
      "phonetic": "/blæk/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名;形",
      "serialNumber": "34"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "4.1",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "35"
    },
    {
      "word": "help",
      "meaning": "帮助",
      "grade": "4.1",
      "phonetic": "/help/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "36"
    },
    {
      "word": "ready",
      "meaning": "准备好的",
      "grade": "4.1",
      "phonetic": "/ˈredi/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "37"
    },
    {
      "word": "them",
      "meaning": "他（她、它）们",
      "grade": "4.1",
      "phonetic": "/ðem/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "代",
      "serialNumber": "38"
    },
    {
      "word": "friendly",
      "meaning": "友好的",
      "grade": "4.1",
      "phonetic": "/ˈfrendli/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "39"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "4.1",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "40"
    },
    {
      "word": "his",
      "meaning": "他的",
      "grade": "4.1",
      "phonetic": "/hɪz/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "代",
      "serialNumber": "41"
    },
    {
      "word": "stick",
      "meaning": "棒子；拐杖",
      "grade": "4.1",
      "phonetic": "/stɪk/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "42"
    },
    {
      "word": "which",
      "meaning": "哪一个",
      "grade": "4.1",
      "phonetic": "/wɪtʃ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "代",
      "serialNumber": "43"
    },
    {
      "word": "fridge",
      "meaning": "冰箱",
      "grade": "4.1",
      "phonetic": "/frɪdʒ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "44"
    },
    {
      "word": "little",
      "meaning": "小的",
      "grade": "4.1",
      "phonetic": "/ˈlɪtl/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "45"
    },
    {
      "word": "dinner",
      "meaning": "正餐",
      "grade": "4.1",
      "phonetic": "/ˈdɪnə(r)/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "46"
    },
    {
      "word": "window",
      "meaning": "窗户",
      "grade": "4.1",
      "phonetic": "/ˈwɪndəʊ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "47"
    },
    {
      "word": "job",
      "meaning": "工作",
      "grade": "4.1",
      "phonetic": "/dʒɒb/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "48"
    },
    {
      "word": "lost",
      "meaning": "丢失的（lose的过去式形式）",
      "grade": "4.1",
      "phonetic": "/lɒst/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "49"
    },
    {
      "word": "strong",
      "meaning": "强壮的",
      "grade": "4.1",
      "phonetic": "/strɒŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "50"
    },
    {
      "word": "doctor",
      "meaning": "医生",
      "grade": "4.1",
      "phonetic": "/ˈdɒktə(r)/",
      "highlightLetters": "第1个o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "51"
    },
    {
      "word": "chopstick(s)",
      "meaning": "筷子(复数)",
      "grade": "4.1",
      "phonetic": "/ˈtʃɒpstɪk(s)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名,复数",
      "serialNumber": "52"
    },
    {
      "word": "but",
      "meaning": "但是",
      "grade": "4.1",
      "phonetic": "/bʌt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "con连",
      "serialNumber": "53"
    },
    {
      "word": "much",
      "meaning": "许多的(+不可数名词)",
      "grade": "4.1",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "形",
      "serialNumber": "54"
    },
    {
      "word": "puppy",
      "meaning": "小狗",
      "grade": "4.1",
      "phonetic": "/ˈpʌpi/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "55"
    },
    {
      "word": "study",
      "meaning": "书房",
      "grade": "4.1",
      "phonetic": "/ˈstʌdi/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "56"
    },
    {
      "word": "cousin",
      "meaning": "同辈表亲（或堂亲）",
      "grade": "4.1",
      "phonetic": "/ˈkʌzn/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʌ/",
      "note": "ou读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "57"
    },
    {
      "word": "book",
      "meaning": "书",
      "grade": "4.1",
      "phonetic": "/bʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "58"
    },
    {
      "word": "cook",
      "meaning": "厨师",
      "grade": "4.1",
      "phonetic": "/kʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "59"
    },
    {
      "word": "look",
      "meaning": "看",
      "grade": "4.1",
      "phonetic": "/lʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "60"
    },
    {
      "word": "foot",
      "meaning": "脚",
      "grade": "4.1",
      "phonetic": "/fʊt/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "61"
    },
    {
      "word": "good",
      "meaning": "好的",
      "grade": "4.1",
      "phonetic": "/ɡʊd/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "形",
      "serialNumber": "62"
    },
    {
      "word": "put",
      "meaning": "放置",
      "grade": "4.1",
      "phonetic": "/pʊt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʊ/",
      "note": "u读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "63"
    },
    {
      "word": "woman",
      "meaning": "妇女",
      "grade": "4.1",
      "phonetic": "/ˈwʊmən/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʊ/",
      "note": "o读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "64"
    },
    {
      "word": "aunt",
      "meaning": "姑母；姨母",
      "grade": "4.1",
      "phonetic": "/ɑːnt/",
      "highlightLetters": "au",
      "highlightPhonetic": "/ɑː/",
      "note": "au读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "65"
    },
    {
      "word": "farmer",
      "meaning": "农民",
      "grade": "4.1",
      "phonetic": "/ˈfɑːmə(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "66"
    },
    {
      "word": "pass",
      "meaning": "给；递",
      "grade": "4.1",
      "phonetic": "/pɑːs/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "动",
      "serialNumber": "67"
    },
    {
      "word": "class",
      "meaning": "班级",
      "grade": "4.1",
      "phonetic": "/klɑːs/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "68"
    },
    {
      "word": "glasses",
      "meaning": "眼镜",
      "grade": "4.1",
      "phonetic": "/ˈɡlɑːsɪz/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名,复数",
      "serialNumber": "69"
    },
    {
      "word": "basketball",
      "meaning": "篮球",
      "grade": "4.1",
      "phonetic": "/ˈbɑːskɪtbɔːl/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "70"
    },
    {
      "word": "bathroom",
      "meaning": "浴室；洗手间",
      "grade": "4.1",
      "phonetic": "/ˈbɑːθruːm/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "71"
    },
    {
      "word": "or",
      "meaning": "或者",
      "grade": "4.1",
      "phonetic": "/ɔː(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "con连",
      "serialNumber": "72"
    },
    {
      "word": "fork",
      "meaning": "餐叉",
      "grade": "4.1",
      "phonetic": "/fɔːk/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "73"
    },
    {
      "word": "story",
      "meaning": "故事",
      "grade": "4.1",
      "phonetic": "/stɔːri/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "74"
    },
    {
      "word": "door",
      "meaning": "门",
      "grade": "4.1",
      "phonetic": "/dɔː(r)/",
      "highlightLetters": "oor",
      "highlightPhonetic": "/ɔː/",
      "note": "oor读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "75"
    },
    {
      "word": "floor",
      "meaning": "地板",
      "grade": "4.1",
      "phonetic": "/flɔː(r)/",
      "highlightLetters": "oor",
      "highlightPhonetic": "/ɔː/",
      "note": "oor读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "76"
    },
    {
      "word": "wall",
      "meaning": "墙壁",
      "grade": "4.1",
      "phonetic": "/wɔːl/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "77"
    },
    {
      "word": "ball",
      "meaning": "球",
      "grade": "4.1",
      "phonetic": "/bɔːl/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "78"
    },
    {
      "word": "board",
      "meaning": "板",
      "grade": "4.1",
      "phonetic": "/bɔːd/",
      "highlightLetters": "oar",
      "highlightPhonetic": "/ɔː/",
      "note": "oar读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "79"
    },
    {
      "word": "her",
      "meaning": "她；她的",
      "grade": "4.1",
      "phonetic": "/hɜː(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ɜː/",
      "note": "er重读长音/ɜː/",
      "partOfSpeech": "代",
      "serialNumber": "80"
    },
    {
      "word": "learn",
      "meaning": "学习",
      "grade": "4.1",
      "phonetic": "/lɜːn/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɜː/",
      "note": "ear读长元音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "81"
    },
    {
      "word": "nurse",
      "meaning": "护士",
      "grade": "4.1",
      "phonetic": "/nɜːs/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "82"
    },
    {
      "word": "purple",
      "meaning": "紫色(的)",
      "grade": "4.1",
      "phonetic": "/ˈpɜːpl/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名;形",
      "serialNumber": "83"
    },
    {
      "word": "beef",
      "meaning": "牛肉",
      "grade": "4.1",
      "phonetic": "/biːf/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "84"
    },
    {
      "word": "clean",
      "meaning": "打扫",
      "grade": "4.1",
      "phonetic": "/kliːn/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "85"
    },
    {
      "word": "key",
      "meaning": "钥匙",
      "grade": "4.1",
      "phonetic": "/kiː/",
      "highlightLetters": "ey",
      "highlightPhonetic": "/iː/",
      "note": "ey读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "86"
    },
    {
      "word": "people",
      "meaning": "人们（复数）",
      "grade": "4.1",
      "phonetic": "/ˈpiːpl/",
      "highlightLetters": "eo",
      "highlightPhonetic": "/iː/",
      "note": "eo读长元音/iː/",
      "partOfSpeech": "名,复数",
      "serialNumber": "87"
    },
    {
      "word": "shoe",
      "meaning": "鞋",
      "grade": "4.1",
      "phonetic": "/ʃuː/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/uː/",
      "note": "oe读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "88"
    },
    {
      "word": "soup",
      "meaning": "汤",
      "grade": "4.1",
      "phonetic": "/suːp/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/uː/",
      "note": "ou读长元音/uː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "89"
    },
    {
      "word": "room",
      "meaning": "房间",
      "grade": "4.1",
      "phonetic": "/ruːm/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "90"
    },
    {
      "word": "school",
      "meaning": "学校",
      "grade": "4.1",
      "phonetic": "/skuːl/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "91"
    },
    {
      "word": "spoon",
      "meaning": "勺",
      "grade": "4.1",
      "phonetic": "/spuːn/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "92"
    },
    {
      "word": "noodles",
      "meaning": "面条",
      "grade": "4.1",
      "phonetic": "/ˈnuːdlz/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名,复数",
      "serialNumber": "93"
    },
    {
      "word": "mate",
      "meaning": "伙伴，同伴",
      "grade": "4.1",
      "phonetic": "/meɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "94"
    },
    {
      "word": "table",
      "meaning": "桌子",
      "grade": "4.1",
      "phonetic": "/ˈteɪbl/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "95"
    },
    {
      "word": "baby",
      "meaning": "婴儿",
      "grade": "4.1",
      "phonetic": "/ˈbeɪbi/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "96"
    },
    {
      "word": "player",
      "meaning": "运动员",
      "grade": "4.1",
      "phonetic": "/ˈpleɪə(r)/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "97"
    },
    {
      "word": "knife",
      "meaning": "刀",
      "grade": "4.1",
      "phonetic": "/naɪf/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "98"
    },
    {
      "word": "driver",
      "meaning": "司机",
      "grade": "4.1",
      "phonetic": "/ˈdraɪvə(r)/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "99"
    },
    {
      "word": "find",
      "meaning": "找到",
      "grade": "4.1",
      "phonetic": "/faɪnd/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "100"
    },
    {
      "word": "light",
      "meaning": "电灯",
      "grade": "4.1",
      "phonetic": "/laɪt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "101"
    },
    {
      "word": "right",
      "meaning": "正确的; 对的",
      "grade": "4.1",
      "phonetic": "/raɪt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "102"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "4.1",
      "phonetic": "/ˈkwaɪət/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "103"
    },
    {
      "word": "try",
      "meaning": "试；尝试",
      "grade": "4.1",
      "phonetic": "/traɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y的重音读/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "104"
    },
    {
      "word": "boy",
      "meaning": "男生",
      "grade": "4.1",
      "phonetic": "/bɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "105"
    },
    {
      "word": "toy",
      "meaning": "玩具",
      "grade": "4.1",
      "phonetic": "/tɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "106"
    },
    {
      "word": "wow",
      "meaning": "哇；呀",
      "grade": "4.1",
      "phonetic": "/waʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/aʊ/",
      "note": "ow读双元音/aʊ/",
      "partOfSpeech": "int.感叹",
      "serialNumber": "107"
    },
    {
      "word": "now",
      "meaning": "现在",
      "grade": "4.1",
      "phonetic": "/naʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/aʊ/",
      "note": "ow读双元音/aʊ/",
      "partOfSpeech": "副",
      "serialNumber": "108"
    },
    {
      "word": "sofa",
      "meaning": "长沙发",
      "grade": "4.1",
      "phonetic": "/ˈsəʊfə/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "109"
    },
    {
      "word": "phone",
      "meaning": "电话",
      "grade": "4.1",
      "phonetic": "/fəʊn/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "110"
    },
    {
      "word": "notebook",
      "meaning": "笔记本",
      "grade": "4.1",
      "phonetic": "/ˈnəʊtbʊk/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "111"
    },
    {
      "word": "bowl",
      "meaning": "碗",
      "grade": "4.1",
      "phonetic": "/bəʊl/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "112"
    },
    {
      "word": "window",
      "meaning": "窗户",
      "grade": "4.1",
      "phonetic": "/ˈwɪndəʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "113"
    },
    {
      "word": "near",
      "meaning": "在……附近",
      "grade": "4.1",
      "phonetic": "/nɪə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɪə/",
      "note": "ear读双元音/ɪə/",
      "partOfSpeech": "介",
      "serialNumber": "114"
    },
    {
      "word": "here",
      "meaning": "在这儿",
      "grade": "4.1",
      "phonetic": "/hɪə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/ɪə/",
      "note": "ere读双元音/ɪə/",
      "partOfSpeech": "副",
      "serialNumber": "115"
    },
    {
      "word": "really",
      "meaning": "（表示惊讶）真地",
      "grade": "4.1",
      "phonetic": "/ˈrɪəli/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/ɪə/",
      "note": "ea读双元音/ɪə/",
      "partOfSpeech": "副",
      "serialNumber": "116"
    },
    {
      "word": "bear",
      "meaning": "熊",
      "grade": "4.1",
      "phonetic": "/beə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/eə/",
      "note": "ear读双元音/eə/",
      "partOfSpeech": "名",
      "serialNumber": "117"
    },
    {
      "word": "hair",
      "meaning": "头发",
      "grade": "4.1",
      "phonetic": "/heə(r)/",
      "highlightLetters": "air",
      "highlightPhonetic": "/eə/",
      "note": "air读双元音/eə/",
      "partOfSpeech": "名",
      "serialNumber": "118"
    },
    {
      "word": "parents",
      "meaning": "父母",
      "grade": "4.1",
      "phonetic": "/ˈpeərənts/",
      "highlightLetters": "are",
      "highlightPhonetic": "/eə/",
      "note": "are读双元音/eə/",
      "partOfSpeech": "名,复数",
      "serialNumber": "119"
    },
    {
      "word": "there",
      "meaning": "在那儿",
      "grade": "4.1",
      "phonetic": "/ðeə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "120"
    },
    {
      "word": "where",
      "meaning": "在哪儿",
      "grade": "4.1",
      "phonetic": "/weə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "121"
    },
    {
      "word": "sure",
      "meaning": "当然可以",
      "grade": "4.1",
      "phonetic": "/ʃuə(r)/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/uə/",
      "note": "ure读双元音/uə/",
      "partOfSpeech": "副",
      "serialNumber": "122"
    },
    {
      "word": "poor",
      "meaning": "穷的；可怜的",
      "grade": "4.1",
      "phonetic": "/puə(r)/",
      "highlightLetters": "oor",
      "highlightPhonetic": "/uə/",
      "note": "oor读双元音/uə/",
      "partOfSpeech": "形",
      "serialNumber": "123"
    },
    {
      "word": "sofa",
      "meaning": "长沙发",
      "grade": "4.1",
      "phonetic": "/ˈsəʊfə/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "124"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "4.1",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "125"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "4.1",
      "phonetic": "/ˈkwaɪət/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "126"
    },
    {
      "word": "computer",
      "meaning": "计算机",
      "grade": "4.1",
      "phonetic": "/kəmˈpjuːtə(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "127"
    },
    {
      "word": "really",
      "meaning": "（表惊讶）真地",
      "grade": "4.1",
      "phonetic": "/ˈrɪəli/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "副",
      "serialNumber": "128"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "4.1",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "129"
    },
    {
      "word": "puppy",
      "meaning": "小狗",
      "grade": "4.1",
      "phonetic": "/ˈpʌpi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "130"
    },
    {
      "word": "ready",
      "meaning": "准备好的",
      "grade": "4.1",
      "phonetic": "/ˈredi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "131"
    },
    {
      "word": "study",
      "meaning": "书房",
      "grade": "4.1",
      "phonetic": "/ˈstʌdi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "132"
    },
    {
      "word": "friendly",
      "meaning": "友好的",
      "grade": "4.1",
      "phonetic": "/ˈfrendli/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "133"
    },
    {
      "word": "driver",
      "meaning": "司机",
      "grade": "4.1",
      "phonetic": "/ˈdraɪvə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "134"
    },
    {
      "word": "farmer",
      "meaning": "农民",
      "grade": "4.1",
      "phonetic": "/ˈfɑːmə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "135"
    },
    {
      "word": "dinner",
      "meaning": "正餐",
      "grade": "4.1",
      "phonetic": "/ˈdɪnə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "136"
    },
    {
      "word": "doctor",
      "meaning": "医生",
      "grade": "4.1",
      "phonetic": "/ˈdɒktə(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ə/",
      "note": "or弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "137"
    },
    {
      "word": "picture",
      "meaning": "图画",
      "grade": "4.1",
      "phonetic": "/ˈpɪktʃə(r)/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/ə/",
      "note": "ure弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "138"
    },
    {
      "word": "colour",
      "meaning": "颜色",
      "grade": "4.1",
      "phonetic": "/ˈkʌlə(r)/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ə/",
      "note": "our弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "139"
    },
    {
      "word": "chicken",
      "meaning": "鸡肉",
      "grade": "4.1",
      "phonetic": "/ˈtʃɪkin/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "不可数名",
      "serialNumber": "140"
    },
    {
      "word": "kitchen",
      "meaning": "厨房",
      "grade": "4.1",
      "phonetic": "/ˈkɪtʃin/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "141"
    },
    {
      "word": "cousin",
      "meaning": "同辈表亲（或堂亲）",
      "grade": "4.1",
      "phonetic": "/ˈkʌzn/",
      "highlightLetters": "sin",
      "highlightPhonetic": "/zn/",
      "note": "/zn/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "142"
    },
    {
      "word": "uncle",
      "meaning": "舅；叔；伯/姑/姨父",
      "grade": "4.1",
      "phonetic": "/ˈʌŋkl/",
      "highlightLetters": "cle",
      "highlightPhonetic": "/kl/",
      "note": "/kl/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "143"
    },
    {
      "word": "noodles",
      "meaning": "面条",
      "grade": "4.1",
      "phonetic": "/ˈnuːdlz/",
      "highlightLetters": "dle",
      "highlightPhonetic": "/dl/",
      "note": "/dl/弱音省略",
      "partOfSpeech": "名,复数",
      "serialNumber": "144"
    },
    {
      "word": "people",
      "meaning": "人们",
      "grade": "4.1",
      "phonetic": "/ˈpiːpl/",
      "highlightLetters": "ple",
      "highlightPhonetic": "/pl/",
      "note": "/pl/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "145"
    },
    {
      "word": "little",
      "meaning": "小的",
      "grade": "4.1",
      "phonetic": "/ˈlɪtl/",
      "highlightLetters": "ttle",
      "highlightPhonetic": "/tl/",
      "note": "/tl/弱音省略",
      "partOfSpeech": "形",
      "serialNumber": "146"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "4.1",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "ble",
      "highlightPhonetic": "/bl/",
      "note": "/bl/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "147"
    },
    {
      "word": "job",
      "meaning": "工作",
      "grade": "4.1",
      "phonetic": "/dʒɒb/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "148"
    },
    {
      "word": "but",
      "meaning": "但是",
      "grade": "4.1",
      "phonetic": "/bʌt/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "con连",
      "serialNumber": "149"
    },
    {
      "word": "bath",
      "meaning": "洗澡",
      "grade": "4.1",
      "phonetic": "/bɑːθ/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "150"
    },
    {
      "word": "basket",
      "meaning": "篮子",
      "grade": "4.1",
      "phonetic": "/bɑːskɪt/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "151"
    },
    {
      "word": "beef",
      "meaning": "牛肉",
      "grade": "4.1",
      "phonetic": "/biːf/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "不可数名",
      "serialNumber": "152"
    },
    {
      "word": "black",
      "meaning": "黑色（的）",
      "grade": "4.1",
      "phonetic": "/blæk/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名;形",
      "serialNumber": "153"
    },
    {
      "word": "bowl",
      "meaning": "碗",
      "grade": "4.1",
      "phonetic": "/bəʊl/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "154"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "4.1",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名",
      "serialNumber": "155"
    },
    {
      "word": "cook",
      "meaning": "厨师;做饭",
      "grade": "4.1",
      "phonetic": "/kʊk/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名;动",
      "serialNumber": "156"
    },
    {
      "word": "cousin",
      "meaning": "同辈表亲（或堂亲）",
      "grade": "4.1",
      "phonetic": "/ˈkʌzn/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在u前）",
      "partOfSpeech": "名",
      "serialNumber": "157"
    },
    {
      "word": "cute",
      "meaning": "可爱的",
      "grade": "4.1",
      "phonetic": "/kjuːt/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在辅音前）",
      "partOfSpeech": "形",
      "serialNumber": "158"
    },
    {
      "word": "clean",
      "meaning": "打扫",
      "grade": "4.1",
      "phonetic": "/kliːn/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在辅音前）",
      "partOfSpeech": "动",
      "serialNumber": "159"
    },
    {
      "word": "doctor",
      "meaning": "医生",
      "grade": "4.1",
      "phonetic": "/ˈdɒktə(r)/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在辅音前）",
      "partOfSpeech": "名",
      "serialNumber": "160"
    },
    {
      "word": "picture",
      "meaning": "图画",
      "grade": "4.1",
      "phonetic": "/ˈpɪktʃə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "161"
    },
    {
      "word": "bed",
      "meaning": "床",
      "grade": "4.1",
      "phonetic": "/bed/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "162"
    },
    {
      "word": "find",
      "meaning": "找到",
      "grade": "4.1",
      "phonetic": "/faɪnd/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "163"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "4.1",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "164"
    },
    {
      "word": "door",
      "meaning": "门",
      "grade": "4.1",
      "phonetic": "/dɔː(r)/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "165"
    },
    {
      "word": "dinner",
      "meaning": "正餐",
      "grade": "4.1",
      "phonetic": "/ˈdɪnə(r)/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "166"
    },
    {
      "word": "doctor",
      "meaning": "医生",
      "grade": "4.1",
      "phonetic": "/ˈdɒktə(r)/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "167"
    },
    {
      "word": "fan",
      "meaning": "风扇",
      "grade": "4.1",
      "phonetic": "/fæn/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "168"
    },
    {
      "word": "find",
      "meaning": "找到",
      "grade": "4.1",
      "phonetic": "/faɪnd/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "169"
    },
    {
      "word": "fork",
      "meaning": "餐叉",
      "grade": "4.1",
      "phonetic": "/fɔːk/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "170"
    },
    {
      "word": "farmer",
      "meaning": "农民",
      "grade": "4.1",
      "phonetic": "/ˈfɑːmə(r)/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "171"
    },
    {
      "word": "beef",
      "meaning": "牛肉",
      "grade": "4.1",
      "phonetic": "/biːf/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "不可数名",
      "serialNumber": "172"
    },
    {
      "word": "sofa",
      "meaning": "长沙发",
      "grade": "4.1",
      "phonetic": "/ˈsəʊfə/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "173"
    },
    {
      "word": "knife",
      "meaning": "刀",
      "grade": "4.1",
      "phonetic": "/naɪf/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "174"
    },
    {
      "word": "giraffe",
      "meaning": "长颈鹿",
      "grade": "4.1",
      "phonetic": "/dʒəˈrɑːf/",
      "highlightLetters": "ff",
      "highlightPhonetic": "/f/",
      "note": "ff读/f/",
      "partOfSpeech": "名",
      "serialNumber": "175"
    },
    {
      "word": "phone",
      "meaning": "电话",
      "grade": "4.1",
      "phonetic": "/fəʊn/",
      "highlightLetters": "ph",
      "highlightPhonetic": "/f/",
      "note": "ph读/f/",
      "partOfSpeech": "名",
      "serialNumber": "176"
    },
    {
      "word": "bag",
      "meaning": "包；袋",
      "grade": "4.1",
      "phonetic": "/bæɡ/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "177"
    },
    {
      "word": "garden",
      "meaning": "花园",
      "grade": "4.1",
      "phonetic": "/ˈɡɑːdn/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "178"
    },
    {
      "word": "glasses",
      "meaning": "眼镜",
      "grade": "4.1",
      "phonetic": "/ˈɡlɑːsɪz/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名,复数",
      "serialNumber": "179"
    },
    {
      "word": "grass",
      "meaning": "草（地）（不可数）",
      "grade": "4.1",
      "phonetic": "/ɡrɑːs/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "180"
    },
    {
      "word": "has",
      "meaning": "（他/她/它）有",
      "grade": "4.1",
      "phonetic": "/hæz/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "181"
    },
    {
      "word": "hat",
      "meaning": "(常指带檐的) 帽子",
      "grade": "4.1",
      "phonetic": "/hæt/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "182"
    },
    {
      "word": "her",
      "meaning": "她，她的",
      "grade": "4.1",
      "phonetic": "/hɜː(r)/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代",
      "serialNumber": "183"
    },
    {
      "word": "his",
      "meaning": "他的；他的东西",
      "grade": "4.1",
      "phonetic": "/hɪz/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代",
      "serialNumber": "184"
    },
    {
      "word": "hair",
      "meaning": "头发",
      "grade": "4.1",
      "phonetic": "/heə(r)/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "185"
    },
    {
      "word": "help",
      "meaning": "帮助",
      "grade": "4.1",
      "phonetic": "/help/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "186"
    },
    {
      "word": "have",
      "meaning": "（我/你/他们）有",
      "grade": "4.1",
      "phonetic": "/hæv/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "187"
    },
    {
      "word": "who",
      "meaning": "谁",
      "grade": "4.1",
      "phonetic": "/hu:/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代",
      "serialNumber": "188"
    },
    {
      "word": "cook",
      "meaning": "厨师;做饭",
      "grade": "4.1",
      "phonetic": "/kʊk/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名;动",
      "serialNumber": "189"
    },
    {
      "word": "key",
      "meaning": "钥匙",
      "grade": "4.1",
      "phonetic": "/kiː/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "190"
    },
    {
      "word": "kitchen",
      "meaning": "厨房",
      "grade": "4.1",
      "phonetic": "/ˈkɪtʃɪn/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "191"
    },
    {
      "word": "basket",
      "meaning": "篮了",
      "grade": "4.1",
      "phonetic": "/ˈbɑːskɪtbɔːl/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "192"
    },
    {
      "word": "stick",
      "meaning": "棒子",
      "grade": "4.1",
      "phonetic": "/stɪk/",
      "highlightLetters": "ck",
      "highlightPhonetic": "/k/",
      "note": "ck读/k/",
      "partOfSpeech": "名",
      "serialNumber": "193"
    },
    {
      "word": "black",
      "meaning": "黑板",
      "grade": "4.1",
      "phonetic": "/blæk/",
      "highlightLetters": "ck",
      "highlightPhonetic": "/k/",
      "note": "ck读/k/",
      "partOfSpeech": "名;形",
      "serialNumber": "194"
    },
    {
      "word": "chicken",
      "meaning": "鸡肉",
      "grade": "4.1",
      "phonetic": "/ˈtʃɪkɪn/",
      "highlightLetters": "ck",
      "highlightPhonetic": "/k/",
      "note": "ck读/k/",
      "partOfSpeech": "不可数名",
      "serialNumber": "195"
    },
    {
      "word": "knife",
      "meaning": "刀",
      "grade": "4.1",
      "phonetic": "/naɪf/",
      "highlightLetters": "kn",
      "highlightPhonetic": "/n/",
      "note": "k不发音",
      "partOfSpeech": "名",
      "serialNumber": "196"
    },
    {
      "word": "light",
      "meaning": "电灯",
      "grade": "4.1",
      "phonetic": "/laɪt/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "197"
    },
    {
      "word": "little",
      "meaning": "小的",
      "grade": "4.1",
      "phonetic": "/ˈlɪtl/",
      "highlightLetters": "l, l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "形",
      "serialNumber": "198"
    },
    {
      "word": "lost",
      "meaning": "丢失的",
      "grade": "4.1",
      "phonetic": "/lɒst/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "形",
      "serialNumber": "199"
    },
    {
      "word": "bowl",
      "meaning": "碗",
      "grade": "4.1",
      "phonetic": "/bəʊl/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "200"
    },
    {
      "word": "real",
      "meaning": "真的",
      "grade": "4.1",
      "phonetic": "/ˈrɪəl/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "形",
      "serialNumber": "201"
    },
    {
      "word": "school",
      "meaning": "学校",
      "grade": "4.1",
      "phonetic": "/ˈskuːl/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "名",
      "serialNumber": "202"
    },
    {
      "word": "ball",
      "meaning": "球",
      "grade": "4.1",
      "phonetic": "/bɔːl/",
      "highlightLetters": "ll",
      "highlightPhonetic": "/l/",
      "note": "ll读/l/(元音后)",
      "partOfSpeech": "名",
      "serialNumber": "203"
    },
    {
      "word": "wall",
      "meaning": "墙壁",
      "grade": "4.1",
      "phonetic": "/wɔːl/",
      "highlightLetters": "ll",
      "highlightPhonetic": "/l/",
      "note": "ll读/l/(元音后)",
      "partOfSpeech": "名",
      "serialNumber": "204"
    },
    {
      "word": "help",
      "meaning": "帮助",
      "grade": "4.1",
      "phonetic": "/help/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "动",
      "serialNumber": "205"
    },
    {
      "word": "them",
      "meaning": "他（她、它）们",
      "grade": "4.1",
      "phonetic": "/ðem/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "代",
      "serialNumber": "206"
    },
    {
      "word": "room",
      "meaning": "房间",
      "grade": "4.1",
      "phonetic": "/ruːm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "207"
    },
    {
      "word": "computer",
      "meaning": "计算机",
      "grade": "4.1",
      "phonetic": "/kəmˈpjuːtə(r)/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "208"
    },
    {
      "word": "farmer",
      "meaning": "农民",
      "grade": "4.1",
      "phonetic": "/ˈfɑːmə(r)/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "209"
    },
    {
      "word": "noodles",
      "meaning": "面条(复数)",
      "grade": "4.1",
      "phonetic": "/ˈnuːdlz/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名,复数",
      "serialNumber": "210"
    },
    {
      "word": "note",
      "meaning": "笔记",
      "grade": "4.1",
      "phonetic": "/nəʊt/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "211"
    },
    {
      "word": "nurse",
      "meaning": "护士",
      "grade": "4.1",
      "phonetic": "/nɜːs/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "212"
    },
    {
      "word": "phone",
      "meaning": "电话",
      "grade": "4.1",
      "phonetic": "/fəʊn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "213"
    },
    {
      "word": "spoon",
      "meaning": "勺",
      "grade": "4.1",
      "phonetic": "/spuːn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "214"
    },
    {
      "word": "parents",
      "meaning": "父母",
      "grade": "4.1",
      "phonetic": "/ˈpeərənts/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名,复数",
      "serialNumber": "215"
    },
    {
      "word": "uncle",
      "meaning": "舅父；叔父；伯父；姑父；姨父",
      "grade": "4.1",
      "phonetic": "/ˈʌŋkl/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "n读/ŋ/（在/k/音前）",
      "partOfSpeech": "名",
      "serialNumber": "216"
    },
    {
      "word": "pink",
      "meaning": "粉色（的）",
      "grade": "4.1",
      "phonetic": "/pɪŋk/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "n读/ŋ/（在/k/音前）",
      "partOfSpeech": "名;形",
      "serialNumber": "217"
    },
    {
      "word": "monkey",
      "meaning": "猴子",
      "grade": "4.1",
      "phonetic": "/ˈmʌŋki/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "n读/ŋ/（在/k/音前）",
      "partOfSpeech": "名",
      "serialNumber": "218"
    },
    {
      "word": "living",
      "meaning": "生活的，居住的",
      "grade": "4.1",
      "phonetic": "/ˈlɪvɪŋ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "形",
      "serialNumber": "219"
    },
    {
      "word": "strong",
      "meaning": "强壮的",
      "grade": "4.1",
      "phonetic": "/strɒŋ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "形",
      "serialNumber": "220"
    },
    {
      "word": "pass",
      "meaning": "给；递",
      "grade": "4.1",
      "phonetic": "/pɑːs/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "动",
      "serialNumber": "221"
    },
    {
      "word": "parents",
      "meaning": "父母",
      "grade": "4.1",
      "phonetic": "/ˈpeərənts/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名,复数",
      "serialNumber": "222"
    },
    {
      "word": "people",
      "meaning": "人们",
      "grade": "4.1",
      "phonetic": "/ˈpiːpl/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名,复数",
      "serialNumber": "223"
    },
    {
      "word": "picture",
      "meaning": "图画",
      "grade": "4.1",
      "phonetic": "/ˈpɪktʃə(r)/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "224"
    },
    {
      "word": "puppy",
      "meaning": "小狗",
      "grade": "4.1",
      "phonetic": "/ˈpʌpi/",
      "highlightLetters": "p, pp",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "225"
    },
    {
      "word": "purple",
      "meaning": "紫色(的)",
      "grade": "4.1",
      "phonetic": "/ˈpɜːpl/",
      "highlightLetters": "p, p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名;形",
      "serialNumber": "226"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "4.1",
      "phonetic": "/ˈkwaiət/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "形",
      "serialNumber": "227"
    },
    {
      "word": "quite",
      "meaning": "非常；十分",
      "grade": "4.1",
      "phonetic": "/ˈkwait/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "副",
      "serialNumber": "228"
    },
    {
      "word": "queen",
      "meaning": "女王",
      "grade": "4.1",
      "phonetic": "/kwiːn/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "名",
      "serialNumber": "229"
    },
    {
      "word": "ready",
      "meaning": "准备好",
      "grade": "4.1",
      "phonetic": "/ˈredi/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "形",
      "serialNumber": "230"
    },
    {
      "word": "really",
      "meaning": "真地",
      "grade": "4.1",
      "phonetic": "/ˈrɪəli/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "副",
      "serialNumber": "231"
    },
    {
      "word": "right",
      "meaning": "正确的; 对的",
      "grade": "4.1",
      "phonetic": "/raɪt/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "形",
      "serialNumber": "232"
    },
    {
      "word": "sofa",
      "meaning": "长沙发",
      "grade": "4.1",
      "phonetic": "/ˈsəʊfə/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "233"
    },
    {
      "word": "soup",
      "meaning": "汤（不可数，视为单数）",
      "grade": "4.1",
      "phonetic": "/suːp/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "不可数名",
      "serialNumber": "234"
    },
    {
      "word": "basket",
      "meaning": "篮子",
      "grade": "4.1",
      "phonetic": "/bɑːskɪt/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "235"
    },
    {
      "word": "lost",
      "meaning": "丢失的",
      "grade": "4.1",
      "phonetic": "/lɒst/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "形",
      "serialNumber": "236"
    },
    {
      "word": "nurse",
      "meaning": "护士",
      "grade": "4.1",
      "phonetic": "/nɜːs/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "形",
      "serialNumber": "237"
    },
    {
      "word": "pass",
      "meaning": "给；递",
      "grade": "4.1",
      "phonetic": "/pɑːs/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "动",
      "serialNumber": "238"
    },
    {
      "word": "books",
      "meaning": "书(复数)",
      "grade": "4.1",
      "phonetic": "/bʊks/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名,复数",
      "serialNumber": "239"
    },
    {
      "word": "forks",
      "meaning": "餐叉（复数）",
      "grade": "4.1",
      "phonetic": "/fɔːks/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名,复数",
      "serialNumber": "240"
    },
    {
      "word": "maths",
      "meaning": "数学（不可数，视为单数）",
      "grade": "4.1",
      "phonetic": "/mæθs/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "不可数名",
      "serialNumber": "241"
    },
    {
      "word": "parents",
      "meaning": "父母（双亲，复数）",
      "grade": "4.1",
      "phonetic": "/ˈpeərənts/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名,复数",
      "serialNumber": "242"
    },
    {
      "word": "his",
      "meaning": "他的",
      "grade": "4.1",
      "phonetic": "/hɪz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "代",
      "serialNumber": "243"
    },
    {
      "word": "jobs",
      "meaning": "工作（复数）",
      "grade": "4.1",
      "phonetic": "/dʒɒbz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "244"
    },
    {
      "word": "fans",
      "meaning": "风扇（复数）",
      "grade": "4.1",
      "phonetic": "/fænz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "245"
    },
    {
      "word": "keys",
      "meaning": "钥匙（复数）",
      "grade": "4.1",
      "phonetic": "/kiːz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "246"
    },
    {
      "word": "toys",
      "meaning": "玩具(复数)",
      "grade": "4.1",
      "phonetic": "/tɔɪz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "247"
    },
    {
      "word": "doors",
      "meaning": "门（复数）",
      "grade": "4.1",
      "phonetic": "/dɔː(r)z/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "248"
    },
    {
      "word": "cousins",
      "meaning": "堂/表兄弟姐妹（复数）",
      "grade": "4.1",
      "phonetic": "/ˈkʌznz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "249"
    },
    {
      "word": "noodles",
      "meaning": "面条（复数）",
      "grade": "4.1",
      "phonetic": "/ˈnuːdlz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "250"
    },
    {
      "word": "glasses",
      "meaning": "眼镜（复数）",
      "grade": "4.1",
      "phonetic": "/ˈɡlɑːsɪz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "最后1个s读/z/",
      "partOfSpeech": "名,复数",
      "serialNumber": "251"
    },
    {
      "word": "table",
      "meaning": "桌子",
      "grade": "4.1",
      "phonetic": "/ˈteɪbl/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "252"
    },
    {
      "word": "toy",
      "meaning": "玩具",
      "grade": "4.1",
      "phonetic": "/tɔɪ/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "253"
    },
    {
      "word": "lost",
      "meaning": "丢失的",
      "grade": "4.1",
      "phonetic": "/lɒst/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形",
      "serialNumber": "254"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "4.1",
      "phonetic": "/ˈkwaɪət/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形",
      "serialNumber": "255"
    },
    {
      "word": "light",
      "meaning": "电灯",
      "grade": "4.1",
      "phonetic": "/laɪt/",
      "highlightLetters": "ght",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "256"
    },
    {
      "word": "right",
      "meaning": "正确的; 对的",
      "grade": "4.1",
      "phonetic": "/raɪt/",
      "highlightLetters": "ght",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形",
      "serialNumber": "257"
    },
    {
      "word": "picture",
      "meaning": "图画",
      "grade": "4.1",
      "phonetic": "/ˈpɪktʃə(r)/",
      "highlightLetters": "t",
      "highlightPhonetic": "/tʃ/",
      "note": "t读/tʃ/",
      "partOfSpeech": "名",
      "serialNumber": "258"
    },
    {
      "word": "driver",
      "meaning": "司机",
      "grade": "4.1",
      "phonetic": "/ˈdraɪvə(r)/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "259"
    },
    {
      "word": "knives",
      "meaning": "刀(复数)",
      "grade": "4.1",
      "phonetic": "/naɪvz/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名,复数",
      "serialNumber": "260"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "4.1",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "261"
    },
    {
      "word": "wall",
      "meaning": "墙壁",
      "grade": "4.1",
      "phonetic": "/wɔːl/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "262"
    },
    {
      "word": "window",
      "meaning": "窗户",
      "grade": "4.1",
      "phonetic": "/ˈwɪndəʊ/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "263"
    },
    {
      "word": "wow",
      "meaning": "哇；呀",
      "grade": "4.1",
      "phonetic": "/waʊ/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "int.感叹",
      "serialNumber": "264"
    },
    {
      "word": "what",
      "meaning": "什么",
      "grade": "4.1",
      "phonetic": "/wɒt/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "代",
      "serialNumber": "265"
    },
    {
      "word": "white",
      "meaning": "白色(的)",
      "grade": "4.1",
      "phonetic": "/waɪt/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名;形",
      "serialNumber": "266"
    },
    {
      "word": "fox",
      "meaning": "狐狸",
      "grade": "4.1",
      "phonetic": "/fɒks/",
      "highlightLetters": "x",
      "highlightPhonetic": "/ks/",
      "note": "x读/ks/",
      "partOfSpeech": "名",
      "serialNumber": "267"
    },
    {
      "word": "six",
      "meaning": "六",
      "grade": "4.1",
      "phonetic": "/sɪks/",
      "highlightLetters": "x",
      "highlightPhonetic": "/ks/",
      "note": "x读/ks/",
      "partOfSpeech": "数",
      "serialNumber": "268"
    },
    {
      "word": "yourself",
      "meaning": "你自己",
      "grade": "4.1",
      "phonetic": "/jɔːˈself/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （用作辅音）",
      "partOfSpeech": "代",
      "serialNumber": "269"
    },
    {
      "word": "yummy",
      "meaning": "很好吃的",
      "grade": "4.1",
      "phonetic": "/ˈjʌmi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （用作辅音）",
      "partOfSpeech": "形",
      "serialNumber": "270"
    },
    {
      "word": "zip",
      "meaning": "拉链",
      "grade": "4.1",
      "phonetic": "/zɪp/",
      "highlightLetters": "z",
      "highlightPhonetic": "/z/",
      "note": "z读/z/",
      "partOfSpeech": "名",
      "serialNumber": "271"
    },
    {
      "word": "quiz",
      "meaning": "小测验",
      "grade": "4.1",
      "phonetic": "/kwɪz/",
      "highlightLetters": "z",
      "highlightPhonetic": "/z/",
      "note": "z读/z/",
      "partOfSpeech": "名",
      "serialNumber": "272"
    },
    {
      "word": "lost",
      "meaning": "丢失的",
      "grade": "4.1",
      "phonetic": "/lɒst/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "形",
      "serialNumber": "273"
    },
    {
      "word": "help",
      "meaning": "帮助",
      "grade": "4.1",
      "phonetic": "/help/",
      "highlightLetters": "lp",
      "highlightPhonetic": "/lp/",
      "note": "lf读/lf/",
      "partOfSpeech": "动",
      "serialNumber": "274"
    },
    {
      "word": "yourself",
      "meaning": "你自己",
      "grade": "4.1",
      "phonetic": "/jɔːˈself/",
      "highlightLetters": "lf",
      "highlightPhonetic": "/lf/",
      "note": "lf读/lf/",
      "partOfSpeech": "代",
      "serialNumber": "275"
    },
    {
      "word": "fridge",
      "meaning": "冰箱",
      "grade": "4.1",
      "phonetic": "/frɪdʒ/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "名",
      "serialNumber": "276"
    },
    {
      "word": "friendly",
      "meaning": "友好的",
      "grade": "4.1",
      "phonetic": "/ˈfrendli/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "形",
      "serialNumber": "277"
    },
    {
      "word": "driver",
      "meaning": "司机",
      "grade": "4.1",
      "phonetic": "/ˈdraɪvə(r)/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "名",
      "serialNumber": "278"
    },
    {
      "word": "bedroom",
      "meaning": "卧室",
      "grade": "4.1",
      "phonetic": "/ˈbedruːm/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "名",
      "serialNumber": "279"
    },
    {
      "word": "try",
      "meaning": "试；尝试",
      "grade": "4.1",
      "phonetic": "/traɪ/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/tr/",
      "partOfSpeech": "动",
      "serialNumber": "280"
    },
    {
      "word": "bathroom",
      "meaning": "浴室；洗手间",
      "grade": "4.1",
      "phonetic": "/ˈbɑːθruːm/",
      "highlightLetters": "thr",
      "highlightPhonetic": "/θr/",
      "note": "thr读/θr/",
      "partOfSpeech": "名",
      "serialNumber": "281"
    },
    {
      "word": "class",
      "meaning": "班级",
      "grade": "4.1",
      "phonetic": "/klɑːs/",
      "highlightLetters": "cl",
      "highlightPhonetic": "/kl/",
      "note": "cl读/kl/",
      "partOfSpeech": "名",
      "serialNumber": "282"
    },
    {
      "word": "clean",
      "meaning": "打扫",
      "grade": "4.1",
      "phonetic": "/kliːn/",
      "highlightLetters": "cl",
      "highlightPhonetic": "/kl/",
      "note": "cl读/kl/",
      "partOfSpeech": "动",
      "serialNumber": "283"
    },
    {
      "word": "floor",
      "meaning": "地板",
      "grade": "4.1",
      "phonetic": "/flɔː(r)/",
      "highlightLetters": "fl",
      "highlightPhonetic": "/fl/",
      "note": "fl读/fl/",
      "partOfSpeech": "名",
      "serialNumber": "284"
    },
    {
      "word": "glasses",
      "meaning": "眼镜",
      "grade": "4.1",
      "phonetic": "/ˈɡlɑːsɪz/",
      "highlightLetters": "gl",
      "highlightPhonetic": "/ɡl/",
      "note": "gl读/ɡl/",
      "partOfSpeech": "名,复数",
      "serialNumber": "285"
    },
    {
      "word": "spoon",
      "meaning": "勺",
      "grade": "4.1",
      "phonetic": "/spuːn/",
      "highlightLetters": "sp",
      "highlightPhonetic": "/sp/",
      "note": "sp读/sp/",
      "partOfSpeech": "名",
      "serialNumber": "286"
    },
    {
      "word": "story",
      "meaning": "故事",
      "grade": "4.1",
      "phonetic": "/stɔːri/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "名",
      "serialNumber": "287"
    },
    {
      "word": "study",
      "meaning": "书房",
      "grade": "4.1",
      "phonetic": "/ˈstʌdi/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "名",
      "serialNumber": "288"
    },
    {
      "word": "strong",
      "meaning": "强壮的",
      "grade": "4.1",
      "phonetic": "/strɒŋ/",
      "highlightLetters": "str",
      "highlightPhonetic": "/str/",
      "note": "str读/str/",
      "partOfSpeech": "形",
      "serialNumber": "289"
    },
    {
      "word": "China",
      "meaning": "中国",
      "grade": "4.1",
      "phonetic": "/ˈtʃaɪnə/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "名",
      "serialNumber": "290"
    },
    {
      "word": "much",
      "meaning": "许多；大量",
      "grade": "4.1",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "形",
      "serialNumber": "291"
    },
    {
      "word": "touch",
      "meaning": "触摸；碰",
      "grade": "4.1",
      "phonetic": "/tʌtʃ/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "动",
      "serialNumber": "292"
    },
    {
      "word": "teacher",
      "meaning": "教师",
      "grade": "4.1",
      "phonetic": "/ˈtiːtʃə(r)/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "名",
      "serialNumber": "293"
    },
    {
      "word": "shelf",
      "meaning": "架子",
      "grade": "4.1",
      "phonetic": "/ʃelf/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "294"
    },
    {
      "word": "short",
      "meaning": "短的；矮的",
      "grade": "4.1",
      "phonetic": "/ʃɔːt/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "形",
      "serialNumber": "295"
    },
    {
      "word": "the",
      "meaning": "这(那)个；这(那)些",
      "grade": "4.1",
      "phonetic": "/ðiː/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "冠",
      "serialNumber": "296"
    },
    {
      "word": "this",
      "meaning": "这个",
      "grade": "4.1",
      "phonetic": "/ðiz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "代;形",
      "serialNumber": "297"
    },
    {
      "word": "that",
      "meaning": "那个",
      "grade": "4.1",
      "phonetic": "/ðæt/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "代;形",
      "serialNumber": "298"
    },
    {
      "word": "these",
      "meaning": "这些",
      "grade": "4.1",
      "phonetic": "/ðiːz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "代;形",
      "serialNumber": "299"
    },
    {
      "word": "those",
      "meaning": "那些",
      "grade": "4.1",
      "phonetic": "/ðəuz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "代;形",
      "serialNumber": "300"
    },
    {
      "word": "them",
      "meaning": "他（她、它）们",
      "grade": "4.1",
      "phonetic": "/ðem/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "代",
      "serialNumber": "301"
    },
    {
      "word": "twelve",
      "meaning": "十二",
      "grade": "4.1",
      "phonetic": "/twelv/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "数",
      "serialNumber": "302"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "4.1",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "数",
      "serialNumber": "303"
    },
    {
      "word": "two",
      "meaning": "太；也",
      "grade": "4.1",
      "phonetic": "/tu:/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "数",
      "serialNumber": "304"
    }
  ]
};
