// 自动生成的JS模块 - grade4_2.json
// 生成时间: 2025-12-20T02:20:07.074Z

module.exports = {
  "grade": 4,
  "semester": 2,
  "gradeName": "小学四年级下册",
  "total": 362,
  "lastUpdated": "2025-12-20T02:06:14.921Z",
  "words": [
    {
      "word": "sale",
      "meaning": "特价销售; 大减价",
      "grade": "4.2",
      "phonetic": "/seɪl/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "1"
    },
    {
      "word": "grape",
      "meaning": "葡萄",
      "grade": "4.2",
      "phonetic": "/ɡreɪp/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "2"
    },
    {
      "word": "grapes",
      "meaning": "葡萄(复数)",
      "grade": "4.2",
      "phonetic": "/ɡreɪps/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "3"
    },
    {
      "word": "potato",
      "meaning": "土豆",
      "grade": "4.2",
      "phonetic": "/pəˈteɪtəʊ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "4"
    },
    {
      "word": "potatoes",
      "meaning": "土豆(复数)",
      "grade": "4.2",
      "phonetic": "/pəˈteɪtəʊz/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "5"
    },
    {
      "word": "be",
      "meaning": "be动词，起连接作用",
      "grade": "4.2",
      "phonetic": "/biː /",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读字母音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "6"
    },
    {
      "word": "PE",
      "meaning": "体育",
      "grade": "4.2",
      "phonetic": "/ˌpiː ˈiː /",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读字母音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "7"
    },
    {
      "word": "these",
      "meaning": "（this 的复数）这些",
      "grade": "4.2",
      "phonetic": "/ðiːz/",
      "highlightLetters": "e,e",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "代;形",
      "serialNumber": "8"
    },
    {
      "word": "green",
      "meaning": "绿色（的）",
      "grade": "4.2",
      "phonetic": "/ɡriːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "名;形",
      "serialNumber": "9"
    },
    {
      "word": "sheep",
      "meaning": "羊；绵羊",
      "grade": "4.2",
      "phonetic": "/ʃiːp/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "10"
    },
    {
      "word": "degree",
      "meaning": "度数",
      "grade": "4.2",
      "phonetic": "/dɪˈɡriː/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "11"
    },
    {
      "word": "mine",
      "meaning": "我的",
      "grade": "4.2",
      "phonetic": "/maɪn/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "代",
      "serialNumber": "12"
    },
    {
      "word": "nice",
      "meaning": "好的",
      "grade": "4.2",
      "phonetic": "/naɪs/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "13"
    },
    {
      "word": "size",
      "meaning": "尺码；号",
      "grade": "4.2",
      "phonetic": "/saɪz/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "14"
    },
    {
      "word": "outside",
      "meaning": "在户外",
      "grade": "4.2",
      "phonetic": "/ˌaʊtˈsaɪd/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "副",
      "serialNumber": "15"
    },
    {
      "word": "by",
      "meaning": "以/通过……方式；",
      "grade": "4.2",
      "phonetic": "/baɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "介",
      "serialNumber": "16"
    },
    {
      "word": "my",
      "meaning": "我的",
      "grade": "4.2",
      "phonetic": "/maɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "代",
      "serialNumber": "17"
    },
    {
      "word": "fly",
      "meaning": "飞；放（风筝等）",
      "grade": "4.2",
      "phonetic": "/flaɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "18"
    },
    {
      "word": "try",
      "meaning": "试试；尝试",
      "grade": "4.2",
      "phonetic": "/traɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "19"
    },
    {
      "word": "why",
      "meaning": "为什么",
      "grade": "4.2",
      "phonetic": "/waɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读/aɪ/",
      "partOfSpeech": "副",
      "serialNumber": "20"
    },
    {
      "word": "go",
      "meaning": "去",
      "grade": "4.2",
      "phonetic": "/ɡəʊ /",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "21"
    },
    {
      "word": "tomato",
      "meaning": "西红柿",
      "grade": "4.2",
      "phonetic": "/təˈmɑːtəʊ/",
      "highlightLetters": "第2个o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "22"
    },
    {
      "word": "home",
      "meaning": "家",
      "grade": "4.2",
      "phonetic": "/həʊm/",
      "highlightLetters": "o,e",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "23"
    },
    {
      "word": "those",
      "meaning": "（that 的复数）那些",
      "grade": "4.2",
      "phonetic": "/ðəʊz/",
      "highlightLetters": "o,e",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "代;形",
      "serialNumber": "24"
    },
    {
      "word": "homework",
      "meaning": "作业",
      "grade": "4.2",
      "phonetic": "/ˈhəʊmwɜːk/",
      "highlightLetters": "o,e",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "25"
    },
    {
      "word": "use",
      "meaning": "使用",
      "grade": "4.2",
      "phonetic": "/juːz/",
      "highlightLetters": "u,e",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "动",
      "serialNumber": "26"
    },
    {
      "word": "cute",
      "meaning": "可爱的",
      "grade": "4.2",
      "phonetic": "/kjuːt/",
      "highlightLetters": "u,e",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "形",
      "serialNumber": "27"
    },
    {
      "word": "pack",
      "meaning": "收拾（行李）",
      "grade": "4.2",
      "phonetic": "/pæk/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "动",
      "serialNumber": "28"
    },
    {
      "word": "pants",
      "meaning": "裤子",
      "grade": "4.2",
      "phonetic": "/pænts/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "29"
    },
    {
      "word": "carrot",
      "meaning": "胡萝卜",
      "grade": "4.2",
      "phonetic": "/ˈkærət/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "30"
    },
    {
      "word": "jacket",
      "meaning": "夹克衫",
      "grade": "4.2",
      "phonetic": "/ˈdʒækɪt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "31"
    },
    {
      "word": "animal",
      "meaning": "兽；动物",
      "grade": "4.2",
      "phonetic": "/ˈænɪml/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "32"
    },
    {
      "word": "get",
      "meaning": "到达；获得",
      "grade": "4.2",
      "phonetic": "/ɡet/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "33"
    },
    {
      "word": "hen",
      "meaning": "母鸡",
      "grade": "4.2",
      "phonetic": "/hen/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "34"
    },
    {
      "word": "next",
      "meaning": "下一个",
      "grade": "4.2",
      "phonetic": "/ˈnekst/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "35"
    },
    {
      "word": "dress",
      "meaning": "连衣裙",
      "grade": "4.2",
      "phonetic": "/dres/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "36"
    },
    {
      "word": "second",
      "meaning": "第二（的）",
      "grade": "4.2",
      "phonetic": "/ˈsekənd/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "数;形",
      "serialNumber": "37"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "4.2",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "数",
      "serialNumber": "38"
    },
    {
      "word": "expensive",
      "meaning": "昂贵的",
      "grade": "4.2",
      "phonetic": "/ɪkˈspensɪv/",
      "highlightLetters": "第2个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "39"
    },
    {
      "word": "umbrella",
      "meaning": "雨伞",
      "grade": "4.2",
      "phonetic": "/ʌmˈbrelə/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "40"
    },
    {
      "word": "breakfast",
      "meaning": "早餐",
      "grade": "4.2",
      "phonetic": "/ˈbrekfəst/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "不可数名",
      "serialNumber": "41"
    },
    {
      "word": "sweater",
      "meaning": "毛衣",
      "grade": "4.2",
      "phonetic": "/ˈswetə(r)/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "42"
    },
    {
      "word": "weather",
      "meaning": "天气",
      "grade": "4.2",
      "phonetic": "/ˈweðə(r)/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "不可数名",
      "serialNumber": "43"
    },
    {
      "word": "kid",
      "meaning": "小孩",
      "grade": "4.2",
      "phonetic": "/kɪd/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "44"
    },
    {
      "word": "dinner",
      "meaning": "正餐",
      "grade": "4.2",
      "phonetic": "/ˈdɪnə(r)/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "不可数名",
      "serialNumber": "45"
    },
    {
      "word": "fifty",
      "meaning": "五十",
      "grade": "4.2",
      "phonetic": "/ˈfɪfti/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "数",
      "serialNumber": "46"
    },
    {
      "word": "windy",
      "meaning": "刮风的",
      "grade": "4.2",
      "phonetic": "/ˈwɪndi/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "47"
    },
    {
      "word": "English",
      "meaning": "英语",
      "grade": "4.2",
      "phonetic": "/ˈɪŋɡliʃ /",
      "highlightLetters": "e",
      "highlightPhonetic": "/ɪ/",
      "note": "e读短音/ɪ /",
      "partOfSpeech": "名;形",
      "serialNumber": "48"
    },
    {
      "word": "pretty",
      "meaning": "美观的；精致的",
      "grade": "4.2",
      "phonetic": "/ˈprɪti/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ɪ/",
      "note": "e读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "49"
    },
    {
      "word": "Sydney",
      "meaning": "悉尼",
      "grade": "4.2",
      "phonetic": "/ˈsɪ(d)ni/",
      "highlightLetters": "y",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "50"
    },
    {
      "word": "of",
      "meaning": "……的",
      "grade": "4.2",
      "phonetic": "/ɒv/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "介",
      "serialNumber": "51"
    },
    {
      "word": "on",
      "meaning": "表示持续下去",
      "grade": "4.2",
      "phonetic": "/ɒn/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "介",
      "serialNumber": "52"
    },
    {
      "word": "hot",
      "meaning": "热的; 烫的；辣的",
      "grade": "4.2",
      "phonetic": "/hɒt/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "53"
    },
    {
      "word": "sock",
      "meaning": "短袜",
      "grade": "4.2",
      "phonetic": "/sɒk/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "54"
    },
    {
      "word": "o’clock",
      "meaning": "（表示整点）……点钟",
      "grade": "4.2",
      "phonetic": "/əˈklɒk/",
      "highlightLetters": "第2个o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "55"
    },
    {
      "word": "dollar",
      "meaning": "美（加）元",
      "grade": "4.2",
      "phonetic": "/ˈdɒlə(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "56"
    },
    {
      "word": "office",
      "meaning": "办公室",
      "grade": "4.2",
      "phonetic": "/ˈɒfɪs/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "57"
    },
    {
      "word": "up",
      "meaning": "向上地；朝上地",
      "grade": "4.2",
      "phonetic": "/ʌp/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "副",
      "serialNumber": "58"
    },
    {
      "word": "us",
      "meaning": "我们（用于动或介词之后）",
      "grade": "4.2",
      "phonetic": "/ʌs/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "代",
      "serialNumber": "59"
    },
    {
      "word": "yum",
      "meaning": "味道好的",
      "grade": "4.2",
      "phonetic": "/jʌm/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "形",
      "serialNumber": "60"
    },
    {
      "word": "just",
      "meaning": "正好；就；只",
      "grade": "4.2",
      "phonetic": "/dʒʌst/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "副",
      "serialNumber": "61"
    },
    {
      "word": "lunch",
      "meaning": "午餐；午饭",
      "grade": "4.2",
      "phonetic": "/lʌntʃ/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "不可数名",
      "serialNumber": "62"
    },
    {
      "word": "much",
      "meaning": "许多（+不可数名词）",
      "grade": "4.2",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "形",
      "serialNumber": "63"
    },
    {
      "word": "hurry",
      "meaning": "匆忙；赶快",
      "grade": "4.2",
      "phonetic": "/ˈhʌri/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "64"
    },
    {
      "word": "sunny",
      "meaning": "晴朗的；有阳光的",
      "grade": "4.2",
      "phonetic": "/ˈsʌni/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "形",
      "serialNumber": "65"
    },
    {
      "word": "umbrella",
      "meaning": "雨伞",
      "grade": "4.2",
      "phonetic": "/ʌmˈbrelə/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "66"
    },
    {
      "word": "come",
      "meaning": "来",
      "grade": "4.2",
      "phonetic": "/kʌm/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "67"
    },
    {
      "word": "love",
      "meaning": "（信尾问候语）爱你的",
      "grade": "4.2",
      "phonetic": "/lʌv/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "68"
    },
    {
      "word": "glove",
      "meaning": "（分手指的）手套",
      "grade": "4.2",
      "phonetic": "/ɡlʌv/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "69"
    },
    {
      "word": "London",
      "meaning": "伦敦",
      "grade": "4.2",
      "phonetic": "/ˈlʌndən/",
      "highlightLetters": "第1个o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "70"
    },
    {
      "word": "book",
      "meaning": "书",
      "grade": "4.2",
      "phonetic": "/bʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "71"
    },
    {
      "word": "cook",
      "meaning": "厨师",
      "grade": "4.2",
      "phonetic": "/kʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "72"
    },
    {
      "word": "look",
      "meaning": "看",
      "grade": "4.2",
      "phonetic": "/lʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "73"
    },
    {
      "word": "foot",
      "meaning": "脚",
      "grade": "4.2",
      "phonetic": "/fʊt/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "74"
    },
    {
      "word": "good",
      "meaning": "好的",
      "grade": "4.2",
      "phonetic": "/ɡʊd/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "形",
      "serialNumber": "75"
    },
    {
      "word": "woman",
      "meaning": "妇女",
      "grade": "4.2",
      "phonetic": "/ˈwʊmən/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʊ/",
      "note": "o读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "76"
    },
    {
      "word": "art",
      "meaning": "美术；艺术",
      "grade": "4.2",
      "phonetic": "/ɑːt /",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "77"
    },
    {
      "word": "farm",
      "meaning": "农场",
      "grade": "4.2",
      "phonetic": "/fɑːm/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "78"
    },
    {
      "word": "scarf",
      "meaning": "围巾；披巾",
      "grade": "4.2",
      "phonetic": "/skɑːf/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "79"
    },
    {
      "word": "glasses",
      "meaning": "眼镜",
      "grade": "4.2",
      "phonetic": "/ɡlɑːsɪz/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "80"
    },
    {
      "word": "tomato",
      "meaning": "西红柿",
      "grade": "4.2",
      "phonetic": "/təˈmɑːtəʊ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "81"
    },
    {
      "word": "warm",
      "meaning": "温暖的；暖和的",
      "grade": "4.2",
      "phonetic": "/wɔːm/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɔː/",
      "note": "ar读长元音/ɔː/",
      "partOfSpeech": "形",
      "serialNumber": "82"
    },
    {
      "word": "horse",
      "meaning": "马",
      "grade": "4.2",
      "phonetic": "/hɔːs/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "83"
    },
    {
      "word": "shorts",
      "meaning": "短裤",
      "grade": "4.2",
      "phonetic": "/ʃɔːts/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "84"
    },
    {
      "word": "forty",
      "meaning": "四十",
      "grade": "4.2",
      "phonetic": "/ˈfɔːti/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "数",
      "serialNumber": "85"
    },
    {
      "word": "New York",
      "meaning": "纽约",
      "grade": "4.2",
      "phonetic": "/njuː jɔːk/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "86"
    },
    {
      "word": "floor",
      "meaning": "地板；楼层",
      "grade": "4.2",
      "phonetic": "/flɔː(r)/",
      "highlightLetters": "oor",
      "highlightPhonetic": "/ɔː/",
      "note": "oor读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "87"
    },
    {
      "word": "more",
      "meaning": "更多的",
      "grade": "4.2",
      "phonetic": "/mɔː(r)/",
      "highlightLetters": "ore",
      "highlightPhonetic": "/ɔː/",
      "note": "ore读长元音/ɔː/",
      "partOfSpeech": "形",
      "serialNumber": "88"
    },
    {
      "word": "Singapore",
      "meaning": "新加坡",
      "grade": "4.2",
      "phonetic": "/ˌsɪŋəˈpɔː(r)/",
      "highlightLetters": "ore",
      "highlightPhonetic": "/ɔː/",
      "note": "ore读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "89"
    },
    {
      "word": "course",
      "meaning": "进展",
      "grade": "4.2",
      "phonetic": "/kɔːs/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ɔː/",
      "note": "our读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "90"
    },
    {
      "word": "yours",
      "meaning": "你的东西；你们的东西",
      "grade": "4.2",
      "phonetic": "/jɔːz/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ɔː/",
      "note": "our读长元音/ɔː/",
      "partOfSpeech": "代",
      "serialNumber": "91"
    },
    {
      "word": "shirt",
      "meaning": "男士衬衫",
      "grade": "4.2",
      "phonetic": "/ʃɜːt/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "92"
    },
    {
      "word": "skirt",
      "meaning": "女裙",
      "grade": "4.2",
      "phonetic": "/skɜːt/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "93"
    },
    {
      "word": "thirty",
      "meaning": "三十",
      "grade": "4.2",
      "phonetic": "/ˈθɜːti/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir重读长音/ɜː/",
      "partOfSpeech": "数",
      "serialNumber": "94"
    },
    {
      "word": "word",
      "meaning": "单词；言语",
      "grade": "4.2",
      "phonetic": "/wɜːd/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɜː/",
      "note": "or重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "95"
    },
    {
      "word": "world",
      "meaning": "世界",
      "grade": "4.2",
      "phonetic": "/wɜːld/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɜː/",
      "note": "or重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "96"
    },
    {
      "word": "nurse",
      "meaning": "护士",
      "grade": "4.2",
      "phonetic": "/nɜːs/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "97"
    },
    {
      "word": "purple",
      "meaning": "紫色(的)",
      "grade": "4.2",
      "phonetic": "/ˈpɜːpl/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名;形",
      "serialNumber": "98"
    },
    {
      "word": "eat",
      "meaning": "吃",
      "grade": "4.2",
      "phonetic": "/iːt/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "99"
    },
    {
      "word": "beans",
      "meaning": "豆子（复数）",
      "grade": "4.2",
      "phonetic": "/biːnz/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "100"
    },
    {
      "word": "cheap",
      "meaning": "便宜的",
      "grade": "4.2",
      "phonetic": "/tʃiːp/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "形",
      "serialNumber": "101"
    },
    {
      "word": "teachers",
      "meaning": "教师们（复数）",
      "grade": "4.2",
      "phonetic": "/ˈtiːtʃə(r)z /",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "102"
    },
    {
      "word": "teachers’",
      "meaning": "教师们的",
      "grade": "4.2",
      "phonetic": "/ˈtiːtʃə(r)z /",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名;形",
      "serialNumber": "103"
    },
    {
      "word": "to",
      "meaning": "到（+地点）",
      "grade": "4.2",
      "phonetic": "/tu:/",
      "highlightLetters": "o",
      "highlightPhonetic": "/uː/",
      "note": "o读长元音/uː/",
      "partOfSpeech": "介",
      "serialNumber": "104"
    },
    {
      "word": "two",
      "meaning": "二",
      "grade": "4.2",
      "phonetic": "/tuː/",
      "highlightLetters": "o",
      "highlightPhonetic": "/uː/",
      "note": "o读长元音/uː/",
      "partOfSpeech": "数",
      "serialNumber": "105"
    },
    {
      "word": "who",
      "meaning": "谁",
      "grade": "4.2",
      "phonetic": "/huː/",
      "highlightLetters": "o",
      "highlightPhonetic": "/uː/",
      "note": "o读长元音/uː/",
      "partOfSpeech": "代",
      "serialNumber": "106"
    },
    {
      "word": "whose",
      "meaning": "谁的（东西）",
      "grade": "4.2",
      "phonetic": "/huːz/",
      "highlightLetters": "o",
      "highlightPhonetic": "/uː/",
      "note": "o读长元音/uː/",
      "partOfSpeech": "代",
      "serialNumber": "107"
    },
    {
      "word": "too",
      "meaning": "太；也",
      "grade": "4.2",
      "phonetic": "/tuː/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "副",
      "serialNumber": "108"
    },
    {
      "word": "cool",
      "meaning": "凉的；酷的",
      "grade": "4.2",
      "phonetic": "/kuːl/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "形",
      "serialNumber": "109"
    },
    {
      "word": "room",
      "meaning": "房间；空间",
      "grade": "4.2",
      "phonetic": "/ruːm/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "110"
    },
    {
      "word": "school",
      "meaning": "学校",
      "grade": "4.2",
      "phonetic": "/skuːl/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "111"
    },
    {
      "word": "way",
      "meaning": "方向；方式",
      "grade": "4.2",
      "phonetic": "/weɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "112"
    },
    {
      "word": "play",
      "meaning": "玩；打（球）；放（音乐）",
      "grade": "4.2",
      "phonetic": "/ˈpleɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "113"
    },
    {
      "word": "playground",
      "meaning": "操场",
      "grade": "4.2",
      "phonetic": "/ˈpleɪɡraʊnd/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "114"
    },
    {
      "word": "wait",
      "meaning": "等待",
      "grade": "4.2",
      "phonetic": "/weɪt/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/eɪ/",
      "note": "ai读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "115"
    },
    {
      "word": "rainy",
      "meaning": "阴雨的；多雨的",
      "grade": "4.2",
      "phonetic": "/ˈreɪni/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/eɪ/",
      "note": "ai读双元音/eɪ/",
      "partOfSpeech": "形",
      "serialNumber": "116"
    },
    {
      "word": "eighty",
      "meaning": "八十",
      "grade": "4.2",
      "phonetic": "/ˈeɪti/",
      "highlightLetters": "ei",
      "highlightPhonetic": "/eɪ/",
      "note": "ei读双元音/eɪ/",
      "partOfSpeech": "数",
      "serialNumber": "117"
    },
    {
      "word": "fly",
      "meaning": "飞；放（风筝等）",
      "grade": "4.2",
      "phonetic": "/flaɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y的重音读/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "118"
    },
    {
      "word": "nice",
      "meaning": "好的",
      "grade": "4.2",
      "phonetic": "/naɪs/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "119"
    },
    {
      "word": "outside",
      "meaning": "在户外",
      "grade": "4.2",
      "phonetic": "/ˌaʊtˈsaɪd/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "副",
      "serialNumber": "120"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "4.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "121"
    },
    {
      "word": "boy",
      "meaning": "男生",
      "grade": "4.2",
      "phonetic": "/bɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "122"
    },
    {
      "word": "toy",
      "meaning": "玩具",
      "grade": "4.2",
      "phonetic": "/tɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "123"
    },
    {
      "word": "cow",
      "meaning": "母牛；奶牛",
      "grade": "4.2",
      "phonetic": "/kaʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/aʊ/",
      "note": "ow读双元音/aʊ/",
      "partOfSpeech": "名",
      "serialNumber": "124"
    },
    {
      "word": "now",
      "meaning": "现在；目前",
      "grade": "4.2",
      "phonetic": "/naʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/aʊ/",
      "note": "ow读双元音/aʊ/",
      "partOfSpeech": "副",
      "serialNumber": "125"
    },
    {
      "word": "about",
      "meaning": "关于;大约",
      "grade": "4.2",
      "phonetic": "/əˈbaʊt/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "介;副",
      "serialNumber": "126"
    },
    {
      "word": "cloudy",
      "meaning": "阴天的；多云的",
      "grade": "4.2",
      "phonetic": "/ˈklaʊdi/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "形",
      "serialNumber": "127"
    },
    {
      "word": "ground",
      "meaning": "场地；地面",
      "grade": "4.2",
      "phonetic": "/ɡraʊnd/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "名",
      "serialNumber": "128"
    },
    {
      "word": "cold",
      "meaning": "寒冷的；冷的",
      "grade": "4.2",
      "phonetic": "/kəʊld/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "形",
      "serialNumber": "129"
    },
    {
      "word": "clothes",
      "meaning": "衣服；服装",
      "grade": "4.2",
      "phonetic": "/kləʊðz/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "130"
    },
    {
      "word": "over",
      "meaning": "结束的",
      "grade": "4.2",
      "phonetic": "/ˈəʊvə(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "形",
      "serialNumber": "131"
    },
    {
      "word": "coat",
      "meaning": "外衣；大衣",
      "grade": "4.2",
      "phonetic": "/kəʊt/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "132"
    },
    {
      "word": "goat",
      "meaning": "山羊",
      "grade": "4.2",
      "phonetic": "/ɡəʊt/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "133"
    },
    {
      "word": "Moscow",
      "meaning": "莫斯科",
      "grade": "4.2",
      "phonetic": "/ˈmɒskəʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "134"
    },
    {
      "word": "snowy",
      "meaning": "下雪的",
      "grade": "4.2",
      "phonetic": "/ˈsnəʊi/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "形",
      "serialNumber": "135"
    },
    {
      "word": "hear",
      "meaning": "听见",
      "grade": "4.2",
      "phonetic": "/hɪə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɪə/",
      "note": "ear读双元音/ɪə/",
      "partOfSpeech": "动",
      "serialNumber": "136"
    },
    {
      "word": "near",
      "meaning": "在……附近",
      "grade": "4.2",
      "phonetic": "/nɪə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɪə/",
      "note": "ear读双元音/ɪə/",
      "partOfSpeech": "介",
      "serialNumber": "137"
    },
    {
      "word": "year",
      "meaning": "年纪；年",
      "grade": "4.2",
      "phonetic": "/jɪə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɪə/",
      "note": "ear读双元音/ɪə/",
      "partOfSpeech": "名",
      "serialNumber": "138"
    },
    {
      "word": "here",
      "meaning": "在这儿",
      "grade": "4.2",
      "phonetic": "/hɪə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/ɪə/",
      "note": "ere读双元音/ɪə/",
      "partOfSpeech": "副",
      "serialNumber": "139"
    },
    {
      "word": "real",
      "meaning": "真实的",
      "grade": "4.2",
      "phonetic": "/ˈrɪəl/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/ɪə/",
      "note": "ea读双元音/ɪə/",
      "partOfSpeech": "形",
      "serialNumber": "140"
    },
    {
      "word": "air",
      "meaning": "空气（不可数）",
      "grade": "4.2",
      "phonetic": "/eə(r)/",
      "highlightLetters": "air",
      "highlightPhonetic": "/eə/",
      "note": "air读双元音/eə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "141"
    },
    {
      "word": "hair",
      "meaning": "头发",
      "grade": "4.2",
      "phonetic": "/heə(r)/",
      "highlightLetters": "air",
      "highlightPhonetic": "/eə/",
      "note": "air读双元音/eə/",
      "partOfSpeech": "名",
      "serialNumber": "142"
    },
    {
      "word": "bear",
      "meaning": "熊",
      "grade": "4.2",
      "phonetic": "/beə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/eə/",
      "note": "ear读双元音/eə/",
      "partOfSpeech": "名",
      "serialNumber": "143"
    },
    {
      "word": "share",
      "meaning": "分享",
      "grade": "4.2",
      "phonetic": "/ʃeə(r)/",
      "highlightLetters": "are",
      "highlightPhonetic": "/eə/",
      "note": "are读双元音/eə/",
      "partOfSpeech": "动",
      "serialNumber": "144"
    },
    {
      "word": "careful",
      "meaning": "小心的；仔细的",
      "grade": "4.2",
      "phonetic": "/ˈkeəfl/",
      "highlightLetters": "are",
      "highlightPhonetic": "/eə/",
      "note": "are读双元音/eə/",
      "partOfSpeech": "形",
      "serialNumber": "145"
    },
    {
      "word": "where",
      "meaning": "在哪儿",
      "grade": "4.2",
      "phonetic": "/weə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "146"
    },
    {
      "word": "there",
      "meaning": "在那儿",
      "grade": "4.2",
      "phonetic": "/weə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "147"
    },
    {
      "word": "sure",
      "meaning": "当然可以",
      "grade": "4.2",
      "phonetic": "/ʃuə(r)/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/uə/",
      "note": "ure读双元音/uə/",
      "partOfSpeech": "副",
      "serialNumber": "148"
    },
    {
      "word": "poor",
      "meaning": "穷的；可怜的",
      "grade": "4.2",
      "phonetic": "/puə(r)/",
      "highlightLetters": "oor",
      "highlightPhonetic": "/uə/",
      "note": "oor读双元音/uə/",
      "partOfSpeech": "形",
      "serialNumber": "149"
    },
    {
      "word": "about",
      "meaning": "关于",
      "grade": "4.2",
      "phonetic": "/əˈbaʊt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "介",
      "serialNumber": "150"
    },
    {
      "word": "breakfast",
      "meaning": "早餐；早饭",
      "grade": "4.2",
      "phonetic": "/ˈbrekfəst/",
      "highlightLetters": "第2个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "151"
    },
    {
      "word": "London",
      "meaning": "伦敦",
      "grade": "4.2",
      "phonetic": "/ˈlʌndən/",
      "highlightLetters": "第2个o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "152"
    },
    {
      "word": "tomato",
      "meaning": "西红柿",
      "grade": "4.2",
      "phonetic": "/təˈmɑːtəʊ/",
      "highlightLetters": "第1个o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "153"
    },
    {
      "word": "degree",
      "meaning": "度数",
      "grade": "4.2",
      "phonetic": "/dɪˈɡriː/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "154"
    },
    {
      "word": "expensive",
      "meaning": "昂贵的",
      "grade": "4.2",
      "phonetic": "/ɪkˈspensɪv/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "155"
    },
    {
      "word": "jacket",
      "meaning": "夹克衫",
      "grade": "4.2",
      "phonetic": "/ˈdʒækɪt/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "156"
    },
    {
      "word": "minute",
      "meaning": "分钟",
      "grade": "4.2",
      "phonetic": "/mɪnɪt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/i/",
      "note": "u弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "157"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "4.2",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "数",
      "serialNumber": "158"
    },
    {
      "word": "thirty",
      "meaning": "三十",
      "grade": "4.2",
      "phonetic": "/ˈθɜːti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "数",
      "serialNumber": "159"
    },
    {
      "word": "forty",
      "meaning": "四十",
      "grade": "4.2",
      "phonetic": "/ˈfɔːti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "数",
      "serialNumber": "160"
    },
    {
      "word": "fifty",
      "meaning": "五十",
      "grade": "4.2",
      "phonetic": "/ˈfɪfti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "数",
      "serialNumber": "161"
    },
    {
      "word": "eighty",
      "meaning": "八十",
      "grade": "4.2",
      "phonetic": "/ˈeɪti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "数",
      "serialNumber": "162"
    },
    {
      "word": "cloudy",
      "meaning": "阴天的；多云的",
      "grade": "4.2",
      "phonetic": "/ˈklaʊdi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "163"
    },
    {
      "word": "hurry",
      "meaning": "匆忙；赶快",
      "grade": "4.2",
      "phonetic": "/ˈhʌri/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "动",
      "serialNumber": "164"
    },
    {
      "word": "pretty",
      "meaning": "美观的；精致的",
      "grade": "4.2",
      "phonetic": "/ˈprɪti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "165"
    },
    {
      "word": "rainy",
      "meaning": "阴雨的；多雨的",
      "grade": "4.2",
      "phonetic": "/ˈreɪni/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "166"
    },
    {
      "word": "snowy",
      "meaning": "下雪（多）的",
      "grade": "4.2",
      "phonetic": "/ˈsnəʊi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "167"
    },
    {
      "word": "sunny",
      "meaning": "阳光充足的",
      "grade": "4.2",
      "phonetic": "/ˈsʌni/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "168"
    },
    {
      "word": "windy",
      "meaning": "多风的；风大的",
      "grade": "4.2",
      "phonetic": "/ˈwɪndi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "169"
    },
    {
      "word": "Sydney",
      "meaning": "悉尼",
      "grade": "4.2",
      "phonetic": "/ˈsɪ(d)ni/",
      "highlightLetters": "ey",
      "highlightPhonetic": "/i/",
      "note": "ey弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "170"
    },
    {
      "word": "dinner",
      "meaning": "正餐",
      "grade": "4.2",
      "phonetic": "/ˈdɪnə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "171"
    },
    {
      "word": "weather",
      "meaning": "天气",
      "grade": "4.2",
      "phonetic": "/ˈweðə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "172"
    },
    {
      "word": "dollar",
      "meaning": "美（加）元",
      "grade": "4.2",
      "phonetic": "/ˈdɒlə(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ə/",
      "note": "ar弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "173"
    },
    {
      "word": "animal",
      "meaning": "兽；动物",
      "grade": "4.2",
      "phonetic": "/ˈænɪml/",
      "highlightLetters": "mal",
      "highlightPhonetic": "/ml/",
      "note": "/ml/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "174"
    },
    {
      "word": "careful",
      "meaning": "小心的；仔细的",
      "grade": "4.2",
      "phonetic": "/ˈkeəfl/",
      "highlightLetters": "ful",
      "highlightPhonetic": "/fl/",
      "note": "/fl/弱音省略",
      "partOfSpeech": "形",
      "serialNumber": "175"
    },
    {
      "word": "garden",
      "meaning": "花园；菜园",
      "grade": "4.2",
      "phonetic": "/ˈɡɑːdn/",
      "highlightLetters": "den",
      "highlightPhonetic": "/dn/",
      "note": "/dn/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "176"
    },
    {
      "word": "be",
      "meaning": "be动词",
      "grade": "4.2",
      "phonetic": "/biː /",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "动",
      "serialNumber": "177"
    },
    {
      "word": "beans",
      "meaning": "豆子（复数）",
      "grade": "4.2",
      "phonetic": "/biːnz/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "178"
    },
    {
      "word": "breakfast",
      "meaning": "早餐；早饭",
      "grade": "4.2",
      "phonetic": "/ˈbrekfəst/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "不可数名",
      "serialNumber": "179"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "4.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "180"
    },
    {
      "word": "careful",
      "meaning": "小心的；仔细的",
      "grade": "4.2",
      "phonetic": "/ˈkeəfl/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "形",
      "serialNumber": "181"
    },
    {
      "word": "carrot",
      "meaning": "胡萝卜",
      "grade": "4.2",
      "phonetic": "/ˈkærət/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名",
      "serialNumber": "182"
    },
    {
      "word": "coat",
      "meaning": "外衣；大衣",
      "grade": "4.2",
      "phonetic": "/kəʊt/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名",
      "serialNumber": "183"
    },
    {
      "word": "cold",
      "meaning": "寒冷的；冷的",
      "grade": "4.2",
      "phonetic": "/kəʊld/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "形",
      "serialNumber": "184"
    },
    {
      "word": "come",
      "meaning": "来",
      "grade": "4.2",
      "phonetic": "/kʌm/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "动",
      "serialNumber": "185"
    },
    {
      "word": "computer",
      "meaning": "计算机；电脑",
      "grade": "4.2",
      "phonetic": "/kəmˈpjuːtə(r)/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名",
      "serialNumber": "186"
    },
    {
      "word": "cool",
      "meaning": "凉的；凉爽的",
      "grade": "4.2",
      "phonetic": "/kuːl/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "形",
      "serialNumber": "187"
    },
    {
      "word": "course",
      "meaning": "进展",
      "grade": "4.2",
      "phonetic": "/kɔːs/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名",
      "serialNumber": "188"
    },
    {
      "word": "cow",
      "meaning": "母牛；奶牛",
      "grade": "4.2",
      "phonetic": "/kaʊ/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名",
      "serialNumber": "189"
    },
    {
      "word": "second",
      "meaning": "第二（的）",
      "grade": "4.2",
      "phonetic": "/ˈsekənd/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名;形",
      "serialNumber": "190"
    },
    {
      "word": "jacket",
      "meaning": "夹克衫",
      "grade": "4.2",
      "phonetic": "/ˈdʒækɪt/",
      "highlightLetters": "ck",
      "highlightPhonetic": "/k/",
      "note": "ck读/k/",
      "partOfSpeech": "名",
      "serialNumber": "191"
    },
    {
      "word": "o’clock",
      "meaning": "（表示整点）……点钟",
      "grade": "4.2",
      "phonetic": "/əˈklɒk/",
      "highlightLetters": "ck",
      "highlightPhonetic": "/k/",
      "note": "ck读/k/",
      "partOfSpeech": "名",
      "serialNumber": "192"
    },
    {
      "word": "pack",
      "meaning": "收拾（行李）",
      "grade": "4.2",
      "phonetic": "/pæk/",
      "highlightLetters": "ck",
      "highlightPhonetic": "/k/",
      "note": "ck读/k/",
      "partOfSpeech": "动",
      "serialNumber": "193"
    },
    {
      "word": "sock",
      "meaning": "短袜",
      "grade": "4.2",
      "phonetic": "/sɒk/",
      "highlightLetters": "ck",
      "highlightPhonetic": "/k/",
      "note": "ck读/k/",
      "partOfSpeech": "名",
      "serialNumber": "194"
    },
    {
      "word": "kid",
      "meaning": "小孩",
      "grade": "4.2",
      "phonetic": "/kɪd/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "195"
    },
    {
      "word": "old",
      "meaning": "旧的",
      "grade": "4.2",
      "phonetic": "/əʊld/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形",
      "serialNumber": "196"
    },
    {
      "word": "cold",
      "meaning": "寒冷的；冷的",
      "grade": "4.2",
      "phonetic": "/kəʊld/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形",
      "serialNumber": "197"
    },
    {
      "word": "degree",
      "meaning": "度数",
      "grade": "4.2",
      "phonetic": "/dɪˈɡriː/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "198"
    },
    {
      "word": "dinner",
      "meaning": "正餐",
      "grade": "4.2",
      "phonetic": "/ˈdɪnə(r)/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "不可数名",
      "serialNumber": "199"
    },
    {
      "word": "London",
      "meaning": "伦敦",
      "grade": "4.2",
      "phonetic": "/ˈlʌndən/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "200"
    },
    {
      "word": "dollar",
      "meaning": "美（加）元",
      "grade": "4.2",
      "phonetic": "/ˈdɒlə(r)/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "201"
    },
    {
      "word": "ground",
      "meaning": "场地；地面",
      "grade": "4.2",
      "phonetic": "/ɡraʊnd/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "202"
    },
    {
      "word": "second",
      "meaning": "第二（的）",
      "grade": "4.2",
      "phonetic": "/ˈsekənd/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "数;形",
      "serialNumber": "203"
    },
    {
      "word": "farm",
      "meaning": "农场",
      "grade": "4.2",
      "phonetic": "/fɑːm/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "204"
    },
    {
      "word": "fifty",
      "meaning": "五十",
      "grade": "4.2",
      "phonetic": "/ˈfɪfti/",
      "highlightLetters": "f,f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "数",
      "serialNumber": "205"
    },
    {
      "word": "first",
      "meaning": "第一（的）",
      "grade": "4.2",
      "phonetic": "/fɜːst/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "数",
      "serialNumber": "206"
    },
    {
      "word": "forty",
      "meaning": "四十",
      "grade": "4.2",
      "phonetic": "/ˈfɔːti/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "数",
      "serialNumber": "207"
    },
    {
      "word": "scarf",
      "meaning": "围巾；披巾",
      "grade": "4.2",
      "phonetic": "/skɑːf/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "208"
    },
    {
      "word": "office",
      "meaning": "办公室",
      "grade": "4.2",
      "phonetic": "/ˈɒfɪs/",
      "highlightLetters": "ff",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "209"
    },
    {
      "word": "get",
      "meaning": "到达；获得",
      "grade": "4.2",
      "phonetic": "/ɡet/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "动",
      "serialNumber": "210"
    },
    {
      "word": "go",
      "meaning": "去",
      "grade": "4.2",
      "phonetic": "/ɡəʊ /",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "动",
      "serialNumber": "211"
    },
    {
      "word": "goat",
      "meaning": "山羊",
      "grade": "4.2",
      "phonetic": "/ɡəʊt/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "212"
    },
    {
      "word": "garden",
      "meaning": "花园；菜园",
      "grade": "4.2",
      "phonetic": "/ˈɡɑːdn/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "213"
    },
    {
      "word": "giraffe",
      "meaning": "长颈鹿",
      "grade": "4.2",
      "phonetic": "/dʒəˈrɑːf/",
      "highlightLetters": "g",
      "highlightPhonetic": "/dʒ/",
      "note": "g读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "214"
    },
    {
      "word": "orange",
      "meaning": "橙子；柑橘",
      "grade": "4.2",
      "phonetic": "/ˈɒrɪndʒ/",
      "highlightLetters": "g",
      "highlightPhonetic": "/dʒ/",
      "note": "g读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "215"
    },
    {
      "word": "hat",
      "meaning": "（带檐的）帽子",
      "grade": "4.2",
      "phonetic": "/hæt/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "216"
    },
    {
      "word": "hen",
      "meaning": "母鸡",
      "grade": "4.2",
      "phonetic": "/hen/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "217"
    },
    {
      "word": "home",
      "meaning": "家",
      "grade": "4.2",
      "phonetic": "/həʊm/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "218"
    },
    {
      "word": "horse",
      "meaning": "马",
      "grade": "4.2",
      "phonetic": "/hɔːs/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "219"
    },
    {
      "word": "hot",
      "meaning": "热的; 烫的；辣的",
      "grade": "4.2",
      "phonetic": "/hɒt/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "形",
      "serialNumber": "220"
    },
    {
      "word": "how",
      "meaning": "如何；怎样",
      "grade": "4.2",
      "phonetic": "/haʊ/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "副",
      "serialNumber": "221"
    },
    {
      "word": "hurry",
      "meaning": "匆忙；赶快",
      "grade": "4.2",
      "phonetic": "/ˈhʌri/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "222"
    },
    {
      "word": "jacket",
      "meaning": "夹克衫",
      "grade": "4.2",
      "phonetic": "/ˈdʒækɪt/",
      "highlightLetters": "j",
      "highlightPhonetic": "/dʒ/",
      "note": "j读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "223"
    },
    {
      "word": "just",
      "meaning": "正好；就；只",
      "grade": "4.2",
      "phonetic": "/dʒʌst/",
      "highlightLetters": "j",
      "highlightPhonetic": "/dʒ/",
      "note": "j读/dʒ/",
      "partOfSpeech": "副",
      "serialNumber": "224"
    },
    {
      "word": "kid",
      "meaning": "小孩",
      "grade": "4.2",
      "phonetic": "/kɪd/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "225"
    },
    {
      "word": "work",
      "meaning": "工作；学习；劳动",
      "grade": "4.2",
      "phonetic": "/wɜːk/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "不可数名",
      "serialNumber": "226"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "4.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "227"
    },
    {
      "word": "London",
      "meaning": "伦敦",
      "grade": "4.2",
      "phonetic": "/ˈlʌndən/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "228"
    },
    {
      "word": "love",
      "meaning": "（信尾问候语）爱你的",
      "grade": "4.2",
      "phonetic": "/lʌv/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "229"
    },
    {
      "word": "lunch",
      "meaning": "午餐；午饭",
      "grade": "4.2",
      "phonetic": "/lʌntʃ/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "不可数名",
      "serialNumber": "230"
    },
    {
      "word": "umbrella",
      "meaning": "伞；雨伞",
      "grade": "4.2",
      "phonetic": "/ʌmˈbrelə/",
      "highlightLetters": "ll",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "231"
    },
    {
      "word": "sale",
      "meaning": "特价销售; 大减价",
      "grade": "4.2",
      "phonetic": "/seɪl/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "232"
    },
    {
      "word": "school",
      "meaning": "学校",
      "grade": "4.2",
      "phonetic": "/skuːl/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "233"
    },
    {
      "word": "world",
      "meaning": "世界",
      "grade": "4.2",
      "phonetic": "/wɜːld/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "234"
    },
    {
      "word": "mine",
      "meaning": "我的",
      "grade": "4.2",
      "phonetic": "/maɪn/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "代",
      "serialNumber": "235"
    },
    {
      "word": "minute",
      "meaning": "分钟",
      "grade": "4.2",
      "phonetic": "/mɪnɪt/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "236"
    },
    {
      "word": "more",
      "meaning": "更多的",
      "grade": "4.2",
      "phonetic": "/mɔː(r)/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "形",
      "serialNumber": "237"
    },
    {
      "word": "Moscow",
      "meaning": "莫斯科",
      "grade": "4.2",
      "phonetic": "/ˈmɒskəʊ/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "238"
    },
    {
      "word": "much",
      "meaning": "许多（+不可数名词）",
      "grade": "4.2",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "形",
      "serialNumber": "239"
    },
    {
      "word": "music",
      "meaning": "音乐",
      "grade": "4.2",
      "phonetic": "/ˈmjuːzɪk/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "不可数名",
      "serialNumber": "240"
    },
    {
      "word": "tomato",
      "meaning": "西红柿",
      "grade": "4.2",
      "phonetic": "/təˈmɑːtəʊ/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "241"
    },
    {
      "word": "room",
      "meaning": "房间；空间",
      "grade": "4.2",
      "phonetic": "/ruːm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "242"
    },
    {
      "word": "warm",
      "meaning": "温暖的；暖和的",
      "grade": "4.2",
      "phonetic": "/wɔːm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "形",
      "serialNumber": "243"
    },
    {
      "word": "yum",
      "meaning": "味道好",
      "grade": "4.2",
      "phonetic": "/jʌm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "形",
      "serialNumber": "244"
    },
    {
      "word": "next",
      "meaning": "下一个",
      "grade": "4.2",
      "phonetic": "/ˈnekst/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "形",
      "serialNumber": "245"
    },
    {
      "word": "nice",
      "meaning": "好的",
      "grade": "4.2",
      "phonetic": "/naɪs/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "形",
      "serialNumber": "246"
    },
    {
      "word": "now",
      "meaning": "现在；目前",
      "grade": "4.2",
      "phonetic": "/naʊ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "副",
      "serialNumber": "247"
    },
    {
      "word": "sunny",
      "meaning": "阳光充足的",
      "grade": "4.2",
      "phonetic": "/ˈsʌni/",
      "highlightLetters": "nn",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "形",
      "serialNumber": "248"
    },
    {
      "word": "Sydney",
      "meaning": "悉尼",
      "grade": "4.2",
      "phonetic": "/ˈsɪ(d)ni/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "249"
    },
    {
      "word": "on",
      "meaning": "表示持续下去",
      "grade": "4.2",
      "phonetic": "/ɒn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "副",
      "serialNumber": "250"
    },
    {
      "word": "pants",
      "meaning": "裤子",
      "grade": "4.2",
      "phonetic": "/pænts/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "251"
    },
    {
      "word": "windy",
      "meaning": "多风的；风大的",
      "grade": "4.2",
      "phonetic": "/ˈwɪndi/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "形",
      "serialNumber": "252"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "4.2",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "数",
      "serialNumber": "253"
    },
    {
      "word": "English",
      "meaning": "英语（的）",
      "grade": "4.2",
      "phonetic": "/ˈɪŋɡlɪʃ /",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "名;形",
      "serialNumber": "254"
    },
    {
      "word": "Singapore",
      "meaning": "新加坡（市）",
      "grade": "4.2",
      "phonetic": "/ˌsɪŋəˈpɔː(r)/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "名",
      "serialNumber": "255"
    },
    {
      "word": "pink",
      "meaning": "粉色（的）",
      "grade": "4.2",
      "phonetic": "/pɪŋk/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "n读/ŋ/（在/k/音前）",
      "partOfSpeech": "名;形",
      "serialNumber": "256"
    },
    {
      "word": "uncle",
      "meaning": "伯伯，叔叔，舅舅",
      "grade": "4.2",
      "phonetic": "/ˈʌŋkl/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "n读/ŋ/（在/k/音前）",
      "partOfSpeech": "名",
      "serialNumber": "257"
    },
    {
      "word": "monkey",
      "meaning": "猴子",
      "grade": "4.2",
      "phonetic": "/ˈmʌŋki/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "n读/ŋ/（在/k/音前）",
      "partOfSpeech": "名",
      "serialNumber": "258"
    },
    {
      "word": "pack",
      "meaning": "收拾（行李）",
      "grade": "4.2",
      "phonetic": "/pæk/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "动",
      "serialNumber": "259"
    },
    {
      "word": "pants",
      "meaning": "裤子",
      "grade": "4.2",
      "phonetic": "/pænts/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "260"
    },
    {
      "word": "PE",
      "meaning": "体育",
      "grade": "4.2",
      "phonetic": "/ˌpiː ˈiː /",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "不可数名",
      "serialNumber": "261"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "4.2",
      "phonetic": "/ˈkwaiət/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "形",
      "serialNumber": "262"
    },
    {
      "word": "quite",
      "meaning": "非常；十分",
      "grade": "4.2",
      "phonetic": "/ˈkwait/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "副",
      "serialNumber": "263"
    },
    {
      "word": "queen",
      "meaning": "女王",
      "grade": "4.2",
      "phonetic": "/kwiːn/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "名",
      "serialNumber": "264"
    },
    {
      "word": "rainy",
      "meaning": "阴雨的；多雨的",
      "grade": "4.2",
      "phonetic": "/ˈreɪni/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "形",
      "serialNumber": "265"
    },
    {
      "word": "room",
      "meaning": "房间；空间",
      "grade": "4.2",
      "phonetic": "/ruːm/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "266"
    },
    {
      "word": "umbrella",
      "meaning": "伞；雨伞",
      "grade": "4.2",
      "phonetic": "/ʌmˈbrelə/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "267"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "4.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "r,r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "268"
    },
    {
      "word": "carrot",
      "meaning": "胡萝卜",
      "grade": "4.2",
      "phonetic": "/ˈkærət/",
      "highlightLetters": "rr",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "269"
    },
    {
      "word": "hurry",
      "meaning": "匆忙；赶快",
      "grade": "4.2",
      "phonetic": "/ˈhʌri/",
      "highlightLetters": "rr",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "动",
      "serialNumber": "270"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "4.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "r,r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "271"
    },
    {
      "word": "sale",
      "meaning": "特价销售; 大减价",
      "grade": "4.2",
      "phonetic": "/seɪl/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "272"
    },
    {
      "word": "second",
      "meaning": "第二（的）",
      "grade": "4.2",
      "phonetic": "/ˈsekənd/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "数;形",
      "serialNumber": "273"
    },
    {
      "word": "size",
      "meaning": "尺码；号",
      "grade": "4.2",
      "phonetic": "/saɪz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "274"
    },
    {
      "word": "sock",
      "meaning": "短袜",
      "grade": "4.2",
      "phonetic": "/sɒk/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "275"
    },
    {
      "word": "sunglasses",
      "meaning": "太阳镜",
      "grade": "4.2",
      "phonetic": "/ˈsʌnɡlɑːsɪz/",
      "highlightLetters": "前3个s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "276"
    },
    {
      "word": "sunny",
      "meaning": "阳光充足的",
      "grade": "4.2",
      "phonetic": "/ˈsʌni/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "形",
      "serialNumber": "277"
    },
    {
      "word": "course",
      "meaning": "进展",
      "grade": "4.2",
      "phonetic": "/kɔːs/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "278"
    },
    {
      "word": "dress",
      "meaning": "连衣裙",
      "grade": "4.2",
      "phonetic": "/dres/",
      "highlightLetters": "ss",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "279"
    },
    {
      "word": "glass",
      "meaning": "玻璃",
      "grade": "4.2",
      "phonetic": "ɡlɑːs/",
      "highlightLetters": "ss",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "不可数名",
      "serialNumber": "280"
    },
    {
      "word": "horse",
      "meaning": "马",
      "grade": "4.2",
      "phonetic": "/hɔːs/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "281"
    },
    {
      "word": "just",
      "meaning": "正好；就；只",
      "grade": "4.2",
      "phonetic": "/dʒʌst/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "副",
      "serialNumber": "282"
    },
    {
      "word": "pants",
      "meaning": "裤子",
      "grade": "4.2",
      "phonetic": "/pænts/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "283"
    },
    {
      "word": "nice",
      "meaning": "好的",
      "grade": "4.2",
      "phonetic": "/naɪs/",
      "highlightLetters": "ce",
      "highlightPhonetic": "/s/",
      "note": "c读/s/",
      "partOfSpeech": "形",
      "serialNumber": "284"
    },
    {
      "word": "office",
      "meaning": "办公室",
      "grade": "4.2",
      "phonetic": "/ˈɒfɪs/",
      "highlightLetters": "ce",
      "highlightPhonetic": "/s/",
      "note": "c读/s/",
      "partOfSpeech": "名",
      "serialNumber": "285"
    },
    {
      "word": "music",
      "meaning": "音乐",
      "grade": "4.2",
      "phonetic": "/ˈmjuːzɪk/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "不可数名",
      "serialNumber": "286"
    },
    {
      "word": "those",
      "meaning": "（that 的复数）那些",
      "grade": "4.2",
      "phonetic": "/ðəʊz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "代;形",
      "serialNumber": "287"
    },
    {
      "word": "whose",
      "meaning": "谁的",
      "grade": "4.2",
      "phonetic": "/huːz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "代;形",
      "serialNumber": "288"
    },
    {
      "word": "beans",
      "meaning": "豆子（复数）",
      "grade": "4.2",
      "phonetic": "/biːnz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "289"
    },
    {
      "word": "yours",
      "meaning": "你的东西；你们的东西",
      "grade": "4.2",
      "phonetic": "/jɔːz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "代",
      "serialNumber": "290"
    },
    {
      "word": "dollar(s)",
      "meaning": "美（加）元(复数)",
      "grade": "4.2",
      "phonetic": "/ˈdɒlə(r)(z)/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "291"
    },
    {
      "word": "clothes",
      "meaning": "衣服；服装",
      "grade": "4.2",
      "phonetic": "/kləʊðz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "292"
    },
    {
      "word": "glasses",
      "meaning": "眼镜",
      "grade": "4.2",
      "phonetic": "/ɡlɑːsɪz/",
      "highlightLetters": "第3个s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "293"
    },
    {
      "word": "teachers’",
      "meaning": "教师们的",
      "grade": "4.2",
      "phonetic": "/ˈtiːtʃə(r)z /",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名;形",
      "serialNumber": "294"
    },
    {
      "word": "to",
      "meaning": "到（+地点）",
      "grade": "4.2",
      "phonetic": "/tu:/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "介",
      "serialNumber": "295"
    },
    {
      "word": "too",
      "meaning": "太；也",
      "grade": "4.2",
      "phonetic": "/tuː/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "副",
      "serialNumber": "296"
    },
    {
      "word": "tomato",
      "meaning": "西红柿",
      "grade": "4.2",
      "phonetic": "/təˈmɑːtəʊ/",
      "highlightLetters": "t，t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "297"
    },
    {
      "word": "hat",
      "meaning": "（带檐的）帽子",
      "grade": "4.2",
      "phonetic": "/hæt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "298"
    },
    {
      "word": "hot",
      "meaning": "热的; 烫的",
      "grade": "4.2",
      "phonetic": "/hɒt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形",
      "serialNumber": "299"
    },
    {
      "word": "just",
      "meaning": "正好；就；只",
      "grade": "4.2",
      "phonetic": "/dʒʌst/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "副",
      "serialNumber": "300"
    },
    {
      "word": "next",
      "meaning": "下一个",
      "grade": "4.2",
      "phonetic": "/ˈnekst/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形",
      "serialNumber": "301"
    },
    {
      "word": "skirt",
      "meaning": "女裙",
      "grade": "4.2",
      "phonetic": "/skɜːt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "302"
    },
    {
      "word": "wait",
      "meaning": "等待",
      "grade": "4.2",
      "phonetic": "/weɪt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "303"
    },
    {
      "word": "eight",
      "meaning": "八",
      "grade": "4.2",
      "phonetic": "/eɪt/",
      "highlightLetters": "ght",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "数",
      "serialNumber": "304"
    },
    {
      "word": "right",
      "meaning": "右边的；正确的",
      "grade": "4.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "ght",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形",
      "serialNumber": "305"
    },
    {
      "word": "van",
      "meaning": "面包车",
      "grade": "4.2",
      "phonetic": "/væn/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "306"
    },
    {
      "word": "vet",
      "meaning": "兽医",
      "grade": "4.2",
      "phonetic": "/vet/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "307"
    },
    {
      "word": "have",
      "meaning": "有",
      "grade": "4.2",
      "phonetic": "/hæv/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "动",
      "serialNumber": "308"
    },
    {
      "word": "give",
      "meaning": "给",
      "grade": "4.2",
      "phonetic": "/ɡɪv/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "动",
      "serialNumber": "309"
    },
    {
      "word": "of",
      "meaning": "的",
      "grade": "4.2",
      "phonetic": "/əv/",
      "highlightLetters": "f",
      "highlightPhonetic": "/v/",
      "note": "f读/v/",
      "partOfSpeech": "介",
      "serialNumber": "310"
    },
    {
      "word": "wait",
      "meaning": "等待",
      "grade": "4.2",
      "phonetic": "/weɪt/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "311"
    },
    {
      "word": "warm",
      "meaning": "温暖的；暖和的",
      "grade": "4.2",
      "phonetic": "/wɔːm/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "形",
      "serialNumber": "312"
    },
    {
      "word": "way",
      "meaning": "方向",
      "grade": "4.2",
      "phonetic": "/weɪ/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "313"
    },
    {
      "word": "weather",
      "meaning": "天气",
      "grade": "4.2",
      "phonetic": "/ˈweðə(r)/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "不可数名",
      "serialNumber": "314"
    },
    {
      "word": "windy",
      "meaning": "多风的；风大的",
      "grade": "4.2",
      "phonetic": "/ˈwɪndi/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "形",
      "serialNumber": "315"
    },
    {
      "word": "world",
      "meaning": "世界",
      "grade": "4.2",
      "phonetic": "/wɜːld/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "316"
    },
    {
      "word": "who",
      "meaning": "谁",
      "grade": "4.2",
      "phonetic": "/huː/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代",
      "serialNumber": "317"
    },
    {
      "word": "whose",
      "meaning": "谁的",
      "grade": "4.2",
      "phonetic": "/huːz/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代;形",
      "serialNumber": "318"
    },
    {
      "word": "box",
      "meaning": "盒子；箱子",
      "grade": "4.2",
      "phonetic": "/bɒks/",
      "highlightLetters": "x",
      "highlightPhonetic": "/ks/",
      "note": "x读/ks/",
      "partOfSpeech": "名",
      "serialNumber": "319"
    },
    {
      "word": "fox",
      "meaning": "狐狸",
      "grade": "4.2",
      "phonetic": "/fɒks/",
      "highlightLetters": "x",
      "highlightPhonetic": "/ks/",
      "note": "x读/ks/",
      "partOfSpeech": "名",
      "serialNumber": "320"
    },
    {
      "word": "six",
      "meaning": "六",
      "grade": "4.2",
      "phonetic": "/sɪks/",
      "highlightLetters": "x",
      "highlightPhonetic": "/ks/",
      "note": "x读/ks/",
      "partOfSpeech": "数",
      "serialNumber": "321"
    },
    {
      "word": "yours",
      "meaning": "你的东西；你们的东西",
      "grade": "4.2",
      "phonetic": "/jɔːz/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （用作辅音）",
      "partOfSpeech": "代",
      "serialNumber": "322"
    },
    {
      "word": "yum",
      "meaning": "味道好",
      "grade": "4.2",
      "phonetic": "/jʌm/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （用作辅音）",
      "partOfSpeech": "形",
      "serialNumber": "323"
    },
    {
      "word": "zoo",
      "meaning": "动物园",
      "grade": "4.2",
      "phonetic": "/zu:/",
      "highlightLetters": "z",
      "highlightPhonetic": "/z/",
      "note": "z读/z/",
      "partOfSpeech": "名",
      "serialNumber": "324"
    },
    {
      "word": "quiz",
      "meaning": "小测验",
      "grade": "4.2",
      "phonetic": "/kwɪz/",
      "highlightLetters": "z",
      "highlightPhonetic": "/z/",
      "note": "z读/z/",
      "partOfSpeech": "名",
      "serialNumber": "325"
    },
    {
      "word": "breakfast",
      "meaning": "早餐；早饭",
      "grade": "4.2",
      "phonetic": "/ˈbrekfəst/",
      "highlightLetters": "br",
      "highlightPhonetic": "/br/",
      "note": "br读/dr/",
      "partOfSpeech": "不可数名",
      "serialNumber": "326"
    },
    {
      "word": "dress",
      "meaning": "连衣裙",
      "grade": "4.2",
      "phonetic": "/dres/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "名",
      "serialNumber": "327"
    },
    {
      "word": "friend",
      "meaning": "朋友",
      "grade": "4.2",
      "phonetic": "/frend/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "名",
      "serialNumber": "328"
    },
    {
      "word": "degree",
      "meaning": "度数",
      "grade": "4.2",
      "phonetic": "/dɪˈɡriː/",
      "highlightLetters": "gr",
      "highlightPhonetic": "/ɡr/",
      "note": "gr读/ɡr/",
      "partOfSpeech": "名",
      "serialNumber": "329"
    },
    {
      "word": "green",
      "meaning": "绿色（的）",
      "grade": "4.2",
      "phonetic": "/ɡriːn/",
      "highlightLetters": "gr",
      "highlightPhonetic": "/ɡr/",
      "note": "gr读/ɡr/",
      "partOfSpeech": "名;形",
      "serialNumber": "330"
    },
    {
      "word": "ground",
      "meaning": "场地；地面",
      "grade": "4.2",
      "phonetic": "/ɡraʊnd/",
      "highlightLetters": "gr",
      "highlightPhonetic": "/ɡr/",
      "note": "gr读/ɡr/",
      "partOfSpeech": "名",
      "serialNumber": "331"
    },
    {
      "word": "pretty",
      "meaning": "美观的；精致的",
      "grade": "4.2",
      "phonetic": "/ˈprɪti/",
      "highlightLetters": "pr",
      "highlightPhonetic": "/pr/",
      "note": "pr读/dr/",
      "partOfSpeech": "形",
      "serialNumber": "332"
    },
    {
      "word": "try",
      "meaning": "试试；尝试",
      "grade": "4.2",
      "phonetic": "/traɪ/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/tr/",
      "partOfSpeech": "动",
      "serialNumber": "333"
    },
    {
      "word": "three",
      "meaning": "三",
      "grade": "4.2",
      "phonetic": "/θriː/",
      "highlightLetters": "thr",
      "highlightPhonetic": "/θr/",
      "note": "thr读/θr/",
      "partOfSpeech": "数",
      "serialNumber": "334"
    },
    {
      "word": "floor",
      "meaning": "地板；楼层",
      "grade": "4.2",
      "phonetic": "/flɔː(r)/",
      "highlightLetters": "fl",
      "highlightPhonetic": "/fl/",
      "note": "fl读/fl/",
      "partOfSpeech": "名",
      "serialNumber": "335"
    },
    {
      "word": "fly",
      "meaning": "放（风筝等）",
      "grade": "4.2",
      "phonetic": "/flaɪ/",
      "highlightLetters": "fl",
      "highlightPhonetic": "/fl/",
      "note": "fl读/fl/",
      "partOfSpeech": "动",
      "serialNumber": "336"
    },
    {
      "word": "glass",
      "meaning": "玻璃（不可数）",
      "grade": "4.2",
      "phonetic": "ɡlɑːs/",
      "highlightLetters": "gl",
      "highlightPhonetic": "/ɡl/",
      "note": "gl读/ɡl/",
      "partOfSpeech": "不可数名",
      "serialNumber": "337"
    },
    {
      "word": "glasses",
      "meaning": "眼镜",
      "grade": "4.2",
      "phonetic": "/ɡlɑːsɪz/",
      "highlightLetters": "gl",
      "highlightPhonetic": "/ɡl/",
      "note": "gl读/ɡl/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "338"
    },
    {
      "word": "glove",
      "meaning": "（分手指的）手套",
      "grade": "4.2",
      "phonetic": "/ɡlʌv/",
      "highlightLetters": "gl",
      "highlightPhonetic": "/ɡl/",
      "note": "gl读/ɡl/",
      "partOfSpeech": "名",
      "serialNumber": "339"
    },
    {
      "word": "play",
      "meaning": "玩；打（球）；放（音乐）",
      "grade": "4.2",
      "phonetic": "/ˈpleɪ/",
      "highlightLetters": "pl",
      "highlightPhonetic": "/pl/",
      "note": "pl读/kl/",
      "partOfSpeech": "动",
      "serialNumber": "340"
    },
    {
      "word": "playground",
      "meaning": "操场",
      "grade": "4.2",
      "phonetic": "/ˈpleɪɡraʊnd/",
      "highlightLetters": "pl",
      "highlightPhonetic": "/pl/",
      "note": "pl读/kl/",
      "partOfSpeech": "名",
      "serialNumber": "341"
    },
    {
      "word": "skirt",
      "meaning": "女裙",
      "grade": "4.2",
      "phonetic": "/skɜːt/",
      "highlightLetters": "sk",
      "highlightPhonetic": "/sk/",
      "note": "sk读/sk/",
      "partOfSpeech": "名",
      "serialNumber": "342"
    },
    {
      "word": "school",
      "meaning": "学校",
      "grade": "4.2",
      "phonetic": "/skuːl/",
      "highlightLetters": "sch",
      "highlightPhonetic": "/sk/",
      "note": "sch读/sk/",
      "partOfSpeech": "名",
      "serialNumber": "343"
    },
    {
      "word": "snowy",
      "meaning": "下雪（多）的",
      "grade": "4.2",
      "phonetic": "/ˈsnəʊi/",
      "highlightLetters": "sn",
      "highlightPhonetic": "/sn/",
      "note": "sn读/sn/",
      "partOfSpeech": "形",
      "serialNumber": "344"
    },
    {
      "word": "sweater",
      "meaning": "毛衣",
      "grade": "4.2",
      "phonetic": "/ˈswetə(r)/",
      "highlightLetters": "sw",
      "highlightPhonetic": "/sw/",
      "note": "sw读/sw/",
      "partOfSpeech": "名",
      "serialNumber": "345"
    },
    {
      "word": "cheap",
      "meaning": "便宜的",
      "grade": "4.2",
      "phonetic": "/tʃiːp/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "形",
      "serialNumber": "346"
    },
    {
      "word": "lunch",
      "meaning": "午餐；午饭",
      "grade": "4.2",
      "phonetic": "/lʌntʃ/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "347"
    },
    {
      "word": "much",
      "meaning": "许多（+不可数名词）",
      "grade": "4.2",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "形",
      "serialNumber": "348"
    },
    {
      "word": "teachers",
      "meaning": "教师们(复数)",
      "grade": "4.2",
      "phonetic": "/ˈtiːtʃə(r)z /",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "349"
    },
    {
      "word": "sheep",
      "meaning": "羊；绵羊",
      "grade": "4.2",
      "phonetic": "/ʃiːp/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "350"
    },
    {
      "word": "shirt",
      "meaning": "（尤指男士）衬衫",
      "grade": "4.2",
      "phonetic": "/ʃɜːt/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "351"
    },
    {
      "word": "shorts",
      "meaning": "短裤",
      "grade": "4.2",
      "phonetic": "/ʃɔːts/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "352"
    },
    {
      "word": "three",
      "meaning": "三",
      "grade": "4.2",
      "phonetic": "/θriː/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "数",
      "serialNumber": "353"
    },
    {
      "word": "thirty",
      "meaning": "三十",
      "grade": "4.2",
      "phonetic": "/ˈθɜːti/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "数",
      "serialNumber": "354"
    },
    {
      "word": "mouth",
      "meaning": "嘴",
      "grade": "4.2",
      "phonetic": "/maʊθ/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "名",
      "serialNumber": "355"
    },
    {
      "word": "these",
      "meaning": "（this 的复数）这些",
      "grade": "4.2",
      "phonetic": "/ðiːz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "代;形",
      "serialNumber": "356"
    },
    {
      "word": "those",
      "meaning": "（that 的复数）那些",
      "grade": "4.2",
      "phonetic": "/ðəʊz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "代;形",
      "serialNumber": "357"
    },
    {
      "word": "clothes",
      "meaning": "衣服；服装",
      "grade": "4.2",
      "phonetic": "/kləʊðz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "358"
    },
    {
      "word": "weather",
      "meaning": "天气",
      "grade": "4.2",
      "phonetic": "/ˈweðə(r)/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "不可数名",
      "serialNumber": "359"
    },
    {
      "word": "two",
      "meaning": "太；也",
      "grade": "4.2",
      "phonetic": "/tu:/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/t/",
      "note": "tw读/t/",
      "partOfSpeech": "数",
      "serialNumber": "360"
    },
    {
      "word": "twelve",
      "meaning": "十二",
      "grade": "4.2",
      "phonetic": "/twelv/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "数",
      "serialNumber": "361"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "4.2",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "数",
      "serialNumber": "362"
    }
  ]
};
