// 自动生成的JS模块 - grade5_2.json
// 生成时间: 2025-12-20T08:18:44.856Z

module.exports = {
  "grade": 5,
  "semester": 2,
  "gradeName": "小学五年级下册",
  "total": 142,
  "lastUpdated": "2025-12-20T02:06:14.961Z",
  "words": [
    {
      "word": "brave",
      "meaning": "勇敢的",
      "grade": "5.2",
      "phonetic": "/breɪv/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "形",
      "serialNumber": "1"
    },
    {
      "word": "keep",
      "meaning": "保持",
      "grade": "5.2",
      "phonetic": "/kiːp/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "动",
      "serialNumber": "2"
    },
    {
      "word": "mine",
      "meaning": "我的",
      "grade": "5.2",
      "phonetic": "/maɪn/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "代",
      "serialNumber": "3"
    },
    {
      "word": "polite",
      "meaning": "有礼貌的",
      "grade": "5.2",
      "phonetic": "/pəˈlaɪt/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "4"
    },
    {
      "word": "write",
      "meaning": "写",
      "grade": "5.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "5"
    },
    {
      "word": "exercise",
      "meaning": "锻炼；练习",
      "grade": "5.2",
      "phonetic": "/ˈeksəsaɪz/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "6"
    },
    {
      "word": "bamboo",
      "meaning": "竹子",
      "grade": "5.2",
      "phonetic": "/bæmˈbuː/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "7"
    },
    {
      "word": "Spanish",
      "meaning": "西班牙的",
      "grade": "5.2",
      "phonetic": "/ˈspænɪʃ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "8"
    },
    {
      "word": "Thanksgiving",
      "meaning": "感恩节",
      "grade": "5.2",
      "phonetic": "/ˈθæŋksˌɡɪvɪŋ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "9"
    },
    {
      "word": "elephant",
      "meaning": "大象",
      "grade": "5.2",
      "phonetic": "/ˈelɪfənt/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "10"
    },
    {
      "word": "exercise",
      "meaning": "锻炼；练习",
      "grade": "5.2",
      "phonetic": "/ˈeksəsaɪz/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "11"
    },
    {
      "word": "friend",
      "meaning": "朋友",
      "grade": "5.2",
      "phonetic": "/frend/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/e/",
      "note": "ie读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "12"
    },
    {
      "word": "clever",
      "meaning": "聪明的",
      "grade": "5.2",
      "phonetic": "/ˈklevə(r)/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "13"
    },
    {
      "word": "festival",
      "meaning": "节日",
      "grade": "5.2",
      "phonetic": "/ˈfestɪvəl/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "14"
    },
    {
      "word": "letter",
      "meaning": "信件",
      "grade": "5.2",
      "phonetic": "/ˈletə(r)/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "15"
    },
    {
      "word": "helpful",
      "meaning": "乐于助人的",
      "grade": "5.2",
      "phonetic": "/ˈhelpfʊl/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "16"
    },
    {
      "word": "win",
      "meaning": "赢；获胜",
      "grade": "5.2",
      "phonetic": "/wɪn/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "17"
    },
    {
      "word": "trip",
      "meaning": "旅行",
      "grade": "5.2",
      "phonetic": "/trɪp/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "18"
    },
    {
      "word": "swim",
      "meaning": "游泳",
      "grade": "5.2",
      "phonetic": "/swɪm/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "19"
    },
    {
      "word": "spring",
      "meaning": "春天",
      "grade": "5.2",
      "phonetic": "/sprɪŋ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "20"
    },
    {
      "word": "listen",
      "meaning": "听",
      "grade": "5.2",
      "phonetic": "/ˈlɪsn/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "21"
    },
    {
      "word": "winter",
      "meaning": "冬天",
      "grade": "5.2",
      "phonetic": "/ˈwɪntə(r)/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "22"
    },
    {
      "word": "Christmas",
      "meaning": "圣诞节",
      "grade": "5.2",
      "phonetic": "/ˈkrɪsməs/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "23"
    },
    {
      "word": "busy",
      "meaning": "忙碌的",
      "grade": "5.2",
      "phonetic": "/ˈbɪzi/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ɪ/",
      "note": "u读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "24"
    },
    {
      "word": "contest",
      "meaning": "比赛",
      "grade": "5.2",
      "phonetic": "/ˈkɒntest/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "25"
    },
    {
      "word": "honest",
      "meaning": "诚实的",
      "grade": "5.2",
      "phonetic": "/ˈɒnɪst/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "26"
    },
    {
      "word": "summer",
      "meaning": "夏天",
      "grade": "5.2",
      "phonetic": "/ˈsʌmə(r)/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "27"
    },
    {
      "word": "monkey",
      "meaning": "猴子",
      "grade": "5.2",
      "phonetic": "/ˈmʌŋki/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "28"
    },
    {
      "word": "park",
      "meaning": "公园",
      "grade": "5.2",
      "phonetic": "/pɑːk/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "29"
    },
    {
      "word": "plant",
      "meaning": "植物；种植",
      "grade": "5.2",
      "phonetic": "/plɑːnt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名或动",
      "serialNumber": "30"
    },
    {
      "word": "giraffe",
      "meaning": "长颈鹿",
      "grade": "5.2",
      "phonetic": "/dʒəˈrɑːf/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "31"
    },
    {
      "word": "koala",
      "meaning": "考拉",
      "grade": "5.2",
      "phonetic": "/kəʊˈɑːlə/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "32"
    },
    {
      "word": "draw",
      "meaning": "画画",
      "grade": "5.2",
      "phonetic": "/drɔː/",
      "highlightLetters": "aw",
      "highlightPhonetic": "/ɔː/",
      "note": "aw读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "33"
    },
    {
      "word": "autumn",
      "meaning": "秋天",
      "grade": "5.2",
      "phonetic": "/ˈɔːtəm/",
      "highlightLetters": "au",
      "highlightPhonetic": "/ɔː/",
      "note": "au读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "34"
    },
    {
      "word": "walk",
      "meaning": "走路",
      "grade": "5.2",
      "phonetic": "/wɔːk/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "35"
    },
    {
      "word": "yours",
      "meaning": "你的",
      "grade": "5.2",
      "phonetic": "/jɔːz/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ɔː/",
      "note": "our读长元音/ɔː/",
      "partOfSpeech": "代",
      "serialNumber": "36"
    },
    {
      "word": "fur",
      "meaning": "毛皮",
      "grade": "5.2",
      "phonetic": "/fɜː(r)/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "37"
    },
    {
      "word": "clean",
      "meaning": "干净的；打扫",
      "grade": "5.2",
      "phonetic": "/kliːn/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "38"
    },
    {
      "word": "read",
      "meaning": "读",
      "grade": "5.2",
      "phonetic": "/riːd/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "39"
    },
    {
      "word": "season",
      "meaning": "季节",
      "grade": "5.2",
      "phonetic": "/ˈsiːzn/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "40"
    },
    {
      "word": "speak",
      "meaning": "说",
      "grade": "5.2",
      "phonetic": "/spiːk/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "41"
    },
    {
      "word": "teach",
      "meaning": "教",
      "grade": "5.2",
      "phonetic": "/tiːtʃ/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "42"
    },
    {
      "word": "sleeping",
      "meaning": "睡觉",
      "grade": "5.2",
      "phonetic": "/ˈsliːpɪŋ/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "43"
    },
    {
      "word": "sushi",
      "meaning": "寿司",
      "grade": "5.2",
      "phonetic": "/ˈsuːʃi/",
      "highlightLetters": "u",
      "highlightPhonetic": "/uː/",
      "note": "u读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "44"
    },
    {
      "word": "bamboo",
      "meaning": "竹子",
      "grade": "5.2",
      "phonetic": "/bæmˈbuː/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "45"
    },
    {
      "word": "usually",
      "meaning": "通常地",
      "grade": "5.2",
      "phonetic": "/ˈjuːʒuəli/",
      "highlightLetters": "第1个u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "副",
      "serialNumber": "46"
    },
    {
      "word": "labour",
      "meaning": "劳动",
      "grade": "5.2",
      "phonetic": "/ˈleɪbə/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "47"
    },
    {
      "word": "Canadian",
      "meaning": "加拿大的",
      "grade": "5.2",
      "phonetic": "/kəˈneɪdiən/",
      "highlightLetters": "第2个a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "形",
      "serialNumber": "48"
    },
    {
      "word": "vacation",
      "meaning": "假期",
      "grade": "5.2",
      "phonetic": "/vəˈkeɪʃn/",
      "highlightLetters": "第2个a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "49"
    },
    {
      "word": "climbing",
      "meaning": "正在爬",
      "grade": "5.2",
      "phonetic": "/ˈklaɪmɪŋ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "现在分词",
      "serialNumber": "50"
    },
    {
      "word": "diary",
      "meaning": "日记",
      "grade": "5.2",
      "phonetic": "/ˈdaɪəri/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "51"
    },
    {
      "word": "excited",
      "meaning": "兴奋的",
      "grade": "5.2",
      "phonetic": "/ɪkˈsaɪtɪd/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "52"
    },
    {
      "word": "island",
      "meaning": "岛屿",
      "grade": "5.2",
      "phonetic": "/ˈaɪlənd/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "53"
    },
    {
      "word": "kind",
      "meaning": "友善的",
      "grade": "5.2",
      "phonetic": "/kaɪnd/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "54"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "5.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "55"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "5.2",
      "phonetic": "/ˈkwaɪət/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形",
      "serialNumber": "56"
    },
    {
      "word": "snowman",
      "meaning": "雪人",
      "grade": "5.2",
      "phonetic": "/ˈsnəʊmæn/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "57"
    },
    {
      "word": "park",
      "meaning": "公园",
      "grade": "5.2",
      "phonetic": "/pɑːk/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读双元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "58"
    },
    {
      "word": "theirs",
      "meaning": "他们的",
      "grade": "5.2",
      "phonetic": "/ðeəz/",
      "highlightLetters": "eir",
      "highlightPhonetic": "/eə/",
      "note": "eir读双元音/eə/",
      "partOfSpeech": "代",
      "serialNumber": "59"
    },
    {
      "word": "ours",
      "meaning": "我们的",
      "grade": "5.2",
      "phonetic": "/aʊəz/",
      "highlightLetters": "our",
      "highlightPhonetic": "/aʊə/",
      "note": "our读双元音/aʊə/",
      "partOfSpeech": "代",
      "serialNumber": "60"
    },
    {
      "word": "yours",
      "meaning": "你的",
      "grade": "5.2",
      "phonetic": "/jɔːz/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ɔː/",
      "note": "our读双元音/ɔː/",
      "partOfSpeech": "代",
      "serialNumber": "61"
    },
    {
      "word": "labour",
      "meaning": "劳动",
      "grade": "5.2",
      "phonetic": "/ˈleɪbə/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ə/",
      "note": "our读弱音/ə/",
      "partOfSpeech": "名",
      "serialNumber": "62"
    },
    {
      "word": "fur",
      "meaning": "毛皮",
      "grade": "5.2",
      "phonetic": "/fɜː(r)/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "63"
    },
    {
      "word": "turn",
      "meaning": "转动",
      "grade": "5.2",
      "phonetic": "/tɜːn/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "64"
    },
    {
      "word": "autumn",
      "meaning": "秋天",
      "grade": "5.2",
      "phonetic": "/ˈɔːtəm/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ə/",
      "note": "u弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "65"
    },
    {
      "word": "Christmas",
      "meaning": "圣诞节",
      "grade": "5.2",
      "phonetic": "/ˈkrɪsməs/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "66"
    },
    {
      "word": "exercise",
      "meaning": "锻炼；练习",
      "grade": "5.2",
      "phonetic": "/ˈeksəsaɪz/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "67"
    },
    {
      "word": "festival",
      "meaning": "节日",
      "grade": "5.2",
      "phonetic": "/ˈfestɪvəl/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "68"
    },
    {
      "word": "giraffe",
      "meaning": "长颈鹿",
      "grade": "5.2",
      "phonetic": "/dʒəˈrɑːf/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ə/",
      "note": "i弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "69"
    },
    {
      "word": "island",
      "meaning": "岛屿",
      "grade": "5.2",
      "phonetic": "/ˈaɪlənd/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "70"
    },
    {
      "word": "koala",
      "meaning": "考拉",
      "grade": "5.2",
      "phonetic": "/kəʊˈɑːlə/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "71"
    },
    {
      "word": "labour",
      "meaning": "劳动",
      "grade": "5.2",
      "phonetic": "/ˈleɪbə/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ə/",
      "note": "our读弱音/ə/",
      "partOfSpeech": "名",
      "serialNumber": "72"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "5.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "73"
    },
    {
      "word": "panda",
      "meaning": "熊猫",
      "grade": "5.2",
      "phonetic": "/ˈpændə/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "74"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "5.2",
      "phonetic": "/ˈkwaɪət/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ə/",
      "note": "e弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "75"
    },
    {
      "word": "usually",
      "meaning": "通常地",
      "grade": "5.2",
      "phonetic": "/ˈjuːʒuəli/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "副",
      "serialNumber": "76"
    },
    {
      "word": "vacation",
      "meaning": "假期",
      "grade": "5.2",
      "phonetic": "/vəˈkeɪʃn/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "77"
    },
    {
      "word": "honest",
      "meaning": "诚实的",
      "grade": "5.2",
      "phonetic": "/ˈɒnɪst/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "78"
    },
    {
      "word": "monkey",
      "meaning": "猴子",
      "grade": "5.2",
      "phonetic": "/ˈmʌŋki/",
      "highlightLetters": "ey",
      "highlightPhonetic": "/i/",
      "note": "ey弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "79"
    },
    {
      "word": "elephant",
      "meaning": "大象",
      "grade": "5.2",
      "phonetic": "/ˈelɪfənt/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "80"
    },
    {
      "word": "excited",
      "meaning": "兴奋的",
      "grade": "5.2",
      "phonetic": "/ɪkˈsaɪtɪd/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "81"
    },
    {
      "word": "listen",
      "meaning": "听",
      "grade": "5.2",
      "phonetic": "/ˈlɪsn/",
      "highlightLetters": "sten",
      "highlightPhonetic": "/sn/",
      "note": "/sn/弱音省略",
      "partOfSpeech": "动",
      "serialNumber": "82"
    },
    {
      "word": "season",
      "meaning": "季节",
      "grade": "5.2",
      "phonetic": "/ˈsiːzn/",
      "highlightLetters": "son",
      "highlightPhonetic": "/zn/",
      "note": "/zn/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "83"
    },
    {
      "word": "bamboo",
      "meaning": "竹子",
      "grade": "5.2",
      "phonetic": "/bæmˈbuː/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "84"
    },
    {
      "word": "busy",
      "meaning": "忙碌的",
      "grade": "5.2",
      "phonetic": "/ˈbɪzi/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "形",
      "serialNumber": "85"
    },
    {
      "word": "Canadian",
      "meaning": "加拿大的",
      "grade": "5.2",
      "phonetic": "/kəˈneɪdiən/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "形",
      "serialNumber": "86"
    },
    {
      "word": "clean",
      "meaning": "干净的；打扫",
      "grade": "5.2",
      "phonetic": "/kliːn/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在辅音前）",
      "partOfSpeech": "形；动",
      "serialNumber": "87"
    },
    {
      "word": "contest",
      "meaning": "比赛",
      "grade": "5.2",
      "phonetic": "/ˈkɒntest/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名",
      "serialNumber": "88"
    },
    {
      "word": "diary",
      "meaning": "日记",
      "grade": "5.2",
      "phonetic": "/ˈdaɪəri/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "89"
    },
    {
      "word": "festival",
      "meaning": "节日",
      "grade": "5.2",
      "phonetic": "/ˈfestɪvəl/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "90"
    },
    {
      "word": "fur",
      "meaning": "毛皮（不可数）",
      "grade": "5.2",
      "phonetic": "/fɜː(r)/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "91"
    },
    {
      "word": "giraffe",
      "meaning": "长颈鹿",
      "grade": "5.2",
      "phonetic": "/dʒəˈrɑːf/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "92"
    },
    {
      "word": "honest",
      "meaning": "诚实的",
      "grade": "5.2",
      "phonetic": "/ˈɒnɪst/",
      "highlightLetters": "h",
      "highlightPhonetic": "",
      "note": "h不发音",
      "partOfSpeech": "形",
      "serialNumber": "93"
    },
    {
      "word": "keep",
      "meaning": "保持",
      "grade": "5.2",
      "phonetic": "/kiːp/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "动",
      "serialNumber": "94"
    },
    {
      "word": "kind",
      "meaning": "友善的",
      "grade": "5.2",
      "phonetic": "/kaɪnd/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "形",
      "serialNumber": "95"
    },
    {
      "word": "koala",
      "meaning": "考拉",
      "grade": "5.2",
      "phonetic": "/kəʊˈɑːlə/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "96"
    },
    {
      "word": "labour",
      "meaning": "劳动",
      "grade": "5.2",
      "phonetic": "/ˈleɪbə/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "97"
    },
    {
      "word": "letter",
      "meaning": "信件",
      "grade": "5.2",
      "phonetic": "/ˈletə(r)/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "98"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "5.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "99"
    },
    {
      "word": "listen",
      "meaning": "听",
      "grade": "5.2",
      "phonetic": "/ˈlɪsn/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "100"
    },
    {
      "word": "mine",
      "meaning": "我的",
      "grade": "5.2",
      "phonetic": "/maɪn/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "代",
      "serialNumber": "101"
    },
    {
      "word": "monkey",
      "meaning": "猴子",
      "grade": "5.2",
      "phonetic": "/ˈmʌŋki/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "102"
    },
    {
      "word": "panda",
      "meaning": "熊猫",
      "grade": "5.2",
      "phonetic": "/ˈpændə/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "103"
    },
    {
      "word": "park",
      "meaning": "公园",
      "grade": "5.2",
      "phonetic": "/pɑːk/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "104"
    },
    {
      "word": "polite",
      "meaning": "有礼貌的",
      "grade": "5.2",
      "phonetic": "/pəˈlaɪt/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "形",
      "serialNumber": "105"
    },
    {
      "word": "elephant",
      "meaning": "大象",
      "grade": "5.2",
      "phonetic": "/ˈelɪfənt/",
      "highlightLetters": "ph",
      "highlightPhonetic": "/f/",
      "note": "ph读/f/",
      "partOfSpeech": "名",
      "serialNumber": "106"
    },
    {
      "word": "read",
      "meaning": "读",
      "grade": "5.2",
      "phonetic": "/riːd/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "动",
      "serialNumber": "107"
    },
    {
      "word": "season",
      "meaning": "季节",
      "grade": "5.2",
      "phonetic": "/ˈsiːzn/",
      "highlightLetters": "第1个s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "108"
    },
    {
      "word": "summer",
      "meaning": "夏天",
      "grade": "5.2",
      "phonetic": "/ˈsʌmə(r)/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "109"
    },
    {
      "word": "sushi",
      "meaning": "寿司",
      "grade": "5.2",
      "phonetic": "/ˈsuːʃi/",
      "highlightLetters": "第1个s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "110"
    },
    {
      "word": "noise",
      "meaning": "噪音",
      "grade": "5.2",
      "phonetic": "/nɔɪz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "111"
    },
    {
      "word": "usually",
      "meaning": "通常地",
      "grade": "5.2",
      "phonetic": "/ˈjuːʒuəli/",
      "highlightLetters": "s",
      "highlightPhonetic": "/ʒ/",
      "note": "s读/ʒ/",
      "partOfSpeech": "副",
      "serialNumber": "112"
    },
    {
      "word": "island",
      "meaning": "岛屿",
      "grade": "5.2",
      "phonetic": "/ˈaɪlənd/",
      "highlightLetters": "s",
      "highlightPhonetic": "",
      "note": "s不发音",
      "partOfSpeech": "名",
      "serialNumber": "113"
    },
    {
      "word": "teach",
      "meaning": "教",
      "grade": "5.2",
      "phonetic": "/tiːtʃ/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "114"
    },
    {
      "word": "turn",
      "meaning": "转动",
      "grade": "5.2",
      "phonetic": "/tɜːn/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "115"
    },
    {
      "word": "walk",
      "meaning": "走路",
      "grade": "5.2",
      "phonetic": "/wɔːk/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "116"
    },
    {
      "word": "win",
      "meaning": "赢；获胜",
      "grade": "5.2",
      "phonetic": "/wɪn/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "117"
    },
    {
      "word": "winter",
      "meaning": "冬天",
      "grade": "5.2",
      "phonetic": "/ˈwɪntə(r)/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "118"
    },
    {
      "word": "yours",
      "meaning": "你的",
      "grade": "5.2",
      "phonetic": "/jɔːz/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （辅音）",
      "partOfSpeech": "代",
      "serialNumber": "119"
    },
    {
      "word": "brave",
      "meaning": "勇敢的",
      "grade": "5.2",
      "phonetic": "/breɪv/",
      "highlightLetters": "br",
      "highlightPhonetic": "/br/",
      "note": "br读/br/",
      "partOfSpeech": "形",
      "serialNumber": "120"
    },
    {
      "word": "library",
      "meaning": "图书馆",
      "grade": "5.2",
      "phonetic": "/ˈlaɪbrəri/",
      "highlightLetters": "br",
      "highlightPhonetic": "/br/",
      "note": "br读/br/",
      "partOfSpeech": "名",
      "serialNumber": "121"
    },
    {
      "word": "Christmas",
      "meaning": "圣诞节",
      "grade": "5.2",
      "phonetic": "/ˈkrɪsməs/",
      "highlightLetters": "chr",
      "highlightPhonetic": "/kr/",
      "note": "kr读/kr/",
      "partOfSpeech": "名",
      "serialNumber": "122"
    },
    {
      "word": "draw",
      "meaning": "画画",
      "grade": "5.2",
      "phonetic": "/drɔː/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "动",
      "serialNumber": "123"
    },
    {
      "word": "friend",
      "meaning": "朋友",
      "grade": "5.2",
      "phonetic": "/frend/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "名",
      "serialNumber": "124"
    },
    {
      "word": "trip",
      "meaning": "旅行",
      "grade": "5.2",
      "phonetic": "/trɪp/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/fr/",
      "partOfSpeech": "名",
      "serialNumber": "125"
    },
    {
      "word": "clever",
      "meaning": "聪明的",
      "grade": "5.2",
      "phonetic": "/ˈklevə(r)/",
      "highlightLetters": "cl",
      "highlightPhonetic": "/kl/",
      "note": "cl读/fl/",
      "partOfSpeech": "形",
      "serialNumber": "126"
    },
    {
      "word": "plant",
      "meaning": "植物；种植",
      "grade": "5.2",
      "phonetic": "/plɑːnt/",
      "highlightLetters": "pl",
      "highlightPhonetic": "/pl/",
      "note": "pl读/kl/",
      "partOfSpeech": "名或动",
      "serialNumber": "127"
    },
    {
      "word": "sleeping",
      "meaning": "睡觉",
      "grade": "5.2",
      "phonetic": "/ˈsliːpɪŋ/",
      "highlightLetters": "sl",
      "highlightPhonetic": "/sl/",
      "note": "sl读/kl/",
      "partOfSpeech": "现在分词",
      "serialNumber": "128"
    },
    {
      "word": "snowman",
      "meaning": "雪人",
      "grade": "5.2",
      "phonetic": "/ˈsnəʊmæn/",
      "highlightLetters": "sn",
      "highlightPhonetic": "/sn/",
      "note": "sn读/sn/",
      "partOfSpeech": "名",
      "serialNumber": "129"
    },
    {
      "word": "speak",
      "meaning": "说",
      "grade": "5.2",
      "phonetic": "/spiːk/",
      "highlightLetters": "sp",
      "highlightPhonetic": "/sp/",
      "note": "sp读/sp/",
      "partOfSpeech": "动",
      "serialNumber": "130"
    },
    {
      "word": "spring",
      "meaning": "春天",
      "grade": "5.2",
      "phonetic": "/sprɪŋ/",
      "highlightLetters": "sp",
      "highlightPhonetic": "/sp/",
      "note": "sp读/sp/",
      "partOfSpeech": "名",
      "serialNumber": "131"
    },
    {
      "word": "swim",
      "meaning": "游泳",
      "grade": "5.2",
      "phonetic": "/swɪm/",
      "highlightLetters": "sw",
      "highlightPhonetic": "/sw/",
      "note": "sw读/sw/",
      "partOfSpeech": "名",
      "serialNumber": "132"
    },
    {
      "word": "vacation",
      "meaning": "假期",
      "grade": "5.2",
      "phonetic": "/vəˈkeɪʃn/",
      "highlightLetters": "tion",
      "highlightPhonetic": "/ʃn/",
      "note": "tion读/ʃn/",
      "partOfSpeech": "名",
      "serialNumber": "133"
    },
    {
      "word": "national",
      "meaning": "国家的；民族的",
      "grade": "5.2",
      "phonetic": "/ˈnæʃənəl/",
      "highlightLetters": "tion",
      "highlightPhonetic": "/ʃn/",
      "note": "tion读/ʃn/",
      "partOfSpeech": "形",
      "serialNumber": "134"
    },
    {
      "word": "Thanksgiving",
      "meaning": "感恩节",
      "grade": "5.2",
      "phonetic": "/ˈθæŋksˌɡɪvɪŋ/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "名",
      "serialNumber": "135"
    },
    {
      "word": "theirs",
      "meaning": "他们的",
      "grade": "5.2",
      "phonetic": "/ðeəz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "代",
      "serialNumber": "136"
    },
    {
      "word": "autumn",
      "meaning": "秋天",
      "grade": "5.2",
      "phonetic": "/ˈɔːtəm/",
      "highlightLetters": "mn",
      "highlightPhonetic": "/m/",
      "note": "n不发音",
      "partOfSpeech": "名",
      "serialNumber": "137"
    },
    {
      "word": "climbing",
      "meaning": "正在爬",
      "grade": "5.2",
      "phonetic": "/ˈklaɪmɪŋ/",
      "highlightLetters": "mb",
      "highlightPhonetic": "/m/",
      "note": "b不发音",
      "partOfSpeech": "现在分词",
      "serialNumber": "138"
    },
    {
      "word": "Christmas",
      "meaning": "圣诞节",
      "grade": "5.2",
      "phonetic": "/ˈkrɪsməs/",
      "highlightLetters": "tm",
      "highlightPhonetic": "/m/",
      "note": "t不发音",
      "partOfSpeech": "名",
      "serialNumber": "139"
    },
    {
      "word": "island",
      "meaning": "岛屿",
      "grade": "5.2",
      "phonetic": "/ˈaɪlənd/",
      "highlightLetters": "sl",
      "highlightPhonetic": "/s/",
      "note": "s不发音",
      "partOfSpeech": "名",
      "serialNumber": "140"
    },
    {
      "word": "honest",
      "meaning": "诚实的",
      "grade": "5.2",
      "phonetic": "/ˈɒnɪst/",
      "highlightLetters": "h",
      "highlightPhonetic": "/ɒ/",
      "note": "h不发音",
      "partOfSpeech": "形",
      "serialNumber": "141"
    },
    {
      "word": "write",
      "meaning": "写",
      "grade": "5.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "wr",
      "highlightPhonetic": "/r/",
      "note": "w不发音",
      "partOfSpeech": "动",
      "serialNumber": "142"
    }
  ]
};
