// 自动生成的JS模块 - grade6_2.json
// 生成时间: 2025-12-20T08:18:45.101Z

module.exports = {
  "grade": 6,
  "semester": 2,
  "gradeName": "小学六年级下册",
  "total": 221,
  "lastUpdated": "2025-12-20T08:15:10.324Z",
  "words": [
    {
      "word": "ate",
      "meaning": "（eat 的过去式）吃",
      "grade": "6.2",
      "phonetic": "/eɪt/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "1"
    },
    {
      "word": "skate",
      "meaning": "滑",
      "grade": "6.2",
      "phonetic": "/skeɪt/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "2"
    },
    {
      "word": "race",
      "meaning": "赛跑",
      "grade": "6.2",
      "phonetic": "/reɪs/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "3"
    },
    {
      "word": "wake",
      "meaning": "醒",
      "grade": "6.2",
      "phonetic": "/weik/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "4"
    },
    {
      "word": "cheetah",
      "meaning": "猎豹",
      "grade": "6.2",
      "phonetic": "/ˈtʃiːtə/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "5"
    },
    {
      "word": "ice",
      "meaning": "冰",
      "grade": "6.2",
      "phonetic": "/aɪs/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "6"
    },
    {
      "word": "ride",
      "meaning": "骑（马；自行车）",
      "grade": "6.2",
      "phonetic": "/raid/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "7"
    },
    {
      "word": "ago",
      "meaning": "以前",
      "grade": "6.2",
      "phonetic": "/əˈɡəʊ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "副",
      "serialNumber": "8"
    },
    {
      "word": "rode",
      "meaning": "（ride 的过去式）骑（马；自行车）",
      "grade": "6.2",
      "phonetic": "/rəʊd/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "9"
    },
    {
      "word": "woke",
      "meaning": "（wake 的过去式）醒",
      "grade": "6.2",
      "phonetic": "/wəʊk/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "10"
    },
    {
      "word": "mule",
      "meaning": "骡子",
      "grade": "6.2",
      "phonetic": "/mjuːl/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "11"
    },
    {
      "word": "had",
      "meaning": "（have 的过去式）患病；得病",
      "grade": "6.2",
      "phonetic": "/hæd/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "动",
      "serialNumber": "12"
    },
    {
      "word": "camp",
      "meaning": "野营",
      "grade": "6.2",
      "phonetic": "/kæmp/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "13"
    },
    {
      "word": "lamp",
      "meaning": "台灯",
      "grade": "6.2",
      "phonetic": "/læmp/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "14"
    },
    {
      "word": "than",
      "meaning": "比",
      "grade": "6.2",
      "phonetic": "/ðæn/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "连或介",
      "serialNumber": "15"
    },
    {
      "word": "drank",
      "meaning": "（drink 的过去式）喝",
      "grade": "6.2",
      "phonetic": "/dræŋk/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "动",
      "serialNumber": "16"
    },
    {
      "word": "active",
      "meaning": "积极的；活跃的",
      "grade": "6.2",
      "phonetic": "/ˈæktɪv/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "17"
    },
    {
      "word": "badminton",
      "meaning": "羽毛球运动",
      "grade": "6.2",
      "phonetic": "/ˈbædmɪntən/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "18"
    },
    {
      "word": "fell",
      "meaning": "（fall的过去式）摔倒",
      "grade": "6.2",
      "phonetic": "/fel/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "19"
    },
    {
      "word": "felt",
      "meaning": "（feel 的过去式）感觉",
      "grade": "6.2",
      "phonetic": "/felt/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "20"
    },
    {
      "word": "went",
      "meaning": "（go 的过去式）去",
      "grade": "6.2",
      "phonetic": "/went/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "21"
    },
    {
      "word": "slept",
      "meaning": "（sleep 的过去式）睡觉",
      "grade": "6.2",
      "phonetic": "/slept/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "22"
    },
    {
      "word": "hotel",
      "meaning": "旅馆",
      "grade": "6.2",
      "phonetic": "/həʊˈtel/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "23"
    },
    {
      "word": "better",
      "meaning": "（well 的比较级）更好的",
      "grade": "6.2",
      "phonetic": "/ˈbetə(r)/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "24"
    },
    {
      "word": "yesterday",
      "meaning": "昨天",
      "grade": "6.2",
      "phonetic": "/ˈjestədeɪ/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "副",
      "serialNumber": "25"
    },
    {
      "word": "heavier",
      "meaning": "（heavy 的比较级）更重的",
      "grade": "6.2",
      "phonetic": "/ˈheviə(r)/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "26"
    },
    {
      "word": "fish",
      "meaning": "钓鱼；捕鱼",
      "grade": "6.2",
      "phonetic": "/fɪʃ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "27"
    },
    {
      "word": "gift",
      "meaning": "礼物",
      "grade": "6.2",
      "phonetic": "/ɡɪft/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "28"
    },
    {
      "word": "gym",
      "meaning": "体育馆",
      "grade": "6.2",
      "phonetic": "/dʒɪm/",
      "highlightLetters": "y",
      "highlightPhonetic": "/ɪ/",
      "note": "y读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "29"
    },
    {
      "word": "till",
      "meaning": "直到",
      "grade": "6.2",
      "phonetic": "/tɪl/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "连或介",
      "serialNumber": "30"
    },
    {
      "word": "trip",
      "meaning": "绊倒；短途旅行",
      "grade": "6.2",
      "phonetic": "/trɪp/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动或名",
      "serialNumber": "31"
    },
    {
      "word": "licked",
      "meaning": "（lick 的过去式）舔",
      "grade": "6.2",
      "phonetic": "/lɪkt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "32"
    },
    {
      "word": "fixed",
      "meaning": "（fix 的过去式）修理",
      "grade": "6.2",
      "phonetic": "/fɪkst/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "33"
    },
    {
      "word": "bigger",
      "meaning": "（big 的比较级）更大的",
      "grade": "6.2",
      "phonetic": "/ˈbɪɡə(r)/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "34"
    },
    {
      "word": "thinner",
      "meaning": "（thin 的比较级）更瘦的",
      "grade": "6.2",
      "phonetic": "/ˈθɪnə(r)/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "35"
    },
    {
      "word": "different",
      "meaning": "不同的",
      "grade": "6.2",
      "phonetic": "/ˈdɪfrənt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "36"
    },
    {
      "word": "Internet",
      "meaning": "互联网",
      "grade": "6.2",
      "phonetic": "/ˈɪntənet/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "37"
    },
    {
      "word": "kilogram",
      "meaning": "千克；公斤",
      "grade": "6.2",
      "phonetic": "/ˈkɪləɡræm/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "38"
    },
    {
      "word": "off",
      "meaning": "从（某处）落下",
      "grade": "6.2",
      "phonetic": "/ɒf/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "副",
      "serialNumber": "39"
    },
    {
      "word": "longer",
      "meaning": "（long 的比较级）更长的",
      "grade": "6.2",
      "phonetic": "/ˈlɒŋɡə(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "40"
    },
    {
      "word": "stronger",
      "meaning": "（strong 的比较级）更强壮的",
      "grade": "6.2",
      "phonetic": "/ˈstrɒŋɡə(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "41"
    },
    {
      "word": "washed",
      "meaning": "（wash 的过去式）洗",
      "grade": "6.2",
      "phonetic": "/wɒʃt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɒ/",
      "note": "a读短音/ɒ /",
      "partOfSpeech": "动",
      "serialNumber": "42"
    },
    {
      "word": "watched",
      "meaning": "（watch 的过去式）看",
      "grade": "6.2",
      "phonetic": "/wɒtʃt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɒ/",
      "note": "a读短音/ɒ /",
      "partOfSpeech": "动",
      "serialNumber": "43"
    },
    {
      "word": "become",
      "meaning": "开始变得；变成",
      "grade": "6.2",
      "phonetic": "/bɪˈkʌm/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "44"
    },
    {
      "word": "nothing",
      "meaning": "没有什么",
      "grade": "6.2",
      "phonetic": "/ˈnʌθɪŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "代",
      "serialNumber": "45"
    },
    {
      "word": "countryside",
      "meaning": "乡村",
      "grade": "6.2",
      "phonetic": "/ˈkʌntrisaɪd/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʌ/",
      "note": "ou读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "46"
    },
    {
      "word": "younger",
      "meaning": "（young 的比较级）更年轻的",
      "grade": "6.2",
      "phonetic": "/ˈjʌŋɡə(r)/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʌ/",
      "note": "ou读短音/ʌ /",
      "partOfSpeech": "形",
      "serialNumber": "47"
    },
    {
      "word": "look",
      "meaning": "看",
      "grade": "6.2",
      "phonetic": "/lʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ/",
      "partOfSpeech": "动",
      "serialNumber": "48"
    },
    {
      "word": "took",
      "meaning": "（take 的过去式）拍照",
      "grade": "6.2",
      "phonetic": "/tʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ/",
      "partOfSpeech": "动",
      "serialNumber": "49"
    },
    {
      "word": "could",
      "meaning": "（can 的过去式）能",
      "grade": "6.2",
      "phonetic": "/kʊd/",
      "highlightLetters": "oul",
      "highlightPhonetic": "/ʊ/",
      "note": "oul读短音/ʊ/",
      "partOfSpeech": "动",
      "serialNumber": "50"
    },
    {
      "word": "basket",
      "meaning": "篮；筐",
      "grade": "6.2",
      "phonetic": "/ˈbɑːskɪt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "51"
    },
    {
      "word": "faster",
      "meaning": "（fast 的比较级）更快的",
      "grade": "6.2",
      "phonetic": "/ˈfɑːstə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "形",
      "serialNumber": "52"
    },
    {
      "word": "grass",
      "meaning": "草坪",
      "grade": "6.2",
      "phonetic": "/ɡrɑːs/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "53"
    },
    {
      "word": "last",
      "meaning": "最近的；上一个的",
      "grade": "6.2",
      "phonetic": "/lɑːst/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "形",
      "serialNumber": "54"
    },
    {
      "word": "star",
      "meaning": "星",
      "grade": "6.2",
      "phonetic": "/stɑː(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "55"
    },
    {
      "word": "part",
      "meaning": "角色",
      "grade": "6.2",
      "phonetic": "/pɑːt/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "56"
    },
    {
      "word": "smarter",
      "meaning": "（smart 的比较级）更聪明的",
      "grade": "6.2",
      "phonetic": "/ˈsmɑːtə(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "形",
      "serialNumber": "57"
    },
    {
      "word": "laughed",
      "meaning": "（laugh 的过去式）笑",
      "grade": "6.2",
      "phonetic": "/lɑːft/",
      "highlightLetters": "au",
      "highlightPhonetic": "/ɑː/",
      "note": "au读长元音/ɑː/",
      "partOfSpeech": "动",
      "serialNumber": "58"
    },
    {
      "word": "before",
      "meaning": "在……之前",
      "grade": "6.2",
      "phonetic": "/bɪˈfɔː(r)/",
      "highlightLetters": "ore",
      "highlightPhonetic": "/ɔː/",
      "note": "ore读长元音/ɔː/",
      "partOfSpeech": "介/连/副",
      "serialNumber": "59"
    },
    {
      "word": "bought",
      "meaning": "（buy 的过去式）买",
      "grade": "6.2",
      "phonetic": "/bɔːt/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ɔː/",
      "note": "ou读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "60"
    },
    {
      "word": "thought",
      "meaning": "（think 的过去式）想",
      "grade": "6.2",
      "phonetic": "/θɔːt/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ɔː/",
      "note": "ou读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "61"
    },
    {
      "word": "dinosaur",
      "meaning": "恐龙",
      "grade": "6.2",
      "phonetic": "/ˈdaɪnəsɔː(r)/",
      "highlightLetters": "aur",
      "highlightPhonetic": "/ɔː/",
      "note": "aur读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "62"
    },
    {
      "word": "hall",
      "meaning": "大厅",
      "grade": "6.2",
      "phonetic": "/hɔːl/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "63"
    },
    {
      "word": "smaller",
      "meaning": "（small 的比较级）更小的",
      "grade": "6.2",
      "phonetic": "/ˈsmɔːlə(r)/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "形",
      "serialNumber": "64"
    },
    {
      "word": "taller",
      "meaning": "（tall 的比较级）更高的",
      "grade": "6.2",
      "phonetic": "/ˈtɔːlə(r)/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "形",
      "serialNumber": "65"
    },
    {
      "word": "shorter",
      "meaning": "（short 的比较级）更矮的；更短的",
      "grade": "6.2",
      "phonetic": "/ˈʃɔːtə(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "形",
      "serialNumber": "66"
    },
    {
      "word": "saw",
      "meaning": "（see 的过去式）看见",
      "grade": "6.2",
      "phonetic": "/sɔː/",
      "highlightLetters": "aw",
      "highlightPhonetic": "/ɔː/",
      "note": "aw读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "67"
    },
    {
      "word": "hurt",
      "meaning": "（hurt 的过去式）（使）受伤",
      "grade": "6.2",
      "phonetic": "/hɜːt/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "68"
    },
    {
      "word": "metre",
      "meaning": "米",
      "grade": "6.2",
      "phonetic": "/ˈmiːtə(r)/",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "69"
    },
    {
      "word": "cheetah",
      "meaning": "猎豹",
      "grade": "6.2",
      "phonetic": "/ˈtʃiːtə/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "70"
    },
    {
      "word": "beach",
      "meaning": "海滩；沙滩",
      "grade": "6.2",
      "phonetic": "/biːtʃ/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "71"
    },
    {
      "word": "cleaned",
      "meaning": "（clean 的过去式）打扫",
      "grade": "6.2",
      "phonetic": "/kliːnd/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "72"
    },
    {
      "word": "dream",
      "meaning": "梦",
      "grade": "6.2",
      "phonetic": "/driːm/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "73"
    },
    {
      "word": "easy",
      "meaning": "容易的",
      "grade": "6.2",
      "phonetic": "/ˈiːzi/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "形",
      "serialNumber": "74"
    },
    {
      "word": "magazine",
      "meaning": "杂志",
      "grade": "6.2",
      "phonetic": "/ˌmæɡəˈziːn/",
      "highlightLetters": "i",
      "highlightPhonetic": "/iː/",
      "note": "i读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "75"
    },
    {
      "word": "Turpan",
      "meaning": "吐鲁番",
      "grade": "6.2",
      "phonetic": "/ˈtuːˈpɑːn/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/uː/",
      "note": "ur读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "76"
    },
    {
      "word": "ate",
      "meaning": "（eat 的过去式）吃",
      "grade": "6.2",
      "phonetic": "/eɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "77"
    },
    {
      "word": "skate",
      "meaning": "滑",
      "grade": "6.2",
      "phonetic": "/skeɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "78"
    },
    {
      "word": "race",
      "meaning": "赛跑",
      "grade": "6.2",
      "phonetic": "/reɪs/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "79"
    },
    {
      "word": "wake",
      "meaning": "醒",
      "grade": "6.2",
      "phonetic": "/weik/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "80"
    },
    {
      "word": "yesterday",
      "meaning": "昨天",
      "grade": "6.2",
      "phonetic": "/ˈjestədeɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "名或副",
      "serialNumber": "81"
    },
    {
      "word": "stay",
      "meaning": "暂住；逗留",
      "grade": "6.2",
      "phonetic": "/steɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "82"
    },
    {
      "word": "stayed",
      "meaning": "（stay 的过去式）停留；待",
      "grade": "6.2",
      "phonetic": "/steɪd/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "83"
    },
    {
      "word": "ride",
      "meaning": "骑（马；自行车）",
      "grade": "6.2",
      "phonetic": "/raid/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读双元音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "84"
    },
    {
      "word": "ice",
      "meaning": "冰",
      "grade": "6.2",
      "phonetic": "/aɪs/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读双元音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "85"
    },
    {
      "word": "countryside",
      "meaning": "乡村",
      "grade": "6.2",
      "phonetic": "/ˈkʌntrisaɪd/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读双元音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "86"
    },
    {
      "word": "cycling",
      "meaning": "骑自行车运动（或活动）",
      "grade": "6.2",
      "phonetic": "/ˈsaɪklɪŋ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y读双元音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "87"
    },
    {
      "word": "dinosaur",
      "meaning": "恐龙",
      "grade": "6.2",
      "phonetic": "/ˈdaɪnəsɔː(r)/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "88"
    },
    {
      "word": "enjoy",
      "meaning": "享受……乐趣；喜爱",
      "grade": "6.2",
      "phonetic": "/ɪnˈdʒɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读字母音/ɔɪ/",
      "partOfSpeech": "动",
      "serialNumber": "89"
    },
    {
      "word": "ago",
      "meaning": "以前",
      "grade": "6.2",
      "phonetic": "/əˈɡəʊ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "副",
      "serialNumber": "90"
    },
    {
      "word": "rode",
      "meaning": "（ride 的过去式）骑（马；自行车）",
      "grade": "6.2",
      "phonetic": "/rəʊd/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "91"
    },
    {
      "word": "woke",
      "meaning": "（wake 的过去式）醒",
      "grade": "6.2",
      "phonetic": "/wəʊk/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "92"
    },
    {
      "word": "hotel",
      "meaning": "旅馆",
      "grade": "6.2",
      "phonetic": "/həʊˈtel/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "93"
    },
    {
      "word": "both",
      "meaning": "两个都",
      "grade": "6.2",
      "phonetic": "/bəʊθ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "代",
      "serialNumber": "94"
    },
    {
      "word": "broken",
      "meaning": "破损的",
      "grade": "6.2",
      "phonetic": "/ˈbrəʊkən/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "形",
      "serialNumber": "95"
    },
    {
      "word": "older",
      "meaning": "（old 的比较级）更年长的",
      "grade": "6.2",
      "phonetic": "/ˈəʊldə(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "形",
      "serialNumber": "96"
    },
    {
      "word": "lower",
      "meaning": "（low 的比较级）更低",
      "grade": "6.2",
      "phonetic": "/ˈləʊə(r)/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "形",
      "serialNumber": "97"
    },
    {
      "word": "shadow",
      "meaning": "阴影；影子",
      "grade": "6.2",
      "phonetic": "/ˈʃædəʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "98"
    },
    {
      "word": "show",
      "meaning": "演出",
      "grade": "6.2",
      "phonetic": "/ʃəʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "99"
    },
    {
      "word": "loud",
      "meaning": "喧闹的；大声的",
      "grade": "6.2",
      "phonetic": "/laʊd/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "形",
      "serialNumber": "100"
    },
    {
      "word": "part",
      "meaning": "角色",
      "grade": "6.2",
      "phonetic": "/pɑːt/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读双元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "101"
    },
    {
      "word": "star",
      "meaning": "星",
      "grade": "6.2",
      "phonetic": "/stɑː(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读双元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "102"
    },
    {
      "word": "smarter",
      "meaning": "（smart 的比较级）更聪明的",
      "grade": "6.2",
      "phonetic": "/ˈsmɑːtə(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读双元音/ɑː/",
      "partOfSpeech": "形",
      "serialNumber": "103"
    },
    {
      "word": "dinosaur",
      "meaning": "恐龙",
      "grade": "6.2",
      "phonetic": "/ˈdaɪnəsɔː(r)/",
      "highlightLetters": "aur",
      "highlightPhonetic": "/ɔː/",
      "note": "aur读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "104"
    },
    {
      "word": "before",
      "meaning": "在……之前",
      "grade": "6.2",
      "phonetic": "/bɪˈfɔː(r)/",
      "highlightLetters": "ore",
      "highlightPhonetic": "/ɔː/",
      "note": "ore读长元音/ɔː/",
      "partOfSpeech": "介/连/副",
      "serialNumber": "105"
    },
    {
      "word": "shorter",
      "meaning": "（short 的比较级）更矮的；更短的",
      "grade": "6.2",
      "phonetic": "/ˈʃɔːtə(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "形",
      "serialNumber": "106"
    },
    {
      "word": "hurt",
      "meaning": "（hurt 的过去式）（使）受伤",
      "grade": "6.2",
      "phonetic": "/hɜːt/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "107"
    },
    {
      "word": "Turpan",
      "meaning": "吐鲁番",
      "grade": "6.2",
      "phonetic": "/ˈtuːˈpɑːn/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/uː/",
      "note": "ur读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "108"
    },
    {
      "word": "ago",
      "meaning": "以前",
      "grade": "6.2",
      "phonetic": "/əˈɡəʊ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "副",
      "serialNumber": "109"
    },
    {
      "word": "cheetah",
      "meaning": "猎豹",
      "grade": "6.2",
      "phonetic": "/ˈtʃiːtə/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "110"
    },
    {
      "word": "magazine",
      "meaning": "杂志",
      "grade": "6.2",
      "phonetic": "/ˌmæɡəˈziːn/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "111"
    },
    {
      "word": "broken",
      "meaning": "破损的",
      "grade": "6.2",
      "phonetic": "/ˈbrəʊkən/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ə/",
      "note": "e弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "112"
    },
    {
      "word": "different",
      "meaning": "不同的",
      "grade": "6.2",
      "phonetic": "/ˈdɪfrənt/",
      "highlightLetters": "第2个e",
      "highlightPhonetic": "/ə/",
      "note": "e弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "113"
    },
    {
      "word": "badminton",
      "meaning": "羽毛球运动",
      "grade": "6.2",
      "phonetic": "/ˈbædmɪntən/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "114"
    },
    {
      "word": "dinosaur",
      "meaning": "恐龙",
      "grade": "6.2",
      "phonetic": "/ˈdaɪnəsɔː(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "115"
    },
    {
      "word": "kilogram",
      "meaning": "千克；公斤",
      "grade": "6.2",
      "phonetic": "/ˈkɪləɡræm/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "116"
    },
    {
      "word": "pictures",
      "meaning": "图片，照片（复数）",
      "grade": "6.2",
      "phonetic": "/ˈpiktʃəz/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/ə/",
      "note": "ure读弱音/ə/",
      "partOfSpeech": "名",
      "serialNumber": "117"
    },
    {
      "word": "basket",
      "meaning": "篮；筐",
      "grade": "6.2",
      "phonetic": "/ˈbɑːskɪt/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "118"
    },
    {
      "word": "become",
      "meaning": "开始变得；变成",
      "grade": "6.2",
      "phonetic": "/bɪˈkʌm/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "动",
      "serialNumber": "119"
    },
    {
      "word": "before",
      "meaning": "在……之前",
      "grade": "6.2",
      "phonetic": "/bɪˈfɔː(r)/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "介/连/副",
      "serialNumber": "120"
    },
    {
      "word": "enjoy",
      "meaning": "享受……乐趣；喜爱",
      "grade": "6.2",
      "phonetic": "/ɪnˈdʒɔɪ/",
      "highlightLetters": "e",
      "highlightPhonetic": "/i/",
      "note": "e弱音读/i/",
      "partOfSpeech": "动",
      "serialNumber": "121"
    },
    {
      "word": "bigger",
      "meaning": "（big 的比较级）更大的",
      "grade": "6.2",
      "phonetic": "/ˈbɪɡə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "122"
    },
    {
      "word": "thinner",
      "meaning": "（thin 的比较级）更瘦的",
      "grade": "6.2",
      "phonetic": "/ˈθɪnə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "123"
    },
    {
      "word": "lower",
      "meaning": "（low 的比较级）更低",
      "grade": "6.2",
      "phonetic": "/ˈləʊə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "124"
    },
    {
      "word": "older",
      "meaning": "（old 的比较级）更年长的",
      "grade": "6.2",
      "phonetic": "/ˈəʊldə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "125"
    },
    {
      "word": "faster",
      "meaning": "（fast 的比较级）更快的",
      "grade": "6.2",
      "phonetic": "/ˈfɑːstə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "126"
    },
    {
      "word": "smaller",
      "meaning": "（small 的比较级）更小的",
      "grade": "6.2",
      "phonetic": "/ˈsmɔːlə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "127"
    },
    {
      "word": "taller",
      "meaning": "（tall 的比较级）更高的",
      "grade": "6.2",
      "phonetic": "/ˈtɔːlə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "128"
    },
    {
      "word": "better",
      "meaning": "（well 的比较级）更好的",
      "grade": "6.2",
      "phonetic": "/ˈbetə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "129"
    },
    {
      "word": "stronger",
      "meaning": "（strong 的比较级）更强壮的",
      "grade": "6.2",
      "phonetic": "/ˈstrɒŋɡə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "130"
    },
    {
      "word": "longer",
      "meaning": "（long 的比较级）更长的",
      "grade": "6.2",
      "phonetic": "/ˈlɒŋɡə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "131"
    },
    {
      "word": "younger",
      "meaning": "（young 的比较级）更年轻的",
      "grade": "6.2",
      "phonetic": "/ˈjʌŋɡə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "132"
    },
    {
      "word": "yesterday",
      "meaning": "昨天",
      "grade": "6.2",
      "phonetic": "/ˈjestədeɪ/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名或副",
      "serialNumber": "133"
    },
    {
      "word": "Internet",
      "meaning": "互联网",
      "grade": "6.2",
      "phonetic": "/ˈɪntənet/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "134"
    },
    {
      "word": "basket",
      "meaning": "篮；筐",
      "grade": "6.2",
      "phonetic": "/ˈbɑːskɪt/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "135"
    },
    {
      "word": "beach",
      "meaning": "海滩；沙滩",
      "grade": "6.2",
      "phonetic": "/biːtʃ/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "136"
    },
    {
      "word": "become",
      "meaning": "开始变得；变成",
      "grade": "6.2",
      "phonetic": "/bɪˈkʌm/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "动",
      "serialNumber": "137"
    },
    {
      "word": "before",
      "meaning": "在……之前",
      "grade": "6.2",
      "phonetic": "/bɪˈfɔː(r)/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "介/连/副",
      "serialNumber": "138"
    },
    {
      "word": "better",
      "meaning": "（well 的比较级）更好的",
      "grade": "6.2",
      "phonetic": "/ˈbetə(r)/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "形",
      "serialNumber": "139"
    },
    {
      "word": "bigger",
      "meaning": "（big 的比较级）更大的",
      "grade": "6.2",
      "phonetic": "/ˈbɪɡə(r)/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "形",
      "serialNumber": "140"
    },
    {
      "word": "both",
      "meaning": "两个都",
      "grade": "6.2",
      "phonetic": "/bəʊθ/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "代",
      "serialNumber": "141"
    },
    {
      "word": "bought",
      "meaning": "（buy 的过去式）买",
      "grade": "6.2",
      "phonetic": "/bɔːt/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "动",
      "serialNumber": "142"
    },
    {
      "word": "camp",
      "meaning": "野营",
      "grade": "6.2",
      "phonetic": "/kæmp/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名",
      "serialNumber": "143"
    },
    {
      "word": "could",
      "meaning": "（can 的过去式）能",
      "grade": "6.2",
      "phonetic": "/kʊd/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "动",
      "serialNumber": "144"
    },
    {
      "word": "countryside",
      "meaning": "乡村",
      "grade": "6.2",
      "phonetic": "/ˈkʌntrisaɪd/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "名",
      "serialNumber": "145"
    },
    {
      "word": "cycling",
      "meaning": "骑自行车运动（或活动）",
      "grade": "6.2",
      "phonetic": "/ˈsaɪklɪŋ/",
      "highlightLetters": "c",
      "highlightPhonetic": "/s/",
      "note": "c读/s/（在y前）",
      "partOfSpeech": "名",
      "serialNumber": "146"
    },
    {
      "word": "different",
      "meaning": "不同的",
      "grade": "6.2",
      "phonetic": "/ˈdɪfrənt/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形",
      "serialNumber": "147"
    },
    {
      "word": "dinosaur",
      "meaning": "恐龙",
      "grade": "6.2",
      "phonetic": "/ˈdaɪnəsɔː(r)/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "148"
    },
    {
      "word": "faster",
      "meaning": "（fast 的比较级）更快的",
      "grade": "6.2",
      "phonetic": "/ˈfɑːstə(r)/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "形",
      "serialNumber": "149"
    },
    {
      "word": "fell",
      "meaning": "（fall的过去式）摔倒",
      "grade": "6.2",
      "phonetic": "/fel/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "150"
    },
    {
      "word": "felt",
      "meaning": "（feel 的过去式）感觉",
      "grade": "6.2",
      "phonetic": "/felt/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "151"
    },
    {
      "word": "fish",
      "meaning": "钓鱼；捕鱼",
      "grade": "6.2",
      "phonetic": "/fɪʃ/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "152"
    },
    {
      "word": "fixed",
      "meaning": "（fix 的过去式）修理",
      "grade": "6.2",
      "phonetic": "/fɪkst/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "153"
    },
    {
      "word": "laughed",
      "meaning": "（laugh 的过去式）笑",
      "grade": "6.2",
      "phonetic": "/lɑːft/",
      "highlightLetters": "gh",
      "highlightPhonetic": "/f/",
      "note": "gh读/f/",
      "partOfSpeech": "动",
      "serialNumber": "154"
    },
    {
      "word": "gift",
      "meaning": "礼物",
      "grade": "6.2",
      "phonetic": "/ɡɪft/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "155"
    },
    {
      "word": "gym",
      "meaning": "体育馆",
      "grade": "6.2",
      "phonetic": "/dʒɪm/",
      "highlightLetters": "g",
      "highlightPhonetic": "/dʒ/",
      "note": "g读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "156"
    },
    {
      "word": "had",
      "meaning": "（have 的过去式）患病；得病",
      "grade": "6.2",
      "phonetic": "/hæd/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "157"
    },
    {
      "word": "hall",
      "meaning": "大厅",
      "grade": "6.2",
      "phonetic": "/hɔːl/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "158"
    },
    {
      "word": "heavier",
      "meaning": "（heavy 的比较级）更重的",
      "grade": "6.2",
      "phonetic": "/ˈheviə(r)/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "形",
      "serialNumber": "159"
    },
    {
      "word": "hotel",
      "meaning": "旅馆",
      "grade": "6.2",
      "phonetic": "/həʊˈtel/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "160"
    },
    {
      "word": "hurt",
      "meaning": "（hurt 的过去式）（使）受伤",
      "grade": "6.2",
      "phonetic": "/hɜːt/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "161"
    },
    {
      "word": "kilogram",
      "meaning": "千克；公斤",
      "grade": "6.2",
      "phonetic": "/ˈkɪləɡræm/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "名",
      "serialNumber": "162"
    },
    {
      "word": "lamp",
      "meaning": "台灯",
      "grade": "6.2",
      "phonetic": "/læmp/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "163"
    },
    {
      "word": "last",
      "meaning": "最近的；上一个的",
      "grade": "6.2",
      "phonetic": "/lɑːst/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "形",
      "serialNumber": "164"
    },
    {
      "word": "laughed",
      "meaning": "（laugh 的过去式）笑",
      "grade": "6.2",
      "phonetic": "/lɑːft/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "165"
    },
    {
      "word": "licked",
      "meaning": "（lick 的过去式）舔",
      "grade": "6.2",
      "phonetic": "/lɪkt/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "166"
    },
    {
      "word": "longer",
      "meaning": "（long 的比较级）更长的",
      "grade": "6.2",
      "phonetic": "/ˈlɒŋɡə(r)/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "形",
      "serialNumber": "167"
    },
    {
      "word": "look",
      "meaning": "看",
      "grade": "6.2",
      "phonetic": "/ˈlʊk/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "168"
    },
    {
      "word": "loud",
      "meaning": "喧闹的；大声的",
      "grade": "6.2",
      "phonetic": "/laʊd/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "形",
      "serialNumber": "169"
    },
    {
      "word": "lower",
      "meaning": "（low 的比较级）更低",
      "grade": "6.2",
      "phonetic": "/ˈləʊə(r)/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "形",
      "serialNumber": "170"
    },
    {
      "word": "magazine",
      "meaning": "杂志",
      "grade": "6.2",
      "phonetic": "/ˌmæɡəˈziːn/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "171"
    },
    {
      "word": "metre",
      "meaning": "米",
      "grade": "6.2",
      "phonetic": "/ˈmiːtə(r)/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "172"
    },
    {
      "word": "mule",
      "meaning": "骡子",
      "grade": "6.2",
      "phonetic": "/mjuːl/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "173"
    },
    {
      "word": "nothing",
      "meaning": "没有什么",
      "grade": "6.2",
      "phonetic": "/ˈnʌθɪŋ/",
      "highlightLetters": "第1个n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "代",
      "serialNumber": "174"
    },
    {
      "word": "part",
      "meaning": "角色",
      "grade": "6.2",
      "phonetic": "/pɑːt/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "175"
    },
    {
      "word": "pictures",
      "meaning": "图片，照片（复数）",
      "grade": "6.2",
      "phonetic": "/ˈpiktʃəz/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "176"
    },
    {
      "word": "race",
      "meaning": "赛跑",
      "grade": "6.2",
      "phonetic": "/reɪs/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "177"
    },
    {
      "word": "read",
      "meaning": "（read 的过去式）读",
      "grade": "6.2",
      "phonetic": "/red/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "动",
      "serialNumber": "178"
    },
    {
      "word": "ride",
      "meaning": "骑（马；自行车）",
      "grade": "6.2",
      "phonetic": "/raid/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "动",
      "serialNumber": "179"
    },
    {
      "word": "rode",
      "meaning": "（ride 的过去式）骑（马；自行车）",
      "grade": "6.2",
      "phonetic": "/rəʊd/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "动",
      "serialNumber": "180"
    },
    {
      "word": "saw",
      "meaning": "（see 的过去式）看见",
      "grade": "6.2",
      "phonetic": "/sɔː/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "动",
      "serialNumber": "181"
    },
    {
      "word": "pictures",
      "meaning": "图片，照片（复数）",
      "grade": "6.2",
      "phonetic": "/ˈpiktʃəz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "182"
    },
    {
      "word": "stars",
      "meaning": "星(复数)",
      "grade": "6.2",
      "phonetic": "/stɑː(r)z/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "183"
    },
    {
      "word": "hotels",
      "meaning": "旅馆(复数)",
      "grade": "6.2",
      "phonetic": "/həʊˈtelz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "184"
    },
    {
      "word": "gyms",
      "meaning": "体育馆(复数)",
      "grade": "6.2",
      "phonetic": "/dʒɪmz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "185"
    },
    {
      "word": "lamps",
      "meaning": "台灯(复数)",
      "grade": "6.2",
      "phonetic": "/læmps/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "186"
    },
    {
      "word": "taller",
      "meaning": "（tall 的比较级）更高的",
      "grade": "6.2",
      "phonetic": "/ˈtɔːlə(r)/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形",
      "serialNumber": "187"
    },
    {
      "word": "till",
      "meaning": "直到",
      "grade": "6.2",
      "phonetic": "/tɪl/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "连或介",
      "serialNumber": "188"
    },
    {
      "word": "took",
      "meaning": "（take 的过去式）拍照",
      "grade": "6.2",
      "phonetic": "/tʊk/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "189"
    },
    {
      "word": "wake",
      "meaning": "醒",
      "grade": "6.2",
      "phonetic": "/weik/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "190"
    },
    {
      "word": "went",
      "meaning": "（go 的过去式）去",
      "grade": "6.2",
      "phonetic": "/went/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "191"
    },
    {
      "word": "woke",
      "meaning": "（wake 的过去式）醒",
      "grade": "6.2",
      "phonetic": "/wəʊk/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "192"
    },
    {
      "word": "yesterday",
      "meaning": "昨天",
      "grade": "6.2",
      "phonetic": "/ˈjestədeɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （辅音）",
      "partOfSpeech": "名或副",
      "serialNumber": "193"
    },
    {
      "word": "younger",
      "meaning": "（young 的比较级）更年轻的",
      "grade": "6.2",
      "phonetic": "/ˈjʌŋɡə(r)/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （辅音）",
      "partOfSpeech": "形",
      "serialNumber": "194"
    },
    {
      "word": "drank",
      "meaning": "（drink 的过去式）喝",
      "grade": "6.2",
      "phonetic": "/dræŋk/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "动",
      "serialNumber": "195"
    },
    {
      "word": "dream",
      "meaning": "梦",
      "grade": "6.2",
      "phonetic": "/driːm/",
      "highlightLetters": "dr",
      "highlightPhonetic": "/dr/",
      "note": "dr读/dr/",
      "partOfSpeech": "名",
      "serialNumber": "196"
    },
    {
      "word": "grass",
      "meaning": "草坪",
      "grade": "6.2",
      "phonetic": "/ɡrɑːs/",
      "highlightLetters": "gr",
      "highlightPhonetic": "/gr/",
      "note": "gr读/ɡr/",
      "partOfSpeech": "名",
      "serialNumber": "197"
    },
    {
      "word": "trip",
      "meaning": "绊倒；短程旅行",
      "grade": "6.2",
      "phonetic": "/trɪp/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/fr/",
      "partOfSpeech": "动或名",
      "serialNumber": "198"
    },
    {
      "word": "cheetah",
      "meaning": "猎豹",
      "grade": "6.2",
      "phonetic": "/ˈtʃiːtə/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "名",
      "serialNumber": "199"
    },
    {
      "word": "watched",
      "meaning": "（watch 的过去式）看",
      "grade": "6.2",
      "phonetic": "/wɒtʃt/",
      "highlightLetters": "tch",
      "highlightPhonetic": "/tʃ/",
      "note": "tch读/tʃ/",
      "partOfSpeech": "动",
      "serialNumber": "200"
    },
    {
      "word": "cleaned",
      "meaning": "（clean 的过去式）打扫",
      "grade": "6.2",
      "phonetic": "/kliːnd/",
      "highlightLetters": "cl",
      "highlightPhonetic": "/kl/",
      "note": "cl读/kl/",
      "partOfSpeech": "动",
      "serialNumber": "201"
    },
    {
      "word": "shadow",
      "meaning": "阴影；影子",
      "grade": "6.2",
      "phonetic": "/ˈʃædəʊ/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "202"
    },
    {
      "word": "shorter",
      "meaning": "（short 的比较级）更矮的；更短的",
      "grade": "6.2",
      "phonetic": "/ˈʃɔːtə(r)/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "形",
      "serialNumber": "203"
    },
    {
      "word": "show",
      "meaning": "演出",
      "grade": "6.2",
      "phonetic": "/ʃəʊ/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "204"
    },
    {
      "word": "washed",
      "meaning": "（wash 的过去式）洗",
      "grade": "6.2",
      "phonetic": "/wɒʃt/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "动",
      "serialNumber": "205"
    },
    {
      "word": "than",
      "meaning": "比",
      "grade": "6.2",
      "phonetic": "/ðən/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "连或介",
      "serialNumber": "206"
    },
    {
      "word": "thinner",
      "meaning": "（thin 的比较级）更瘦的",
      "grade": "6.2",
      "phonetic": "/ˈθɪnə(r)/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "形",
      "serialNumber": "207"
    },
    {
      "word": "thought",
      "meaning": "（think 的过去式）想",
      "grade": "6.2",
      "phonetic": "/θɔːt/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "动",
      "serialNumber": "208"
    },
    {
      "word": "skate",
      "meaning": "滑",
      "grade": "6.2",
      "phonetic": "/skeɪt/",
      "highlightLetters": "sk",
      "highlightPhonetic": "/sk/",
      "note": "sk读/sk/",
      "partOfSpeech": "动",
      "serialNumber": "209"
    },
    {
      "word": "slept",
      "meaning": "（sleep 的过去式）睡觉",
      "grade": "6.2",
      "phonetic": "/slept/",
      "highlightLetters": "sl",
      "highlightPhonetic": "/sl/",
      "note": "sl读/sl/",
      "partOfSpeech": "动",
      "serialNumber": "210"
    },
    {
      "word": "smaller",
      "meaning": "（small 的比较级）更小的",
      "grade": "6.2",
      "phonetic": "/ˈsmɔːlə(r)/",
      "highlightLetters": "sm",
      "highlightPhonetic": "/sm/",
      "note": "sm读/sm/",
      "partOfSpeech": "形",
      "serialNumber": "211"
    },
    {
      "word": "smarter",
      "meaning": "（smart 的比较级）更聪明的",
      "grade": "6.2",
      "phonetic": "/ˈsmɑːtə(r)/",
      "highlightLetters": "sm",
      "highlightPhonetic": "/sm/",
      "note": "sm读/sm/",
      "partOfSpeech": "形",
      "serialNumber": "212"
    },
    {
      "word": "star",
      "meaning": "星",
      "grade": "6.2",
      "phonetic": "/stɑː(r)/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "名",
      "serialNumber": "213"
    },
    {
      "word": "stay",
      "meaning": "暂住；逗留",
      "grade": "6.2",
      "phonetic": "/steɪ/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "动",
      "serialNumber": "214"
    },
    {
      "word": "stayed",
      "meaning": "（stay 的过去式）停留；待",
      "grade": "6.2",
      "phonetic": "/steɪd/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "动",
      "serialNumber": "215"
    },
    {
      "word": "stronger",
      "meaning": "（strong 的比较级）更强壮的",
      "grade": "6.2",
      "phonetic": "/ˈstrɒŋɡə(r)/",
      "highlightLetters": "str",
      "highlightPhonetic": "/str/",
      "note": "str读/st/",
      "partOfSpeech": "形",
      "serialNumber": "216"
    },
    {
      "word": "fixed",
      "meaning": "（fix 的过去式）修理",
      "grade": "6.2",
      "phonetic": "/fɪkst/",
      "highlightLetters": "ed",
      "highlightPhonetic": "/t/",
      "note": "ed读/t/(在清辅音后)",
      "partOfSpeech": "动",
      "serialNumber": "217"
    },
    {
      "word": "laughed",
      "meaning": "（laugh 的过去式）笑",
      "grade": "6.2",
      "phonetic": "/lɑːft/",
      "highlightLetters": "ed",
      "highlightPhonetic": "/t/",
      "note": "ed读/t/(在清辅音后)",
      "partOfSpeech": "动",
      "serialNumber": "218"
    },
    {
      "word": "licked",
      "meaning": "（lick 的过去式）舔",
      "grade": "6.2",
      "phonetic": "/lɪkt/",
      "highlightLetters": "ed",
      "highlightPhonetic": "/t/",
      "note": "ed读/t/(在清辅音后)",
      "partOfSpeech": "动",
      "serialNumber": "219"
    },
    {
      "word": "cleaned",
      "meaning": "（clean 的过去式）打扫",
      "grade": "6.2",
      "phonetic": "/kliːnd/",
      "highlightLetters": "ed",
      "highlightPhonetic": "/d/",
      "note": "ed读/d/(在浊辅音后)",
      "partOfSpeech": "动",
      "serialNumber": "220"
    },
    {
      "word": "stayed",
      "meaning": "（stay 的过去式）停留；待",
      "grade": "6.2",
      "phonetic": "/steɪd/",
      "highlightLetters": "ed",
      "highlightPhonetic": "/d/",
      "note": "ed读/d/(在元音后)",
      "partOfSpeech": "动",
      "serialNumber": "221"
    }
  ]
};
