// 自动生成的JS模块 - grade3_2.json
// 生成时间: 2025-12-20T02:20:06.811Z

module.exports = {
  "grade": 3,
  "semester": 2,
  "gradeName": "小学三年级下册",
  "total": 360,
  "lastUpdated": "2025-12-20T02:06:14.863Z",
  "words": [
    {
      "word": "game",
      "meaning": "游戏",
      "grade": "3.2",
      "phonetic": "/geɪm/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "1"
    },
    {
      "word": "name",
      "meaning": "名字",
      "grade": "3.2",
      "phonetic": "/neɪm/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "2"
    },
    {
      "word": "Jake",
      "meaning": "杰克（人名）",
      "grade": "3.2",
      "phonetic": "/dʒeɪk/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "3"
    },
    {
      "word": "Dave",
      "meaning": "戴夫（男名）",
      "grade": "3.2",
      "phonetic": "/deɪv/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "4"
    },
    {
      "word": "date",
      "meaning": "日期",
      "grade": "3.2",
      "phonetic": "/deɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "5"
    },
    {
      "word": "hate",
      "meaning": "憎恨；不喜欢",
      "grade": "3.2",
      "phonetic": "/heɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "6"
    },
    {
      "word": "face",
      "meaning": "脸；面孔",
      "grade": "3.2",
      "phonetic": "/feɪs/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "7"
    },
    {
      "word": "cake",
      "meaning": "蛋糕",
      "grade": "3.2",
      "phonetic": "/keɪk/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "8"
    },
    {
      "word": "make",
      "meaning": "制作",
      "grade": "3.2",
      "phonetic": "/meɪk/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "9"
    },
    {
      "word": "grape",
      "meaning": "葡萄",
      "grade": "3.2",
      "phonetic": "/ɡreɪp/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "10"
    },
    {
      "word": "plate",
      "meaning": "盘子",
      "grade": "3.2",
      "phonetic": "/pleɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "11"
    },
    {
      "word": "taste",
      "meaning": "尝（味道）",
      "grade": "3.2",
      "phonetic": "/teɪst/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "12"
    },
    {
      "word": "classmate",
      "meaning": "同班同学",
      "grade": "3.2",
      "phonetic": "/ˈklɑːsmeɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "13"
    },
    {
      "word": "paper",
      "meaning": "纸",
      "grade": "3.2",
      "phonetic": "/ˈpeɪpə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "14"
    },
    {
      "word": "eraser",
      "meaning": "橡皮",
      "grade": "3.2",
      "phonetic": "/ɪˈreɪzə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "15"
    },
    {
      "word": "be",
      "meaning": "是",
      "grade": "3.2",
      "phonetic": "/biː/",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读字母音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "16"
    },
    {
      "word": "me",
      "meaning": "我",
      "grade": "3.2",
      "phonetic": "/miː/",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读字母音/iː/",
      "partOfSpeech": "代",
      "serialNumber": "17"
    },
    {
      "word": "we",
      "meaning": "我们",
      "grade": "3.2",
      "phonetic": "/wiː/",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读字母音/iː/",
      "partOfSpeech": "代",
      "serialNumber": "18"
    },
    {
      "word": "these",
      "meaning": "这些",
      "grade": "3.2",
      "phonetic": "/ðiːz/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "代;形容",
      "serialNumber": "19"
    },
    {
      "word": "see",
      "meaning": "看见",
      "grade": "3.2",
      "phonetic": "/siː/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "动",
      "serialNumber": "20"
    },
    {
      "word": "keep",
      "meaning": "保有；留着",
      "grade": "3.2",
      "phonetic": "/kiːp/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "动",
      "serialNumber": "21"
    },
    {
      "word": "thirteen",
      "meaning": "十三",
      "grade": "3.2",
      "phonetic": "/ˌθɜːˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "数",
      "serialNumber": "22"
    },
    {
      "word": "fourteen",
      "meaning": "十四",
      "grade": "3.2",
      "phonetic": "/ˌfɔːˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "数",
      "serialNumber": "23"
    },
    {
      "word": "fifteen",
      "meaning": "十五",
      "grade": "3.2",
      "phonetic": "/ˌfɪfˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "数",
      "serialNumber": "24"
    },
    {
      "word": "sixteen",
      "meaning": "十六",
      "grade": "3.2",
      "phonetic": "/ˌsɪksˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "数",
      "serialNumber": "25"
    },
    {
      "word": "seventeen",
      "meaning": "十七",
      "grade": "3.2",
      "phonetic": "/ˌsevnˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "数",
      "serialNumber": "26"
    },
    {
      "word": "eighteen",
      "meaning": "十八",
      "grade": "3.2",
      "phonetic": "/ˌeɪˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "数",
      "serialNumber": "27"
    },
    {
      "word": "nineteen",
      "meaning": "十九",
      "grade": "3.2",
      "phonetic": "/ˌnaɪnˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "数",
      "serialNumber": "28"
    },
    {
      "word": "bike",
      "meaning": "自行车",
      "grade": "3.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "29"
    },
    {
      "word": "like",
      "meaning": "喜欢；像",
      "grade": "3.2",
      "phonetic": "/laɪk/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动; 介",
      "serialNumber": "30"
    },
    {
      "word": "fine",
      "meaning": "身体好的",
      "grade": "3.2",
      "phonetic": "/faɪn/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "31"
    },
    {
      "word": "kite",
      "meaning": "风筝",
      "grade": "3.2",
      "phonetic": "/kaɪt/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "32"
    },
    {
      "word": "write",
      "meaning": "写",
      "grade": "3.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "33"
    },
    {
      "word": "nice",
      "meaning": "美好的；好心的",
      "grade": "3.2",
      "phonetic": "/naɪs/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "34"
    },
    {
      "word": "rice",
      "meaning": "大米",
      "grade": "3.2",
      "phonetic": "/raɪs/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "35"
    },
    {
      "word": "size",
      "meaning": "尺寸",
      "grade": "3.2",
      "phonetic": "/saɪz/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "36"
    },
    {
      "word": "time",
      "meaning": "时间",
      "grade": "3.2",
      "phonetic": "/taɪm/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "37"
    },
    {
      "word": "so",
      "meaning": "如此的",
      "grade": "3.2",
      "phonetic": "/səʊ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "形容",
      "serialNumber": "38"
    },
    {
      "word": "home",
      "meaning": "家",
      "grade": "3.2",
      "phonetic": "/həʊm/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名; 副",
      "serialNumber": "39"
    },
    {
      "word": "hope",
      "meaning": "希望",
      "grade": "3.2",
      "phonetic": "/həʊp/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "40"
    },
    {
      "word": "joke",
      "meaning": "玩笑",
      "grade": "3.2",
      "phonetic": "/dʒəʊk/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "41"
    },
    {
      "word": "bone",
      "meaning": "骨头",
      "grade": "3.2",
      "phonetic": "/bəʊn/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "42"
    },
    {
      "word": "cone",
      "meaning": "圆锥形物体",
      "grade": "3.2",
      "phonetic": "/kəʊn/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "43"
    },
    {
      "word": "note",
      "meaning": "笔记",
      "grade": "3.2",
      "phonetic": "/nəʊt/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "44"
    },
    {
      "word": "Jones",
      "meaning": "琼斯（姓）",
      "grade": "3.2",
      "phonetic": "/dʒəʊnz/",
      "highlightLetters": "oe",
      "highlightPhonetic": "/əʊ/",
      "note": "o读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "45"
    },
    {
      "word": "use",
      "meaning": "使用",
      "grade": "3.2",
      "phonetic": "/juːz/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "动",
      "serialNumber": "46"
    },
    {
      "word": "excuse",
      "meaning": "原谅",
      "grade": "3.2",
      "phonetic": "/iks'kjuːz/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "动",
      "serialNumber": "47"
    },
    {
      "word": "cute",
      "meaning": "可爱的",
      "grade": "3.2",
      "phonetic": "/kjuːt/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "形容",
      "serialNumber": "48"
    },
    {
      "word": "mute",
      "meaning": "哑的；无声的",
      "grade": "3.2",
      "phonetic": "/mjuːt/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "形容",
      "serialNumber": "49"
    },
    {
      "word": "tube",
      "meaning": "管子",
      "grade": "3.2",
      "phonetic": "/tjuːb/",
      "highlightLetters": "ue",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "50"
    },
    {
      "word": "student",
      "meaning": "学生",
      "grade": "3.2",
      "phonetic": "/ˈstjuːdnt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "51"
    },
    {
      "word": "computer",
      "meaning": "计算机；电脑",
      "grade": "3.2",
      "phonetic": "/kəmˈpjuːtə(r)/",
      "highlightLetters": "u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "52"
    },
    {
      "word": "at",
      "meaning": "在（某处）",
      "grade": "3.2",
      "phonetic": "/æt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "介",
      "serialNumber": "53"
    },
    {
      "word": "fat",
      "meaning": "肥的；肥胖的",
      "grade": "3.2",
      "phonetic": "/fæt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形容",
      "serialNumber": "54"
    },
    {
      "word": "hat",
      "meaning": "帽子",
      "grade": "3.2",
      "phonetic": "/hæt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "55"
    },
    {
      "word": "has",
      "meaning": "（她/他/它）有",
      "grade": "3.2",
      "phonetic": "/hæz/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "动",
      "serialNumber": "56"
    },
    {
      "word": "cap",
      "meaning": "帽子",
      "grade": "3.2",
      "phonetic": "/kæp/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "57"
    },
    {
      "word": "map",
      "meaning": "地图",
      "grade": "3.2",
      "phonetic": "/mæp/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "58"
    },
    {
      "word": "man",
      "meaning": "成年男子；男人",
      "grade": "3.2",
      "phonetic": "/mæn/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "59"
    },
    {
      "word": "back",
      "meaning": "回到原处",
      "grade": "3.2",
      "phonetic": "/bæk/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "副",
      "serialNumber": "60"
    },
    {
      "word": "bank",
      "meaning": "银行",
      "grade": "3.2",
      "phonetic": "/bæŋk/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "61"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "3.2",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "62"
    },
    {
      "word": "Canada",
      "meaning": "加拿大",
      "grade": "3.2",
      "phonetic": "/ˈkænədə/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "63"
    },
    {
      "word": "egg",
      "meaning": "鸡蛋",
      "grade": "3.2",
      "phonetic": "/eɡ/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "64"
    },
    {
      "word": "leg",
      "meaning": "腿",
      "grade": "3.2",
      "phonetic": "/leɡ/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "65"
    },
    {
      "word": "pen",
      "meaning": "钢笔",
      "grade": "3.2",
      "phonetic": "/pen/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "66"
    },
    {
      "word": "shelf",
      "meaning": "架子",
      "grade": "3.2",
      "phonetic": "/ʃelf/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "67"
    },
    {
      "word": "twelve",
      "meaning": "十二",
      "grade": "3.2",
      "phonetic": "/twelv/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "数",
      "serialNumber": "68"
    },
    {
      "word": "smell",
      "meaning": "闻（气味）",
      "grade": "3.2",
      "phonetic": "/smel/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "69"
    },
    {
      "word": "pencil",
      "meaning": "铅笔",
      "grade": "3.2",
      "phonetic": "/ˈpensl/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "70"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "3.2",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "数",
      "serialNumber": "71"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "3.2",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "72"
    },
    {
      "word": "eleven",
      "meaning": "十一",
      "grade": "3.2",
      "phonetic": "/ɪˈlevn/",
      "highlightLetters": "第2个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "数",
      "serialNumber": "73"
    },
    {
      "word": "bread",
      "meaning": "面包",
      "grade": "3.2",
      "phonetic": "/bred/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "74"
    },
    {
      "word": "breakfast",
      "meaning": "早餐；早饭",
      "grade": "3.2",
      "phonetic": "/ˈbrekfəst/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "75"
    },
    {
      "word": "healthy",
      "meaning": "健康的",
      "grade": "3.2",
      "phonetic": "/ˈhelθi/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "形容",
      "serialNumber": "76"
    },
    {
      "word": "in",
      "meaning": "在……内/里；",
      "grade": "3.2",
      "phonetic": "/ɪn/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "介",
      "serialNumber": "77"
    },
    {
      "word": "fin",
      "meaning": "鱼鳍",
      "grade": "3.2",
      "phonetic": "/fɪn/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "78"
    },
    {
      "word": "thin",
      "meaning": "瘦的；薄的",
      "grade": "3.2",
      "phonetic": "/θɪn/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形容",
      "serialNumber": "79"
    },
    {
      "word": "lip",
      "meaning": "嘴唇",
      "grade": "3.2",
      "phonetic": "/lɪp/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "80"
    },
    {
      "word": "sit",
      "meaning": "坐",
      "grade": "3.2",
      "phonetic": "/sɪt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "81"
    },
    {
      "word": "gift",
      "meaning": "礼物",
      "grade": "3.2",
      "phonetic": "/ɡɪft/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "82"
    },
    {
      "word": "milk",
      "meaning": "牛奶",
      "grade": "3.2",
      "phonetic": "/mɪlk/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "83"
    },
    {
      "word": "still",
      "meaning": "还是；仍然",
      "grade": "3.2",
      "phonetic": "/stɪl/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "副",
      "serialNumber": "84"
    },
    {
      "word": "sing",
      "meaning": "唱（歌）",
      "grade": "3.2",
      "phonetic": "/sɪŋ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "85"
    },
    {
      "word": "piggy",
      "meaning": "猪形的",
      "grade": "3.2",
      "phonetic": "/ˈpɪɡi/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形容",
      "serialNumber": "86"
    },
    {
      "word": "picture",
      "meaning": "图画",
      "grade": "3.2",
      "phonetic": "/ˈpɪktʃə(r)/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "87"
    },
    {
      "word": "English",
      "meaning": "英语(的)",
      "grade": "3.2",
      "phonetic": "/ˈɪŋɡlɪʃ/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ɪ/",
      "note": "e读短音/ɪ /",
      "partOfSpeech": "形容",
      "serialNumber": "88"
    },
    {
      "word": "on",
      "meaning": "在……上（表面）",
      "grade": "3.2",
      "phonetic": "/ɒn/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "介",
      "serialNumber": "89"
    },
    {
      "word": "not",
      "meaning": "表示否定，不",
      "grade": "3.2",
      "phonetic": "/nɒt/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "副",
      "serialNumber": "90"
    },
    {
      "word": "hot",
      "meaning": "热的；辣的",
      "grade": "3.2",
      "phonetic": "/hɒt/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形容",
      "serialNumber": "91"
    },
    {
      "word": "box",
      "meaning": "盒子",
      "grade": "3.2",
      "phonetic": "/bɒks/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "92"
    },
    {
      "word": "doll",
      "meaning": "玩偶；玩具娃娃",
      "grade": "3.2",
      "phonetic": "/dɒl/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "93"
    },
    {
      "word": "John",
      "meaning": "约翰（男名）",
      "grade": "3.2",
      "phonetic": "/dʒɒn/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "94"
    },
    {
      "word": "from",
      "meaning": "来自，从……来",
      "grade": "3.2",
      "phonetic": "/frɒm/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "介",
      "serialNumber": "95"
    },
    {
      "word": "long",
      "meaning": "长的",
      "grade": "3.2",
      "phonetic": "/lɒŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形容",
      "serialNumber": "96"
    },
    {
      "word": "song",
      "meaning": "歌；歌曲",
      "grade": "3.2",
      "phonetic": "/sɒŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "97"
    },
    {
      "word": "body",
      "meaning": "身体",
      "grade": "3.2",
      "phonetic": "/ˈbɒdi/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "98"
    },
    {
      "word": "us",
      "meaning": "我们（动/介词+...）",
      "grade": "3.2",
      "phonetic": "/ʌs/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "代",
      "serialNumber": "99"
    },
    {
      "word": "cut",
      "meaning": "切;剪",
      "grade": "3.2",
      "phonetic": "/kʌt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "100"
    },
    {
      "word": "fun",
      "meaning": "乐趣；嬉戏",
      "grade": "3.2",
      "phonetic": "/fʌn/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "不可数名",
      "serialNumber": "101"
    },
    {
      "word": "much",
      "meaning": "许多；大量",
      "grade": "3.2",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "代",
      "serialNumber": "102"
    },
    {
      "word": "under",
      "meaning": "在……下面",
      "grade": "3.2",
      "phonetic": "/ˈʌndə(r)/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "介",
      "serialNumber": "103"
    },
    {
      "word": "yummy",
      "meaning": "好吃的；美味的",
      "grade": "3.2",
      "phonetic": "/ˈjʌmi/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "形容",
      "serialNumber": "104"
    },
    {
      "word": "uncle",
      "meaning": "伯伯，叔叔，舅舅",
      "grade": "3.2",
      "phonetic": "/ˈʌŋkl/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "105"
    },
    {
      "word": "love",
      "meaning": "喜爱；爱",
      "grade": "3.2",
      "phonetic": "/lʌv/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "106"
    },
    {
      "word": "tongue",
      "meaning": "舌；舌头",
      "grade": "3.2",
      "phonetic": "/tʌŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "不可数名",
      "serialNumber": "107"
    },
    {
      "word": "colourful",
      "meaning": "五彩缤纷的",
      "grade": "3.2",
      "phonetic": "/ˈkʌləfl/",
      "highlightLetters": "第1个o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "形容",
      "serialNumber": "108"
    },
    {
      "word": "touch",
      "meaning": "触摸；碰",
      "grade": "3.2",
      "phonetic": "/tʌtʃ/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʌ/",
      "note": "ou读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "109"
    },
    {
      "word": "cousin",
      "meaning": "堂（表）兄/弟/姐/妹",
      "grade": "3.2",
      "phonetic": "/ˈkʌzn/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʌ/",
      "note": "ou读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "110"
    },
    {
      "word": "put",
      "meaning": "放；安置",
      "grade": "3.2",
      "phonetic": "/pʊt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʊ/",
      "note": "u读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "111"
    },
    {
      "word": "woman",
      "meaning": "成年女子；妇女",
      "grade": "3.2",
      "phonetic": "/ˈwʊmən/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʊ/",
      "note": "o读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "112"
    },
    {
      "word": "good",
      "meaning": "好的",
      "grade": "3.2",
      "phonetic": "/ɡʊd/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "形容",
      "serialNumber": "113"
    },
    {
      "word": "book",
      "meaning": "书",
      "grade": "3.2",
      "phonetic": "/bʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "114"
    },
    {
      "word": "look",
      "meaning": "看",
      "grade": "3.2",
      "phonetic": "/lʊk/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "115"
    },
    {
      "word": "foot",
      "meaning": "脚",
      "grade": "3.2",
      "phonetic": "/fʊt/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "116"
    },
    {
      "word": "car",
      "meaning": "小汽车；轿车",
      "grade": "3.2",
      "phonetic": "/kɑː(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "117"
    },
    {
      "word": "card",
      "meaning": "贺卡；卡片",
      "grade": "3.2",
      "phonetic": "/kɑːd/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "118"
    },
    {
      "word": "after",
      "meaning": "在……后面",
      "grade": "3.2",
      "phonetic": "/ˈɑːftə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "介",
      "serialNumber": "119"
    },
    {
      "word": "dance",
      "meaning": "跳舞",
      "grade": "3.2",
      "phonetic": "/dɑːns/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "动",
      "serialNumber": "120"
    },
    {
      "word": "class",
      "meaning": "课；班级",
      "grade": "3.2",
      "phonetic": "/klɑːs/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "121"
    },
    {
      "word": "classmate",
      "meaning": "同班同学",
      "grade": "3.2",
      "phonetic": "/ˈklɑːsmeɪt/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "122"
    },
    {
      "word": "or",
      "meaning": "或者",
      "grade": "3.2",
      "phonetic": "/ɔː(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "conj.连",
      "serialNumber": "123"
    },
    {
      "word": "for",
      "meaning": "为了",
      "grade": "3.2",
      "phonetic": "/fɔː(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "介",
      "serialNumber": "124"
    },
    {
      "word": "short",
      "meaning": "短的；矮的",
      "grade": "3.2",
      "phonetic": "/ʃɔːt/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "形容",
      "serialNumber": "125"
    },
    {
      "word": "fourteen",
      "meaning": "十四",
      "grade": "3.2",
      "phonetic": "/ˌfɔːˈtiːn/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ɔː/",
      "note": "our读长元音/ɔː/",
      "partOfSpeech": "数",
      "serialNumber": "126"
    },
    {
      "word": "all",
      "meaning": "所有(的)，全部(的)",
      "grade": "3.2",
      "phonetic": "/ɔːl/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "形容; 代",
      "serialNumber": "127"
    },
    {
      "word": "ball",
      "meaning": "球",
      "grade": "3.2",
      "phonetic": "/bɔːl/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "128"
    },
    {
      "word": "talk",
      "meaning": "说话；聊天",
      "grade": "3.2",
      "phonetic": "/tɔːk/",
      "highlightLetters": "al",
      "highlightPhonetic": "/ɔː/",
      "note": "al读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "129"
    },
    {
      "word": "draw",
      "meaning": "画画",
      "grade": "3.2",
      "phonetic": "/drɔː/",
      "highlightLetters": "aw",
      "highlightPhonetic": "/ɔː/",
      "note": "aw读长元音/ɔː/",
      "partOfSpeech": "动",
      "serialNumber": "130"
    },
    {
      "word": "water",
      "meaning": "水；浇水",
      "grade": "3.2",
      "phonetic": "/ˈwɔːtə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɔː/",
      "note": "a读长元音/ɔː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "131"
    },
    {
      "word": "her",
      "meaning": "她；她的",
      "grade": "3.2",
      "phonetic": "/hɜː(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ɜː/",
      "note": "er重读长音/ɜː/",
      "partOfSpeech": "代",
      "serialNumber": "132"
    },
    {
      "word": "bird",
      "meaning": "鸟",
      "grade": "3.2",
      "phonetic": "/bɜːd/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "133"
    },
    {
      "word": "girl",
      "meaning": "女孩",
      "grade": "3.2",
      "phonetic": "/ɡɜːl/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir读长元音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "134"
    },
    {
      "word": "thirteen",
      "meaning": "十三",
      "grade": "3.2",
      "phonetic": "/ˌθɜːˈtiːn/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir读长元音/ɜː/",
      "partOfSpeech": "数",
      "serialNumber": "135"
    },
    {
      "word": "learn",
      "meaning": "学习",
      "grade": "3.2",
      "phonetic": "/lɜːn/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɜː/",
      "note": "ear读长元音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "136"
    },
    {
      "word": "purple",
      "meaning": "紫色(的)",
      "grade": "3.2",
      "phonetic": "/ˈpɜːpl/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ir读长元音/ɜː/",
      "partOfSpeech": "名; 形容",
      "serialNumber": "137"
    },
    {
      "word": "meat",
      "meaning": "肉",
      "grade": "3.2",
      "phonetic": "/miːt/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "138"
    },
    {
      "word": "teacher",
      "meaning": "教师",
      "grade": "3.2",
      "phonetic": "/ˈtiːtʃə(r)/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "139"
    },
    {
      "word": "see",
      "meaning": "看见",
      "grade": "3.2",
      "phonetic": "/siː/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "140"
    },
    {
      "word": "keep",
      "meaning": "保持；留着",
      "grade": "3.2",
      "phonetic": "/kiːp/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "141"
    },
    {
      "word": "fifteen",
      "meaning": "十五",
      "grade": "3.2",
      "phonetic": "/ˌfɪfˈtiːn/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "数",
      "serialNumber": "142"
    },
    {
      "word": "who",
      "meaning": "谁",
      "grade": "3.2",
      "phonetic": "/huː/",
      "highlightLetters": "o",
      "highlightPhonetic": "/uː/",
      "note": "o读长元音/uː/",
      "partOfSpeech": "代",
      "serialNumber": "143"
    },
    {
      "word": "cool",
      "meaning": "酷的，绝妙的",
      "grade": "3.2",
      "phonetic": "/kuːl/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "形容",
      "serialNumber": "144"
    },
    {
      "word": "noodle",
      "meaning": "面条",
      "grade": "3.2",
      "phonetic": "/ˈnuːdl/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "145"
    },
    {
      "word": "soup",
      "meaning": "汤",
      "grade": "3.2",
      "phonetic": "/suːp/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/uː/",
      "note": "ou读长元音/uː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "146"
    },
    {
      "word": "ruler",
      "meaning": "直尺",
      "grade": "3.2",
      "phonetic": "/ˈruːlə(r)/",
      "highlightLetters": "u",
      "highlightPhonetic": "/uː/",
      "note": "u读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "147"
    },
    {
      "word": "fruit",
      "meaning": "水果",
      "grade": "3.2",
      "phonetic": "/fruːt/",
      "highlightLetters": "ui",
      "highlightPhonetic": "/uː/",
      "note": "ui读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "148"
    },
    {
      "word": "juice",
      "meaning": "果汁",
      "grade": "3.2",
      "phonetic": "/dʒuːs/",
      "highlightLetters": "ui",
      "highlightPhonetic": "/uː/",
      "note": "ui读长元音/uː/",
      "partOfSpeech": "不可数名",
      "serialNumber": "149"
    },
    {
      "word": "pay",
      "meaning": "付费",
      "grade": "3.2",
      "phonetic": "/peɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "150"
    },
    {
      "word": "today",
      "meaning": "今天",
      "grade": "3.2",
      "phonetic": "/təˈdeɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "副",
      "serialNumber": "151"
    },
    {
      "word": "tail",
      "meaning": "尾巴",
      "grade": "3.2",
      "phonetic": "/teɪl/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/eɪ/",
      "note": "ai读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "152"
    },
    {
      "word": "eighteen",
      "meaning": "十八",
      "grade": "3.2",
      "phonetic": "/ˌeɪˈtiːn/",
      "highlightLetters": "ei",
      "highlightPhonetic": "/eɪ/",
      "note": "ei读双元音/eɪ/",
      "partOfSpeech": "数",
      "serialNumber": "153"
    },
    {
      "word": "neighbour",
      "meaning": "邻居",
      "grade": "3.2",
      "phonetic": "/ˈneɪbə(r)/",
      "highlightLetters": "ei",
      "highlightPhonetic": "/eɪ/",
      "note": "ei读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "154"
    },
    {
      "word": "eraser",
      "meaning": "橡皮",
      "grade": "3.2",
      "phonetic": "/ɪˈreɪzə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "155"
    },
    {
      "word": "paper",
      "meaning": "纸",
      "grade": "3.2",
      "phonetic": "/ˈpeɪpə(r)/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "156"
    },
    {
      "word": "classmate",
      "meaning": "同班同学",
      "grade": "3.2",
      "phonetic": "/ˈklɑːsmeɪt/",
      "highlightLetters": "ae",
      "highlightPhonetic": "/eɪ/",
      "note": "a读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "157"
    },
    {
      "word": "rice",
      "meaning": "大米",
      "grade": "3.2",
      "phonetic": "/raɪs/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "158"
    },
    {
      "word": "time",
      "meaning": "时间",
      "grade": "3.2",
      "phonetic": "/taɪm/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "159"
    },
    {
      "word": "nineteen",
      "meaning": "十九",
      "grade": "3.2",
      "phonetic": "/ˌnaɪnˈtiːn/",
      "highlightLetters": "ie",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "数",
      "serialNumber": "160"
    },
    {
      "word": "high",
      "meaning": "高的",
      "grade": "3.2",
      "phonetic": "/haɪ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "161"
    },
    {
      "word": "right",
      "meaning": "准确的；恰当的",
      "grade": "3.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "形容",
      "serialNumber": "162"
    },
    {
      "word": "find",
      "meaning": "找到",
      "grade": "3.2",
      "phonetic": "/faɪnd/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "动",
      "serialNumber": "163"
    },
    {
      "word": "China",
      "meaning": "中国",
      "grade": "3.2",
      "phonetic": "/ˈtʃaɪnə/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "164"
    },
    {
      "word": "boy",
      "meaning": "男生",
      "grade": "3.2",
      "phonetic": "/bɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "165"
    },
    {
      "word": "toy",
      "meaning": "玩具",
      "grade": "3.2",
      "phonetic": "/tɔɪ/",
      "highlightLetters": "oy",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oy读双元音/ɔɪ/",
      "partOfSpeech": "名",
      "serialNumber": "166"
    },
    {
      "word": "about",
      "meaning": "大约；左右",
      "grade": "3.2",
      "phonetic": "/əˈbaʊt/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "副",
      "serialNumber": "167"
    },
    {
      "word": "mouth",
      "meaning": "嘴",
      "grade": "3.2",
      "phonetic": "/maʊθ/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "名",
      "serialNumber": "168"
    },
    {
      "word": "boat",
      "meaning": "小船；舟",
      "grade": "3.2",
      "phonetic": "/bəʊt/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "169"
    },
    {
      "word": "slow",
      "meaning": "缓慢的；慢的",
      "grade": "3.2",
      "phonetic": "/sləʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "形容",
      "serialNumber": "170"
    },
    {
      "word": "hear",
      "meaning": "听见",
      "grade": "3.2",
      "phonetic": "/hɪə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɪə/",
      "note": "ear读双元音/ɪə/",
      "partOfSpeech": "动",
      "serialNumber": "171"
    },
    {
      "word": "near",
      "meaning": "在……附近",
      "grade": "3.2",
      "phonetic": "/nɪə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɪə/",
      "note": "ear读双元音/ɪə/",
      "partOfSpeech": "介",
      "serialNumber": "172"
    },
    {
      "word": "here",
      "meaning": "在这儿",
      "grade": "3.2",
      "phonetic": "/hɪə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/ɪə/",
      "note": "ere读双元音/ɪə/",
      "partOfSpeech": "副",
      "serialNumber": "173"
    },
    {
      "word": "bear",
      "meaning": "熊",
      "grade": "3.2",
      "phonetic": "/beə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/eə/",
      "note": "ear读双元音/eə/",
      "partOfSpeech": "名",
      "serialNumber": "174"
    },
    {
      "word": "share",
      "meaning": "分享",
      "grade": "3.2",
      "phonetic": "/ʃeə(r)/",
      "highlightLetters": "are",
      "highlightPhonetic": "/eə/",
      "note": "are读双元音/eə/",
      "partOfSpeech": "动",
      "serialNumber": "175"
    },
    {
      "word": "where",
      "meaning": "在哪儿",
      "grade": "3.2",
      "phonetic": "/weə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "176"
    },
    {
      "word": "there",
      "meaning": "在那儿",
      "grade": "3.2",
      "phonetic": "/eə(r)/",
      "highlightLetters": "ere",
      "highlightPhonetic": "/eə/",
      "note": "ere读双元音/eə/",
      "partOfSpeech": "副",
      "serialNumber": "177"
    },
    {
      "word": "sure",
      "meaning": "当然可以",
      "grade": "3.2",
      "phonetic": "/ʃuə(r)/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/uə/",
      "note": "ure读双元音/uə/",
      "partOfSpeech": "副",
      "serialNumber": "178"
    },
    {
      "word": "poor",
      "meaning": "穷的；可怜的",
      "grade": "3.2",
      "phonetic": "/puə(r)/",
      "highlightLetters": "oor",
      "highlightPhonetic": "/uə/",
      "note": "oor读双元音/uə/",
      "partOfSpeech": "形容",
      "serialNumber": "179"
    },
    {
      "word": "about",
      "meaning": "大约",
      "grade": "3.2",
      "phonetic": "/əˈbaʊt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "副",
      "serialNumber": "180"
    },
    {
      "word": "breakfast",
      "meaning": "早餐",
      "grade": "3.2",
      "phonetic": "/ˈbrekfəst/",
      "highlightLetters": "第2个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "181"
    },
    {
      "word": "Canada",
      "meaning": "加拿大",
      "grade": "3.2",
      "phonetic": "/ˈkænədə/",
      "highlightLetters": "后2个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "182"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "3.2",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "183"
    },
    {
      "word": "today",
      "meaning": "今天",
      "grade": "3.2",
      "phonetic": "/təˈdeɪ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "副",
      "serialNumber": "184"
    },
    {
      "word": "seven",
      "meaning": "七",
      "grade": "3.2",
      "phonetic": "/ˈsevn/",
      "highlightLetters": "第2个e",
      "highlightPhonetic": "",
      "note": "e读弱音省略",
      "partOfSpeech": "数",
      "serialNumber": "185"
    },
    {
      "word": "eleven",
      "meaning": "十一",
      "grade": "3.2",
      "phonetic": "/ɪˈlevn/",
      "highlightLetters": "第3个e",
      "highlightPhonetic": "",
      "note": "e读弱音省略",
      "partOfSpeech": "数",
      "serialNumber": "186"
    },
    {
      "word": "student",
      "meaning": "学生",
      "grade": "3.2",
      "phonetic": "/ˈstjuːdnt/",
      "highlightLetters": "e",
      "highlightPhonetic": "",
      "note": "e读弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "187"
    },
    {
      "word": "body",
      "meaning": "身体",
      "grade": "3.2",
      "phonetic": "/ˈbɒdi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "188"
    },
    {
      "word": "very",
      "meaning": "很；十分",
      "grade": "3.2",
      "phonetic": "/ˈveri/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "副",
      "serialNumber": "189"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "3.2",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "190"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "3.2",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "数",
      "serialNumber": "191"
    },
    {
      "word": "healthy",
      "meaning": "健康的",
      "grade": "3.2",
      "phonetic": "/ˈhelθi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "192"
    },
    {
      "word": "yummy",
      "meaning": "很好吃的",
      "grade": "3.2",
      "phonetic": "/ˈjʌmi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形容",
      "serialNumber": "193"
    },
    {
      "word": "after",
      "meaning": "在……后面",
      "grade": "3.2",
      "phonetic": "/ˈɑːftə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "介",
      "serialNumber": "194"
    },
    {
      "word": "paper",
      "meaning": "纸",
      "grade": "3.2",
      "phonetic": "/ˈpeɪpə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "195"
    },
    {
      "word": "under",
      "meaning": "在……下面",
      "grade": "3.2",
      "phonetic": "/ˈʌndə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "介",
      "serialNumber": "196"
    },
    {
      "word": "ruler",
      "meaning": "直尺",
      "grade": "3.2",
      "phonetic": "/ˈruːlə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "197"
    },
    {
      "word": "teacher",
      "meaning": "教师",
      "grade": "3.2",
      "phonetic": "/ˈtiːtʃə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "198"
    },
    {
      "word": "eraser",
      "meaning": "橡皮",
      "grade": "3.2",
      "phonetic": "/ɪˈreɪzə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "199"
    },
    {
      "word": "computer",
      "meaning": "计算机；电脑",
      "grade": "3.2",
      "phonetic": "/kəmˈpjuːtə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "200"
    },
    {
      "word": "picture",
      "meaning": "图画；绘画",
      "grade": "3.2",
      "phonetic": "/ˈpɪktʃə(r)/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/ə/",
      "note": "ure弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "201"
    },
    {
      "word": "neighbour",
      "meaning": "邻居",
      "grade": "3.2",
      "phonetic": "/ˈneɪbə(r)/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ə/",
      "note": "our弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "202"
    },
    {
      "word": "colourful",
      "meaning": "五彩缤纷的",
      "grade": "3.2",
      "phonetic": "/ˈkʌləfl/",
      "highlightLetters": "our",
      "highlightPhonetic": "/ə/",
      "note": "our弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "203"
    },
    {
      "word": "bag",
      "meaning": "包；袋",
      "grade": "3.2",
      "phonetic": "/bæɡ/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "204"
    },
    {
      "word": "back",
      "meaning": "回到原处",
      "grade": "3.2",
      "phonetic": "/bæk/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "副",
      "serialNumber": "205"
    },
    {
      "word": "ball",
      "meaning": "球",
      "grade": "3.2",
      "phonetic": "/bɔːl/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "206"
    },
    {
      "word": "boat",
      "meaning": "小船；舟",
      "grade": "3.2",
      "phonetic": "/bəʊt/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "207"
    },
    {
      "word": "body",
      "meaning": "身体",
      "grade": "3.2",
      "phonetic": "/ˈbɒdi/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "208"
    },
    {
      "word": "cap",
      "meaning": "鸭舌帽",
      "grade": "3.2",
      "phonetic": "/kæp/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名",
      "serialNumber": "209"
    },
    {
      "word": "card",
      "meaning": "贺卡；卡片",
      "grade": "3.2",
      "phonetic": "/kɑːd/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名",
      "serialNumber": "210"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "3.2",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名",
      "serialNumber": "211"
    },
    {
      "word": "Canada",
      "meaning": "加拿大",
      "grade": "3.2",
      "phonetic": "/ˈkænədə/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在a前）",
      "partOfSpeech": "名",
      "serialNumber": "212"
    },
    {
      "word": "cool",
      "meaning": "酷的，绝妙的",
      "grade": "3.2",
      "phonetic": "/kuːl/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在o前）",
      "partOfSpeech": "形容",
      "serialNumber": "213"
    },
    {
      "word": "class",
      "meaning": "课；班级",
      "grade": "3.2",
      "phonetic": "/klɑːs/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/（在辅音前）",
      "partOfSpeech": "名",
      "serialNumber": "214"
    },
    {
      "word": "face",
      "meaning": "脸；面孔",
      "grade": "3.2",
      "phonetic": "/feɪs/",
      "highlightLetters": "ce",
      "highlightPhonetic": "/s/",
      "note": "c读/s/（在e前）",
      "partOfSpeech": "名",
      "serialNumber": "215"
    },
    {
      "word": "rice",
      "meaning": "大米",
      "grade": "3.2",
      "phonetic": "/raɪs/",
      "highlightLetters": "ce",
      "highlightPhonetic": "/s/",
      "note": "c读/s/（在e前）",
      "partOfSpeech": "不可数名",
      "serialNumber": "216"
    },
    {
      "word": "juice",
      "meaning": "果汁",
      "grade": "3.2",
      "phonetic": "/dʒuːs/",
      "highlightLetters": "ce",
      "highlightPhonetic": "/s/",
      "note": "c读/s/（在e前）",
      "partOfSpeech": "不可数名",
      "serialNumber": "217"
    },
    {
      "word": "pencil",
      "meaning": "铅笔",
      "grade": "3.2",
      "phonetic": "/ˈpensl/",
      "highlightLetters": "ci",
      "highlightPhonetic": "/s/",
      "note": "c读/s/（在i前）",
      "partOfSpeech": "名",
      "serialNumber": "218"
    },
    {
      "word": "dance",
      "meaning": "跳舞",
      "grade": "3.2",
      "phonetic": "/dɑːns/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "219"
    },
    {
      "word": "doll",
      "meaning": "玩偶；玩具娃娃",
      "grade": "3.2",
      "phonetic": "/dɒl/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "220"
    },
    {
      "word": "fat",
      "meaning": "肥的；肥胖的",
      "grade": "3.2",
      "phonetic": "/fæt/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "形容",
      "serialNumber": "221"
    },
    {
      "word": "fifteen",
      "meaning": "十五",
      "grade": "3.2",
      "phonetic": "/ˌfɪfˈtiːn/",
      "highlightLetters": "f，f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "数",
      "serialNumber": "222"
    },
    {
      "word": "find",
      "meaning": "找到；发现",
      "grade": "3.2",
      "phonetic": "/faɪnd/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "223"
    },
    {
      "word": "fourteen",
      "meaning": "十四",
      "grade": "3.2",
      "phonetic": "/ˌfɔːˈtiːn/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "数",
      "serialNumber": "224"
    },
    {
      "word": "from",
      "meaning": "来自，从……来",
      "grade": "3.2",
      "phonetic": "/frɒm/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "介",
      "serialNumber": "225"
    },
    {
      "word": "fruit",
      "meaning": "水果",
      "grade": "3.2",
      "phonetic": "/fruːt/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "226"
    },
    {
      "word": "gift",
      "meaning": "礼物",
      "grade": "3.2",
      "phonetic": "/ɡɪft/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "227"
    },
    {
      "word": "girl",
      "meaning": "女孩",
      "grade": "3.2",
      "phonetic": "/ɡɜːl/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "228"
    },
    {
      "word": "bag",
      "meaning": "包；袋",
      "grade": "3.2",
      "phonetic": "/bæɡ/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名",
      "serialNumber": "229"
    },
    {
      "word": "English",
      "meaning": "英语的；英语",
      "grade": "3.2",
      "phonetic": "/ˈɪŋɡlɪʃ/",
      "highlightLetters": "g",
      "highlightPhonetic": "/ɡ/",
      "note": "g读/ɡ/",
      "partOfSpeech": "名; 形容",
      "serialNumber": "230"
    },
    {
      "word": "has",
      "meaning": "(他/她/它)具有",
      "grade": "3.2",
      "phonetic": "/hæz/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "231"
    },
    {
      "word": "he",
      "meaning": "他",
      "grade": "3.2",
      "phonetic": "/hiː/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代",
      "serialNumber": "232"
    },
    {
      "word": "hear",
      "meaning": "听见；听到",
      "grade": "3.2",
      "phonetic": "/hɪə(r)/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "233"
    },
    {
      "word": "her",
      "meaning": "她；她的",
      "grade": "3.2",
      "phonetic": "/hɜː(r)/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "代",
      "serialNumber": "234"
    },
    {
      "word": "home",
      "meaning": "家；住所",
      "grade": "3.2",
      "phonetic": "/həʊm/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名; 副",
      "serialNumber": "235"
    },
    {
      "word": "jet",
      "meaning": "喷气式飞机",
      "grade": "3.2",
      "phonetic": "/dʒet/",
      "highlightLetters": "j",
      "highlightPhonetic": "/dʒ/",
      "note": "j读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "236"
    },
    {
      "word": "job",
      "meaning": "工作",
      "grade": "3.2",
      "phonetic": "/dʒɒb/",
      "highlightLetters": "j",
      "highlightPhonetic": "/dʒ/",
      "note": "j读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "237"
    },
    {
      "word": "juice",
      "meaning": "果汁",
      "grade": "3.2",
      "phonetic": "/dʒuːs/",
      "highlightLetters": "j",
      "highlightPhonetic": "/dʒ/",
      "note": "j读/dʒ/",
      "partOfSpeech": "不可数名",
      "serialNumber": "238"
    },
    {
      "word": "keep",
      "meaning": "保有；留着",
      "grade": "3.2",
      "phonetic": "/kiːp/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "动",
      "serialNumber": "239"
    },
    {
      "word": "like",
      "meaning": "喜欢；像",
      "grade": "3.2",
      "phonetic": "/laɪk/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "动",
      "serialNumber": "240"
    },
    {
      "word": "make",
      "meaning": "使；制作",
      "grade": "3.2",
      "phonetic": "/meɪk/",
      "highlightLetters": "k",
      "highlightPhonetic": "/k/",
      "note": "k读/k/",
      "partOfSpeech": "动",
      "serialNumber": "241"
    },
    {
      "word": "learn",
      "meaning": "学；学习",
      "grade": "3.2",
      "phonetic": "/lɜːn/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "242"
    },
    {
      "word": "long",
      "meaning": "长的",
      "grade": "3.2",
      "phonetic": "/lɒŋ/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "形容",
      "serialNumber": "243"
    },
    {
      "word": "love",
      "meaning": "喜爱；爱",
      "grade": "3.2",
      "phonetic": "/lʌv/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "动",
      "serialNumber": "244"
    },
    {
      "word": "ruler",
      "meaning": "直尺",
      "grade": "3.2",
      "phonetic": "/ˈruːlə(r)/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音前)",
      "partOfSpeech": "名",
      "serialNumber": "245"
    },
    {
      "word": "girl",
      "meaning": "女孩",
      "grade": "3.2",
      "phonetic": "/ɡɜːl/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "名",
      "serialNumber": "246"
    },
    {
      "word": "tail",
      "meaning": "尾；尾巴",
      "grade": "3.2",
      "phonetic": "/teɪl/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "名",
      "serialNumber": "247"
    },
    {
      "word": "doll",
      "meaning": "玩具娃娃",
      "grade": "3.2",
      "phonetic": "/dɒl/",
      "highlightLetters": "ll",
      "highlightPhonetic": "/l/",
      "note": "ll读/l/(元音后)",
      "partOfSpeech": "名",
      "serialNumber": "248"
    },
    {
      "word": "milk",
      "meaning": "牛奶",
      "grade": "3.2",
      "phonetic": "/mɪlk/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "不可数名",
      "serialNumber": "249"
    },
    {
      "word": "shelf",
      "meaning": "架子",
      "grade": "3.2",
      "phonetic": "/ʃelf/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "名",
      "serialNumber": "250"
    },
    {
      "word": "healthy",
      "meaning": "健康的",
      "grade": "3.2",
      "phonetic": "/ˈhelθi/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "形容",
      "serialNumber": "251"
    },
    {
      "word": "twelve",
      "meaning": "十二",
      "grade": "3.2",
      "phonetic": "/twelv/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/(元音后)",
      "partOfSpeech": "数",
      "serialNumber": "252"
    },
    {
      "word": "man",
      "meaning": "成年男子",
      "grade": "3.2",
      "phonetic": "/mæn/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "253"
    },
    {
      "word": "meat",
      "meaning": "肉",
      "grade": "3.2",
      "phonetic": "/miːt/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "不可数名",
      "serialNumber": "254"
    },
    {
      "word": "milk",
      "meaning": "牛奶",
      "grade": "3.2",
      "phonetic": "/mɪlk/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "不可数名",
      "serialNumber": "255"
    },
    {
      "word": "much",
      "meaning": "许多；大量",
      "grade": "3.2",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "代",
      "serialNumber": "256"
    },
    {
      "word": "Mr",
      "meaning": "先生",
      "grade": "3.2",
      "phonetic": "/ˈmɪstə(r)/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "257"
    },
    {
      "word": "Miss",
      "meaning": "女士",
      "grade": "3.2",
      "phonetic": "/mɪs/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "258"
    },
    {
      "word": "from",
      "meaning": "来自，从……来",
      "grade": "3.2",
      "phonetic": "/frɒm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "介",
      "serialNumber": "259"
    },
    {
      "word": "home",
      "meaning": "家",
      "grade": "3.2",
      "phonetic": "/həʊm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名; 副",
      "serialNumber": "260"
    },
    {
      "word": "time",
      "meaning": "时间",
      "grade": "3.2",
      "phonetic": "/taɪm/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "261"
    },
    {
      "word": "in",
      "meaning": "在……内/里；",
      "grade": "3.2",
      "phonetic": "/ɪn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "介",
      "serialNumber": "262"
    },
    {
      "word": "thin",
      "meaning": "瘦的",
      "grade": "3.2",
      "phonetic": "/θɪn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "形容",
      "serialNumber": "263"
    },
    {
      "word": "on",
      "meaning": "在……上（表面）",
      "grade": "3.2",
      "phonetic": "/ɒn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "介",
      "serialNumber": "264"
    },
    {
      "word": "man",
      "meaning": "成年男子；男人",
      "grade": "3.2",
      "phonetic": "/mæn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "265"
    },
    {
      "word": "learn",
      "meaning": "学；学习",
      "grade": "3.2",
      "phonetic": "/lɜːn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "动",
      "serialNumber": "266"
    },
    {
      "word": "candy",
      "meaning": "糖果",
      "grade": "3.2",
      "phonetic": "/ˈkændi/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "267"
    },
    {
      "word": "dance",
      "meaning": "跳舞",
      "grade": "3.2",
      "phonetic": "/dɑːns/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "动",
      "serialNumber": "268"
    },
    {
      "word": "find",
      "meaning": "找到；找回",
      "grade": "3.2",
      "phonetic": "/faɪnd/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "动",
      "serialNumber": "269"
    },
    {
      "word": "neighbour",
      "meaning": "邻居",
      "grade": "3.2",
      "phonetic": "/ˈneɪbə(r)/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "名",
      "serialNumber": "270"
    },
    {
      "word": "nineteen",
      "meaning": "十九",
      "grade": "3.2",
      "phonetic": "/ˌnaɪnˈtiːn/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "数",
      "serialNumber": "271"
    },
    {
      "word": "noodle",
      "meaning": "面条",
      "grade": "3.2",
      "phonetic": "/ˈnuːdl/",
      "highlightLetters": "n",
      "highlightPhonetic": "/n/",
      "note": "n读/n/",
      "partOfSpeech": "数",
      "serialNumber": "272"
    },
    {
      "word": "bank",
      "meaning": "银行",
      "grade": "3.2",
      "phonetic": "/bæŋk/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "n读/ŋ/（在/k/音前）",
      "partOfSpeech": "名",
      "serialNumber": "273"
    },
    {
      "word": "sing",
      "meaning": "唱（歌）",
      "grade": "3.2",
      "phonetic": "/sɪŋ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "动",
      "serialNumber": "274"
    },
    {
      "word": "long",
      "meaning": "长的",
      "grade": "3.2",
      "phonetic": "/lɒŋ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "形容",
      "serialNumber": "275"
    },
    {
      "word": "tongue",
      "meaning": "舌头",
      "grade": "3.2",
      "phonetic": "/tʌŋ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋ/",
      "partOfSpeech": "名",
      "serialNumber": "276"
    },
    {
      "word": "English",
      "meaning": "英语（的）",
      "grade": "3.2",
      "phonetic": "/ˈɪŋɡlɪʃ/",
      "highlightLetters": "n",
      "highlightPhonetic": "/ŋ/",
      "note": "ng读/ŋɡ/",
      "partOfSpeech": "名; 形容",
      "serialNumber": "277"
    },
    {
      "word": "put",
      "meaning": "放；安置",
      "grade": "3.2",
      "phonetic": "/pʊt/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "动",
      "serialNumber": "278"
    },
    {
      "word": "pay",
      "meaning": "付费",
      "grade": "3.2",
      "phonetic": "/peɪ/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "动",
      "serialNumber": "279"
    },
    {
      "word": "pencil",
      "meaning": "铅笔",
      "grade": "3.2",
      "phonetic": "/ˈpensl/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "280"
    },
    {
      "word": "paper",
      "meaning": "纸",
      "grade": "3.2",
      "phonetic": "/ˈpeɪpə(r)/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "281"
    },
    {
      "word": "picture",
      "meaning": "图画",
      "grade": "3.2",
      "phonetic": "/ˈpɪktʃə(r)/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "282"
    },
    {
      "word": "piggy",
      "meaning": "猪形的",
      "grade": "3.2",
      "phonetic": "/ˈpɪɡi/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "形容",
      "serialNumber": "283"
    },
    {
      "word": "quiet",
      "meaning": "安静的",
      "grade": "3.2",
      "phonetic": "/ˈkwaiət/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "形容",
      "serialNumber": "284"
    },
    {
      "word": "quite",
      "meaning": "非常；十分",
      "grade": "3.2",
      "phonetic": "/ˈkwait/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "副",
      "serialNumber": "285"
    },
    {
      "word": "rice",
      "meaning": "大米",
      "grade": "3.2",
      "phonetic": "/raɪs/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "不可数名",
      "serialNumber": "286"
    },
    {
      "word": "right",
      "meaning": "准确的，恰当的",
      "grade": "3.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "形容",
      "serialNumber": "287"
    },
    {
      "word": "ruler",
      "meaning": "直尺",
      "grade": "3.2",
      "phonetic": "/ˈruːlə(r)/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "288"
    },
    {
      "word": "eraser",
      "meaning": "橡皮",
      "grade": "3.2",
      "phonetic": "/ɪˈreɪzə(r)/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "289"
    },
    {
      "word": "very",
      "meaning": "很；非常；十分",
      "grade": "3.2",
      "phonetic": "/ˈveri/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "副",
      "serialNumber": "290"
    },
    {
      "word": "see",
      "meaning": "看见",
      "grade": "3.2",
      "phonetic": "/siː/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "动",
      "serialNumber": "291"
    },
    {
      "word": "sing",
      "meaning": "唱（歌）",
      "grade": "3.2",
      "phonetic": "/sɪŋ/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "动",
      "serialNumber": "292"
    },
    {
      "word": "so",
      "meaning": "这么，那么",
      "grade": "3.2",
      "phonetic": "/səʊ/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "副",
      "serialNumber": "293"
    },
    {
      "word": "song",
      "meaning": "歌；歌曲",
      "grade": "3.2",
      "phonetic": "/sɒŋ/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "名",
      "serialNumber": "294"
    },
    {
      "word": "soup",
      "meaning": "汤",
      "grade": "3.2",
      "phonetic": "/suːp/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "不可数名",
      "serialNumber": "295"
    },
    {
      "word": "sixteen",
      "meaning": "十六",
      "grade": "3.2",
      "phonetic": "/ˌsɪksˈtiːn/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "数",
      "serialNumber": "296"
    },
    {
      "word": "seventeen",
      "meaning": "十七",
      "grade": "3.2",
      "phonetic": "/ˌsevnˈtiːn/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "数",
      "serialNumber": "297"
    },
    {
      "word": "nose",
      "meaning": "鼻子",
      "grade": "3.2",
      "phonetic": "/nəʊz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "298"
    },
    {
      "word": "Jones",
      "meaning": "琼斯（姓）",
      "grade": "3.2",
      "phonetic": "/dʒəʊnz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名",
      "serialNumber": "299"
    },
    {
      "word": "shelves",
      "meaning": "架子（shelf的复数）",
      "grade": "3.2",
      "phonetic": "/ʃelvz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名，复数",
      "serialNumber": "300"
    },
    {
      "word": "noodles",
      "meaning": "（复数）面条",
      "grade": "3.2",
      "phonetic": "/ˈnuːdlz/",
      "highlightLetters": "s",
      "highlightPhonetic": "/z/",
      "note": "s读/z/",
      "partOfSpeech": "名，复数",
      "serialNumber": "301"
    },
    {
      "word": "at",
      "meaning": "在（某处）",
      "grade": "3.2",
      "phonetic": "/æt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "介",
      "serialNumber": "302"
    },
    {
      "word": "fat",
      "meaning": "肥的",
      "grade": "3.2",
      "phonetic": "/fæt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形容",
      "serialNumber": "303"
    },
    {
      "word": "put",
      "meaning": "放；安置",
      "grade": "3.2",
      "phonetic": "/pʊt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "304"
    },
    {
      "word": "tail",
      "meaning": "尾巴",
      "grade": "3.2",
      "phonetic": "/teɪl/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "305"
    },
    {
      "word": "talk",
      "meaning": "说话；聊天",
      "grade": "3.2",
      "phonetic": "/tɔːk/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "形容",
      "serialNumber": "306"
    },
    {
      "word": "taste",
      "meaning": "尝（味道）",
      "grade": "3.2",
      "phonetic": "/teɪst/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "307"
    },
    {
      "word": "time",
      "meaning": "时间",
      "grade": "3.2",
      "phonetic": "/taɪm/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "不可数名",
      "serialNumber": "308"
    },
    {
      "word": "today",
      "meaning": "今天",
      "grade": "3.2",
      "phonetic": "/təˈdeɪ/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "副",
      "serialNumber": "309"
    },
    {
      "word": "tongue",
      "meaning": "舌头",
      "grade": "3.2",
      "phonetic": "/tʌŋ/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "310"
    },
    {
      "word": "touch",
      "meaning": "触摸；碰",
      "grade": "3.2",
      "phonetic": "/tʌtʃ/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "311"
    },
    {
      "word": "van",
      "meaning": "面包车",
      "grade": "3.2",
      "phonetic": "/væn/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "312"
    },
    {
      "word": "vet",
      "meaning": "兽医",
      "grade": "3.2",
      "phonetic": "/vet/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "313"
    },
    {
      "word": "very",
      "meaning": "很；非常；十分",
      "grade": "3.2",
      "phonetic": "/ˈveri/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "副",
      "serialNumber": "314"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "3.2",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "名",
      "serialNumber": "315"
    },
    {
      "word": "woman",
      "meaning": "成年女子；妇女",
      "grade": "3.2",
      "phonetic": "/ˈwʊmən/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "316"
    },
    {
      "word": "where",
      "meaning": "在哪里；到哪里",
      "grade": "3.2",
      "phonetic": "/weə(r)/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/w/",
      "note": "wh读/w/",
      "partOfSpeech": "副",
      "serialNumber": "317"
    },
    {
      "word": "fox",
      "meaning": "狐狸",
      "grade": "3.2",
      "phonetic": "/fɒks/",
      "highlightLetters": "x",
      "highlightPhonetic": "/ks/",
      "note": "x读/ks/",
      "partOfSpeech": "名",
      "serialNumber": "318"
    },
    {
      "word": "six",
      "meaning": "六",
      "grade": "3.2",
      "phonetic": "/sɪks/",
      "highlightLetters": "x",
      "highlightPhonetic": "/ks/",
      "note": "x读/ks/",
      "partOfSpeech": "数",
      "serialNumber": "319"
    },
    {
      "word": "yummy",
      "meaning": "很好吃的",
      "grade": "3.2",
      "phonetic": "/ˈjʌmi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/j/",
      "note": "y读/j/ （用作辅音）",
      "partOfSpeech": "形容",
      "serialNumber": "320"
    },
    {
      "word": "zip",
      "meaning": "拉链",
      "grade": "3.2",
      "phonetic": "/zɪp/",
      "highlightLetters": "z",
      "highlightPhonetic": "/z/",
      "note": "z读/z/",
      "partOfSpeech": "名",
      "serialNumber": "321"
    },
    {
      "word": "quiz",
      "meaning": "小测验",
      "grade": "3.2",
      "phonetic": "/kwɪz/",
      "highlightLetters": "z",
      "highlightPhonetic": "/z/",
      "note": "z读/z/",
      "partOfSpeech": "名",
      "serialNumber": "322"
    },
    {
      "word": "ball",
      "meaning": "球",
      "grade": "3.2",
      "phonetic": "/bɔːl/",
      "highlightLetters": "ll",
      "highlightPhonetic": "/l/",
      "note": "ll读/l/",
      "partOfSpeech": "名",
      "serialNumber": "323"
    },
    {
      "word": "doll",
      "meaning": "玩偶；玩具娃娃",
      "grade": "3.2",
      "phonetic": "/dɒl/",
      "highlightLetters": "ll",
      "highlightPhonetic": "/l/",
      "note": "ll读/l/",
      "partOfSpeech": "名",
      "serialNumber": "324"
    },
    {
      "word": "smell",
      "meaning": "闻（气味）",
      "grade": "3.2",
      "phonetic": "/smel/",
      "highlightLetters": "ll",
      "highlightPhonetic": "/l/",
      "note": "ll读/l/",
      "partOfSpeech": "动",
      "serialNumber": "325"
    },
    {
      "word": "find",
      "meaning": "找到；找回",
      "grade": "3.2",
      "phonetic": "/faɪnd/",
      "highlightLetters": "nd",
      "highlightPhonetic": "/nd/",
      "note": "nd读/nd/",
      "partOfSpeech": "动",
      "serialNumber": "326"
    },
    {
      "word": "gift",
      "meaning": "礼物",
      "grade": "3.2",
      "phonetic": "/ɡɪft/",
      "highlightLetters": "ft",
      "highlightPhonetic": "/ft/",
      "note": "ft读/ft/",
      "partOfSpeech": "名",
      "serialNumber": "327"
    },
    {
      "word": "shelf",
      "meaning": "架子",
      "grade": "3.2",
      "phonetic": "/ʃelf/",
      "highlightLetters": "lf",
      "highlightPhonetic": "/lf/",
      "note": "lf读/lf/",
      "partOfSpeech": "名",
      "serialNumber": "328"
    },
    {
      "word": "bread",
      "meaning": "面包",
      "grade": "3.2",
      "phonetic": "/bred/",
      "highlightLetters": "br",
      "highlightPhonetic": "/br/",
      "note": "br读/br/",
      "partOfSpeech": "不可数名",
      "serialNumber": "329"
    },
    {
      "word": "breakfast",
      "meaning": "早餐；早饭",
      "grade": "3.2",
      "phonetic": "/ˈbrekfəst/",
      "highlightLetters": "br",
      "highlightPhonetic": "/br/",
      "note": "br读/br/",
      "partOfSpeech": "不可数名",
      "serialNumber": "330"
    },
    {
      "word": "from",
      "meaning": "来自，从……来",
      "grade": "3.2",
      "phonetic": "/frɒm/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "介",
      "serialNumber": "331"
    },
    {
      "word": "fruit",
      "meaning": "水果",
      "grade": "3.2",
      "phonetic": "/fruːt/",
      "highlightLetters": "fr",
      "highlightPhonetic": "/fr/",
      "note": "fr读/fr/",
      "partOfSpeech": "名",
      "serialNumber": "332"
    },
    {
      "word": "class",
      "meaning": "课；班级",
      "grade": "3.2",
      "phonetic": "/klɑːs/",
      "highlightLetters": "cl",
      "highlightPhonetic": "/kl/",
      "note": "cl读/kl/",
      "partOfSpeech": "名",
      "serialNumber": "333"
    },
    {
      "word": "classmate",
      "meaning": "同班同学",
      "grade": "3.2",
      "phonetic": "/ˈklɑːsmeɪt/",
      "highlightLetters": "cl",
      "highlightPhonetic": "/kl/",
      "note": "cl读/kl/",
      "partOfSpeech": "名",
      "serialNumber": "334"
    },
    {
      "word": "plate",
      "meaning": "盘子",
      "grade": "3.2",
      "phonetic": "/pleɪt/",
      "highlightLetters": "pl",
      "highlightPhonetic": "/pl/",
      "note": "pl读/pl/",
      "partOfSpeech": "名",
      "serialNumber": "335"
    },
    {
      "word": "slow",
      "meaning": "缓慢的；慢的",
      "grade": "3.2",
      "phonetic": "/sləʊ/",
      "highlightLetters": "sl",
      "highlightPhonetic": "/sl/",
      "note": "sl读/sl/",
      "partOfSpeech": "形容",
      "serialNumber": "336"
    },
    {
      "word": "still",
      "meaning": "还是；仍然",
      "grade": "3.2",
      "phonetic": "/stɪl/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "副",
      "serialNumber": "337"
    },
    {
      "word": "student",
      "meaning": "学生",
      "grade": "3.2",
      "phonetic": "/ˈstjuːdnt/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "名",
      "serialNumber": "338"
    },
    {
      "word": "China",
      "meaning": "中国",
      "grade": "3.2",
      "phonetic": "/ˈtʃaɪnə/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "名",
      "serialNumber": "339"
    },
    {
      "word": "much",
      "meaning": "许多；大量",
      "grade": "3.2",
      "phonetic": "/mʌtʃ/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "代",
      "serialNumber": "340"
    },
    {
      "word": "touch",
      "meaning": "触摸；碰",
      "grade": "3.2",
      "phonetic": "/tʌtʃ/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "动",
      "serialNumber": "341"
    },
    {
      "word": "teacher",
      "meaning": "教师",
      "grade": "3.2",
      "phonetic": "/ˈtiːtʃə(r)/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "名",
      "serialNumber": "342"
    },
    {
      "word": "right",
      "meaning": "准确的，恰当的",
      "grade": "3.2",
      "phonetic": "/raɪt/",
      "highlightLetters": "gh",
      "highlightPhonetic": "",
      "note": "gh不发音",
      "partOfSpeech": "形容",
      "serialNumber": "343"
    },
    {
      "word": "neighbour",
      "meaning": "邻居",
      "grade": "3.2",
      "phonetic": "/ˈneɪbə(r)/",
      "highlightLetters": "gh",
      "highlightPhonetic": "",
      "note": "gh不发音",
      "partOfSpeech": "名",
      "serialNumber": "344"
    },
    {
      "word": "where",
      "meaning": "在哪里；到哪里",
      "grade": "3.2",
      "phonetic": "/weə(r)/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/w/",
      "note": "wh读/w/",
      "partOfSpeech": "副",
      "serialNumber": "345"
    },
    {
      "word": "who",
      "meaning": "谁；什么人",
      "grade": "3.2",
      "phonetic": "/huː/",
      "highlightLetters": "wh",
      "highlightPhonetic": "/h/",
      "note": "wh读/h/",
      "partOfSpeech": "形容",
      "serialNumber": "346"
    },
    {
      "word": "she",
      "meaning": "她",
      "grade": "3.2",
      "phonetic": "/ʃiː/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "代",
      "serialNumber": "347"
    },
    {
      "word": "shelf",
      "meaning": "架子",
      "grade": "3.2",
      "phonetic": "/ʃelf/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "348"
    },
    {
      "word": "short",
      "meaning": "短的；矮的",
      "grade": "3.2",
      "phonetic": "/ʃɔːt/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "形容",
      "serialNumber": "349"
    },
    {
      "word": "English",
      "meaning": "英语(的)",
      "grade": "3.2",
      "phonetic": "/ˈɪŋɡlɪʃ/",
      "highlightLetters": "ng",
      "highlightPhonetic": "/ŋɡ/",
      "note": "ng读/ŋɡ/",
      "partOfSpeech": "名; 形容",
      "serialNumber": "350"
    },
    {
      "word": "these",
      "meaning": "这些",
      "grade": "3.2",
      "phonetic": "/ðiːz/",
      "highlightLetters": "th",
      "highlightPhonetic": "/ð/",
      "note": "th读/ð/",
      "partOfSpeech": "代;形容",
      "serialNumber": "351"
    },
    {
      "word": "thin",
      "meaning": "瘦的",
      "grade": "3.2",
      "phonetic": "/θɪn/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "形容",
      "serialNumber": "352"
    },
    {
      "word": "thirteen",
      "meaning": "十三",
      "grade": "3.2",
      "phonetic": "/ˌθɜːˈtiːn/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "数",
      "serialNumber": "353"
    },
    {
      "word": "healthy",
      "meaning": "健康的",
      "grade": "3.2",
      "phonetic": "/ˈhelθi/",
      "highlightLetters": "th",
      "highlightPhonetic": "/θ/",
      "note": "th读/θ/",
      "partOfSpeech": "形容",
      "serialNumber": "354"
    },
    {
      "word": "twelve",
      "meaning": "十二",
      "grade": "3.2",
      "phonetic": "/twelv/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "数",
      "serialNumber": "355"
    },
    {
      "word": "twenty",
      "meaning": "二十",
      "grade": "3.2",
      "phonetic": "/ˈtwenti/",
      "highlightLetters": "tw",
      "highlightPhonetic": "/tw/",
      "note": "tw读/tw/",
      "partOfSpeech": "数",
      "serialNumber": "356"
    },
    {
      "word": "noodle",
      "meaning": "面条",
      "grade": "3.2",
      "phonetic": "/ˈnuːdl/",
      "highlightLetters": "dle",
      "highlightPhonetic": "/dl/",
      "note": "dle读/dl/",
      "partOfSpeech": "名",
      "serialNumber": "357"
    },
    {
      "word": "vegetable",
      "meaning": "蔬菜",
      "grade": "3.2",
      "phonetic": "/ˈvedʒtəbl/",
      "highlightLetters": "ble",
      "highlightPhonetic": "/bl/",
      "note": "ble读/bl/",
      "partOfSpeech": "名",
      "serialNumber": "358"
    },
    {
      "word": "pencil",
      "meaning": "铅笔",
      "grade": "3.2",
      "phonetic": "/ˈpensl/",
      "highlightLetters": "cil",
      "highlightPhonetic": "/sl/",
      "note": "cil读/sl/",
      "partOfSpeech": "名",
      "serialNumber": "359"
    },
    {
      "word": "colourful",
      "meaning": "五彩缤纷的",
      "grade": "3.2",
      "phonetic": "/ˈkʌləfl/",
      "highlightLetters": "ful",
      "highlightPhonetic": "/fl/",
      "note": "ful读/fl/",
      "partOfSpeech": "形容",
      "serialNumber": "360"
    }
  ]
};
