// 自动生成的JS模块 - grade7_1.json
// 生成时间: 2025-12-25T08:27:53.962Z

module.exports = {
  "grade": 7,
  "semester": 1,
  "gradeName": "初中一年级上册",
  "total": 265,
  "lastUpdated": "2025-12-25T08:25:58.770Z",
  "words": [
    {
      "word": "unit",
      "meaning": "单元",
      "grade": "7.1",
      "phonetic": "/ˈjuːnɪt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "1"
    },
    {
      "word": "starter unit",
      "meaning": "过渡单元",
      "grade": "7.1",
      "phonetic": "/ˈstɑːtə(r)/ unit",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "2"
    },
    {
      "word": "section",
      "meaning": "部分；地区",
      "grade": "7.1",
      "phonetic": "/ˈsekʃn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "3"
    },
    {
      "word": "greet",
      "meaning": "招呼；问候",
      "grade": "7.1",
      "phonetic": "/ɡriːt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "4"
    },
    {
      "word": "spell",
      "meaning": "用字母拼；拼写",
      "grade": "7.1",
      "phonetic": "/spel/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "5"
    },
    {
      "word": "start",
      "meaning": "开始，着手",
      "grade": "7.1",
      "phonetic": "/stɑːt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "6"
    },
    {
      "word": "conversation",
      "meaning": "谈话；交谈",
      "grade": "7.1",
      "phonetic": "/ˌkɒnvəˈseɪʃn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "7"
    },
    {
      "word": "oh",
      "meaning": "哦；啊",
      "grade": "7.1",
      "phonetic": "/əʊ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "interj.",
      "serialNumber": "8"
    },
    {
      "word": "bell",
      "meaning": "铃（声）；钟（声）",
      "grade": "7.1",
      "phonetic": "/bel/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "9"
    },
    {
      "word": "Helen",
      "meaning": "海伦",
      "grade": "7.1",
      "phonetic": "/ˈhelən/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "10"
    },
    {
      "word": "Brown",
      "meaning": "布朗",
      "grade": "7.1",
      "phonetic": "/braʊn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "11"
    },
    {
      "word": "PLA",
      "meaning": "中国人民解放军",
      "grade": "7.1",
      "phonetic": "/ˌpiːˌelˈeɪ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "abbr.",
      "serialNumber": "12"
    },
    {
      "word": "VR",
      "meaning": "虚拟现实",
      "grade": "7.1",
      "phonetic": "/ˌviːˈɑː(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "abbr.",
      "serialNumber": "13"
    },
    {
      "word": "CD",
      "meaning": "光盘",
      "grade": "7.1",
      "phonetic": "/ˌsiːˈdiː/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "abbr.",
      "serialNumber": "14"
    },
    {
      "word": "PRC",
      "meaning": "中华人民共和国",
      "grade": "7.1",
      "phonetic": "/ˌpiːˌɑː(r)ˈsiː/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "abbr.",
      "serialNumber": "15"
    },
    {
      "word": "UN",
      "meaning": "联合国",
      "grade": "7.1",
      "phonetic": "/ˌjuːˈen/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "abbr.",
      "serialNumber": "16"
    },
    {
      "word": "Miller",
      "meaning": "米勒",
      "grade": "7.1",
      "phonetic": "/ˈmɪlə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "17"
    },
    {
      "word": "bottle",
      "meaning": "瓶子",
      "grade": "7.1",
      "phonetic": "/ˈbɒtl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "18"
    },
    {
      "word": "eraser",
      "meaning": "橡皮",
      "grade": "7.1",
      "phonetic": "/ɪˈreɪzə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "19"
    },
    {
      "word": "key",
      "meaning": "钥匙；关键",
      "grade": "7.1",
      "phonetic": "/kiː/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "20"
    },
    {
      "word": "thing",
      "meaning": "东西；事情",
      "grade": "7.1",
      "phonetic": "/θɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "21"
    },
    {
      "word": "need",
      "meaning": "需要",
      "grade": "7.1",
      "phonetic": "/niːd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.&n.",
      "serialNumber": "22"
    },
    {
      "word": "you’re welcome",
      "meaning": "别客气；不用谢",
      "grade": "7.1",
      "phonetic": "短语",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "23"
    },
    {
      "word": "fun",
      "meaning": "乐趣；快乐",
      "grade": "7.1",
      "phonetic": "/fʌn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "24"
    },
    {
      "word": "fun",
      "meaning": "有趣的；使人快乐的",
      "grade": "7.1",
      "phonetic": "/fʌn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "25"
    },
    {
      "word": "yard",
      "meaning": "院子；园圃",
      "grade": "7.1",
      "phonetic": "/jɑːd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "26"
    },
    {
      "word": "carrot",
      "meaning": "胡萝卜",
      "grade": "7.1",
      "phonetic": "/ˈkærət/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "27"
    },
    {
      "word": "goose",
      "meaning": "（pl. geese /ɡiːs/）鹅",
      "grade": "7.1",
      "phonetic": "/ɡuːs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "28"
    },
    {
      "word": "count",
      "meaning": "数数",
      "grade": "7.1",
      "phonetic": "/kaʊnt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "29"
    },
    {
      "word": "another",
      "meaning": "另一；又一（人或事物）",
      "grade": "7.1",
      "phonetic": "/əˈnʌðə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.&pron.",
      "serialNumber": "30"
    },
    {
      "word": "else",
      "meaning": "其他的；别的",
      "grade": "7.1",
      "phonetic": "/els/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "31"
    },
    {
      "word": "look",
      "meaning": "看；瞧",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "32"
    },
    {
      "word": "make friends",
      "meaning": "交朋友",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "33"
    },
    {
      "word": "get to know",
      "meaning": "认识；了解",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "34"
    },
    {
      "word": "each",
      "meaning": "每个；各自",
      "grade": "7.1",
      "phonetic": "/iːtʃ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.&pron.",
      "serialNumber": "35"
    },
    {
      "word": "other",
      "meaning": "另外的人（或物）",
      "grade": "7.1",
      "phonetic": "/ˈʌðə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "pron.",
      "serialNumber": "36"
    },
    {
      "word": "other",
      "meaning": "另外的；其他的",
      "grade": "7.1",
      "phonetic": "/ˈʌðə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "37"
    },
    {
      "word": "each other",
      "meaning": "互相；彼此",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "38"
    },
    {
      "word": "full",
      "meaning": "完整的；满的",
      "grade": "7.1",
      "phonetic": "/fʊl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "39"
    },
    {
      "word": "full name",
      "meaning": "全名",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "40"
    },
    {
      "word": "grade",
      "meaning": "年级；等级",
      "grade": "7.1",
      "phonetic": "/ɡreɪd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "41"
    },
    {
      "word": "last name",
      "meaning": "姓氏",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "42"
    },
    {
      "word": "classmate",
      "meaning": "同班同学",
      "grade": "7.1",
      "phonetic": "/ˈklɑːsmeɪt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "43"
    },
    {
      "word": "class teacher",
      "meaning": "班主任",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "44"
    },
    {
      "word": "first name",
      "meaning": "名字",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "45"
    },
    {
      "word": "mistake",
      "meaning": "错误；失误",
      "grade": "7.1",
      "phonetic": "/mɪˈsteɪk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "46"
    },
    {
      "word": "country",
      "meaning": "国家",
      "grade": "7.1",
      "phonetic": "/ˈkʌntri/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "47"
    },
    {
      "word": "same",
      "meaning": "相同的",
      "grade": "7.1",
      "phonetic": "/seɪm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "48"
    },
    {
      "word": "twin",
      "meaning": "双胞胎之一",
      "grade": "7.1",
      "phonetic": "/twɪn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & adj.",
      "serialNumber": "49"
    },
    {
      "word": "both",
      "meaning": "两个；两个都",
      "grade": "7.1",
      "phonetic": "/bəʊθ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj. & pron.",
      "serialNumber": "50"
    },
    {
      "word": "band",
      "meaning": "乐队",
      "grade": "7.1",
      "phonetic": "/bænd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "51"
    },
    {
      "word": "pot",
      "meaning": "锅",
      "grade": "7.1",
      "phonetic": "/pɒt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "52"
    },
    {
      "word": "a lot",
      "meaning": "很多",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "53"
    },
    {
      "word": "tofu",
      "meaning": "豆腐",
      "grade": "7.1",
      "phonetic": "/ˈtəʊfuː/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "54"
    },
    {
      "word": "parrot",
      "meaning": "鹦鹉",
      "grade": "7.1",
      "phonetic": "/ˈpærət/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "55"
    },
    {
      "word": "guitar",
      "meaning": "吉他",
      "grade": "7.1",
      "phonetic": "/ɡɪˈtɑː(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "56"
    },
    {
      "word": "tennis",
      "meaning": "网球",
      "grade": "7.1",
      "phonetic": "/ˈtenɪs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "57"
    },
    {
      "word": "post",
      "meaning": "帖子；邮政；邮寄；发布",
      "grade": "7.1",
      "phonetic": "/pəʊst/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & v.",
      "serialNumber": "58"
    },
    {
      "word": "even",
      "meaning": "甚至；连；愈加",
      "grade": "7.1",
      "phonetic": "/ˈiːvn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "59"
    },
    {
      "word": "hey",
      "meaning": "嘿；喂",
      "grade": "7.1",
      "phonetic": "/heɪ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "interj.",
      "serialNumber": "60"
    },
    {
      "word": "play the guitar",
      "meaning": "弹吉他",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "61"
    },
    {
      "word": "would",
      "meaning": "想（用于礼貌地邀请或提供）；将会",
      "grade": "7.1",
      "phonetic": "/wʊd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "62"
    },
    {
      "word": "would (’d) like to",
      "meaning": "表示愿意、喜欢",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "63"
    },
    {
      "word": "information",
      "meaning": "信息；消息",
      "grade": "7.1",
      "phonetic": "/ˌɪnfəˈmeɪʃn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "64"
    },
    {
      "word": "hobby",
      "meaning": "业余爱好",
      "grade": "7.1",
      "phonetic": "/ˈhɒbi/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "65"
    },
    {
      "word": "mean",
      "meaning": "意思是；打算",
      "grade": "7.1",
      "phonetic": "/miːn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "66"
    },
    {
      "word": "husband",
      "meaning": "丈夫",
      "grade": "7.1",
      "phonetic": "/ˈhʌzbənd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "67"
    },
    {
      "word": "bat",
      "meaning": "球棒；球拍",
      "grade": "7.1",
      "phonetic": "/bæt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "68"
    },
    {
      "word": "ping-pong bat",
      "meaning": "乒乓球拍",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "69"
    },
    {
      "word": "play ping-pong",
      "meaning": "打乒乓球",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "70"
    },
    {
      "word": "every day",
      "meaning": "每天",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "71"
    },
    {
      "word": "together",
      "meaning": "在一起；共同",
      "grade": "7.1",
      "phonetic": "/təˈɡeðə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "72"
    },
    {
      "word": "fishing rod",
      "meaning": "钓竿",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "73"
    },
    {
      "word": "spend",
      "meaning": "花（时间、钱等）",
      "grade": "7.1",
      "phonetic": "/spend/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "74"
    },
    {
      "word": "a lot of / lots of",
      "meaning": "大量；许多",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "75"
    },
    {
      "word": "really",
      "meaning": "非常；确实；真正地",
      "grade": "7.1",
      "phonetic": "/ˈriːəli/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "76"
    },
    {
      "word": "activity",
      "meaning": "活动",
      "grade": "7.1",
      "phonetic": "/ækˈtɪvəti/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "77"
    },
    {
      "word": "chess",
      "meaning": "国际象棋",
      "grade": "7.1",
      "phonetic": "/tʃes/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "78"
    },
    {
      "word": "Chinese chess",
      "meaning": "中国象棋",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "79"
    },
    {
      "word": "funny",
      "meaning": "好笑的；奇怪的",
      "grade": "7.1",
      "phonetic": "/ˈfʌni/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "80"
    },
    {
      "word": "laugh",
      "meaning": "笑；发笑；笑声",
      "grade": "7.1",
      "phonetic": "/lɑːf/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "81"
    },
    {
      "word": "different",
      "meaning": "不同的",
      "grade": "7.1",
      "phonetic": "/ˈdɪfrənt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "82"
    },
    {
      "word": "violin",
      "meaning": "小提琴",
      "grade": "7.1",
      "phonetic": "/ˌvaɪəˈlɪn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "83"
    },
    {
      "word": "have fun",
      "meaning": "玩得高兴",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "84"
    },
    {
      "word": "pink",
      "meaning": "粉红色（的）",
      "grade": "7.1",
      "phonetic": "/pɪŋk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj. & n.",
      "serialNumber": "85"
    },
    {
      "word": "hat",
      "meaning": "帽子",
      "grade": "7.1",
      "phonetic": "/hæt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "86"
    },
    {
      "word": "handsome",
      "meaning": "英俊的",
      "grade": "7.1",
      "phonetic": "/ˈhænsəm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "87"
    },
    {
      "word": "knee",
      "meaning": "膝；膝盖",
      "grade": "7.1",
      "phonetic": "/niː/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "88"
    },
    {
      "word": "at night",
      "meaning": "在夜晚",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "89"
    },
    {
      "word": "in the middle",
      "meaning": "中间；中部",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "90"
    },
    {
      "word": "grandchild",
      "meaning": "（外）孙子；（外）孙女",
      "grade": "7.1",
      "phonetic": "/ˈɡræntʃaɪld/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. (pl. grandchildren)",
      "serialNumber": "91"
    },
    {
      "word": "son",
      "meaning": "儿子",
      "grade": "7.1",
      "phonetic": "/sʌn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "92"
    },
    {
      "word": "next to",
      "meaning": "紧邻；在……近旁",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "93"
    },
    {
      "word": "hike",
      "meaning": "远足；徒步旅行",
      "grade": "7.1",
      "phonetic": "/haɪk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "94"
    },
    {
      "word": "go hiking",
      "meaning": "远足；徒步旅行",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "95"
    },
    {
      "word": "hall",
      "meaning": "礼堂；大厅",
      "grade": "7.1",
      "phonetic": "/hɔːl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "96"
    },
    {
      "word": "dining hall",
      "meaning": "餐厅",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "97"
    },
    {
      "word": "in front of",
      "meaning": "在……前面",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "98"
    },
    {
      "word": "building",
      "meaning": "建筑物；房子",
      "grade": "7.1",
      "phonetic": "/ˈbɪldɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "99"
    },
    {
      "word": "across",
      "meaning": "过；穿过",
      "grade": "7.1",
      "phonetic": "/əˈkrɒs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "prep. & adv.",
      "serialNumber": "100"
    },
    {
      "word": "across from",
      "meaning": "在对面",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "101"
    },
    {
      "word": "field",
      "meaning": "场地；田地",
      "grade": "7.1",
      "phonetic": "/fiːld/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "102"
    },
    {
      "word": "sports field",
      "meaning": "运动场",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "103"
    },
    {
      "word": "gym",
      "meaning": "体育馆；健身房；（尤指学校的）体育活动",
      "grade": "7.1",
      "phonetic": "/dʒɪm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "104"
    },
    {
      "word": "office",
      "meaning": "办公室",
      "grade": "7.1",
      "phonetic": "/ˈɒfɪs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "105"
    },
    {
      "word": "large",
      "meaning": "大的；大号的",
      "grade": "7.1",
      "phonetic": "/lɑːdʒ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "106"
    },
    {
      "word": "special",
      "meaning": "特别的；特殊的",
      "grade": "7.1",
      "phonetic": "/ˈspeʃl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "107"
    },
    {
      "word": "smart",
      "meaning": "智能的；聪明的",
      "grade": "7.1",
      "phonetic": "/smɑːt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "108"
    },
    {
      "word": "whiteboard",
      "meaning": "白板；白色书写板",
      "grade": "7.1",
      "phonetic": "/ˈwaɪtbɔːd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "109"
    },
    {
      "word": "put up",
      "meaning": "张贴；搭建",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "动词",
      "serialNumber": "110"
    },
    {
      "word": "important",
      "meaning": "重要的",
      "grade": "7.1",
      "phonetic": "/ɪmˈpɔːtnt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "111"
    },
    {
      "word": "notice",
      "meaning": "通知；注意；注意到；意识到",
      "grade": "7.1",
      "phonetic": "/ˈnəʊtɪs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & v.",
      "serialNumber": "112"
    },
    {
      "word": "locker",
      "meaning": "有锁存物柜；寄物柜",
      "grade": "7.1",
      "phonetic": "/ˈlɒkə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "113"
    },
    {
      "word": "drawer",
      "meaning": "抽屉",
      "grade": "7.1",
      "phonetic": "/drɔː(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "114"
    },
    {
      "word": "at the back (of)",
      "meaning": "在（……）后面",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "介词",
      "serialNumber": "115"
    },
    {
      "word": "corner",
      "meaning": "角；墙角；街角",
      "grade": "7.1",
      "phonetic": "/ˈkɔːnə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "116"
    },
    {
      "word": "bookcase",
      "meaning": "书架；书柜",
      "grade": "7.1",
      "phonetic": "/ˈbʊkkeɪs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "117"
    },
    {
      "word": "screen",
      "meaning": "屏幕；银幕",
      "grade": "7.1",
      "phonetic": "/skriːn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "118"
    },
    {
      "word": "at school",
      "meaning": "在学校",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "介词短语",
      "serialNumber": "119"
    },
    {
      "word": "modern",
      "meaning": "现代的；当代的",
      "grade": "7.1",
      "phonetic": "/ˈmɒdn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "120"
    },
    {
      "word": "do exercises",
      "meaning": "做体操",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "121"
    },
    {
      "word": "amazing",
      "meaning": "令人惊奇（惊喜或惊叹）的",
      "grade": "7.1",
      "phonetic": "/əˈmeɪzɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "122"
    },
    {
      "word": "raise",
      "meaning": "使升高；提高",
      "grade": "7.1",
      "phonetic": "/reɪz/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "123"
    },
    {
      "word": "flag",
      "meaning": "旗；旗帜",
      "grade": "7.1",
      "phonetic": "/flæɡ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "124"
    },
    {
      "word": "most",
      "meaning": "大多数；最多；最大；最",
      "grade": "7.1",
      "phonetic": "/məʊst/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj. & pron.,adv.",
      "serialNumber": "125"
    },
    {
      "word": "change",
      "meaning": "改变；变化",
      "grade": "7.1",
      "phonetic": "/tʃeɪndʒ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "126"
    },
    {
      "word": "seat",
      "meaning": "座位",
      "grade": "7.1",
      "phonetic": "/siːt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "127"
    },
    {
      "word": "delicious",
      "meaning": "美味的；可口的",
      "grade": "7.1",
      "phonetic": "/dɪˈlɪʃəs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "128"
    },
    {
      "word": "How about",
      "meaning": "……怎么样；如何",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "129"
    },
    {
      "word": "yours",
      "meaning": "(通常写作Yours) 你的；您的",
      "grade": "7.1",
      "phonetic": "/jɔːz/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "pron.",
      "serialNumber": "130"
    },
    {
      "word": "similar",
      "meaning": "类似的；相像的",
      "grade": "7.1",
      "phonetic": "/ˈsɪmələ(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "131"
    },
    {
      "word": "similar to",
      "meaning": "类似的；相像的",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "132"
    },
    {
      "word": "sound",
      "meaning": "听起来；好像 声音；响声",
      "grade": "7.1",
      "phonetic": "/saʊnd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "133"
    },
    {
      "word": "bye for now",
      "meaning": "再见",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "",
      "serialNumber": "134"
    },
    {
      "word": "biology",
      "meaning": "生物学",
      "grade": "7.1",
      "phonetic": "/baɪˈɒlədʒi/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "135"
    },
    {
      "word": "IT",
      "meaning": "信息技术",
      "grade": "7.1",
      "phonetic": "/ˌaɪ ˈtiː/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "abbr.",
      "serialNumber": "136"
    },
    {
      "word": "geography",
      "meaning": "地理（学）",
      "grade": "7.1",
      "phonetic": "/dʒiˈɒɡrəfi/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "137"
    },
    {
      "word": "history",
      "meaning": "历史；历史课",
      "grade": "7.1",
      "phonetic": "/ˈhɪstri/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "138"
    },
    {
      "word": "boring",
      "meaning": "乏味的；令人生厌的",
      "grade": "7.1",
      "phonetic": "/ˈbɔːrɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "139"
    },
    {
      "word": "useful",
      "meaning": "有用的；有益的",
      "grade": "7.1",
      "phonetic": "/ˈjuːsfl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "140"
    },
    {
      "word": "exciting",
      "meaning": "令人激动的；使人兴奋的",
      "grade": "7.1",
      "phonetic": "/ɪkˈsaɪtɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "141"
    },
    {
      "word": "past",
      "meaning": "过去；过去的事情；过去的；在……之后",
      "grade": "7.1",
      "phonetic": "/pɑːst/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & adj. & prep.",
      "serialNumber": "142"
    },
    {
      "word": "good with",
      "meaning": "灵巧的；善于应付……的",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "143"
    },
    {
      "word": "number",
      "meaning": "数字；号码",
      "grade": "7.1",
      "phonetic": "/ˈnʌmbə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "144"
    },
    {
      "word": "help sb with",
      "meaning": "帮助某人做（某事）",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "145"
    },
    {
      "word": "reason",
      "meaning": "原因；理由",
      "grade": "7.1",
      "phonetic": "/ˈriːzn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "146"
    },
    {
      "word": "listen to",
      "meaning": "听；倾听",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "147"
    },
    {
      "word": "good at",
      "meaning": "擅长",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "148"
    },
    {
      "word": "remember",
      "meaning": "记住；记起",
      "grade": "7.1",
      "phonetic": "/rɪˈmembə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "149"
    },
    {
      "word": "everyone",
      "meaning": "每人；所有人",
      "grade": "7.1",
      "phonetic": "/ˈevriwʌn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "pron.",
      "serialNumber": "150"
    },
    {
      "word": "as",
      "meaning": "如同；作为 当……时；由于",
      "grade": "7.1",
      "phonetic": "/æz; əz/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "prep. & conj.",
      "serialNumber": "151"
    },
    {
      "word": "AM",
      "meaning": "上午",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "152"
    },
    {
      "word": "PM",
      "meaning": "下午；午后",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "153"
    },
    {
      "word": "French",
      "meaning": "法语；法国的；法国人的",
      "grade": "7.1",
      "phonetic": "/frentʃ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.、adj.",
      "serialNumber": "154"
    },
    {
      "word": "excellent",
      "meaning": "优秀的；极好的",
      "grade": "7.1",
      "phonetic": "/ˈeksələnt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "155"
    },
    {
      "word": "instrument",
      "meaning": "器械；工具",
      "grade": "7.1",
      "phonetic": "/ˈɪnstrəmənt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "156"
    },
    {
      "word": "singer",
      "meaning": "歌手",
      "grade": "7.1",
      "phonetic": "/ˈsɪŋə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "157"
    },
    {
      "word": "future",
      "meaning": "将来；未来",
      "grade": "7.1",
      "phonetic": "/ˈfjuːtʃə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "158"
    },
    {
      "word": "in the future",
      "meaning": "将来；未来",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "159"
    },
    {
      "word": "term",
      "meaning": "学期",
      "grade": "7.1",
      "phonetic": "/tɜːm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "160"
    },
    {
      "word": "work out",
      "meaning": "计算出；解决",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "161"
    },
    {
      "word": "problem",
      "meaning": "难题；困难",
      "grade": "7.1",
      "phonetic": "/ˈprɒbləm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "162"
    },
    {
      "word": "in class",
      "meaning": "课堂上",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "163"
    },
    {
      "word": "magic",
      "meaning": "魔法；魔力；魔术",
      "grade": "7.1",
      "phonetic": "/ˈmædʒɪk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "164"
    },
    {
      "word": "life",
      "meaning": "生活；生命",
      "grade": "7.1",
      "phonetic": "/laɪf/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "165"
    },
    {
      "word": "scientist",
      "meaning": "科学家",
      "grade": "7.1",
      "phonetic": "/ˈsaɪəntɪst/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "166"
    },
    {
      "word": "club",
      "meaning": "俱乐部；社团",
      "grade": "7.1",
      "phonetic": "/klʌb/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "167"
    },
    {
      "word": "join",
      "meaning": "参加；加入",
      "grade": "7.1",
      "phonetic": "/dʒɔɪn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "168"
    },
    {
      "word": "choose",
      "meaning": "选择；挑选",
      "grade": "7.1",
      "phonetic": "/tʃuːz/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "169"
    },
    {
      "word": "drama",
      "meaning": "戏剧；戏剧表演",
      "grade": "7.1",
      "phonetic": "/ˈdrɑːmə/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "170"
    },
    {
      "word": "play Chinese chess",
      "meaning": "下中国象棋",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "171"
    },
    {
      "word": "feeling",
      "meaning": "感觉；情感",
      "grade": "7.1",
      "phonetic": "/ˈfiːlɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "172"
    },
    {
      "word": "news",
      "meaning": "消息；新闻",
      "grade": "7.1",
      "phonetic": "/njuːz/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "173"
    },
    {
      "word": "musical",
      "meaning": "音乐的；有音乐天赋的",
      "grade": "7.1",
      "phonetic": "/ˈmjuːzɪkəl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "174"
    },
    {
      "word": "musical instrument",
      "meaning": "乐器",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "175"
    },
    {
      "word": "exactly",
      "meaning": "正是如此；准确地",
      "grade": "7.1",
      "phonetic": "/ɪɡˈzæktli/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "176"
    },
    {
      "word": "drum",
      "meaning": "鼓",
      "grade": "7.1",
      "phonetic": "/drʌm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "177"
    },
    {
      "word": "ability",
      "meaning": "能力；才能",
      "grade": "7.1",
      "phonetic": "/əˈbɪləti/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "178"
    },
    {
      "word": "paint",
      "meaning": "用颜料画；在……上刷油漆；油漆；涂料",
      "grade": "7.1",
      "phonetic": "/peɪnt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "179"
    },
    {
      "word": "climb",
      "meaning": "攀登；爬",
      "grade": "7.1",
      "phonetic": "/klaɪm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "180"
    },
    {
      "word": "more",
      "meaning": "更多（的）",
      "grade": "7.1",
      "phonetic": "/mɔː(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj. & pron.",
      "serialNumber": "181"
    },
    {
      "word": "act",
      "meaning": "扮演；行动；（戏剧等）一幕",
      "grade": "7.1",
      "phonetic": "/ækt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.；n.",
      "serialNumber": "182"
    },
    {
      "word": "act out",
      "meaning": "表演",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "183"
    },
    {
      "word": "at home",
      "meaning": "在家里",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "184"
    },
    {
      "word": "interested",
      "meaning": "感兴趣的",
      "grade": "7.1",
      "phonetic": "/ˈɪntrəstɪd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "185"
    },
    {
      "word": "interested in",
      "meaning": "对……感兴趣",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "186"
    },
    {
      "word": "nature",
      "meaning": "自然界；大自然",
      "grade": "7.1",
      "phonetic": "/ˈneɪtʃə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "187"
    },
    {
      "word": "beef",
      "meaning": "牛肉",
      "grade": "7.1",
      "phonetic": "/biːf/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "188"
    },
    {
      "word": "soon",
      "meaning": "不久；很快",
      "grade": "7.1",
      "phonetic": "/suːn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "189"
    },
    {
      "word": "than",
      "meaning": "（用以引出比较的第二部分）比",
      "grade": "7.1",
      "phonetic": "/ðæn; ðən/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "prep. & conj.",
      "serialNumber": "190"
    },
    {
      "word": "more than",
      "meaning": "多于",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "191"
    },
    {
      "word": "mind",
      "meaning": "头脑；心思",
      "grade": "7.1",
      "phonetic": "/maɪnd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "192"
    },
    {
      "word": "fall",
      "meaning": "进入；掉落；跌倒 n.（美式）秋天",
      "grade": "7.1",
      "phonetic": "/fɔːl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "193"
    },
    {
      "word": "fall in love with",
      "meaning": "爱上……",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "194"
    },
    {
      "word": "take photos / take a photo",
      "meaning": "拍照",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "195"
    },
    {
      "word": "collect",
      "meaning": "收集；采集",
      "grade": "7.1",
      "phonetic": "/kəˈlekt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "196"
    },
    {
      "word": "discover",
      "meaning": "发现；发觉",
      "grade": "7.1",
      "phonetic": "/dɪˈskʌvə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "197"
    },
    {
      "word": "wildlife",
      "meaning": "野生动物；野生生物",
      "grade": "7.1",
      "phonetic": "/ˈwaɪldlaɪf/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "198"
    },
    {
      "word": "make use of",
      "meaning": "使用……；利用……",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "199"
    },
    {
      "word": "shower",
      "meaning": "淋浴；淋浴器 v. 洗淋浴",
      "grade": "7.1",
      "phonetic": "/ˈʃaʊə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & v.",
      "serialNumber": "200"
    },
    {
      "word": "take a shower",
      "meaning": "淋浴",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "201"
    },
    {
      "word": "get dressed",
      "meaning": "穿衣服",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "202"
    },
    {
      "word": "brush",
      "meaning": "（用刷子）刷；刷子；画笔",
      "grade": "7.1",
      "phonetic": "/brʌʃ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.；n.",
      "serialNumber": "203"
    },
    {
      "word": "tooth",
      "meaning": "（pl. teeth）牙齿",
      "grade": "7.1",
      "phonetic": "/tuːθ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "204"
    },
    {
      "word": "duty",
      "meaning": "值班；职责",
      "grade": "7.1",
      "phonetic": "/ˈdjuːti/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "205"
    },
    {
      "word": "on duty",
      "meaning": "值班",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "206"
    },
    {
      "word": "usually",
      "meaning": "通常地；一般地",
      "grade": "7.1",
      "phonetic": "/ˈjuːʒuəli/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "207"
    },
    {
      "word": "get up",
      "meaning": "起床；站起",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "208"
    },
    {
      "word": "reporter",
      "meaning": "记者",
      "grade": "7.1",
      "phonetic": "/rɪˈpɔːtə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "209"
    },
    {
      "word": "around",
      "meaning": "大约；环绕；到处",
      "grade": "7.1",
      "phonetic": "/əˈraʊnd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "prep. & adv.",
      "serialNumber": "210"
    },
    {
      "word": "homework",
      "meaning": "家庭作业",
      "grade": "7.1",
      "phonetic": "/ˈhəʊmwɜːk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "211"
    },
    {
      "word": "go to bed",
      "meaning": "上床睡觉",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "212"
    },
    {
      "word": "saying",
      "meaning": "谚语；格言",
      "grade": "7.1",
      "phonetic": "/ˈseɪɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "213"
    },
    {
      "word": "rise",
      "meaning": "起床；升起；增长",
      "grade": "7.1",
      "phonetic": "/raɪz/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "214"
    },
    {
      "word": "stay",
      "meaning": "停留；待",
      "grade": "7.1",
      "phonetic": "/steɪ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "215"
    },
    {
      "word": "routine",
      "meaning": "常规",
      "grade": "7.1",
      "phonetic": "/ruːˈtiːn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "216"
    },
    {
      "word": "restaurant",
      "meaning": "餐馆；餐厅",
      "grade": "7.1",
      "phonetic": "/ˈrestrɒnt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "217"
    },
    {
      "word": "housework",
      "meaning": "家务劳动",
      "grade": "7.1",
      "phonetic": "/ˈhaʊswɜːk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "218"
    },
    {
      "word": "while",
      "meaning": "一段时间；一会儿 在……期间；当……的时候",
      "grade": "7.1",
      "phonetic": "/waɪl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.conj.",
      "serialNumber": "219"
    },
    {
      "word": "weekend",
      "meaning": "周末",
      "grade": "7.1",
      "phonetic": "/ˌwiːkˈend/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "220"
    },
    {
      "word": "daily",
      "meaning": "每日的；日常的",
      "grade": "7.1",
      "phonetic": "/ˈdeɪli/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "221"
    },
    {
      "word": "daily routine",
      "meaning": "日常生活",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "222"
    },
    {
      "word": "only",
      "meaning": "只；仅",
      "grade": "7.1",
      "phonetic": "/ˈəʊnli/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "223"
    },
    {
      "word": "break",
      "meaning": "休息；间断；(使) 破碎；损坏",
      "grade": "7.1",
      "phonetic": "/breɪk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & v.",
      "serialNumber": "224"
    },
    {
      "word": "Finnish",
      "meaning": "芬兰语；芬兰的；芬兰人的；芬兰语的",
      "grade": "7.1",
      "phonetic": "/ˈfɪnɪʃ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & adj.",
      "serialNumber": "225"
    },
    {
      "word": "finish",
      "meaning": "结束；完成",
      "grade": "7.1",
      "phonetic": "/ˈfɪnɪʃ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "226"
    },
    {
      "word": "hockey",
      "meaning": "曲棍球",
      "grade": "7.1",
      "phonetic": "/ˈhɒki/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "227"
    },
    {
      "word": "ice hockey",
      "meaning": "冰球运动；冰上曲棍球",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "228"
    },
    {
      "word": "already",
      "meaning": "已经；早已",
      "grade": "7.1",
      "phonetic": "/ɔːlˈredi/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.",
      "serialNumber": "229"
    },
    {
      "word": "dark",
      "meaning": "昏暗的；深色的",
      "grade": "7.1",
      "phonetic": "/dɑːk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "230"
    },
    {
      "word": "outside",
      "meaning": "在外面；外面的；在……外面",
      "grade": "7.1",
      "phonetic": "/ˌaʊtˈsaɪd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv.、adj.、prep.",
      "serialNumber": "231"
    },
    {
      "word": "prepare",
      "meaning": "把……预备好；准备",
      "grade": "7.1",
      "phonetic": "/prɪˈpeə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "232"
    },
    {
      "word": "home economics",
      "meaning": "家事经济",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "233"
    },
    {
      "word": "celebrate",
      "meaning": "庆祝；庆贺",
      "grade": "7.1",
      "phonetic": "/ˈselɪbreɪt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "234"
    },
    {
      "word": "surprise",
      "meaning": "惊奇；惊讶；使感到意外",
      "grade": "7.1",
      "phonetic": "/səˈpraɪz/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.、v.",
      "serialNumber": "235"
    },
    {
      "word": "something",
      "meaning": "某事；某物",
      "grade": "7.1",
      "phonetic": "/ˈsʌmθɪŋ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "pron.",
      "serialNumber": "236"
    },
    {
      "word": "sale",
      "meaning": "出售；销售",
      "grade": "7.1",
      "phonetic": "/seɪl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "237"
    },
    {
      "word": "kilo",
      "meaning": "千克；公斤",
      "grade": "7.1",
      "phonetic": "/ˈkiːləʊ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "238"
    },
    {
      "word": "yogurt",
      "meaning": "酸奶",
      "grade": "7.1",
      "phonetic": "/ˈjɒɡət/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "239"
    },
    {
      "word": "total",
      "meaning": "总数；合计 总的；全体的",
      "grade": "7.1",
      "phonetic": "/ˈtəʊtl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n. & adj.",
      "serialNumber": "240"
    },
    {
      "word": "price",
      "meaning": "价格",
      "grade": "7.1",
      "phonetic": "/praɪs/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "241"
    },
    {
      "word": "balloon",
      "meaning": "气球",
      "grade": "7.1",
      "phonetic": "/bəˈluːn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "242"
    },
    {
      "word": "chocolate",
      "meaning": "巧克力",
      "grade": "7.1",
      "phonetic": "/ˈtʃɒklət/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "243"
    },
    {
      "word": "pizza",
      "meaning": "比萨饼",
      "grade": "7.1",
      "phonetic": "/ˈpiːtsə/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "244"
    },
    {
      "word": "list",
      "meaning": "列表；列清单 名单；清单",
      "grade": "7.1",
      "phonetic": "/lɪst/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "245"
    },
    {
      "word": "own",
      "meaning": "自己的；本人的",
      "grade": "7.1",
      "phonetic": "/əʊn/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj. & pron.",
      "serialNumber": "246"
    },
    {
      "word": "example",
      "meaning": "例子；范例",
      "grade": "7.1",
      "phonetic": "/ɪɡˈzɑːmpl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "247"
    },
    {
      "word": "for example",
      "meaning": "例如",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "248"
    },
    {
      "word": "language",
      "meaning": "语言",
      "grade": "7.1",
      "phonetic": "/ˈlæŋɡwɪdʒ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "249"
    },
    {
      "word": "international",
      "meaning": "国际的",
      "grade": "7.1",
      "phonetic": "/ˌɪntəˈnæʃnəl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "250"
    },
    {
      "word": "mark",
      "meaning": "做记号；纪念；打分；记号",
      "grade": "7.1",
      "phonetic": "/mɑːk/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v. & n.",
      "serialNumber": "251"
    },
    {
      "word": "date",
      "meaning": "日期；日子",
      "grade": "7.1",
      "phonetic": "/deɪt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "252"
    },
    {
      "word": "national",
      "meaning": "国家的；民族的",
      "grade": "7.1",
      "phonetic": "/ˈnæʃnəl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "253"
    },
    {
      "word": "found",
      "meaning": "创建；创立",
      "grade": "7.1",
      "phonetic": "/faʊnd/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "254"
    },
    {
      "word": "meaningful",
      "meaning": "重要的；重大的",
      "grade": "7.1",
      "phonetic": "/ˈmiːnɪŋfl/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adj.",
      "serialNumber": "255"
    },
    {
      "word": "make a wish",
      "meaning": "许愿",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "256"
    },
    {
      "word": "village",
      "meaning": "村庄；村镇",
      "grade": "7.1",
      "phonetic": "/ˈvɪlɪdʒ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "257"
    },
    {
      "word": "grow",
      "meaning": "成长；长大；增长",
      "grade": "7.1",
      "phonetic": "/ɡrəʊ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "258"
    },
    {
      "word": "blow",
      "meaning": "吹；刮",
      "grade": "7.1",
      "phonetic": "/bləʊ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "259"
    },
    {
      "word": "blow out",
      "meaning": "吹灭",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "260"
    },
    {
      "word": "enjoy",
      "meaning": "享受……的乐趣；喜欢",
      "grade": "7.1",
      "phonetic": "/ɪnˈdʒɔɪ/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "v.",
      "serialNumber": "261"
    },
    {
      "word": "height",
      "meaning": "身高；高度",
      "grade": "7.1",
      "phonetic": "/haɪt/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "n.",
      "serialNumber": "262"
    },
    {
      "word": "later",
      "meaning": "以后（的）；后来（的）",
      "grade": "7.1",
      "phonetic": "/ˈleɪtə(r)/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "adv. & adj.",
      "serialNumber": "263"
    },
    {
      "word": "next time",
      "meaning": "下次",
      "grade": "7.1",
      "phonetic": "",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "短语",
      "serialNumber": "264"
    },
    {
      "word": "whom",
      "meaning": "谁；什么人",
      "grade": "7.1",
      "phonetic": "/huːm/",
      "highlightLetters": "",
      "highlightPhonetic": "",
      "note": "",
      "partOfSpeech": "pron.",
      "serialNumber": "265"
    }
  ]
};
