// 自动生成的JS模块 - grade6_1.json
// 生成时间: 2025-12-21T01:03:40.390Z

module.exports = {
  "grade": 6,
  "semester": 1,
  "gradeName": "小学六年级上册",
  "total": 302,
  "lastUpdated": "2025-12-21T00:51:03.395Z",
  "words": [
    {
      "word": "chase",
      "meaning": "追赶",
      "grade": "6.1",
      "phonetic": "/tʃeɪs/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "1"
    },
    {
      "word": "gave",
      "meaning": "（give 的过去式）提供；交给",
      "grade": "6.1",
      "phonetic": "/ɡeɪv/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "2"
    },
    {
      "word": "plane",
      "meaning": "飞机",
      "grade": "6.1",
      "phonetic": "/pleɪn/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "3"
    },
    {
      "word": "space",
      "meaning": "太空",
      "grade": "6.1",
      "phonetic": "/speɪs/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "4"
    },
    {
      "word": "take",
      "meaning": "取走，拿走",
      "grade": "6.1",
      "phonetic": "/teik/",
      "highlightLetters": "a,e",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "5"
    },
    {
      "word": "feel",
      "meaning": "觉得；感到",
      "grade": "6.1",
      "phonetic": "/fiːl/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "动",
      "serialNumber": "6"
    },
    {
      "word": "street",
      "meaning": "大街；街道",
      "grade": "6.1",
      "phonetic": "/striːt/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "7"
    },
    {
      "word": "sea",
      "meaning": "大海",
      "grade": "6.1",
      "phonetic": "/siː/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "8"
    },
    {
      "word": "feature",
      "meaning": "特点",
      "grade": "6.1",
      "phonetic": "/ˈfiːtʃə(r)/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读/iː/",
      "partOfSpeech": "名",
      "serialNumber": "9"
    },
    {
      "word": "by",
      "meaning": "（表示方式）乘",
      "grade": "6.1",
      "phonetic": "/baɪ/",
      "highlightLetters": "y",
      "highlightPhonetic": "/aɪ/",
      "note": "y词尾重读/aɪ/",
      "partOfSpeech": "介",
      "serialNumber": "10"
    },
    {
      "word": "mice",
      "meaning": "（mouse 的复数）老鼠",
      "grade": "6.1",
      "phonetic": "/maɪs/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "11"
    },
    {
      "word": "price",
      "meaning": "价格",
      "grade": "6.1",
      "phonetic": "/praɪs/",
      "highlightLetters": "i,e",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "12"
    },
    {
      "word": "type",
      "meaning": "打字",
      "grade": "6.1",
      "phonetic": "/taɪp/",
      "highlightLetters": "y,e",
      "highlightPhonetic": "/aɪ/",
      "note": "y重读/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "13"
    },
    {
      "word": "coach",
      "meaning": "教练",
      "grade": "6.1",
      "phonetic": "/kəʊtʃ/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "14"
    },
    {
      "word": "goal",
      "meaning": "射门",
      "grade": "6.1",
      "phonetic": "/ɡəʊl/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读字母音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "15"
    },
    {
      "word": "use",
      "meaning": "使用",
      "grade": "6.1",
      "phonetic": "/juːz/",
      "highlightLetters": "u,e",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "动",
      "serialNumber": "16"
    },
    {
      "word": "Munich",
      "meaning": "慕尼黑（德国城市）",
      "grade": "6.1",
      "phonetic": "/ˈmjuːnɪk/",
      "highlightLetters": "u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "17"
    },
    {
      "word": "museum",
      "meaning": "博物馆",
      "grade": "6.1",
      "phonetic": "/mjuːˈziːəm/",
      "highlightLetters": "第1个u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "18"
    },
    {
      "word": "university",
      "meaning": "大学",
      "grade": "6.1",
      "phonetic": "/ˌjuːnɪˈvɜːsəti/",
      "highlightLetters": "u",
      "highlightPhonetic": "/juː/",
      "note": "u读字母音/juː/",
      "partOfSpeech": "名",
      "serialNumber": "19"
    },
    {
      "word": "ant",
      "meaning": "蚂蚁",
      "grade": "6.1",
      "phonetic": "/ænt/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "20"
    },
    {
      "word": "bad",
      "meaning": "邪恶的；坏的",
      "grade": "6.1",
      "phonetic": "/bæd/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "21"
    },
    {
      "word": "sad",
      "meaning": "难过的",
      "grade": "6.1",
      "phonetic": "/sæd/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "22"
    },
    {
      "word": "shall",
      "meaning": "表示征求意见",
      "grade": "6.1",
      "phonetic": "/ʃæl/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "动",
      "serialNumber": "23"
    },
    {
      "word": "angry",
      "meaning": "生气的",
      "grade": "6.1",
      "phonetic": "/ˈæŋɡri/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "24"
    },
    {
      "word": "happy",
      "meaning": "高兴的",
      "grade": "6.1",
      "phonetic": "/ˈhæpi/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "25"
    },
    {
      "word": "taxi",
      "meaning": "出租汽车",
      "grade": "6.1",
      "phonetic": "/ˈtæksi/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "26"
    },
    {
      "word": "traffic",
      "meaning": "交通",
      "grade": "6.1",
      "phonetic": "/ˈtræfɪk/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "27"
    },
    {
      "word": "travel",
      "meaning": "（尤指长途）旅行",
      "grade": "6.1",
      "phonetic": "/ˈtrævl/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "28"
    },
    {
      "word": "Alaska",
      "meaning": "阿拉斯加州（美国州名）",
      "grade": "6.1",
      "phonetic": "/əˈlæskə/",
      "highlightLetters": "第2个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "29"
    },
    {
      "word": "Canberra",
      "meaning": "堪培拉（澳大利亚首都）",
      "grade": "6.1",
      "phonetic": "/ˈkænbərə/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "30"
    },
    {
      "word": "factory",
      "meaning": "工厂",
      "grade": "6.1",
      "phonetic": "/ˈfæktri/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "31"
    },
    {
      "word": "Italian",
      "meaning": "意大利的",
      "grade": "6.1",
      "phonetic": "/ɪˈtæliən/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "形",
      "serialNumber": "32"
    },
    {
      "word": "jasmine",
      "meaning": "茉莉",
      "grade": "6.1",
      "phonetic": "/ˈdʒæzmɪn/",
      "highlightLetters": "a",
      "highlightPhonetic": "/æ/",
      "note": "a读短音/æ/",
      "partOfSpeech": "名",
      "serialNumber": "33"
    },
    {
      "word": "get",
      "meaning": "到达",
      "grade": "6.1",
      "phonetic": "/ɡet/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "34"
    },
    {
      "word": "left",
      "meaning": "左边（的）",
      "grade": "6.1",
      "phonetic": "/left/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名;形",
      "serialNumber": "35"
    },
    {
      "word": "sled",
      "meaning": "雪橇",
      "grade": "6.1",
      "phonetic": "/sled/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "36"
    },
    {
      "word": "tell",
      "meaning": "告诉",
      "grade": "6.1",
      "phonetic": "/tel/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "动",
      "serialNumber": "37"
    },
    {
      "word": "well",
      "meaning": "健康的；身体好的",
      "grade": "6.1",
      "phonetic": "/wel/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "形",
      "serialNumber": "38"
    },
    {
      "word": "ferry",
      "meaning": "轮渡",
      "grade": "6.1",
      "phonetic": "/ˈferi/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "39"
    },
    {
      "word": "helmet",
      "meaning": "头盔",
      "grade": "6.1",
      "phonetic": "/ˈhelmɪt/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "40"
    },
    {
      "word": "lesson",
      "meaning": "课",
      "grade": "6.1",
      "phonetic": "/ˈlesn/",
      "highlightLetters": "e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "41"
    },
    {
      "word": "everyone",
      "meaning": "每人",
      "grade": "6.1",
      "phonetic": "/ˈevriwʌn/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "代",
      "serialNumber": "42"
    },
    {
      "word": "festival",
      "meaning": "节日",
      "grade": "6.1",
      "phonetic": "/ˈfestɪvl/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "43"
    },
    {
      "word": "secretary",
      "meaning": "秘书",
      "grade": "6.1",
      "phonetic": "/ˈsekrətri/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "44"
    },
    {
      "word": "together",
      "meaning": "一起",
      "grade": "6.1",
      "phonetic": "/təˈɡeðə(r)/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/e/",
      "note": "e读短音/e/",
      "partOfSpeech": "副",
      "serialNumber": "45"
    },
    {
      "word": "head",
      "meaning": "头",
      "grade": "6.1",
      "phonetic": "/hed/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "46"
    },
    {
      "word": "breath",
      "meaning": "呼吸",
      "grade": "6.1",
      "phonetic": "/breθ/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/e/",
      "note": "ea读短音/e/",
      "partOfSpeech": "名",
      "serialNumber": "47"
    },
    {
      "word": "if",
      "meaning": "如果",
      "grade": "6.1",
      "phonetic": "/ɪf/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "连",
      "serialNumber": "48"
    },
    {
      "word": "ill",
      "meaning": "有病；不舒服",
      "grade": "6.1",
      "phonetic": "/ɪl/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "49"
    },
    {
      "word": "film",
      "meaning": "电影",
      "grade": "6.1",
      "phonetic": "/fɪlm/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "50"
    },
    {
      "word": "ship",
      "meaning": "（大）船",
      "grade": "6.1",
      "phonetic": "/ʃɪp/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "51"
    },
    {
      "word": "sit",
      "meaning": "坐",
      "grade": "6.1",
      "phonetic": "/sɪt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "52"
    },
    {
      "word": "trip",
      "meaning": "旅行",
      "grade": "6.1",
      "phonetic": "/trɪp/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "53"
    },
    {
      "word": "visit",
      "meaning": "拜访",
      "grade": "6.1",
      "phonetic": "/ˈvɪzɪt/",
      "highlightLetters": "第1个i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "54"
    },
    {
      "word": "quickly",
      "meaning": "迅速地",
      "grade": "6.1",
      "phonetic": "/ˈkwɪkli/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "副",
      "serialNumber": "55"
    },
    {
      "word": "cinema",
      "meaning": "电影院",
      "grade": "6.1",
      "phonetic": "/ˈsɪnəmə/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "56"
    },
    {
      "word": "dictionary",
      "meaning": "词典",
      "grade": "6.1",
      "phonetic": "/ˈdɪkʃənri/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "57"
    },
    {
      "word": "fisherman",
      "meaning": "渔民",
      "grade": "6.1",
      "phonetic": "/ˈfɪʃəmən/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "58"
    },
    {
      "word": "interesting",
      "meaning": "有趣的",
      "grade": "6.1",
      "phonetic": "/ˈɪntrəstɪŋ/",
      "highlightLetters": "第1个i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "形",
      "serialNumber": "59"
    },
    {
      "word": "businessman",
      "meaning": "商人；企业家",
      "grade": "6.1",
      "phonetic": "/ˈbɪznəsmæn/",
      "highlightLetters": "i",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "60"
    },
    {
      "word": "gym",
      "meaning": "体育馆",
      "grade": "6.1",
      "phonetic": "/dʒɪm/",
      "highlightLetters": "y",
      "highlightPhonetic": "/ɪ/",
      "note": "y读短音/ɪ /",
      "partOfSpeech": "名",
      "serialNumber": "61"
    },
    {
      "word": "build",
      "meaning": "建造；建设",
      "grade": "6.1",
      "phonetic": "/bild/",
      "highlightLetters": "ui",
      "highlightPhonetic": "/ɪ/",
      "note": "i读短音/ɪ /",
      "partOfSpeech": "动",
      "serialNumber": "62"
    },
    {
      "word": "stop",
      "meaning": "停下",
      "grade": "6.1",
      "phonetic": "/stɒp/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "动",
      "serialNumber": "63"
    },
    {
      "word": "wrong",
      "meaning": "有毛病",
      "grade": "6.1",
      "phonetic": "/rɒŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "64"
    },
    {
      "word": "comic",
      "meaning": "滑稽的",
      "grade": "6.1",
      "phonetic": "/ˈkɒmɪk/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "形",
      "serialNumber": "65"
    },
    {
      "word": "crossing",
      "meaning": "十字路口",
      "grade": "6.1",
      "phonetic": "/ˈkrɒsɪŋ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "66"
    },
    {
      "word": "follow",
      "meaning": "跟着",
      "grade": "6.1",
      "phonetic": "/ˈfɒləʊ/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "动",
      "serialNumber": "67"
    },
    {
      "word": "hobby",
      "meaning": "业余爱好",
      "grade": "6.1",
      "phonetic": "/ˈhɒbi/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "68"
    },
    {
      "word": "office",
      "meaning": "办公室",
      "grade": "6.1",
      "phonetic": "/ˌɒfɪs/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "69"
    },
    {
      "word": "Scotland",
      "meaning": "苏格兰",
      "grade": "6.1",
      "phonetic": "/ˈskɒtlənd/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "70"
    },
    {
      "word": "hospital",
      "meaning": "医院",
      "grade": "6.1",
      "phonetic": "/ˈhɒspɪtl/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "71"
    },
    {
      "word": "tomorrow",
      "meaning": "明天",
      "grade": "6.1",
      "phonetic": "/təˈmɒrəʊ/",
      "highlightLetters": "第2个o",
      "highlightPhonetic": "/ɒ/",
      "note": "o读短音/ɒ /",
      "partOfSpeech": "名",
      "serialNumber": "72"
    },
    {
      "word": "bus",
      "meaning": "公共汽车",
      "grade": "6.1",
      "phonetic": "/bʌs/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "73"
    },
    {
      "word": "mud",
      "meaning": "泥",
      "grade": "6.1",
      "phonetic": "/mʌd/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "74"
    },
    {
      "word": "club",
      "meaning": "俱乐部",
      "grade": "6.1",
      "phonetic": "/klʌb/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "75"
    },
    {
      "word": "must",
      "meaning": "必须",
      "grade": "6.1",
      "phonetic": "/mʌst/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "76"
    },
    {
      "word": "stuck",
      "meaning": "陷住；无法移动",
      "grade": "6.1",
      "phonetic": "/stʌk/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "77"
    },
    {
      "word": "country",
      "meaning": "国家",
      "grade": "6.1",
      "phonetic": "/ˈkʌntri/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʌ/",
      "note": "ou读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "78"
    },
    {
      "word": "puzzle",
      "meaning": "谜",
      "grade": "6.1",
      "phonetic": "/ˈpʌzl/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "79"
    },
    {
      "word": "studies",
      "meaning": "（study 的第三人称单数形式）学习",
      "grade": "6.1",
      "phonetic": "/ˈstʌdiz/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "80"
    },
    {
      "word": "subway",
      "meaning": "地铁",
      "grade": "6.1",
      "phonetic": "/ˈsʌbweɪ/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʌ/",
      "note": "u读短音/ʌ /",
      "partOfSpeech": "名",
      "serialNumber": "81"
    },
    {
      "word": "worry",
      "meaning": "担心；担忧",
      "grade": "6.1",
      "phonetic": "/ˈwʌri/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ʌ/",
      "note": "o读短音/ʌ /",
      "partOfSpeech": "动",
      "serialNumber": "82"
    },
    {
      "word": "foot",
      "meaning": "脚",
      "grade": "6.1",
      "phonetic": "/ˈfʊt/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/ʊ/",
      "note": "oo读短音/ʊ /",
      "partOfSpeech": "名",
      "serialNumber": "83"
    },
    {
      "word": "pull",
      "meaning": "拉；拽",
      "grade": "6.1",
      "phonetic": "/pʊl/",
      "highlightLetters": "u",
      "highlightPhonetic": "/ʊ/",
      "note": "u读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "84"
    },
    {
      "word": "should",
      "meaning": "应该",
      "grade": "6.1",
      "phonetic": "/ʃʊd/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/ʊ/",
      "note": "ou读短音/ʊ /",
      "partOfSpeech": "动",
      "serialNumber": "85"
    },
    {
      "word": "ask",
      "meaning": "问",
      "grade": "6.1",
      "phonetic": "/ɑːsk/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "动",
      "serialNumber": "86"
    },
    {
      "word": "fast",
      "meaning": "快",
      "grade": "6.1",
      "phonetic": "/fɑːst/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "形",
      "serialNumber": "87"
    },
    {
      "word": "grass",
      "meaning": "草坪",
      "grade": "6.1",
      "phonetic": "/ɡrɑːs/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "88"
    },
    {
      "word": "half",
      "meaning": "一半",
      "grade": "6.1",
      "phonetic": "/hɑːf/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ɑː/",
      "note": "a读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "89"
    },
    {
      "word": "far",
      "meaning": "远的",
      "grade": "6.1",
      "phonetic": "/fɑː(r)/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "形",
      "serialNumber": "90"
    },
    {
      "word": "postcard",
      "meaning": "明信片",
      "grade": "6.1",
      "phonetic": "/ˈpəʊstkɑːd/",
      "highlightLetters": "ar",
      "highlightPhonetic": "/ɑː/",
      "note": "ar读长元音/ɑː/",
      "partOfSpeech": "名",
      "serialNumber": "91"
    },
    {
      "word": "reporter",
      "meaning": "记者",
      "grade": "6.1",
      "phonetic": "/rɪˈpɔːtə(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɔː/",
      "note": "or读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "92"
    },
    {
      "word": "bookstore",
      "meaning": "书店",
      "grade": "6.1",
      "phonetic": "/ˈbʊkstɔː(r)/",
      "highlightLetters": "ore",
      "highlightPhonetic": "/ɔː/",
      "note": "ore读长元音/ɔː/",
      "partOfSpeech": "名",
      "serialNumber": "93"
    },
    {
      "word": "more",
      "meaning": "更多的",
      "grade": "6.1",
      "phonetic": "/mɔː(r)/",
      "highlightLetters": "ore",
      "highlightPhonetic": "/ɔː/",
      "note": "ore读长元音/ɔː/",
      "partOfSpeech": "形",
      "serialNumber": "94"
    },
    {
      "word": "sir",
      "meaning": "（对男子的礼貌称呼）先生",
      "grade": "6.1",
      "phonetic": "/sɜː(r)/",
      "highlightLetters": "ir",
      "highlightPhonetic": "/ɜː/",
      "note": "ir重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "95"
    },
    {
      "word": "hurt",
      "meaning": "（使）受伤",
      "grade": "6.1",
      "phonetic": "/hɜːt/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "96"
    },
    {
      "word": "turn",
      "meaning": "转弯",
      "grade": "6.1",
      "phonetic": "/tɜːn/",
      "highlightLetters": "ur",
      "highlightPhonetic": "/ɜː/",
      "note": "ur读长元音/ɜː/",
      "partOfSpeech": "动",
      "serialNumber": "97"
    },
    {
      "word": "early",
      "meaning": "早到的",
      "grade": "6.1",
      "phonetic": "/ˈɜːli/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/ɜː/",
      "note": "ear重读长音/ɜː/",
      "partOfSpeech": "形",
      "serialNumber": "98"
    },
    {
      "word": "word",
      "meaning": "单词",
      "grade": "6.1",
      "phonetic": "/wɜːd/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɜː/",
      "note": "or重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "99"
    },
    {
      "word": "worker",
      "meaning": "工人",
      "grade": "6.1",
      "phonetic": "/ˈwɜːkə(r)/",
      "highlightLetters": "or",
      "highlightPhonetic": "/ɜː/",
      "note": "or重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "100"
    },
    {
      "word": "Germany",
      "meaning": "德国",
      "grade": "6.1",
      "phonetic": "/ˈdʒɜːməni/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ɜː/",
      "note": "er重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "101"
    },
    {
      "word": "university",
      "meaning": "大学",
      "grade": "6.1",
      "phonetic": "/ˌjuːnɪˈvɜːsəti/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ɜː/",
      "note": "er重读长音/ɜː/",
      "partOfSpeech": "名",
      "serialNumber": "102"
    },
    {
      "word": "deep",
      "meaning": "深的",
      "grade": "6.1",
      "phonetic": "/diːp/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "形",
      "serialNumber": "103"
    },
    {
      "word": "feel",
      "meaning": "觉得；感到",
      "grade": "6.1",
      "phonetic": "/fiːl/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "动",
      "serialNumber": "104"
    },
    {
      "word": "street",
      "meaning": "大街；街道",
      "grade": "6.1",
      "phonetic": "/striːt/",
      "highlightLetters": "ee",
      "highlightPhonetic": "/iː/",
      "note": "ee读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "105"
    },
    {
      "word": "pizza",
      "meaning": "比萨饼",
      "grade": "6.1",
      "phonetic": "/ˈpiːtsə/",
      "highlightLetters": "i",
      "highlightPhonetic": "/iː/",
      "note": "i读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "106"
    },
    {
      "word": "police",
      "meaning": "警方",
      "grade": "6.1",
      "phonetic": "/pəˈliːs /",
      "highlightLetters": "i",
      "highlightPhonetic": "/iː/",
      "note": "i读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "107"
    },
    {
      "word": "evening",
      "meaning": "晚上；傍晚",
      "grade": "6.1",
      "phonetic": "/ˈiːvnɪŋ/",
      "highlightLetters": "第1个e",
      "highlightPhonetic": "/iː/",
      "note": "e读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "108"
    },
    {
      "word": "museum",
      "meaning": "博物馆",
      "grade": "6.1",
      "phonetic": "/mjuːˈziːəm/",
      "highlightLetters": "e",
      "highlightPhonetic": "/iː/",
      "note": "e读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "109"
    },
    {
      "word": "feature",
      "meaning": "特点",
      "grade": "6.1",
      "phonetic": "/ˈfiːtʃə(r)/",
      "highlightLetters": "ea",
      "highlightPhonetic": "/iː/",
      "note": "ea读长元音/iː/",
      "partOfSpeech": "名",
      "serialNumber": "110"
    },
    {
      "word": "moon",
      "meaning": "月亮",
      "grade": "6.1",
      "phonetic": "/muːn/",
      "highlightLetters": "oo",
      "highlightPhonetic": "/uː/",
      "note": "oo读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "111"
    },
    {
      "word": "supermarket",
      "meaning": "超市",
      "grade": "6.1",
      "phonetic": "/ˈsuːpəmɑːkɪt/",
      "highlightLetters": "u",
      "highlightPhonetic": "/uː/",
      "note": "u读长元音/uː/",
      "partOfSpeech": "名",
      "serialNumber": "112"
    },
    {
      "word": "pay",
      "meaning": "支付",
      "grade": "6.1",
      "phonetic": "/pei/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "113"
    },
    {
      "word": "stay",
      "meaning": "保持",
      "grade": "6.1",
      "phonetic": "/steɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "动",
      "serialNumber": "114"
    },
    {
      "word": "subway",
      "meaning": "地铁",
      "grade": "6.1",
      "phonetic": "/ˈsʌbweɪ/",
      "highlightLetters": "ay",
      "highlightPhonetic": "/eɪ/",
      "note": "ay读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "115"
    },
    {
      "word": "amazing",
      "meaning": "令人惊奇的",
      "grade": "6.1",
      "phonetic": "/əˈmeɪzɪŋ/",
      "highlightLetters": "a",
      "highlightPhonetic": "/eɪ/",
      "note": "a读字母音/eɪ/",
      "partOfSpeech": "形",
      "serialNumber": "116"
    },
    {
      "word": "afraid",
      "meaning": "害怕",
      "grade": "6.1",
      "phonetic": "/əˈfreɪd/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/eɪ/",
      "note": "ai读双元音/eɪ/",
      "partOfSpeech": "形",
      "serialNumber": "117"
    },
    {
      "word": "straight",
      "meaning": "笔直地",
      "grade": "6.1",
      "phonetic": "/streɪt/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/eɪ/",
      "note": "ai读双元音/eɪ/",
      "partOfSpeech": "副",
      "serialNumber": "118"
    },
    {
      "word": "train",
      "meaning": "火车",
      "grade": "6.1",
      "phonetic": "/treɪn/",
      "highlightLetters": "ai",
      "highlightPhonetic": "/eɪ/",
      "note": "ai读双元音/eɪ/",
      "partOfSpeech": "名",
      "serialNumber": "119"
    },
    {
      "word": "hiking",
      "meaning": "远足",
      "grade": "6.1",
      "phonetic": "/ˈhaɪkɪŋ/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "120"
    },
    {
      "word": "idea",
      "meaning": "想法；主意",
      "grade": "6.1",
      "phonetic": "/aɪˈdɪə/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "121"
    },
    {
      "word": "pilot",
      "meaning": "飞行员",
      "grade": "6.1",
      "phonetic": "/ˈpaɪlət/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "122"
    },
    {
      "word": "light(s)",
      "meaning": "灯(复数)",
      "grade": "6.1",
      "phonetic": "/laɪt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "123"
    },
    {
      "word": "right",
      "meaning": "右",
      "grade": "6.1",
      "phonetic": "/raɪt/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "124"
    },
    {
      "word": "science",
      "meaning": "科学",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəns/",
      "highlightLetters": "i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "125"
    },
    {
      "word": "scientist",
      "meaning": "科学家",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəntɪst/",
      "highlightLetters": "第1个i",
      "highlightPhonetic": "/aɪ/",
      "note": "i读字母音/aɪ/",
      "partOfSpeech": "名",
      "serialNumber": "126"
    },
    {
      "word": "join",
      "meaning": "加入",
      "grade": "6.1",
      "phonetic": "/dʒɔɪn/",
      "highlightLetters": "oi",
      "highlightPhonetic": "/ɔɪ/",
      "note": "oi读双元音/ɔɪ/",
      "partOfSpeech": "动",
      "serialNumber": "127"
    },
    {
      "word": "count",
      "meaning": "数数",
      "grade": "6.1",
      "phonetic": "/kaʊnt/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "动",
      "serialNumber": "128"
    },
    {
      "word": "down",
      "meaning": "减少；降低",
      "grade": "6.1",
      "phonetic": "/daʊn/",
      "highlightLetters": "ou",
      "highlightPhonetic": "/aʊ/",
      "note": "ou读双元音/aʊ/",
      "partOfSpeech": "副",
      "serialNumber": "129"
    },
    {
      "word": "goal",
      "meaning": "射门",
      "grade": "6.1",
      "phonetic": "/ɡəʊl/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "130"
    },
    {
      "word": "coach",
      "meaning": "教练",
      "grade": "6.1",
      "phonetic": "/kəʊtʃ/",
      "highlightLetters": "oa",
      "highlightPhonetic": "/əʊ/",
      "note": "oa读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "131"
    },
    {
      "word": "follow",
      "meaning": "跟着",
      "grade": "6.1",
      "phonetic": "/ˈfɒləʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "动",
      "serialNumber": "132"
    },
    {
      "word": "slow",
      "meaning": "（使）放慢速度；慢的",
      "grade": "6.1",
      "phonetic": "/sləʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "形",
      "serialNumber": "133"
    },
    {
      "word": "tomorrow",
      "meaning": "明天",
      "grade": "6.1",
      "phonetic": "/təˈmɒrəʊ/",
      "highlightLetters": "ow",
      "highlightPhonetic": "/əʊ/",
      "note": "ow读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "134"
    },
    {
      "word": "poem",
      "meaning": "诗",
      "grade": "6.1",
      "phonetic": "/ˈpəʊɪm/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "135"
    },
    {
      "word": "postcard",
      "meaning": "明信片",
      "grade": "6.1",
      "phonetic": "/ˈpəʊstkɑːd/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "136"
    },
    {
      "word": "postman",
      "meaning": "邮递员",
      "grade": "6.1",
      "phonetic": "/ˈpəʊstmən/",
      "highlightLetters": "o",
      "highlightPhonetic": "/əʊ/",
      "note": "o读双元音/əʊ/",
      "partOfSpeech": "名",
      "serialNumber": "137"
    },
    {
      "word": "wear",
      "meaning": "戴；穿",
      "grade": "6.1",
      "phonetic": "/weə(r)/",
      "highlightLetters": "ear",
      "highlightPhonetic": "/eə/",
      "note": "ear读双元音/eə/",
      "partOfSpeech": "动",
      "serialNumber": "138"
    },
    {
      "word": "share",
      "meaning": "分享",
      "grade": "6.1",
      "phonetic": "/ʃeə(r)/",
      "highlightLetters": "are",
      "highlightPhonetic": "/eə/",
      "note": "are读双元音/eə/",
      "partOfSpeech": "动",
      "serialNumber": "139"
    },
    {
      "word": "afraid",
      "meaning": "害怕",
      "grade": "6.1",
      "phonetic": "/əˈfreɪd/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "140"
    },
    {
      "word": "amazing",
      "meaning": "令人惊奇的",
      "grade": "6.1",
      "phonetic": "/əˈmeɪzɪŋ/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "形",
      "serialNumber": "141"
    },
    {
      "word": "attention",
      "meaning": "注意",
      "grade": "6.1",
      "phonetic": "/əˈtenʃn/",
      "highlightLetters": "第1个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "142"
    },
    {
      "word": "pizza",
      "meaning": "比萨饼",
      "grade": "6.1",
      "phonetic": "/ˈpiːtsə/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "143"
    },
    {
      "word": "Alaska",
      "meaning": "阿拉斯加州（美国州名）",
      "grade": "6.1",
      "phonetic": "/əˈlæskə/",
      "highlightLetters": "第1,3个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "144"
    },
    {
      "word": "cinema",
      "meaning": "电影院",
      "grade": "6.1",
      "phonetic": "/ˈsɪnəmə/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "145"
    },
    {
      "word": "Canberra",
      "meaning": "堪培拉（澳大利亚首都）",
      "grade": "6.1",
      "phonetic": "/ˈkænbərə/",
      "highlightLetters": "第2个a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "146"
    },
    {
      "word": "dictionary",
      "meaning": "词典",
      "grade": "6.1",
      "phonetic": "/ˈdɪkʃənri/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "147"
    },
    {
      "word": "postman",
      "meaning": "邮递员",
      "grade": "6.1",
      "phonetic": "/ˈpəʊstmən/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "148"
    },
    {
      "word": "Germany",
      "meaning": "德国",
      "grade": "6.1",
      "phonetic": "/ˈdʒɜːməni/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "149"
    },
    {
      "word": "Scotland",
      "meaning": "苏格兰",
      "grade": "6.1",
      "phonetic": "/ˈskɒtlənd/",
      "highlightLetters": "a",
      "highlightPhonetic": "/ə/",
      "note": "a弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "150"
    },
    {
      "word": "science",
      "meaning": "科学",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəns/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ə/",
      "note": "e弱音读/ə/",
      "partOfSpeech": "不可数名",
      "serialNumber": "151"
    },
    {
      "word": "scientist",
      "meaning": "科学家",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəntɪst/",
      "highlightLetters": "e",
      "highlightPhonetic": "/ə/",
      "note": "e弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "152"
    },
    {
      "word": "together",
      "meaning": "一起",
      "grade": "6.1",
      "phonetic": "/təˈɡeðə(r)/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "副",
      "serialNumber": "153"
    },
    {
      "word": "police",
      "meaning": "警方",
      "grade": "6.1",
      "phonetic": "/pəˈliːs /",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "154"
    },
    {
      "word": "pilot",
      "meaning": "飞行员",
      "grade": "6.1",
      "phonetic": "/ˈpaɪlət/",
      "highlightLetters": "o",
      "highlightPhonetic": "/ə/",
      "note": "o弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "155"
    },
    {
      "word": "museum",
      "meaning": "博物馆",
      "grade": "6.1",
      "phonetic": "/mjuːˈziːəm/",
      "highlightLetters": "第2个u",
      "highlightPhonetic": "/ə/",
      "note": "u弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "156"
    },
    {
      "word": "worker",
      "meaning": "工人",
      "grade": "6.1",
      "phonetic": "/ˈwɜːkə(r)/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "157"
    },
    {
      "word": "supermarket",
      "meaning": "超市",
      "grade": "6.1",
      "phonetic": "/ˈsuːpəmɑːkɪt/",
      "highlightLetters": "er",
      "highlightPhonetic": "/ə/",
      "note": "er弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "158"
    },
    {
      "word": "feature",
      "meaning": "特点",
      "grade": "6.1",
      "phonetic": "/ˈfiːtʃə(r)/",
      "highlightLetters": "ure",
      "highlightPhonetic": "/ə/",
      "note": "ure弱音读/ə/",
      "partOfSpeech": "名",
      "serialNumber": "159"
    },
    {
      "word": "angry",
      "meaning": "生气的",
      "grade": "6.1",
      "phonetic": "/ˈæŋɡri/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "160"
    },
    {
      "word": "ferry",
      "meaning": "轮渡",
      "grade": "6.1",
      "phonetic": "/ˈferi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "161"
    },
    {
      "word": "worry",
      "meaning": "担心；担忧",
      "grade": "6.1",
      "phonetic": "/ˈwʌri/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "动",
      "serialNumber": "162"
    },
    {
      "word": "country",
      "meaning": "国家",
      "grade": "6.1",
      "phonetic": "/ˈkʌntri/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "163"
    },
    {
      "word": "dictionary",
      "meaning": "词典",
      "grade": "6.1",
      "phonetic": "/ˈdɪkʃənri/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "164"
    },
    {
      "word": "happy",
      "meaning": "高兴的",
      "grade": "6.1",
      "phonetic": "/ˈhæpi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "165"
    },
    {
      "word": "hobby",
      "meaning": "业余爱好",
      "grade": "6.1",
      "phonetic": "/ˈhɒbi/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "166"
    },
    {
      "word": "early",
      "meaning": "早到的",
      "grade": "6.1",
      "phonetic": "/ˈɜːli/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "形",
      "serialNumber": "167"
    },
    {
      "word": "quickly",
      "meaning": "迅速地",
      "grade": "6.1",
      "phonetic": "/ˈkwɪkli/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "副",
      "serialNumber": "168"
    },
    {
      "word": "Germany",
      "meaning": "德国",
      "grade": "6.1",
      "phonetic": "/ˈdʒɜːməni/",
      "highlightLetters": "y",
      "highlightPhonetic": "/i/",
      "note": "y弱音读/i/",
      "partOfSpeech": "名",
      "serialNumber": "169"
    },
    {
      "word": "attention",
      "meaning": "注意",
      "grade": "6.1",
      "phonetic": "/əˈtenʃn/",
      "highlightLetters": "tion",
      "highlightPhonetic": "/ʃn/",
      "note": "/ʃn/弱音省略",
      "partOfSpeech": "不可数名",
      "serialNumber": "170"
    },
    {
      "word": "lesson",
      "meaning": "课",
      "grade": "6.1",
      "phonetic": "/ˈlesn/",
      "highlightLetters": "sson",
      "highlightPhonetic": "/sn/",
      "note": "/sn/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "171"
    },
    {
      "word": "businessman",
      "meaning": "商人；企业家",
      "grade": "6.1",
      "phonetic": "/ˈbɪznəsmæn/",
      "highlightLetters": "sin",
      "highlightPhonetic": "/zn/",
      "note": "/zn/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "172"
    },
    {
      "word": "factory",
      "meaning": "工厂",
      "grade": "6.1",
      "phonetic": "/ˈfæktri/",
      "highlightLetters": "tor",
      "highlightPhonetic": "/tr/",
      "note": "/tr/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "173"
    },
    {
      "word": "secretary",
      "meaning": "秘书",
      "grade": "6.1",
      "phonetic": "/ˈsekrətri/",
      "highlightLetters": "tar",
      "highlightPhonetic": "/tr/",
      "note": "/tr/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "174"
    },
    {
      "word": "interesting",
      "meaning": "有趣的",
      "grade": "6.1",
      "phonetic": "/ˈɪntrəstɪŋ/",
      "highlightLetters": "ter",
      "highlightPhonetic": "/tr/",
      "note": "/tr/弱音省略",
      "partOfSpeech": "形",
      "serialNumber": "175"
    },
    {
      "word": "restaurant",
      "meaning": "餐馆",
      "grade": "6.1",
      "phonetic": "/ˈrestrɒnt/",
      "highlightLetters": "taur",
      "highlightPhonetic": "/tr/",
      "note": "/tr/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "176"
    },
    {
      "word": "hospital",
      "meaning": "医院",
      "grade": "6.1",
      "phonetic": "/ˈhɒspɪtl/",
      "highlightLetters": "tal",
      "highlightPhonetic": "/tl/",
      "note": "/tl/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "177"
    },
    {
      "word": "travel",
      "meaning": "（尤指长途）旅行",
      "grade": "6.1",
      "phonetic": "/ˈtrævl/",
      "highlightLetters": "vel",
      "highlightPhonetic": "/vl/",
      "note": "/vl/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "178"
    },
    {
      "word": "festival",
      "meaning": "节日",
      "grade": "6.1",
      "phonetic": "/ˈfestɪvl/",
      "highlightLetters": "val",
      "highlightPhonetic": "/vl/",
      "note": "/vl/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "179"
    },
    {
      "word": "puzzle",
      "meaning": "谜",
      "grade": "6.1",
      "phonetic": "/ˈpʌzl/",
      "highlightLetters": "zzle",
      "highlightPhonetic": "/zl/",
      "note": "/zl/弱音省略",
      "partOfSpeech": "名",
      "serialNumber": "180"
    },
    {
      "word": "build",
      "meaning": "建造；建设",
      "grade": "6.1",
      "phonetic": "/bild/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "动",
      "serialNumber": "181"
    },
    {
      "word": "club",
      "meaning": "俱乐部",
      "grade": "6.1",
      "phonetic": "/klʌb/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "182"
    },
    {
      "word": "hobby",
      "meaning": "业余爱好",
      "grade": "6.1",
      "phonetic": "/ˈhɒbi/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "183"
    },
    {
      "word": "subway",
      "meaning": "地铁",
      "grade": "6.1",
      "phonetic": "/ˈsʌbweɪ/",
      "highlightLetters": "b",
      "highlightPhonetic": "/b/",
      "note": "b读/b/",
      "partOfSpeech": "名",
      "serialNumber": "184"
    },
    {
      "word": "coach",
      "meaning": "教练",
      "grade": "6.1",
      "phonetic": "/kəʊtʃ/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/",
      "partOfSpeech": "名",
      "serialNumber": "185"
    },
    {
      "word": "comic",
      "meaning": "滑稽的",
      "grade": "6.1",
      "phonetic": "/ˈkɒmɪk/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/",
      "partOfSpeech": "形",
      "serialNumber": "186"
    },
    {
      "word": "count",
      "meaning": "数数",
      "grade": "6.1",
      "phonetic": "/kaʊnt/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/",
      "partOfSpeech": "动",
      "serialNumber": "187"
    },
    {
      "word": "country",
      "meaning": "国家",
      "grade": "6.1",
      "phonetic": "/ˈkʌntri/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/",
      "partOfSpeech": "名",
      "serialNumber": "188"
    },
    {
      "word": "traffic",
      "meaning": "交通",
      "grade": "6.1",
      "phonetic": "/ˈtræfɪk/",
      "highlightLetters": "c",
      "highlightPhonetic": "/k/",
      "note": "c读/k/",
      "partOfSpeech": "名",
      "serialNumber": "189"
    },
    {
      "word": "deep",
      "meaning": "深的",
      "grade": "6.1",
      "phonetic": "/diːp/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "形",
      "serialNumber": "190"
    },
    {
      "word": "dictionary",
      "meaning": "词典",
      "grade": "6.1",
      "phonetic": "/ˈdɪkʃənri/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "191"
    },
    {
      "word": "down",
      "meaning": "减少；降低",
      "grade": "6.1",
      "phonetic": "/daʊn/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "副",
      "serialNumber": "192"
    },
    {
      "word": "sad",
      "meaning": "难过的",
      "grade": "6.1",
      "phonetic": "/sæd/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "193"
    },
    {
      "word": "sled",
      "meaning": "雪橇",
      "grade": "6.1",
      "phonetic": "/sled/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "名",
      "serialNumber": "194"
    },
    {
      "word": "should",
      "meaning": "应该",
      "grade": "6.1",
      "phonetic": "/ʃʊd/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "195"
    },
    {
      "word": "studies",
      "meaning": "（study 的三单形式）学习",
      "grade": "6.1",
      "phonetic": "/ˈstʌdiz/",
      "highlightLetters": "d",
      "highlightPhonetic": "/d/",
      "note": "d读/d/",
      "partOfSpeech": "动",
      "serialNumber": "196"
    },
    {
      "word": "far",
      "meaning": "远的",
      "grade": "6.1",
      "phonetic": "/fɑː(r)/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "形",
      "serialNumber": "197"
    },
    {
      "word": "fast",
      "meaning": "快",
      "grade": "6.1",
      "phonetic": "/fɑːst/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "形",
      "serialNumber": "198"
    },
    {
      "word": "feature",
      "meaning": "特点",
      "grade": "6.1",
      "phonetic": "/ˈfiːtʃə(r)/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "199"
    },
    {
      "word": "feel",
      "meaning": "觉得；感到",
      "grade": "6.1",
      "phonetic": "/fiːl/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "200"
    },
    {
      "word": "ferry",
      "meaning": "轮渡",
      "grade": "6.1",
      "phonetic": "/ˈferi/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "201"
    },
    {
      "word": "festival",
      "meaning": "节日",
      "grade": "6.1",
      "phonetic": "/ˈfestɪvl/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "202"
    },
    {
      "word": "film",
      "meaning": "电影",
      "grade": "6.1",
      "phonetic": "/fɪlm/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "203"
    },
    {
      "word": "fisherman",
      "meaning": "渔民",
      "grade": "6.1",
      "phonetic": "/ˈfɪʃəmən/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "204"
    },
    {
      "word": "follow",
      "meaning": "跟着",
      "grade": "6.1",
      "phonetic": "/ˈfɒləʊ/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "动",
      "serialNumber": "205"
    },
    {
      "word": "foot",
      "meaning": "脚",
      "grade": "6.1",
      "phonetic": "/ˈfʊt/",
      "highlightLetters": "f",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "206"
    },
    {
      "word": "office",
      "meaning": "办公室",
      "grade": "6.1",
      "phonetic": "/ˌɒfɪs/",
      "highlightLetters": "ff",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "207"
    },
    {
      "word": "officer",
      "meaning": "官员",
      "grade": "6.1",
      "phonetic": "/ˌɒfɪsə/",
      "highlightLetters": "ff",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "208"
    },
    {
      "word": "traffic",
      "meaning": "交通",
      "grade": "6.1",
      "phonetic": "/ˈtræfɪk/",
      "highlightLetters": "ff",
      "highlightPhonetic": "/f/",
      "note": "f读/f/",
      "partOfSpeech": "名",
      "serialNumber": "209"
    },
    {
      "word": "gave",
      "meaning": "（give 的过去式）给",
      "grade": "6.1",
      "phonetic": "/ɡeɪv/",
      "highlightLetters": "g",
      "highlightPhonetic": "/g/",
      "note": "g读/g/",
      "partOfSpeech": "动",
      "serialNumber": "210"
    },
    {
      "word": "get",
      "meaning": "到达",
      "grade": "6.1",
      "phonetic": "/ɡet/",
      "highlightLetters": "g",
      "highlightPhonetic": "/g/",
      "note": "g读/g/",
      "partOfSpeech": "动",
      "serialNumber": "211"
    },
    {
      "word": "goal",
      "meaning": "射门",
      "grade": "6.1",
      "phonetic": "/ɡəʊl/",
      "highlightLetters": "g",
      "highlightPhonetic": "/g/",
      "note": "g读/g/",
      "partOfSpeech": "名",
      "serialNumber": "212"
    },
    {
      "word": "grass",
      "meaning": "草坪",
      "grade": "6.1",
      "phonetic": "/ɡrɑːs/",
      "highlightLetters": "g",
      "highlightPhonetic": "/g/",
      "note": "g读/g/",
      "partOfSpeech": "名",
      "serialNumber": "213"
    },
    {
      "word": "gym",
      "meaning": "体育馆",
      "grade": "6.1",
      "phonetic": "/dʒɪm/",
      "highlightLetters": "g",
      "highlightPhonetic": "/dʒ/",
      "note": "g读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "214"
    },
    {
      "word": "angry",
      "meaning": "生气的",
      "grade": "6.1",
      "phonetic": "/ˈæŋɡri/",
      "highlightLetters": "g",
      "highlightPhonetic": "/g/",
      "note": "g读/g/",
      "partOfSpeech": "形",
      "serialNumber": "215"
    },
    {
      "word": "together",
      "meaning": "一起",
      "grade": "6.1",
      "phonetic": "/təˈɡeðə(r)/",
      "highlightLetters": "g",
      "highlightPhonetic": "/g/",
      "note": "g读/g/",
      "partOfSpeech": "副",
      "serialNumber": "216"
    },
    {
      "word": "Germany",
      "meaning": "德国",
      "grade": "6.1",
      "phonetic": "/ˈdʒɜːməni/",
      "highlightLetters": "g",
      "highlightPhonetic": "/dʒ/",
      "note": "g读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "217"
    },
    {
      "word": "half",
      "meaning": "一半",
      "grade": "6.1",
      "phonetic": "/hɑːf/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "218"
    },
    {
      "word": "happy",
      "meaning": "高兴的",
      "grade": "6.1",
      "phonetic": "/ˈhæpi/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "形",
      "serialNumber": "219"
    },
    {
      "word": "head",
      "meaning": "头",
      "grade": "6.1",
      "phonetic": "/hed/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "220"
    },
    {
      "word": "hear",
      "meaning": "听见",
      "grade": "6.1",
      "phonetic": "/hɪə(r)/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "221"
    },
    {
      "word": "helmet",
      "meaning": "头盔",
      "grade": "6.1",
      "phonetic": "/ˈhelmɪt/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "222"
    },
    {
      "word": "hiking",
      "meaning": "远足",
      "grade": "6.1",
      "phonetic": "/ˈhaɪkɪŋ/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "不可数名",
      "serialNumber": "223"
    },
    {
      "word": "hobby",
      "meaning": "业余爱好",
      "grade": "6.1",
      "phonetic": "/ˈhɒbi/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "224"
    },
    {
      "word": "hospital",
      "meaning": "医院",
      "grade": "6.1",
      "phonetic": "/ˈhɒspɪtl/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "名",
      "serialNumber": "225"
    },
    {
      "word": "hurt",
      "meaning": "（使）受伤",
      "grade": "6.1",
      "phonetic": "/hɜːt/",
      "highlightLetters": "h",
      "highlightPhonetic": "/h/",
      "note": "h读/h/",
      "partOfSpeech": "动",
      "serialNumber": "226"
    },
    {
      "word": "jasmine",
      "meaning": "茉莉",
      "grade": "6.1",
      "phonetic": "/ˈdʒæzmɪn/",
      "highlightLetters": "j",
      "highlightPhonetic": "/dʒ/",
      "note": "j读/dʒ/",
      "partOfSpeech": "名",
      "serialNumber": "227"
    },
    {
      "word": "join",
      "meaning": "加入",
      "grade": "6.1",
      "phonetic": "/dʒɔɪn/",
      "highlightLetters": "j",
      "highlightPhonetic": "/dʒ/",
      "note": "j读/dʒ/",
      "partOfSpeech": "动",
      "serialNumber": "228"
    },
    {
      "word": "left",
      "meaning": "左边（的）",
      "grade": "6.1",
      "phonetic": "/left/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/",
      "partOfSpeech": "名;形",
      "serialNumber": "229"
    },
    {
      "word": "lesson",
      "meaning": "课",
      "grade": "6.1",
      "phonetic": "/ˈlesn/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/",
      "partOfSpeech": "名",
      "serialNumber": "230"
    },
    {
      "word": "light(s)",
      "meaning": "灯(复数)",
      "grade": "6.1",
      "phonetic": "/laɪt/",
      "highlightLetters": "l",
      "highlightPhonetic": "/l/",
      "note": "l读/l/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "231"
    },
    {
      "word": "mice",
      "meaning": "（mouse 的复数）老鼠",
      "grade": "6.1",
      "phonetic": "/maɪs/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名, 复数",
      "serialNumber": "232"
    },
    {
      "word": "moon",
      "meaning": "月亮",
      "grade": "6.1",
      "phonetic": "/muːn/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "233"
    },
    {
      "word": "mooncake",
      "meaning": "月饼",
      "grade": "6.1",
      "phonetic": "/muːn keik/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "234"
    },
    {
      "word": "more",
      "meaning": "更多的",
      "grade": "6.1",
      "phonetic": "/mɔː(r)/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "形",
      "serialNumber": "235"
    },
    {
      "word": "mud",
      "meaning": "泥",
      "grade": "6.1",
      "phonetic": "/mʌd/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "不可数名",
      "serialNumber": "236"
    },
    {
      "word": "Munich",
      "meaning": "慕尼黑（德国城市）",
      "grade": "6.1",
      "phonetic": "/ˈmjuːnɪk/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "237"
    },
    {
      "word": "museum",
      "meaning": "博物馆",
      "grade": "6.1",
      "phonetic": "/mjuːˈziːəm/",
      "highlightLetters": "2个m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "名",
      "serialNumber": "238"
    },
    {
      "word": "must",
      "meaning": "必须",
      "grade": "6.1",
      "phonetic": "/mʌst/",
      "highlightLetters": "m",
      "highlightPhonetic": "/m/",
      "note": "m读/m/",
      "partOfSpeech": "动",
      "serialNumber": "239"
    },
    {
      "word": "pilot",
      "meaning": "飞行员",
      "grade": "6.1",
      "phonetic": "/ˈpaɪlət/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "240"
    },
    {
      "word": "pizza",
      "meaning": "比萨饼",
      "grade": "6.1",
      "phonetic": "/ˈpiːtsə/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "241"
    },
    {
      "word": "poem",
      "meaning": "诗",
      "grade": "6.1",
      "phonetic": "/ˈpəʊɪm/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "242"
    },
    {
      "word": "police",
      "meaning": "警方",
      "grade": "6.1",
      "phonetic": "/pəˈliːs /",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "243"
    },
    {
      "word": "postcard",
      "meaning": "明信片",
      "grade": "6.1",
      "phonetic": "/ˈpəʊstkɑːd/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "244"
    },
    {
      "word": "postman",
      "meaning": "邮递员",
      "grade": "6.1",
      "phonetic": "/ˈpəʊstmən/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "245"
    },
    {
      "word": "pull",
      "meaning": "拉；拽",
      "grade": "6.1",
      "phonetic": "/pʊl/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "动",
      "serialNumber": "246"
    },
    {
      "word": "puzzle",
      "meaning": "谜",
      "grade": "6.1",
      "phonetic": "/ˈpʌzl/",
      "highlightLetters": "p",
      "highlightPhonetic": "/p/",
      "note": "p读/p/",
      "partOfSpeech": "名",
      "serialNumber": "247"
    },
    {
      "word": "quickly",
      "meaning": "迅速地",
      "grade": "6.1",
      "phonetic": "/ˈkwɪkli/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "副",
      "serialNumber": "248"
    },
    {
      "word": "reporter",
      "meaning": "记者",
      "grade": "6.1",
      "phonetic": "/rɪˈpɔːtə(r)/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "249"
    },
    {
      "word": "restaurant",
      "meaning": "餐馆",
      "grade": "6.1",
      "phonetic": "/ˈrestrɒnt/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "250"
    },
    {
      "word": "right",
      "meaning": "右",
      "grade": "6.1",
      "phonetic": "/raɪt/",
      "highlightLetters": "r",
      "highlightPhonetic": "/r/",
      "note": "r读/r/",
      "partOfSpeech": "名",
      "serialNumber": "251"
    },
    {
      "word": "sad",
      "meaning": "难过的",
      "grade": "6.1",
      "phonetic": "/sæd/",
      "highlightLetters": "s",
      "highlightPhonetic": "/s/",
      "note": "s读/s/",
      "partOfSpeech": "形",
      "serialNumber": "252"
    },
    {
      "word": "science",
      "meaning": "科学",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəns/",
      "highlightLetters": "sc",
      "highlightPhonetic": "/s/",
      "note": "sc读/s/",
      "partOfSpeech": "名",
      "serialNumber": "253"
    },
    {
      "word": "scientist",
      "meaning": "科学家",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəntɪst/",
      "highlightLetters": "sc",
      "highlightPhonetic": "/s/",
      "note": "sc读/s/",
      "partOfSpeech": "名",
      "serialNumber": "254"
    },
    {
      "word": "take",
      "meaning": "取走，拿走",
      "grade": "6.1",
      "phonetic": "/teik/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "255"
    },
    {
      "word": "taxi",
      "meaning": "出租汽车",
      "grade": "6.1",
      "phonetic": "/ˈtæksi/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "256"
    },
    {
      "word": "tell",
      "meaning": "告诉",
      "grade": "6.1",
      "phonetic": "/tel/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "257"
    },
    {
      "word": "together",
      "meaning": "一起",
      "grade": "6.1",
      "phonetic": "/təˈɡeðə(r)/",
      "highlightLetters": "第1个t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "副",
      "serialNumber": "258"
    },
    {
      "word": "tomorrow",
      "meaning": "明天",
      "grade": "6.1",
      "phonetic": "/təˈmɒrəʊ/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "259"
    },
    {
      "word": "tonight",
      "meaning": "在今晚",
      "grade": "6.1",
      "phonetic": "/təˈnaɪt/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "副",
      "serialNumber": "260"
    },
    {
      "word": "turn",
      "meaning": "转弯",
      "grade": "6.1",
      "phonetic": "/tɜːn/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "动",
      "serialNumber": "261"
    },
    {
      "word": "type",
      "meaning": "打字",
      "grade": "6.1",
      "phonetic": "/taɪp/",
      "highlightLetters": "t",
      "highlightPhonetic": "/t/",
      "note": "t读/t/",
      "partOfSpeech": "名",
      "serialNumber": "262"
    },
    {
      "word": "visit",
      "meaning": "拜访",
      "grade": "6.1",
      "phonetic": "/ˈvɪzɪt/",
      "highlightLetters": "v",
      "highlightPhonetic": "/v/",
      "note": "v读/v/",
      "partOfSpeech": "动",
      "serialNumber": "263"
    },
    {
      "word": "wear",
      "meaning": "戴；穿",
      "grade": "6.1",
      "phonetic": "/weə(r)/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "264"
    },
    {
      "word": "well",
      "meaning": "健康的；身体好的",
      "grade": "6.1",
      "phonetic": "/wel/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "形",
      "serialNumber": "265"
    },
    {
      "word": "word",
      "meaning": "单词",
      "grade": "6.1",
      "phonetic": "/wɜːd/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "266"
    },
    {
      "word": "worker",
      "meaning": "工人",
      "grade": "6.1",
      "phonetic": "/ˈwɜːkə(r)/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "名",
      "serialNumber": "267"
    },
    {
      "word": "worried",
      "meaning": "担心的；发愁的",
      "grade": "6.1",
      "phonetic": "/ˈwʌrid/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "形",
      "serialNumber": "268"
    },
    {
      "word": "worry",
      "meaning": "担心；担忧",
      "grade": "6.1",
      "phonetic": "/ˈwʌri/",
      "highlightLetters": "w",
      "highlightPhonetic": "/w/",
      "note": "w读/w/",
      "partOfSpeech": "动",
      "serialNumber": "269"
    },
    {
      "word": "sled",
      "meaning": "雪橇",
      "grade": "6.1",
      "phonetic": "/sled/",
      "highlightLetters": "sl",
      "highlightPhonetic": "/sl/",
      "note": "sl读/sl/",
      "partOfSpeech": "名",
      "serialNumber": "270"
    },
    {
      "word": "slow",
      "meaning": "（使）放慢速度；慢的",
      "grade": "6.1",
      "phonetic": "/sləʊ/",
      "highlightLetters": "sl",
      "highlightPhonetic": "/sl/",
      "note": "sl读/sl/",
      "partOfSpeech": "形",
      "serialNumber": "271"
    },
    {
      "word": "space",
      "meaning": "太空",
      "grade": "6.1",
      "phonetic": "/speɪs/",
      "highlightLetters": "sp",
      "highlightPhonetic": "/sp/",
      "note": "sp读/sp/",
      "partOfSpeech": "不可数名",
      "serialNumber": "272"
    },
    {
      "word": "stay",
      "meaning": "保持",
      "grade": "6.1",
      "phonetic": "/steɪ/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "动",
      "serialNumber": "273"
    },
    {
      "word": "stop",
      "meaning": "停下",
      "grade": "6.1",
      "phonetic": "/stɒp/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "动",
      "serialNumber": "274"
    },
    {
      "word": "stuck",
      "meaning": "陷住；无法移动",
      "grade": "6.1",
      "phonetic": "/stʌk/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "动",
      "serialNumber": "275"
    },
    {
      "word": "studies",
      "meaning": "（study 的三单形式）学习",
      "grade": "6.1",
      "phonetic": "/ˈstʌdiz/",
      "highlightLetters": "st",
      "highlightPhonetic": "/st/",
      "note": "st读/st/",
      "partOfSpeech": "动",
      "serialNumber": "276"
    },
    {
      "word": "straight",
      "meaning": "笔直地",
      "grade": "6.1",
      "phonetic": "/streɪt/",
      "highlightLetters": "str",
      "highlightPhonetic": "/str/",
      "note": "str读/str/",
      "partOfSpeech": "副",
      "serialNumber": "277"
    },
    {
      "word": "street",
      "meaning": "大街；街道",
      "grade": "6.1",
      "phonetic": "/striːt/",
      "highlightLetters": "str",
      "highlightPhonetic": "/str/",
      "note": "str读/str/",
      "partOfSpeech": "名",
      "serialNumber": "278"
    },
    {
      "word": "shall",
      "meaning": "表示征求意见",
      "grade": "6.1",
      "phonetic": "/ʃæl/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "动",
      "serialNumber": "279"
    },
    {
      "word": "share",
      "meaning": "分享",
      "grade": "6.1",
      "phonetic": "/ʃeə(r)/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "动",
      "serialNumber": "280"
    },
    {
      "word": "ship",
      "meaning": "（大）船",
      "grade": "6.1",
      "phonetic": "/ʃɪp/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "281"
    },
    {
      "word": "should",
      "meaning": "应该",
      "grade": "6.1",
      "phonetic": "/ʃʊd/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "动",
      "serialNumber": "282"
    },
    {
      "word": "fisherman",
      "meaning": "渔民",
      "grade": "6.1",
      "phonetic": "/ˈfɪʃəmən/",
      "highlightLetters": "sh",
      "highlightPhonetic": "/ʃ/",
      "note": "sh读/ʃ/",
      "partOfSpeech": "名",
      "serialNumber": "283"
    },
    {
      "word": "dictionary",
      "meaning": "词典",
      "grade": "6.1",
      "phonetic": "/ˈdɪkʃənri/",
      "highlightLetters": "tion",
      "highlightPhonetic": "/ʃən/",
      "note": "tion读/ʃən/",
      "partOfSpeech": "名",
      "serialNumber": "284"
    },
    {
      "word": "wrong",
      "meaning": "有毛病的",
      "grade": "6.1",
      "phonetic": "/rɒŋ/",
      "highlightLetters": "wr",
      "highlightPhonetic": "/r/",
      "note": "wr读/r/",
      "partOfSpeech": "形",
      "serialNumber": "285"
    },
    {
      "word": "right",
      "meaning": "右",
      "grade": "6.1",
      "phonetic": "/raɪt/",
      "highlightLetters": "ght",
      "highlightPhonetic": "/t/",
      "note": "ght读/t/",
      "partOfSpeech": "名",
      "serialNumber": "286"
    },
    {
      "word": "tonight",
      "meaning": "在今晚",
      "grade": "6.1",
      "phonetic": "/təˈnaɪt/",
      "highlightLetters": "ght",
      "highlightPhonetic": "/t/",
      "note": "ght读/t/",
      "partOfSpeech": "副",
      "serialNumber": "287"
    },
    {
      "word": "light(s)",
      "meaning": "灯(复数)",
      "grade": "6.1",
      "phonetic": "/laɪt/",
      "highlightLetters": "ght",
      "highlightPhonetic": "/t/",
      "note": "ght读/t/",
      "partOfSpeech": "名",
      "serialNumber": "288"
    },
    {
      "word": "Munich",
      "meaning": "慕尼黑（德国城市）",
      "grade": "6.1",
      "phonetic": "/ˈmjuːnɪk/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/k/",
      "note": "ch读/k/",
      "partOfSpeech": "名",
      "serialNumber": "289"
    },
    {
      "word": "chase",
      "meaning": "追赶",
      "grade": "6.1",
      "phonetic": "/tʃeɪs/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "动",
      "serialNumber": "290"
    },
    {
      "word": "coach",
      "meaning": "教练",
      "grade": "6.1",
      "phonetic": "/kəʊtʃ/",
      "highlightLetters": "ch",
      "highlightPhonetic": "/tʃ/",
      "note": "ch读/tʃ/",
      "partOfSpeech": "名",
      "serialNumber": "291"
    },
    {
      "word": "quickly",
      "meaning": "迅速地",
      "grade": "6.1",
      "phonetic": "/ˈkwɪkli/",
      "highlightLetters": "qu",
      "highlightPhonetic": "/kw/",
      "note": "qu读/kw/",
      "partOfSpeech": "副",
      "serialNumber": "292"
    },
    {
      "word": "breath",
      "meaning": "呼吸",
      "grade": "6.1",
      "phonetic": "/breθ/",
      "highlightLetters": "br",
      "highlightPhonetic": "/br/",
      "note": "br读/br/",
      "partOfSpeech": "名",
      "serialNumber": "293"
    },
    {
      "word": "crossing",
      "meaning": "十字路口",
      "grade": "6.1",
      "phonetic": "/ˈkrɒsɪŋ/",
      "highlightLetters": "cr",
      "highlightPhonetic": "/kr/",
      "note": "kr读/kr/",
      "partOfSpeech": "名",
      "serialNumber": "294"
    },
    {
      "word": "secretary",
      "meaning": "秘书",
      "grade": "6.1",
      "phonetic": "/ˈsekrətri/",
      "highlightLetters": "cr",
      "highlightPhonetic": "/kr/",
      "note": "kr读/kr/",
      "partOfSpeech": "名",
      "serialNumber": "295"
    },
    {
      "word": "grass",
      "meaning": "草坪",
      "grade": "6.1",
      "phonetic": "/ɡrɑːs/",
      "highlightLetters": "gr",
      "highlightPhonetic": "/ɡr/",
      "note": "gr读/ɡr/",
      "partOfSpeech": "名",
      "serialNumber": "296"
    },
    {
      "word": "traffic",
      "meaning": "交通",
      "grade": "6.1",
      "phonetic": "/ˈtræfɪk/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/tr/",
      "partOfSpeech": "名",
      "serialNumber": "297"
    },
    {
      "word": "train",
      "meaning": "火车",
      "grade": "6.1",
      "phonetic": "/treɪn/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/tr/",
      "partOfSpeech": "名",
      "serialNumber": "298"
    },
    {
      "word": "travel",
      "meaning": "（尤指长途）旅行",
      "grade": "6.1",
      "phonetic": "/ˈtrævl/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/tr/",
      "partOfSpeech": "名",
      "serialNumber": "299"
    },
    {
      "word": "trip",
      "meaning": "旅行",
      "grade": "6.1",
      "phonetic": "/trɪp/",
      "highlightLetters": "tr",
      "highlightPhonetic": "/tr/",
      "note": "tr读/tr/",
      "partOfSpeech": "名",
      "serialNumber": "300"
    },
    {
      "word": "science",
      "meaning": "科学",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəns/",
      "highlightLetters": "sc",
      "highlightPhonetic": "/s/",
      "note": "sc读/s/",
      "partOfSpeech": "不可数名",
      "serialNumber": "301"
    },
    {
      "word": "scientist",
      "meaning": "科学家",
      "grade": "6.1",
      "phonetic": "/ˈsaɪəntɪst/",
      "highlightLetters": "sc",
      "highlightPhonetic": "/s/",
      "note": "sc读/s/",
      "partOfSpeech": "名",
      "serialNumber": "302"
    }
  ]
};
